import{describe,expect,it}from'vitest'
import type{Ingredient,IngredientKnowledgeCompatibility,IngredientKnowledgeRole}from'../../../types/domain'
import{classifyDeodorantIngredient,naturalDeodorantFormulaCompatibility}from'../../product-studio/domain/naturalDeodorant'
import{clearIncompatibleKnowledgeValue,createEmptyIngredientKnowledgeProfile,knowledgeCompleteness,resolvedIngredientKnowledge,validateIngredientKnowledgeAggregate,validateMeasuredValue,validateSensoryValue}from'./ingredientKnowledge'
const ingredient:Ingredient={id:'i',commonName:'Jojoba',inciName:'Simmondsia Chinensis Seed Oil',category:'Wax',functions:['legacy'],description:'',defaultUnit:'g',notes:'',status:'Active',createdAt:'2026-01-01',updatedAt:'2026-01-01'}
describe('Ingredient Knowledge foundation',()=>{
it('loads old ingredients safely with weak fallback',()=>expect(resolvedIngredientKnowledge(ingredient,undefined,[])).toMatchObject({physicalForm:'unknown',fallback:true,physicalFormConfidence:'assumed'}))
it('round-trips unknown and not applicable',()=>{const p=createEmptyIngredientKnowledgeProfile('i');expect(p.identity.casNumber.state).toBe('unknown');p.identity.casNumber={state:'not_applicable',confidence:'verified'};expect(structuredClone(p).identity.casNumber.state).toBe('not_applicable')})
it('keeps documented jojoba physically liquid',()=>{const p=createEmptyIngredientKnowledgeProfile('i');p.physicalProperties.physicalForm={state:'known',value:'liquid',confidence:'supported',sourceReference:'supplier-spec'};expect(classifyDeodorantIngredient(ingredient,p).physicalForm).toBe('liquid')})
it('supports multiple role levels',()=>{const p=createEmptyIngredientKnowledgeProfile('i'),roles:IngredientKnowledgeRole[]=[['r1','liquid_emollient','primary'],['r2','slip_modifier','secondary'],['r3','other','context_dependent']].map(([id,role,level])=>({id,ingredientKnowledgeProfileId:p.id,role:role as IngredientKnowledgeRole['role'],level:level as IngredientKnowledgeRole['level'],context:'',evidenceIds:[],confidence:'observed',notes:'',createdAt:'',updatedAt:''}));expect(resolvedIngredientKnowledge(ingredient,p,roles).roles).toHaveLength(3)})
it('keeps sensory zero distinct from unknown and accepts ten with context',()=>{expect(validateSensoryValue({state:'known',value:0,confidence:'observed',notes:'10% balm observation'})).toEqual([]);expect(validateSensoryValue({state:'known',value:10,confidence:'observed',sourceReference:'observation-1'})).toEqual([]);expect(validateSensoryValue({state:'unknown',confidence:'unknown'})).toEqual([])})
it('rejects invalid sensory, missing units and inverted bounds',()=>{expect(validateSensoryValue({state:'known',value:11,confidence:'observed'})).not.toEqual([]);expect(validateMeasuredValue({state:'known',value:2,confidence:'supported'})).toContain('Known measured values require a unit.');expect(validateMeasuredValue({state:'known',value:2,unit:'g/ml',lowerBound:3,upperBound:2,confidence:'supported'})).toContain('Lower bound cannot exceed upper bound.')})
it('defaults future inputs to unknown',()=>{const p=createEmptyIngredientKnowledgeProfile('i');expect(Object.values(p.predictionInputs).every(field=>field.state==='unknown')).toBe(true);expect(knowledgeCompleteness(p).percentage).toBe(0)})
it('does not interpret compatibility as approval',()=>{const p=createEmptyIngredientKnowledgeProfile('i'),relationship:IngredientKnowledgeCompatibility={id:'c',ingredientKnowledgeProfileId:p.id,targetType:'product_template',targetLabel:'Natural Deodorant',context:'one grade',rating:'excellent',evidenceIds:[],confidence:'observed',notes:'Not safety or stability approval',createdAt:'',updatedAt:''};expect(relationship.notes).toContain('Not safety')})
it('uses structured form in Natural Deodorant validation',()=>{const p=createEmptyIngredientKnowledgeProfile('i');p.physicalProperties.physicalForm={state:'known',value:'liquid',confidence:'supported'};const result=naturalDeodorantFormulaCompatibility('Twist-up stick',[{id:'l',formulaVersionId:'v',ingredientId:'i',percentage:100,phase:'A',sortOrder:1,notes:'',formulationRole:'structuring_wax'}],[ingredient],[p],[]);expect(result.blockingIssues.join(' ')).toContain('solid structuring material')})
it('creates no automatic pairings or recommended level',()=>{const p=createEmptyIngredientKnowledgeProfile('i');expect(p).not.toHaveProperty('recommendedUsageLevel');expect(p).not.toHaveProperty('pairings')})
it('clears stale values, units, and bounds when a field stops being known',()=>{expect(clearIncompatibleKnowledgeValue({state:'known',value:0,unit:'°C',lowerBound:0,upperBound:1,confidence:'supported'},'not_applicable')).toEqual({state:'not_applicable',confidence:'supported',notes:undefined})})
it('does not expose assumed or conflicting roles as supported knowledge',()=>{const p=createEmptyIngredientKnowledgeProfile('i'),roles:IngredientKnowledgeRole[]=[{id:'a',ingredientKnowledgeProfileId:p.id,role:'structuring_wax',level:'primary',context:'guess',evidenceIds:[],confidence:'assumed',notes:'',createdAt:'',updatedAt:''},{id:'c',ingredientKnowledgeProfileId:p.id,role:'liquid_emollient',level:'primary',context:'conflict',evidenceIds:[],confidence:'conflicting',notes:'',createdAt:'',updatedAt:''}];expect(resolvedIngredientKnowledge(ingredient,p,roles).roles).toEqual([]);expect(resolvedIngredientKnowledge(ingredient,p,roles).reviewRequired).toBe(true)})
it('rejects duplicate ids, self compatibility, and empty known values',()=>{const p=createEmptyIngredientKnowledgeProfile('i');p.identity.inci={state:'known',value:'',confidence:'supported'};const evidence={id:'same',ingredientKnowledgeProfileId:p.id,sourceType:'user_note' as const,provenance:'user' as const,title:'Note',summary:'',notes:'',confidence:'observed' as const,createdAt:'',updatedAt:''};const errors=validateIngredientKnowledgeAggregate({profile:p,roles:[],evidence:[evidence],compatibility:[{id:'same',ingredientKnowledgeProfileId:p.id,targetType:'ingredient',targetId:'i',targetLabel:'Self',context:'',rating:'unknown',evidenceIds:[],confidence:'unknown',notes:'',createdAt:'',updatedAt:''}]},['i']);expect(errors.join(' ')).toContain('Known fields require a value');expect(errors.join(' ')).toContain('Duplicate relation id');expect(errors.join(' ')).toContain('cannot be compatible with itself')})
})
