import{describe,expect,it}from'vitest'
import type{IngredientKnowledgeCompatibility,IngredientKnowledgeEvidence,IngredientKnowledgeRole}from'../../../types/domain'
import{createEmptyIngredientKnowledgeProfile,validateIngredientKnowledgeAggregate}from'./ingredientKnowledge'
const now='2026-07-20T12:00:00.000Z'
const profile=()=>{const value=createEmptyIngredientKnowledgeProfile('i1',now);value.id='p1';return value}
const evidence=(patch:Partial<IngredientKnowledgeEvidence>={}):IngredientKnowledgeEvidence=>({id:'e1',ingredientKnowledgeProfileId:'p1',sourceType:'supplier_document',provenance:'supplier_specific',title:'Supplier specification',documentId:'DOC-1',documentRevision:'Rev 4',externalUrl:'https://example.test/spec',evidenceDate:'2026-07-20',authorOrOrganisation:'Supplier AS',summary:'Bounded summary.',notes:'Context note.',confidence:'supported',createdAt:now,updatedAt:now,...patch})
const role=(patch:Partial<IngredientKnowledgeRole>={}):IngredientKnowledgeRole=>({id:'r1',ingredientKnowledgeProfileId:'p1',role:'slip_modifier',level:'secondary',context:'10% anhydrous balm',evidenceIds:['e1'],confidence:'observed',notes:'Role note.',createdAt:now,updatedAt:now,...patch})
const compatibility=(patch:Partial<IngredientKnowledgeCompatibility>={}):IngredientKnowledgeCompatibility=>({id:'c1',ingredientKnowledgeProfileId:'p1',targetType:'ingredient',targetId:'i2',targetLabel:'Argan Oil',context:'Directional blend observation',rating:'acceptable',evidenceIds:['e1'],confidence:'observed',notes:'Compatibility note.',createdAt:now,updatedAt:now,...patch})
describe('Ingredient Knowledge child editor contracts',()=>{
 it('round-trips every Role field and preserves links through unrelated edits',()=>{const item=role(),copy=structuredClone(item);copy.role='texture_modifier';copy.level='context_dependent';copy.context='';copy.notes='';expect(copy).toMatchObject({role:'texture_modifier',level:'context_dependent',context:'',confidence:'observed',evidenceIds:['e1'],notes:''})})
 it('rejects duplicate role/context/level combinations',()=>{const p=profile(),e=evidence(),errors=validateIngredientKnowledgeAggregate({profile:p,evidence:[e],roles:[role(),role({id:'r2'})],compatibility:[]},['i1','i2']);expect(errors.some(value=>value.includes('Duplicate'))).toBe(true)})
 it('round-trips canonical and user-defined Compatibility fields and clearing',()=>{const canonical=compatibility(),custom=compatibility({id:'c2',targetType:'packaging_material',targetId:undefined,targetLabel:'User-defined nitrile gasket',context:'',evidenceIds:[],notes:''});expect(structuredClone([canonical,custom])).toEqual([canonical,custom])})
 it('rejects self-reference and unavailable evidence',()=>{const p=profile(),errors=validateIngredientKnowledgeAggregate({profile:p,evidence:[],roles:[],compatibility:[compatibility({targetId:'i1',evidenceIds:['missing']})]},['i1','i2']);expect(errors.join(' ')).toContain('compatible with itself');expect(errors.join(' ')).toContain('unavailable evidence')})
 it('round-trips every Evidence field, clearing, and conflicting confidence',()=>{const item=evidence({confidence:'conflicting'}),copy=structuredClone(item);copy.documentRevision=undefined;copy.evidenceDate=undefined;copy.notes='';copy.summary='';copy.authorOrOrganisation=undefined;copy.externalUrl=undefined;expect(copy).toMatchObject({sourceType:'supplier_document',provenance:'supplier_specific',title:'Supplier specification',documentId:'DOC-1',confidence:'conflicting',notes:'',summary:''})})
 it('does not upgrade supplier evidence confidence',()=>expect(evidence({confidence:'unknown'})).toMatchObject({sourceType:'supplier_document',confidence:'unknown'}))
 it('rejects invalid dates, unsafe URLs, and private paths',()=>{const p=profile(),errors=validateIngredientKnowledgeAggregate({profile:p,roles:[],compatibility:[],evidence:[evidence({evidenceDate:'not-a-date',externalUrl:'file:///secret.pdf',documentId:'/private/bucket/secret.pdf'})]},['i1']);expect(errors.join(' ')).toContain('invalid date');expect(errors.join(' ')).toContain('unsupported URL');expect(errors.join(' ')).toContain('private storage path')})
 it('allows unlinked Evidence deletion but identifies linked records before deletion',()=>{const e=evidence(),roles=[role()],relations=[compatibility()];expect(roles.filter(item=>item.evidenceIds.includes(e.id))).toHaveLength(1);expect(relations.filter(item=>item.evidenceIds.includes(e.id))).toHaveLength(1);roles[0].evidenceIds=[];relations[0].evidenceIds=[];expect([...roles,...relations].some(item=>item.evidenceIds.includes(e.id))).toBe(false);expect([e].filter(item=>item.id!==e.id)).toEqual([])})
})
