begin;
select plan(46);
select has_table('public','finished_goods_inventory_operations','operation journal exists');
select has_table('public','finished_goods_inventory_state_history','state history exists');
select has_table('public','finished_goods_inventory_events','inventory events exist');
select has_pk('public','finished_goods_inventory_operations','has primary key');
select has_pk('public','finished_goods_inventory_state_history','has primary key');
select has_pk('public','finished_goods_inventory_events','has primary key');
select has_column('public','finished_goods_inventory_movements','operation_id','column exists');
select has_column('public','finished_goods_inventory_movements','related_movement_id','column exists');
select has_column('public','finished_goods_inventory_movements','from_location','column exists');
select has_column('public','finished_goods_inventory_movements','to_location','column exists');
select has_column('public','finished_goods_inventory_movements','reason','column exists');
select has_column('public','finished_goods_inventory_movements','evidence','column exists');
select has_column('public','finished_goods_inventory_movements','cost_confidence','column exists');
select has_column('public','finished_goods_inventory_operations','request_fingerprint','column exists');
select has_column('public','finished_goods_inventory_operations','expected_revision','column exists');
select has_column('public','finished_goods_inventory_state_history','quantity_delta','column exists');
select has_column('public','finished_goods_inventory_state_history','state_type','column exists');
select has_column('public','finished_goods_inventory_events','event_key','column exists');
select col_is_unique('public','finished_goods_inventory_operations',array['workspace_id','idempotency_key']);
select col_is_unique('public','finished_goods_inventory_state_history',array['workspace_id','event_key']);
select col_is_unique('public','finished_goods_inventory_events',array['workspace_id','event_key']);
select has_function('public','get_finished_goods_inventory_workspace_v1',array['uuid']);
select has_function('public','list_finished_goods_inventory_fefo_v1',array['text']);
select has_function('public','record_finished_goods_inventory_operation_v1',array['uuid','bigint','text','numeric','text','text','text','text','jsonb','uuid','timestamp with time zone','uuid']);
select function_privs_are('public','get_finished_goods_inventory_workspace_v1',array['uuid'],'authenticated',array['EXECUTE']);
select function_privs_are('public','get_finished_goods_inventory_workspace_v1',array['uuid'],'anon',array[]::text[]);
select function_privs_are('public','list_finished_goods_inventory_fefo_v1',array['text'],'authenticated',array['EXECUTE']);
select function_privs_are('public','record_finished_goods_inventory_operation_v1',array['uuid','bigint','text','numeric','text','text','text','text','jsonb','uuid','timestamp with time zone','uuid'],'authenticated',array['EXECUTE']);
select function_privs_are('public','record_finished_goods_inventory_operation_v1',array['uuid','bigint','text','numeric','text','text','text','text','jsonb','uuid','timestamp with time zone','uuid'],'anon',array[]::text[]);
select table_privs_are('public','finished_goods_inventory_operations','authenticated',array['SELECT']);
select table_privs_are('public','finished_goods_inventory_state_history','authenticated',array['SELECT']);
select table_privs_are('public','finished_goods_inventory_events','authenticated',array['SELECT']);
select table_privs_are('public','finished_goods_inventory_operations','anon',array[]::text[]);
select table_privs_are('public','finished_goods_inventory_state_history','anon',array[]::text[]);
select table_privs_are('public','finished_goods_inventory_events','anon',array[]::text[]);
select is((select relrowsecurity from pg_class where oid='public.finished_goods_inventory_operations'::regclass),true);
select is((select relrowsecurity from pg_class where oid='public.finished_goods_inventory_state_history'::regclass),true);
select is((select relrowsecurity from pg_class where oid='public.finished_goods_inventory_events'::regclass),true);
select trigger_is('public','finished_goods_inventory_operations','finished_goods_inventory_operations_append_only','public','kf_finished_goods_append_only');
select trigger_is('public','finished_goods_inventory_state_history','finished_goods_inventory_state_history_append_only','public','kf_finished_goods_append_only');
select trigger_is('public','finished_goods_inventory_events','finished_goods_inventory_events_append_only','public','kf_finished_goods_append_only');
select has_index('public','finished_goods_inventory_operations','finished_goods_inventory_operations_lot_idx','index exists');
select has_index('public','finished_goods_inventory_state_history','finished_goods_inventory_state_active_idx','index exists');
select has_index('public','finished_goods_inventory_events','finished_goods_inventory_events_lot_idx','index exists');
select has_index('public','released_finished_goods_inventory_lots','released_finished_goods_fefo_idx','index exists');
select has_index('public','finished_goods_inventory_movements','finished_goods_inventory_related_movement_idx','index exists');
select * from finish();
rollback;
