begin;
select plan(22);
select has_table('public','inventory_quality_release_reviews','quality review history exists');
select has_column('public','inventory_quarantine_intakes','released_quantity','released quantity is cumulative');
select has_column('public','inventory_quarantine_intakes','rejected_quantity','rejected quantity is cumulative');
select has_column('public','inventory_quality_release_reviews','review_version','reviews are versioned');
select has_column('public','inventory_quality_release_reviews','decision','disposition decision is explicit');
select has_column('public','inventory_quality_release_reviews','disposition_quantity','disposition quantity is explicit');
select has_column('public','inventory_quality_release_reviews','policy_version','release policy is snapshotted');
select has_column('public','inventory_quality_release_reviews','checklist_snapshot','checklist is snapshotted');
select has_column('public','inventory_quality_release_reviews','evidence','evidence metadata is retained');
select has_column('public','inventory_quality_release_reviews','inventory_lot_id','created lot provenance is retained');
select has_column('public','inventory_quality_release_reviews','opening_movement_id','opening movement provenance is retained');
select has_column('public','inventory_quality_release_reviews','total_acquisition_cost','cost snapshot is nullable');
select has_column('public','inventory_quality_release_reviews','acquisition_cost_source','cost source is explicit');
select has_column('public','inventory_lots','quarantine_intake_id','raw lot links to quarantine');
select has_column('public','inventory_lots','quality_release_review_id','raw lot links to release review');
select has_column('public','packaging_inventory_lots','quarantine_intake_id','packaging lot links to quarantine');
select has_column('public','packaging_inventory_lots','quality_release_review_id','packaging lot links to release review');
select has_function('public','review_quarantined_inventory',array['uuid','bigint','uuid','jsonb'],'atomic release RPC exists');
select results_eq($$select relrowsecurity from pg_class where oid='public.inventory_quality_release_reviews'::regclass$$,array[true],'review RLS active');
select results_eq($$select has_table_privilege('anon','public.inventory_quality_release_reviews','select')$$,array[false],'anonymous review reads denied');
select results_eq($$select has_table_privilege('authenticated','public.inventory_quality_release_reviews','insert')$$,array[false],'browser review inserts denied');
select results_eq($$select has_function_privilege('authenticated','public.review_quarantined_inventory(uuid,bigint,uuid,jsonb)','execute')$$,array[true],'authenticated owner can call release RPC');
select * from finish();
rollback;
