begin;
select plan(18);
select has_table('public','purchase_order_audit_events','draft audit table exists');
select has_column('public','purchase_orders','source_purchase_plan_basket_id','orders retain source basket');
select has_column('public','purchase_orders','verification_snapshot','orders retain verification snapshot');
select has_column('public','purchase_orders','commercial_snapshot','orders retain commercial snapshot');
select has_column('public','purchase_orders','handoff_policy_version','orders retain policy version');
select has_column('public','purchase_order_lines','expected_unit_price','lines retain expected price');
select has_column('public','purchase_order_lines','verified_unit_price','lines retain verified price');
select has_column('public','purchase_order_lines','effective_unit_price','lines retain effective price');
select has_column('public','purchase_order_lines','verification_snapshot','lines retain verification provenance');
select has_function('public','create_draft_purchase_orders_from_plan',array['uuid','bigint','uuid'],'multi-basket handoff RPC exists');
select has_function('public','cancel_draft_purchase_order',array['uuid','bigint','text'],'draft cancellation RPC exists');
select function_lang_is('public','create_draft_purchase_orders_from_plan',array['uuid','bigint','uuid'],'plpgsql','handoff is server-side');
select function_lang_is('public','cancel_draft_purchase_order',array['uuid','bigint','text'],'plpgsql','cancellation is server-side');
select is_definer('public','create_draft_purchase_orders_from_plan',array['uuid','bigint','uuid'],'handoff validates through a definer boundary');
select is_definer('public','cancel_draft_purchase_order',array['uuid','bigint','text'],'cancellation validates through a definer boundary');
select table_privs_are('public','purchase_order_audit_events','authenticated',array['SELECT'],'audit is read-only to browser clients');
select table_privs_are('public','purchase_orders','authenticated',array['SELECT'],'orders remain read-only to browser clients');
select table_privs_are('public','purchase_order_lines','authenticated',array['SELECT'],'order lines remain read-only to browser clients');
select * from finish();
rollback;
