begin;
select plan(20);
select has_column('public','purchase_orders','actual_grand_total','actual total is separate');
select has_column('public','purchase_orders','actual_currency','actual currency is separate');
select has_column('public','purchase_orders','placement_evidence','evidence snapshot exists');
select has_column('public','purchase_orders','placement_comparison','three-layer comparison exists');
select has_column('public','purchase_orders','first_order_discount_applied','actual discount usage is recorded');
select has_column('public','purchase_order_lines','actual_package_count','line package actual exists');
select has_column('public','purchase_order_lines','actual_unit_price','line price actual exists');
select has_column('public','purchase_order_lines','placement_actual_snapshot','line placement snapshot exists');
select has_function('public','record_verified_purchase_order_placement',array['uuid','bigint','uuid','jsonb'],'verified placement RPC exists');
select function_lang_is('public','record_verified_purchase_order_placement',array['uuid','bigint','uuid','jsonb'],'plpgsql','placement is server-side');
select is_definer('public','record_verified_purchase_order_placement',array['uuid','bigint','uuid','jsonb'],'placement uses controlled definer boundary');
select function_privs_are('public','record_verified_purchase_order_placement',array['uuid','bigint','uuid','jsonb'],'anon',array[]::text[],'anonymous has no placement execution');
select function_privs_are('public','record_verified_purchase_order_placement',array['uuid','bigint','uuid','jsonb'],'authenticated',array['EXECUTE'],'authenticated may call validated placement');
select table_privs_are('public','purchase_orders','authenticated',array['SELECT'],'orders remain browser read-only');
select table_privs_are('public','purchase_order_lines','authenticated',array['SELECT'],'order lines remain browser read-only');
select table_privs_are('public','purchase_order_audit_events','authenticated',array['SELECT'],'audit remains browser read-only');
select col_is_null('public','purchase_orders','actual_grand_total','legacy and draft orders need not have actual totals');
select col_is_null('public','purchase_order_lines','actual_unit_price','unplaced lines need not have actual prices');
select has_index('public','purchase_orders','purchase_orders_placement_key','placement retry key is indexed uniquely');
select has_index('public','purchase_orders','purchase_orders_supplier_reference','supplier references are unique for executed orders');
select * from finish();
rollback;
