begin;
select plan(36);
select has_table('public','packaged_output_reconciliations','reconciliations exist');
select has_table('public','finished_goods_lots','lots exist');
select has_table('public','finished_goods_quarantines','quarantines exist');
select has_table('public','finished_goods_lot_events','events exist');
select has_pk('public','packaged_output_reconciliations','reconciliations have PK');
select has_pk('public','finished_goods_lots','lots have PK');
select has_pk('public','finished_goods_quarantines','quarantines have PK');
select has_pk('public','finished_goods_lot_events','events have PK');
select has_column('public','finished_goods_lots','consumer_batch_code','batch code exists');
select has_column('public','finished_goods_lots','product_snapshot','product snapshot exists');
select has_column('public','finished_goods_lots','formula_snapshot','formula snapshot exists');
select has_column('public','finished_goods_lots','packaging_snapshot','packaging snapshot exists');
select has_column('public','finished_goods_lots','label_snapshot','label snapshot exists');
select has_column('public','finished_goods_lots','cost_snapshot','cost snapshot exists');
select has_column('public','finished_goods_lots','genealogy_snapshot','genealogy snapshot exists');
select has_column('public','finished_goods_quarantines','remaining_quantity','remaining quantity exists');
select col_is_unique('public','finished_goods_lots',array['workspace_id','consumer_batch_code']);
select col_is_unique('public','finished_goods_lots',array['workspace_id','internal_lot_code']);
select has_function('public','get_packaging_run_finished_goods_readiness_v1',array['uuid']);
select has_function('public','record_packaged_output_reconciliation_v1',array['uuid','bigint','numeric','numeric','numeric','numeric','numeric','numeric','numeric','text','text','text','timestamp with time zone','uuid']);
select has_function('public','create_finished_goods_lot_v1',array['uuid','bigint','numeric','text','text','text','text','date','text','integer','text','date','text','text','integer','text','text','boolean','text','text','boolean','timestamp with time zone','uuid']);
select has_function('public','get_finished_goods_lot_genealogy_v1',array['uuid']);
select function_privs_are('public','get_packaging_run_finished_goods_readiness_v1',array['uuid'],'authenticated',array['EXECUTE']);
select function_privs_are('public','get_packaging_run_finished_goods_readiness_v1',array['uuid'],'anon',array[]::text[]);
select table_privs_are('public','finished_goods_lots','authenticated',array['SELECT']);
select table_privs_are('public','finished_goods_quarantines','authenticated',array['SELECT']);
select table_privs_are('public','packaged_output_reconciliations','authenticated',array['SELECT']);
select table_privs_are('public','finished_goods_lot_events','authenticated',array['SELECT']);
select table_privs_are('public','finished_goods_lots','anon',array[]::text[]);
select is((select relrowsecurity from pg_class where oid='public.finished_goods_lots'::regclass),true);
select is((select relrowsecurity from pg_class where oid='public.finished_goods_quarantines'::regclass),true);
select is((select relrowsecurity from pg_class where oid='public.packaged_output_reconciliations'::regclass),true);
select trigger_is('public','finished_goods_lots','finished_goods_lots_append_only','public','kf_finished_goods_append_only');
select trigger_is('public','finished_goods_quarantines','finished_goods_quarantines_append_only','public','kf_finished_goods_append_only');
select has_index('public','finished_goods_lots','finished_goods_lots_run_idx','lot run index exists');
select has_index('public','finished_goods_lot_events','finished_goods_events_lot_idx','event lot index exists');
select * from finish();
rollback;
