begin;
select plan(63);
select has_table('public','finished_goods_inspections','inspection history exists');
select has_table('public','finished_goods_deviations','deviations exist');
select has_table('public','finished_goods_disposition_reviews','disposition reviews exist');
select has_table('public','released_finished_goods_inventory_lots','released inventory lots exist');
select has_table('public','finished_goods_inventory_movements','canonical movements exist');
select has_table('public','finished_goods_quality_events','quality events exist');
select has_pk('public','finished_goods_inspections','inspections have PK');
select has_pk('public','finished_goods_deviations','deviations have PK');
select has_pk('public','finished_goods_disposition_reviews','reviews have PK');
select has_pk('public','released_finished_goods_inventory_lots','inventory lots have PK');
select has_pk('public','finished_goods_inventory_movements','movements have PK');
select has_pk('public','finished_goods_quality_events','events have PK');
select has_column('public','finished_goods_inspections','supersedes_inspection_id','inspection supersession exists');
select has_column('public','finished_goods_inspections','evidence','inspection evidence exists');
select has_column('public','finished_goods_deviations','severity','deviation severity exists');
select has_column('public','finished_goods_deviations','approval','deviation approval exists');
select has_column('public','finished_goods_disposition_reviews','decision','decision exists');
select has_column('public','finished_goods_disposition_reviews','released_inventory_lot_id','released lot link exists');
select has_column('public','finished_goods_disposition_reviews','opening_movement_id','movement link exists');
select has_column('public','released_finished_goods_inventory_lots','cost_snapshot','cost snapshot exists');
select has_column('public','released_finished_goods_inventory_lots','consumer_batch_code','batch code exists');
select has_column('public','released_finished_goods_inventory_lots','expiry_date','expiry exists');
select has_column('public','finished_goods_inventory_movements','movement_type','movement type exists');
select col_is_unique('public','finished_goods_inspections',array['workspace_id','idempotency_key']);
select col_is_unique('public','finished_goods_deviations',array['workspace_id','idempotency_key']);
select col_is_unique('public','finished_goods_disposition_reviews',array['workspace_id','idempotency_key']);
select col_is_unique('public','released_finished_goods_inventory_lots',array['workspace_id','release_review_id']);
select col_is_unique('public','finished_goods_inventory_movements',array['workspace_id','idempotency_key']);
select has_function('public','get_finished_goods_inspection_plan_v1',array['uuid']);
select has_function('public','record_finished_goods_inspection_v1',array['uuid','bigint','text','text','numeric','text','text','jsonb','text','text','numeric','timestamp with time zone','uuid','uuid']);
select has_function('public','open_finished_goods_deviation_v1',array['uuid','bigint','uuid','text','text','numeric','text','text','jsonb','text','timestamp with time zone','uuid']);
select has_function('public','resolve_finished_goods_deviation_v1',array['uuid','text','jsonb','jsonb','timestamp with time zone','uuid']);
select has_function('public','get_finished_goods_release_readiness_v1',array['uuid']);
select has_function('public','record_finished_goods_disposition_v1',array['uuid','bigint','text','numeric','text','text','jsonb','text','boolean','timestamp with time zone','uuid']);
select has_function('public','get_finished_goods_quality_workspace_v1',array['uuid']);
select has_function('public','get_released_finished_goods_genealogy_v1',array['uuid']);
select function_privs_are('public','get_finished_goods_release_readiness_v1',array['uuid'],'authenticated',array['EXECUTE']);
select function_privs_are('public','get_finished_goods_release_readiness_v1',array['uuid'],'anon',array[]::text[]);
select function_privs_are('public','record_finished_goods_disposition_v1',array['uuid','bigint','text','numeric','text','text','jsonb','text','boolean','timestamp with time zone','uuid'],'authenticated',array['EXECUTE']);
select function_privs_are('public','record_finished_goods_disposition_v1',array['uuid','bigint','text','numeric','text','text','jsonb','text','boolean','timestamp with time zone','uuid'],'anon',array[]::text[]);
select table_privs_are('public','finished_goods_inspections','authenticated',array['SELECT']);
select table_privs_are('public','finished_goods_deviations','authenticated',array['SELECT']);
select table_privs_are('public','finished_goods_disposition_reviews','authenticated',array['SELECT']);
select table_privs_are('public','released_finished_goods_inventory_lots','authenticated',array['SELECT']);
select table_privs_are('public','finished_goods_inventory_movements','authenticated',array['SELECT']);
select table_privs_are('public','finished_goods_quality_events','authenticated',array['SELECT']);
select table_privs_are('public','finished_goods_inspections','anon',array[]::text[]);
select table_privs_are('public','finished_goods_disposition_reviews','anon',array[]::text[]);
select is((select relrowsecurity from pg_class where oid='public.finished_goods_inspections'::regclass),true);
select is((select relrowsecurity from pg_class where oid='public.finished_goods_deviations'::regclass),true);
select is((select relrowsecurity from pg_class where oid='public.finished_goods_disposition_reviews'::regclass),true);
select is((select relrowsecurity from pg_class where oid='public.released_finished_goods_inventory_lots'::regclass),true);
select is((select relrowsecurity from pg_class where oid='public.finished_goods_inventory_movements'::regclass),true);
select is((select relrowsecurity from pg_class where oid='public.finished_goods_quality_events'::regclass),true);
select trigger_is('public','finished_goods_inspections','finished_goods_inspections_append_only','public','kf_finished_goods_append_only');
select trigger_is('public','finished_goods_deviations','finished_goods_deviations_append_only','public','kf_finished_goods_append_only');
select trigger_is('public','finished_goods_disposition_reviews','finished_goods_disposition_reviews_append_only','public','kf_finished_goods_append_only');
select trigger_is('public','released_finished_goods_inventory_lots','released_finished_goods_inventory_lots_append_only','public','kf_finished_goods_append_only');
select trigger_is('public','finished_goods_inventory_movements','finished_goods_inventory_movements_append_only','public','kf_finished_goods_append_only');
select trigger_is('public','finished_goods_quarantines','finished_goods_quarantines_quality_guard','public','kf_finished_goods_quality_guard');
select has_index('public','finished_goods_inspections','finished_goods_inspections_lot_effective_idx','effective inspection index exists');
select has_index('public','finished_goods_deviations','finished_goods_deviations_lot_status_idx','deviation status index exists');
select has_index('public','finished_goods_inventory_movements','finished_goods_inventory_movement_lot_idx','movement lot index exists');
select * from finish();
rollback;
