begin;
select plan(30);
select has_table('public','purchase_order_receipts','receipt aggregate exists');
select has_table('public','purchase_order_receipt_shipments','receipt shipment links exist');
select has_table('public','purchase_order_receipt_lines','receipt lines exist');
select has_table('public','purchase_order_receipt_discrepancies','discrepancies exist');
select has_table('public','purchase_order_receipt_inspections','inspections exist');
select has_table('public','inventory_quarantine_intakes','quarantine intake exists');
select has_column('public','purchase_order_receipts','physical_receipt_date','physical arrival is explicit');
select has_column('public','purchase_order_receipts','package_count_received','package count is explicit');
select has_column('public','purchase_order_receipt_lines','ordered_quantity','ordered snapshot retained');
select has_column('public','purchase_order_receipt_lines','confirmed_quantity','confirmed snapshot retained');
select has_column('public','purchase_order_receipt_lines','shipped_quantity','shipped snapshot retained');
select has_column('public','purchase_order_receipt_lines','received_total_quantity','received quantity is distinct');
select has_column('public','purchase_order_receipt_lines','damaged_quantity','damaged quantity is distinct');
select has_column('public','purchase_order_receipt_lines','held_quantity','held quantity is distinct');
select has_column('public','purchase_order_receipt_lines','rejected_quantity','rejected quantity is distinct');
select has_column('public','purchase_order_receipt_lines','quarantine_candidate_quantity','candidate quantity is distinct');
select has_column('public','purchase_order_receipt_lines','supplier_lot_number','supplier lot retained');
select has_column('public','purchase_order_receipt_lines','documentation_checks','lot documents retained');
select has_column('public','purchase_order_receipt_discrepancies','resolution_status','discrepancy history retained');
select has_column('public','purchase_order_receipt_inspections','supersedes_inspection_id','inspection history linked');
select has_column('public','inventory_quarantine_intakes','quarantine_status','quarantine lifecycle separate');
select has_function('public','create_purchase_order_receipt',array['uuid','bigint','uuid','jsonb'],'receipt RPC exists');
select has_function('public','record_purchase_order_receipt_line',array['uuid','bigint','uuid','jsonb'],'receipt line RPC exists');
select has_function('public','record_purchase_order_receipt_discrepancy',array['uuid','bigint','uuid','jsonb'],'discrepancy RPC exists');
select has_function('public','record_purchase_order_receipt_inspection',array['uuid','bigint','uuid','jsonb'],'inspection RPC exists');
select has_function('public','complete_purchase_order_receiving',array['uuid','bigint','uuid'],'completion RPC exists');
select has_function('public','place_purchase_order_receipt_into_quarantine',array['uuid','bigint','uuid','jsonb'],'quarantine RPC exists');
select results_eq($$select relrowsecurity from pg_class where oid='public.purchase_order_receipts'::regclass$$,array[true],'receipt RLS active');
select results_eq($$select relrowsecurity from pg_class where oid='public.purchase_order_receipt_lines'::regclass$$,array[true],'receipt line RLS active');
select results_eq($$select relrowsecurity from pg_class where oid='public.inventory_quarantine_intakes'::regclass$$,array[true],'quarantine RLS active');
select * from finish();
rollback;
