begin;
select plan(32);
select has_table('public','purchase_order_confirmations','versioned confirmations exist');
select has_table('public','purchase_order_confirmation_lines','confirmation lines exist');
select has_table('public','purchase_order_shipments','shipments exist');
select has_table('public','purchase_order_shipment_lines','split shipment allocations exist');
select has_table('public','purchase_order_shipment_events','tracking history exists');
select has_column('public','purchase_order_confirmations','payload_fingerprint','confirmation fingerprint exists');
select has_column('public','purchase_order_confirmations','supersedes_confirmation_id','corrected confirmations are linked');
select has_column('public','purchase_order_confirmation_lines','ordered_product_snapshot','ordered snapshot is preserved');
select has_column('public','purchase_order_confirmation_lines','confirmed_snapshot','supplier snapshot is preserved');
select has_column('public','purchase_order_shipments','delivery_reported_at','delivery reporting is explicit');
select has_column('public','purchase_order_shipment_lines','backordered_remainder','split remainder is explicit');
select has_function('public','record_purchase_order_supplier_confirmation',array['uuid','bigint','uuid','jsonb'],'confirmation RPC exists');
select has_function('public','decide_purchase_order_confirmation',array['uuid','bigint','text','text','jsonb'],'decision RPC exists');
select has_function('public','create_purchase_order_shipment',array['uuid','uuid','bigint','uuid','jsonb'],'shipment RPC exists');
select has_function('public','record_purchase_order_shipment_status',array['uuid','bigint','text','jsonb','uuid'],'shipment status RPC exists');
select is_definer('public','record_purchase_order_supplier_confirmation',array['uuid','bigint','uuid','jsonb'],'confirmation uses controlled definer');
select is_definer('public','create_purchase_order_shipment',array['uuid','uuid','bigint','uuid','jsonb'],'shipment uses controlled definer');
select function_privs_are('public','record_purchase_order_supplier_confirmation',array['uuid','bigint','uuid','jsonb'],'anon',array[]::text[],'anonymous confirmation denied');
select function_privs_are('public','create_purchase_order_shipment',array['uuid','uuid','bigint','uuid','jsonb'],'anon',array[]::text[],'anonymous shipment denied');
select function_privs_are('public','record_purchase_order_supplier_confirmation',array['uuid','bigint','uuid','jsonb'],'authenticated',array['EXECUTE'],'authenticated confirmation RPC granted');
select function_privs_are('public','create_purchase_order_shipment',array['uuid','uuid','bigint','uuid','jsonb'],'authenticated',array['EXECUTE'],'authenticated shipment RPC granted');
select table_privs_are('public','purchase_order_confirmations','authenticated',array['SELECT'],'confirmations are browser read-only');
select table_privs_are('public','purchase_order_confirmation_lines','authenticated',array['SELECT'],'confirmation lines are browser read-only');
select table_privs_are('public','purchase_order_shipments','authenticated',array['SELECT'],'shipments are browser read-only');
select table_privs_are('public','purchase_order_shipment_lines','authenticated',array['SELECT'],'shipment lines are browser read-only');
select table_privs_are('public','purchase_order_shipment_events','authenticated',array['SELECT'],'shipment events are browser read-only');
select has_index('public','purchase_order_confirmations','purchase_order_confirmation_reference','supplier confirmation reference indexed');
select has_index('public','purchase_order_confirmations','purchase_order_confirmation_history','confirmation history indexed');
select has_index('public','purchase_order_shipments','purchase_order_shipment_reference','shipment reference indexed');
select has_index('public','purchase_order_shipments','purchase_order_shipment_tracking','tracking indexed');
select has_index('public','purchase_order_shipment_lines','purchase_order_shipment_lines_order','allocation lookup indexed');
select col_is_null('public','purchase_order_shipments','delivery_reported_at','delivery is not inferred');
select * from finish();
rollback;
