import{useMemo,useState}from'react'
import{ArrowLeft,ArrowRight,FlaskConical,Plus,X}from'lucide-react'
import{Link,useNavigate,useSearchParams}from'react-router-dom'
import{useFormulaData}from'../formulas/state/FormulaDataContext'
import type{ProductStudioSelection}from'../../types/domain'
import{formulationIssues}from'../formulas/domain/multiPhaseLogic'
import{formulationArchetypes,productTemplates}from'./domain/formulationEngine'
import{beardButterEvaluationFields,beardButterPhases,beardButterProcess,compareVariants,formulaPercentageTotal,orderedPhases,suggestedPhase,validEvaluationScore,type BeardButterVariant}from'./domain/beardButter'

const propertyOptions=['Soft balm-like texture','Firm butter','Quick melt on contact','Low greasiness','Easy scoopability','Fast absorption','High beard conditioning','Comfortable skin feel','Subtle scent','Warm-climate resilience']
const defaults={texture:'Smooth butter',firmness:'Medium',meltBehavior:'Melts on contact',absorptionFeel:'Balanced',greasiness:'Low to moderate',scoopability:'Easy',beardConditioning:'High',skinFeel:'Comfortable',scentStrength:'Subtle',packagingIntent:'Wide-mouth jar',climateConsiderations:'Temperate indoor storage'}

export function BeardButterStudioPage(){
 const data=useFormulaData(),navigate=useNavigate(),[params]=useSearchParams(),existing=data.productStudioConcepts.find(x=>x.id===params.get('concept')&&x.productType==='beard_butter')
 const previous=(existing?.analysis.targets??defaults)as typeof defaults
 const [name,setName]=useState(existing?.name??'Beard Butter concept'),[notes,setNotes]=useState(existing?.notes??''),[goals,setGoals]=useState(existing?.desiredProperties??[]),[targets,setTargets]=useState(previous)
 const initialLines=useMemo(()=>existing?.selectedIngredients.map(selection=>({ingredientId:selection.ingredientId,role:selection.role,phase:String((existing.analysis.phases as Record<string,string>|undefined)?.[selection.ingredientId]??suggestedPhase(data.ingredients.find(i=>i.id===selection.ingredientId)?.category??'',data.ingredients.find(i=>i.id===selection.ingredientId)?.commonName??'')),percentage:Number((existing.analysis.percentages as Record<string,number>|undefined)?.[selection.ingredientId]??0)}))??[],[data.ingredients,existing])
 const [lines,setLines]=useState(initialLines),[variants,setVariants]=useState<BeardButterVariant[]>((existing?.analysis.variants as BeardButterVariant[]|undefined)??[]),[message,setMessage]=useState('')
 const template=productTemplates.beard_butter,archetype=formulationArchetypes[template.archetypeId],total=formulaPercentageTotal(lines),ordered=orderedPhases(beardButterPhases),formulaIssues=formulationIssues(archetype.capabilities,beardButterPhases,lines,beardButterProcess)
 const add=(ingredientId:string)=>{const ingredient=data.ingredients.find(i=>i.id===ingredientId);if(!ingredient||lines.some(x=>x.ingredientId===ingredientId))return;setLines(current=>[...current,{ingredientId,role:ingredient.category,phase:suggestedPhase(ingredient.category,ingredient.commonName),percentage:0}])}
 const save=async()=>{const selections:ProductStudioSelection[]=lines.map(line=>({ingredientId:line.ingredientId,role:line.role,essential:true}));try{const concept=await data.saveProductStudioConcept({id:existing?.id,name,productType:'beard_butter',intentMode:'design',desiredProperties:goals,selectedIngredients:selections,scentDirections:targets.scentStrength?[targets.scentStrength]:[],candidateSubstitutes:{},notes,analysis:{targets,phases:Object.fromEntries(lines.map(x=>[x.ingredientId,x.phase])),percentages:Object.fromEntries(lines.map(x=>[x.ingredientId,x.percentage])),phaseDefinitions:beardButterPhases,manufacturingProcess:beardButterProcess,variants},generatedProductId:existing?.generatedProductId,generatedFormulaId:existing?.generatedFormulaId,generatedFormulaVersionId:existing?.generatedFormulaVersionId,procurementPlanId:existing?.procurementPlanId});setMessage('Beard Butter concept saved. Planning created no stock movement.');if(!existing)navigate(`/product-studio/beard-butter?concept=${concept.id}`,{replace:true})}catch(cause){setMessage(cause instanceof Error?cause.message:'The concept could not be saved. Try again.')}}
 const handoff=async()=>{if(!existing)return setMessage('Save the concept before creating a Formula.');if(formulaIssues.length)return setMessage(formulaIssues.join(' '));try{const result=await data.createFormulaFromStudio(existing.id,{productName:name,formulaName:`${name} — Studio Draft`,description:`Draft Beard Butter concept. Heat-processed anhydrous starting point requiring physical testing and safety review.`,lines,phaseDefinitions:beardButterPhases,manufacturingProcess:beardButterProcess});navigate(`/formulas/${result.formulaId}`)}catch{setMessage('The Formula could not be saved. Stay here and try again. If it repeats, refresh the workspace and review the highlighted composition.')}}
 const addVariant=()=>setVariants(current=>[...current,{id:crypto.randomUUID(),name:`Variant ${String.fromCharCode(65+current.length)}`,changes:['Record wax, butter, oil, cooling, whipping or fragrance change.'],evaluation:{}}])
 return <div className="beard-studio beard-butter-studio"><Link className="back-link" to="/product-studio"><ArrowLeft size={14}/>Product Studio</Link>
  <header className="beard-studio-header"><div><span className="eyebrow">Guided product design / Beard Butter</span><input aria-label="Concept name" value={name} onChange={e=>setName(e.target.value)}/><p>An anhydrous, heat-processed, multi-phase development workflow. Predictions and draft process guidance require competent formulation, physical testing and safety assessment.</p><small>Formulation system: {archetype.displayName} · {archetype.maturity}</small></div><button className="button" disabled={data.pendingActions.includes('saveProductStudioConcept')} onClick={()=>void save()}>Save concept</button></header>
  <nav className="studio-steps" aria-label="Beard Butter design steps">{['Intent','Targets','Phases','Formula','Process','Variants','Lab'].map((step,index)=><span key={step}><b>{index+1}</b>{step}</span>)}</nav>
  <section className="studio-goals"><div className="studio-section-heading"><div><span className="eyebrow">1 / intent and positioning</span><h2>Target product properties</h2></div></div><div className="goal-chips">{propertyOptions.map(goal=><button key={goal} aria-pressed={goals.includes(goal)} onClick={()=>setGoals(current=>current.includes(goal)?current.filter(x=>x!==goal):[...current,goal])}>{goal}</button>)}</div><div className="butter-target-grid">{Object.entries(targets).map(([key,value])=><label key={key}>{key.replace(/[A-Z]/g,x=>` ${x.toLowerCase()}`)}<input value={value} onChange={e=>setTargets(current=>({...current,[key]:e.target.value}))}/></label>)}</div></section>
  <section className="panel"><div className="studio-section-heading"><div><span className="eyebrow">2–4 / explicit formula phases</span><h2>Multi-phase composition</h2><p>Assign only supported workspace Ingredients. Unknown heat sensitivity remains a review item.</p></div><strong className={total===100?'studio-state ready':'studio-state review'}>{total.toFixed(2)}%</strong></div>
   <div className="phase-definition-grid">{ordered.map(phase=><article key={phase.code}><strong>Phase {phase.code} — {phase.name}</strong><span>{phase.minimumTemperature!=null?`${phase.minimumTemperature}–`:phase.maximumTemperature!=null?'≤ ':''}{phase.maximumTemperature??phase.targetTemperature??'Temperature not established'}{typeof(phase.maximumTemperature??phase.targetTemperature)==='number'?' °C':''}</span><p>{phase.instructions}</p></article>)}</div>
   <label>Add workspace ingredient<select value="" onChange={e=>add(e.target.value)}><option value="">Choose…</option>{data.ingredients.filter(i=>!lines.some(x=>x.ingredientId===i.id)&&i.status!=='Archived').map(i=><option value={i.id} key={i.id}>{i.commonName} · {i.category}</option>)}</select></label>
   <div className="butter-lines">{lines.map(line=>{const ingredient=data.ingredients.find(i=>i.id===line.ingredientId);return <div key={line.ingredientId}><strong>{ingredient?.commonName}</strong><select aria-label={`Phase for ${ingredient?.commonName}`} value={line.phase} onChange={e=>setLines(current=>current.map(x=>x===line?{...x,phase:e.target.value}:x))}>{ordered.map(p=><option key={p.code} value={p.code}>Phase {p.code}</option>)}</select><label>Percentage<input type="number" min="0" max="100" step=".1" value={line.percentage} onChange={e=>setLines(current=>current.map(x=>x===line?{...x,percentage:Number(e.target.value)}:x))}/></label><input aria-label={`Role for ${ingredient?.commonName}`} value={line.role} onChange={e=>setLines(current=>current.map(x=>x===line?{...x,role:e.target.value}:x))}/><button aria-label={`Remove ${ingredient?.commonName}`} onClick={()=>setLines(current=>current.filter(x=>x!==line))}><X size={14}/></button></div>})}</div>
   {formulaIssues.length>0&&<div className="form-error" role="alert">{formulaIssues.map(issue=><p key={issue}>{issue}</p>)}</div>}
  </section>
  <section className="procedure-panel"><span className="eyebrow">5 / draft manufacturing process</span><h2>Heat, cool-down and fill controls</h2><ol>{beardButterProcess.map(step=><li key={step.order}><strong>{step.title}</strong> — {step.instruction}{step.maximumTemperature!=null&&` Maximum ${step.maximumTemperature} °C.`}{step.critical&&' Critical step.'}</li>)}</ol></section>
  <section className="panel"><div className="studio-section-heading"><div><span className="eyebrow">6 / development comparison</span><h2>Variants and structured evaluation</h2><p>Use 1–5 scores consistently; graininess, separation, greasiness and residue are defect-oriented observations where lower may be preferable.</p></div><button className="button" onClick={addVariant}><Plus size={14}/>Add variant</button></div>{compareVariants(variants).map(variant=><article className="butter-variant" key={variant.id}><input value={variant.name} onChange={e=>setVariants(current=>current.map(x=>x.id===variant.id?{...x,name:e.target.value}:x))}/><textarea value={variant.changes.join('\n')} onChange={e=>setVariants(current=>current.map(x=>x.id===variant.id?{...x,changes:e.target.value.split('\n')}:x))}/><div>{beardButterEvaluationFields.map(field=><label key={field}>{field.replace(/[A-Z]/g,x=>` ${x.toLowerCase()}`)}<input type="number" min="1" max="5" value={variant.evaluation?.[field]??''} onChange={e=>{if(!e.target.value)return;const score=Number(e.target.value);if(!validEvaluationScore(score))return setMessage('Variant scores must be finite values from 1 to 5.');setVariants(current=>current.map(x=>x.id===variant.id?{...x,evaluation:{...x.evaluation,[field]:score}}:x))}}/></label>)}</div></article>)}</section>
  <section className="studio-handoff"><div><span className="eyebrow">7 / controlled handoff</span><h2>Draft Formula → Development → Lab Notebook → Testing</h2><p>Formula handoff preserves phase definitions and process steps. Development creates controlled variants against the Draft. Lab creation snapshots phase-aware weights and ordered execution steps. Inventory changes only through existing explicit allocation commitments.</p></div><textarea aria-label="Concept notes" value={notes} onChange={e=>setNotes(e.target.value)}/><div>{!existing?.generatedFormulaId&&<button className="button primary" disabled={formulaIssues.length>0||!lines.length||data.pendingActions.includes('createFormulaFromStudio')} onClick={()=>void handoff()}><FlaskConical size={14}/>{data.pendingActions.includes('createFormulaFromStudio')?'Creating Formula…':'Create multi-phase Formula Draft'}</button>}{existing?.generatedProductId&&existing.generatedFormulaVersionId&&<Link className="button" to={`/development/new?productType=beard_butter&productId=${existing.generatedProductId}&formulaVersionId=${existing.generatedFormulaVersionId}`}>Create Development Experiment</Link>}{existing?.generatedFormulaId&&<Link className="button" to={`/lab?formula=${existing.generatedFormulaId}`}>Prepare Lab Batch <ArrowRight size={14}/></Link>}</div>{message&&<p role="status">{message}</p>}</section>
 </div>
}
