import{useMemo,useState}from'react'
import{Link,useNavigate,useSearchParams}from'react-router-dom'
import{ArrowLeft,ArrowRight,Check,ChevronDown,FlaskConical,Info,PackageSearch,Plus,RefreshCw,ShoppingBasket,TriangleAlert,X}from'lucide-react'
import{useFormulaData}from'../formulas/state/FormulaDataContext'
import{useProcurement}from'../procurement/useProcurement'
import{procurementActions}from'../procurement/actions/procurementActions'
import{ingredientReferenceCatalog}from'../ingredients/reference/catalog'
import type{ProductStudioSelection}from'../../types/domain'
import{formulationIssues}from'../formulas/domain/multiPhaseLogic'
import{productTemplates,formulationArchetypes}from'./domain/formulationEngine'
import{analyzeCombination,beardOilArchitecture,beardOilProperties,equipmentReadiness,formulaStartingPoint,inventoryReadiness,maximumBatchSize,missingItemPlan,observedProfile,packagingReadiness,predictedProfile,profileIngredient,rankIngredients,scentDirections,substituteSuggestions}from'./domain/productStudio'

const severityIcon={information:Info,recommendation:RefreshCw,caution:TriangleAlert,blocking:X}
export function BeardOilStudioPage(){
 const data=useFormulaData(),procurement=useProcurement(),navigate=useNavigate(),[params]=useSearchParams(),mode=params.get('mode')==='make'?'make_today':'design',existing=data.productStudioConcepts.find(x=>x.id===params.get('concept')&&x.productType==='beard_oil')
 const[name,setName]=useState(existing?.name??(mode==='make_today'?'Today’s Beard Oil':'New Beard Oil Direction')),[goals,setGoals]=useState<string[]>(existing?.desiredProperties??[]),[selected,setSelected]=useState<ProductStudioSelection[]>(existing?.selectedIngredients??[]),[scent,setScent]=useState<string[]>(existing?.scentDirections??['Scent-free']),[notes,setNotes]=useState(existing?.notes??''),[details,setDetails]=useState(false),[message,setMessage]=useState('')
 const template=productTemplates.beard_oil,archetype=formulationArchetypes[template.archetypeId],ranked=useMemo(()=>rankIngredients(data.ingredients.filter(i=>i.status!=='Archived'),goals),[data.ingredients,goals]),findings=analyzeCombination(selected,data.ingredients),profile=predictedProfile(selected,data.ingredients),readiness=selected.length?inventoryReadiness(selected,data):[],equipment=equipmentReadiness(procurement.data?.equipment??[]),packaging=packagingReadiness(data.packagingComponents,data.packagingInventoryLots,data.packagingInventoryMovements),formula=selected.length?formulaStartingPoint(selected,data.ingredients):undefined,formulaIssues=formula?formulationIssues(archetype.capabilities,[],formula.lines,[]):[],missing=missingItemPlan(readiness,equipment,packaging),observed=observedProfile(data.labObservations.filter(observation=>{const batch=data.labBatches.find(x=>x.id===observation.labBatchId),version=batch&&data.formulaVersions.find(x=>x.id===batch.formulaVersionId),formulaRecord=version&&data.formulas.find(x=>x.id===version.formulaId),product=formulaRecord&&data.products.find(x=>x.id===formulaRecord.productId);return product?.name.toLowerCase().includes('beard oil')}))
 const add=(ingredientId:string)=>{if(selected.some(x=>x.ingredientId===ingredientId))return;const fit=profileIngredient(data.ingredients.find(x=>x.id===ingredientId)!);setSelected(current=>[...current,{ingredientId,role:fit.role,essential:fit.role==='liquid_base'}])}
 const save=()=>{const concept=data.saveProductStudioConcept({id:existing?.id,name,productType:'beard_oil',intentMode:mode,desiredProperties:goals,selectedIngredients:selected,scentDirections:scent,candidateSubstitutes:Object.fromEntries(readiness.filter(x=>x.state!=='ready').map(x=>[x.id,substituteSuggestions(x.id,data.ingredients,data.inventoryLots,data.inventoryMovements).map(s=>s.ingredientId)])),notes,analysis:{findings,profile,readiness,equipment,packaging},generatedProductId:existing?.generatedProductId,generatedFormulaId:existing?.generatedFormulaId,generatedFormulaVersionId:existing?.generatedFormulaVersionId,procurementPlanId:existing?.procurementPlanId});setMessage('Concept saved to the authoritative workspace.');if(!existing)navigate(`/product-studio/beard-oil?mode=${mode==='make_today'?'make':'design'}&concept=${concept.id}`,{replace:true})}
 const handoffFormula=()=>{if(!existing||!formula||formulaIssues.length||findings.some(x=>x.severity==='blocking'))return setMessage(formulaIssues.join(' ')||'Save the concept and resolve blocking architecture findings before Formula handoff.');const result=data.createFormulaFromStudio(existing.id,{productName:name,formulaName:`${name} — Studio Draft`,description:`Beard Oil concept: ${goals.join(', ')||'open direction'}. Predicted profile requires physical testing.`,lines:formula.lines});navigate(`/formulas/${result.formulaId}`)}
 const handoffProcurement=async()=>{if(!existing||!procurement.workspace)return setMessage('Save the concept in an active hosted workspace before Procurement handoff.');const lines=[...missing.ingredients.map((item,index)=>({inventoryDomain:'raw_material',supplierProductId:item.supplierProductId,description:item.name,quantity:1,unit:'g',reason:item.reason,basis:{conceptId:existing.id},displayOrder:index})),...missing.equipment.map((item,index)=>({inventoryDomain:'equipment',description:item.name,quantity:1,unit:'pcs',reason:item.reason,basis:{conceptId:existing.id},displayOrder:100+index})),...missing.packaging.map((item,index)=>({inventoryDomain:'packaging',description:item.name,quantity:1,unit:'pcs',reason:item.reason,basis:{conceptId:existing.id},displayOrder:200+index}))];try{await procurementActions.createProductStudioPurchasePlan(existing.id,lines);navigate('/suppliers?tab=plans')}catch(cause){setMessage(cause instanceof Error?cause.message:'Could not create Procurement plan.')}
 }
 return <div className="beard-studio"><Link className="back-link" to="/product-studio"><ArrowLeft size={14}/>Product Studio</Link><header className="beard-studio-header"><div><span className="eyebrow">{mode==='make_today'?'Inventory-aware workshop':'Guided product design'} / Beard Oil</span><input aria-label="Concept name" value={name} onChange={e=>setName(e.target.value)}/><p>{beardOilArchitecture.description}</p><small>Formulation system: {archetype.displayName} · {archetype.maturity}</small></div><div><button className="button" onClick={save}>Save concept</button>{existing?.generatedFormulaId&&<Link className="button" to={`/formulas/${existing.generatedFormulaId}`}>Open generated Formula</Link>}</div></header>
 <nav className="studio-steps" aria-label="Beard Oil design steps">{['Direction','Properties','Build base','Support','Scent','Predict','Inventory','Handoff'].map((step,index)=><span key={step}><b>{index+1}</b>{step}</span>)}</nav>
 {mode==='make_today'&&<section className="make-today-banner"><PackageSearch/><div><h2>{readiness.length&&readiness.every(x=>x.state==='ready')&&equipment.every(x=>x.state==='ready')&&packaging.state==='ready'?'Ready to make':'Readiness needs attention'}</h2><p>{readiness.length?`Maximum realistic batch from selected ingredients: ${maximumBatchSize(readiness)} g.`:'Add ingredients or begin from an existing Formula.'} Supplier Products never count as stock.</p></div></section>}
 <section className="studio-goals"><div className="studio-section-heading"><div><span className="eyebrow">1–2 / product intent</span><h2>What should it feel like?</h2></div></div><div className="goal-chips">{beardOilProperties.map(goal=><button key={goal} aria-pressed={goals.includes(goal)} onClick={()=>setGoals(current=>current.includes(goal)?current.filter(x=>x!==goal):[...current,goal])}>{goals.includes(goal)&&<Check size={12}/>} {goal}</button>)}</div></section>
 <div className="studio-workbench"><section className="ingredient-picker"><div className="studio-section-heading"><div><span className="eyebrow">3–4 / ingredient selection</span><h2>{mode==='make_today'?'Stocked and workspace ingredients':'Ranked workspace ingredients'}</h2><p>Recommendations explain their deterministic match. Curated library materials must be adopted before Formula use.</p></div></div><div className="studio-ingredient-grid">{ranked.filter(item=>mode!=='make_today'||inventoryReadiness([{ingredientId:item.fit.ingredient.id,role:item.fit.role,essential:true}],data)[0]?.available>0).map(({fit,score,reasons})=>{const stock=readiness.find(x=>x.id===fit.ingredient.id)??inventoryReadiness([{ingredientId:fit.ingredient.id,role:fit.role,essential:true}],data)[0];return <article key={fit.ingredient.id} className="studio-ingredient-card"><div><span className="eyebrow">{beardOilArchitecture.roles.find(x=>x.id===fit.role)?.label??fit.role}</span><h3>{fit.ingredient.commonName}</h3><p>{fit.ingredient.description}</p></div><dl><div><dt>Starting range</dt><dd>{fit.range.join('–')}%</dd></div><div><dt>Stock</dt><dd>{stock.available>0?`${stock.available} ${fit.ingredient.defaultUnit}`:'No Inventory Lot'}</dd></div><div><dt>Fit</dt><dd>{score>2?'Strong match':score>=0?'Possible':'Needs review'}</dd></div></dl><p className="why"><strong>Why?</strong> {reasons.join('; ')}.</p>{fit.cautions.length>0&&<small>{fit.cautions[0]}</small>}<footer><Link to={`/ingredients/${fit.ingredient.id}`}>Details</Link><button disabled={selected.some(x=>x.ingredientId===fit.ingredient.id)} onClick={()=>add(fit.ingredient.id)}><Plus size={13}/>{selected.some(x=>x.ingredientId===fit.ingredient.id)?'Added':'Add'}</button></footer></article>})}</div><details className="reference-discovery"><summary>Explore curated library materials not yet in the workspace</summary><div>{ingredientReferenceCatalog.filter(entry=>!data.ingredients.some(i=>i.referenceEntryId===entry.id||i.inciName.toLowerCase()===entry.inciName.toLowerCase())).slice(0,8).map(entry=><Link key={entry.id} to={`/ingredients/reference/${entry.id}`}><strong>{entry.commonName}</strong><span>{entry.category} · adopt before use</span></Link>)}</div></details></section>
 <aside className="composition-board"><div className="basket-heading"><ShoppingBasket/><div><span className="eyebrow">Live composition board</span><h2>{selected.length} ingredients</h2></div></div>{selected.length?selected.map((selection,index)=>{const ingredient=data.ingredients.find(i=>i.id===selection.ingredientId)!,fit=profileIngredient(ingredient),stock=readiness.find(x=>x.id===ingredient.id);return <article key={ingredient.id}><span>{index+1}</span><div><strong>{ingredient.commonName}</strong><select aria-label={`${ingredient.commonName} role`} value={selection.role} onChange={e=>setSelected(current=>current.map(x=>x.ingredientId===ingredient.id?{...x,role:e.target.value}:x))}>{beardOilArchitecture.roles.map(role=><option key={role.id} value={role.id}>{role.label}</option>)}</select><small>{fit.range.join('–')}% · {stock?.state==='ready'?'In stock':stock?.state==='low'?'Low stock':'Not in stock'}</small></div><label><input type="checkbox" checked={selection.essential} onChange={e=>setSelected(current=>current.map(x=>x.ingredientId===ingredient.id?{...x,essential:e.target.checked}:x))}/>Essential</label><button aria-label={`Remove ${ingredient.commonName}`} onClick={()=>setSelected(current=>current.filter(x=>x.ingredientId!==ingredient.id))}><X size={14}/></button></article>}):<div className="studio-empty"><p>Add a liquid base to begin. Percentages come later.</p></div>}</aside></div>
 <section className="scent-builder"><div><span className="eyebrow">5 / scent direction</span><h2>Choose a direction before materials</h2><p>Scent-free is fully supported. No maximum usage level is inferred.</p></div><div className="goal-chips">{scentDirections.map(direction=><button key={direction} aria-pressed={scent.includes(direction)} onClick={()=>setScent(direction==='Scent-free'?['Scent-free']:current=>[...current.filter(x=>x!=='Scent-free'&&x!==direction),...(current.includes(direction)?[]:[direction])])}>{direction}</button>)}</div></section>
 <section className="analysis-panel" aria-live="polite"><div className="studio-section-heading"><div><span className="eyebrow">6 / immediate deterministic analysis</span><h2>Combination findings</h2></div><button className="text-button" aria-expanded={details} onClick={()=>setDetails(x=>!x)}>Advanced details <ChevronDown size={14}/></button></div><div className="finding-list">{findings.map(finding=>{const Icon=severityIcon[finding.severity];return <article className={`finding ${finding.severity}`} key={finding.id}><Icon/><div><span>{finding.severity}</span><h3>{finding.title}</h3><p>{finding.explanation}</p>{details&&<><small>Evidence inputs: {finding.evidence.join(' · ')||'Curated architecture rule'}</small><ul>{finding.actions.map(action=><li key={action}>{action}</li>)}</ul><code>{finding.id}</code></>}</div></article>})}</div><div className="predicted-observed"><article><span className="eyebrow">{profile.label}</span><h3>{profile.richness} · {profile.absorption}</h3><dl>{Object.entries(profile).filter(([key])=>!['label','explanation'].includes(key)).map(([key,value])=><div key={key}><dt>{key.replace(/[A-Z]/g,x=>` ${x.toLowerCase()}`)}</dt><dd>{String(value)}</dd></div>)}</dl><p>{profile.explanation}</p></article><article><span className="eyebrow">{observed.label}</span><h3>{observed.available?'Linked physical evidence':'Awaiting a Lab Batch'}</h3>{observed.summary.map(summary=><p key={summary}>{summary}</p>)}{observed.evidenceIds.length>0&&<small>Evidence: {observed.evidenceIds.join(' · ')}</small>}</article></div></section>
 <section className="readiness-panel-studio"><div className="studio-section-heading"><div><span className="eyebrow">7 / real workspace comparison</span><h2>Inventory, equipment and packaging</h2></div></div><div className="readiness-columns"><article><h3>Ingredients</h3>{readiness.map(item=><div className={`readiness-row ${item.state}`} key={item.id}><span>{item.state}</span><div><strong>{item.name}</strong><small>{item.available.toFixed(2)} available / {item.required.toFixed(2)} g needed</small>{item.state!=='ready'&&substituteSuggestions(item.id,data.ingredients,data.inventoryLots,data.inventoryMovements).map(sub=><button key={sub.ingredientId} onClick={()=>setSelected(current=>current.map(x=>x.ingredientId===item.id?{...x,ingredientId:sub.ingredientId}:x))}>Replace with stocked {sub.name}</button>)}</div><Link to={`/ingredients/${item.id}`}>Open</Link></div>)}</article><article><h3>Equipment</h3>{equipment.map(item=><div className={`readiness-row ${item.state}`} key={item.type}><span>{item.level}</span><div><strong>{item.label}</strong><small>{item.explanation}</small></div><Link to="/equipment">Review</Link></div>)}</article><article><h3>Packaging</h3><div className={`readiness-row ${packaging.state}`}><span>{packaging.state}</span><div><strong>Suitable liquid packaging</strong><small>{packaging.explanation}</small></div><Link to="/packaging">Review</Link></div></article></div></section>
 <section className="procedure-panel"><span className="eyebrow">Guided preparation / Beard Oil procedure v1</span><h2>Preparation and Lab handoff</h2><ol>{beardOilArchitecture.procedure.map(step=><li key={step}>{step}</li>)}</ol><p>This generic procedure is operational guidance, not compliance approval. The existing Lab workflow records execution, lots, deviations and observations.</p></section>
 <section className="studio-handoff"><div><span className="eyebrow">8 / deliberate handoff</span><h2>Turn the concept into authoritative work</h2><p>Formula creation uses the existing Product, Formula, Draft Version and Formula Line model. Procurement creates a Draft plan and no order or stock.</p></div><textarea aria-label="Concept notes" placeholder="Concept notes" value={notes} onChange={e=>setNotes(e.target.value)}/><div><button className="button primary" onClick={handoffFormula} disabled={!selected.length||findings.some(x=>x.severity==='blocking')}><FlaskConical size={14}/>Create Formula Draft</button><button className="button" onClick={()=>void handoffProcurement()} disabled={!missing.ingredients.length&&!missing.equipment.length&&!missing.packaging.length}><PackageSearch size={14}/>Add missing items to Procurement</button>{existing?.generatedFormulaId&&<Link className="button" to={`/lab?formula=${existing.generatedFormulaId}`}>Prepare Lab Batch <ArrowRight size={14}/></Link>}</div>{message&&<p role="status">{message}</p>}</section>
 </div>
}
