import{ArrowLeft,ExternalLink,FlaskConical,ShoppingBasket}from'lucide-react'
import{Link}from'react-router-dom'

const benchmarks=[
 {name:'GEHWOL MED Antiperspirant Lotion',format:'Lotion / emulsion',role:'Sweat-control benchmark',source:'https://www.gehwol.de/GEHWOL-MED-Antiperspirant-Lotion/en',manufacturerPositioning:'Manufacturer reports sweat reduction and foot-odour protection with aluminium chlorohydrate; panthenol is included for skin care.',inci:['Aqua (Water)','Aluminum Chlorohydrate','Cetyl Alcohol','Distearoylethyl Dimonium Chloride','Cetearyl Alcohol','Panthenol','Phenoxyethanol','Citric Acid','Parfum (Fragrance)','Camphor','Coumarin','Lavandula Oil/Extract','Linalool','Linalyl Acetate','Menthol','Pogostemon Cablin Oil','Tetramethyl Acetyloctahydronaphthalenes'],functions:['Antiperspirant active system','Emulsion / conditioning base','Skin-conditioning support','Fragrance / sensory system','Preservation and pH support']},
 {name:'GEHWOL MED Deodorant Foot Creme',format:'Cream / emulsion',role:'Odour-control + care benchmark',source:'https://www.gehwol.de/937',manufacturerPositioning:'Manufacturer positions this as a deodorising foot cream with zinc oxide, manuka extract, aloe vera and jojoba oil in a moisturising cream base.',inci:['Aqua (Water)','Isopropyl Palmitate','Propylene Glycol','Polyglyceryl-3 Methylglucose Distearate','Simmondsia Chinensis (Jojoba) Seed Oil','Glyceryl Stearate','Cetyl Alcohol','PPG-3 Benzyl Ether Myristate','Octyldodecanol','Zinc Oxide','Leptospermum Scoparium (Manuka) Leaf Extract','Aloe Barbadensis Leaf Juice Powder','Xanthan Gum','Sodium Caproyl/Lauroyl Lactylate','Triethyl Citrate','Salvia Officinalis (Sage) Oil','Phenoxyethanol','Methylparaben','Ethylparaben','Caprylyl Glycol','Parfum (Fragrance)'],functions:['Deodorising support','Skin-protective powder phase','Emollient / lipid care','Humectant and skin-conditioning support','Emulsification / rheology','Preservation','Fragrance / botanical sensory system']},
 {name:'GEHWOL Foot + Shoe Deodorant',format:'Aerosol spray',role:'Foot + footwear freshness benchmark',source:'https://www.gehwol.de/102360800',manufacturerPositioning:'Manufacturer positions this as a foot-and-shoe deodorant spray; zinc ricinoleate is highlighted for odour control and the formula is alcohol/aerosol based.',inci:['Alcohol denat.','Butane','Propane','Zinc Ricinoleate','Parfum (Fragrance)','Triethanolamine','Propylene Glycol','Tetramethyl Acetyloctahydronaphthalenes','Ethylhexylglycerin','Dipropylene Glycol','Hexyl Cinnamal','Acetyl Cedrene','Limonene','Rosin','Citrus Aurantium Peel Oil','Lactic Acid','Lavandula Oil/Extract','Octenidine HCL','Citrus Limon Peel Oil','Pogostemon Cablin Oil','Alpha-Isomethyl Ionone','Citronellol','Linalool','Linalyl Acetate','Pelargonium Graveolens Flower Oil','Pinene','Camphor','Glyceryl Stearate','Citric Acid','Ascorbyl Palmitate','BHT'],functions:['Volatile alcohol carrier','Aerosol propellant system','Odour-binding support','Humectant / solvent support','Fragrance system','Antimicrobial-support ingredients reported by manufacturer','Antioxidant / formula support']},
] as const

const rawMaterialGroups=[
 {title:'Sweat-control actives',items:['Aluminum Chlorohydrate'],note:'Required only if Koalafrog deliberately develops an antiperspirant product. Regulatory, safety and supplier-document review remain separate.'},
 {title:'Odour-control system',items:['Zinc Ricinoleate','Triethyl Citrate','Zinc Oxide'],note:'Benchmark functions are separated so alternatives can be researched without copying a reference formula.'},
 {title:'Skin-care base',items:['Panthenol','Glycerin','Jojoba Oil','Aloe Vera','Emollient esters','Fatty alcohols'],note:'Build the care profile independently around foot feel, absorption, residue and barrier support.'},
 {title:'Structure / emulsification',items:['Polyglyceryl-3 Methylglucose Distearate','Glyceryl Stearate','Cetearyl/Cetyl Alcohol','Xanthan Gum'],note:'A cream/lotion workflow requires an operational emulsion capability before Formula handoff.'},
 {title:'Spray system',items:['Alcohol denat.','Propellant system','Solvent / humectant support'],note:'Aerosol packaging and propellant handling are a distinct future production capability; do not treat the benchmark as a simple liquid.'},
]

export function FootCareStudioPage(){return <div className="product-studio-entry">
 <Link className="back-link" to="/product-studio"><ArrowLeft size={14}/>Product Studio</Link>
 <header className="studio-hero"><span className="eyebrow">Product Studio / Foot Care research slice</span><h1>Foot Care</h1><p>Start from verified benchmark evidence, separate function from formula, map raw-material gaps, then hand deliberate sourcing work into Ingredients and Procurement.</p><small>Research-first. No benchmark percentages are inferred or copied.</small></header>
 <section className="studio-section"><div className="studio-section-heading"><div><span className="eyebrow">1 / benchmark set</span><h2>Three GEHWOL references</h2><p>Current manufacturer pages are recorded as reference evidence. Manufacturer positioning is not treated as Koalafrog efficacy evidence.</p></div></div><div className="studio-concepts">{benchmarks.map(item=><article key={item.name} className="studio-ready-card"><FlaskConical/><div><span className="studio-state review">{item.role}</span><h3>{item.name}</h3><p>{item.format} · {item.manufacturerPositioning}</p><details><summary>INCI snapshot ({item.inci.length})</summary><p>{item.inci.join(' · ')}</p></details><details><summary>Functional map</summary><p>{item.functions.join(' · ')}</p></details></div><a href={item.source} target="_blank" rel="noreferrer">Manufacturer source <ExternalLink size={13}/></a></article>)}</div></section>
 <section className="studio-section"><div className="studio-section-heading"><div><span className="eyebrow">2 / function-first decomposition</span><h2>Raw-material families to investigate</h2><p>The benchmark set suggests several different product architectures. Koalafrog should choose the intended job first instead of combining every benchmark ingredient into one product.</p></div><Link className="button" to="/ingredients">Open Ingredients</Link></div><div className="studio-ready-grid">{rawMaterialGroups.map(group=><article className="studio-ready-card" key={group.title}><ShoppingBasket/><div><h3>{group.title}</h3><p>{group.items.join(' · ')}</p><small>{group.note}</small></div></article>)}</div></section>
 <section className="studio-section"><div className="studio-section-heading"><div><span className="eyebrow">3 / operational handoff</span><h2>Research → Ingredients → Procurement → Formula</h2><p>Adopt only documented raw materials into Ingredients, source missing Supplier Products through Procurement, then return here for a dedicated Foot Care formulation workflow. Emulsions and aerosol systems must not be forced through the existing simple-liquid or solid-stick engines.</p></div></div><div className="studio-entry-actions"><Link to="/ingredients"><span><strong>Review adopted Ingredients</strong><small>Check what is already canonical before creating new material records.</small></span></Link><Link to="/suppliers"><span><strong>Open Procurement</strong><small>Create or run sourcing work for documented cosmetic-grade raw materials and supplier evidence.</small></span></Link><Link to="/formulas"><span><strong>Formula Library</strong><small>Formula handoff remains blocked until the chosen Foot Care physical system is operational.</small></span></Link></div></section>
 <section className="studio-coming"><span className="eyebrow">Foot Care capability gate</span><p><strong>Research and sourcing slice operational.</strong> Emulsion formulation and aerosol production remain explicit capability gaps; they are not silently approximated.</p></section>
 </div>}
