import{useMemo,useState}from'react'
import{ArrowLeft,Check,FlaskConical,Plus,ShoppingBasket,Sparkles,TriangleAlert,X}from'lucide-react'
import{Link,useNavigate,useSearchParams}from'react-router-dom'
import{useFormulaData}from'../formulas/state/FormulaDataContext'
import{useProcurement}from'../procurement/useProcurement'
import{procurementActions}from'../procurement/actions/procurementActions'
import type{ProductStudioSelection}from'../../types/domain'
import{inventoryReadiness}from'./domain/productStudio'
import{buildFragranceFormula,fragranceConcentrations,fragranceDirections,fragranceHandoffIssues,isAlcoholCarrier,isFragranceMaterial,normalizeConcentratePercentages}from'./domain/fragrance'

export function FragranceStudioPage(){
 const data=useFormulaData(),procurement=useProcurement(),navigate=useNavigate(),[params]=useSearchParams()
 const existing=data.productStudioConcepts.find(concept=>concept.id===params.get('concept')&&String(concept.productType)==='fragrance')
 const savedAnalysis=(existing?.analysis??{})as Record<string,unknown>
 const[name,setName]=useState(existing?.name??'Koalafrog Fragrance 001')
 const[brief,setBrief]=useState(String(savedAnalysis.olfactiveBrief??'Dark, sophisticated and distinctive. Leather and warm woods with dry spice; luxurious without becoming heavy or sweet.'))
 const[directions,setDirections]=useState<string[]>(existing?.scentDirections?.length?existing.scentDirections:['Dark leather','Warm woods','Dry spice'])
 const[selected,setSelected]=useState<ProductStudioSelection[]>(existing?.selectedIngredients??[])
 const[targetConcentration,setTargetConcentration]=useState(Number(savedAnalysis.targetConcentration??18))
 const[percentages,setPercentages]=useState<Record<string,number>>(()=>((savedAnalysis.concentratePercentages as Record<string,number>|undefined)??{}))
 const[message,setMessage]=useState('')
 const materials=useMemo(()=>data.ingredients.filter(isFragranceMaterial).sort((a,b)=>a.commonName.localeCompare(b.commonName)),[data.ingredients])
 const alcohol=data.ingredients.find(isAlcoholCarrier)
 const normalized=normalizeConcentratePercentages(selected,percentages)
 const readiness=selected.length?inventoryReadiness(selected,data):[]
 const finishedFormula=alcohol&&selected.length?buildFragranceFormula({selections:selected,percentages:normalized,targetConcentration,alcoholIngredientId:alcohol.id}):undefined
 const add=(ingredientId:string)=>{if(selected.some(item=>item.ingredientId===ingredientId))return;setSelected(current=>[...current,{ingredientId,role:'fragrance_material',essential:true}]);setPercentages(current=>({...current,[ingredientId]:1}))}
 const remove=(ingredientId:string)=>{setSelected(current=>current.filter(item=>item.ingredientId!==ingredientId));setPercentages(current=>{const next={...current};delete next[ingredientId];return next})}
 const save=async()=>{try{const draft={id:existing?.id,name,productType:'fragrance',intentMode:'design',desiredProperties:[brief],selectedIngredients:selected,scentDirections:directions,candidateSubstitutes:{},notes:'Fine-fragrance Product Studio concept. Predictions remain hypotheses until evaluated in Lab.',analysis:{olfactiveBrief:brief,targetConcentration,concentratePercentages:normalized,alcoholCarrierIngredientId:alcohol?.id??null,alcoholCarrierState:alcohol?'adopted':'missing',materialReadiness:readiness},generatedProductId:existing?.generatedProductId,generatedFormulaId:existing?.generatedFormulaId,generatedFormulaVersionId:existing?.generatedFormulaVersionId,procurementPlanId:existing?.procurementPlanId}as unknown as Parameters<typeof data.saveProductStudioConcept>[0];const concept=await data.saveProductStudioConcept(draft);setMessage('Fragrance concept saved.');if(!existing)navigate(`/product-studio/fragrance?concept=${concept.id}`,{replace:true})}catch(cause){setMessage(cause instanceof Error?cause.message:'The fragrance concept could not be saved.')}}
 const handoffFormula=async()=>{const issues=fragranceHandoffIssues({saved:Boolean(existing),selections:selected,percentages:normalized,targetConcentration,alcoholIngredientId:alcohol?.id});if(issues.length){setMessage(issues.join(' '));return}try{const formula=buildFragranceFormula({selections:selected,percentages:normalized,targetConcentration,alcoholIngredientId:alcohol!.id});const result=await data.createFormulaFromStudio(existing!.id,{productName:name,formulaName:`${name} — Studio Draft`,description:`Fine fragrance · ${targetConcentration}% concentrate in an alcohol-based carrier. Olfactive brief: ${brief} Physical scent evaluation, solubility, stability, allergen and IFRA review remain required.`,lines:formula.lines});navigate(`/formulas/${result.formulaId}`)}catch(cause){setMessage(cause instanceof Error?cause.message:'The fragrance Formula could not be created.') }}
 const handoffProcurement=async()=>{if(!existing||!procurement.workspace){setMessage('Save the concept in an active hosted workspace before Procurement handoff.');return}const missing=readiness.filter(item=>item.state!=='ready');const lines=[...missing.map((item,index)=>({inventoryDomain:'raw_material',supplierProductId:item.supplierProduct?.id,description:item.name,quantity:1,unit:'g',reason:'Selected fragrance material has no usable Inventory Lot for development.',basis:{conceptId:existing.id,productType:'fragrance'},displayOrder:index})),...(!alcohol?[{inventoryDomain:'raw_material',description:"Perfumer's alcohol / cosmetic-grade ethanol",quantity:1,unit:'L',reason:'Required alcohol carrier is not yet an adopted workspace Ingredient. Source a documented cosmetic/perfumery-grade material before finished Formula handoff.',basis:{conceptId:existing.id,productType:'fragrance'},displayOrder:100}]:[])];if(!lines.length){setMessage('Selected materials and alcohol carrier are already represented in the workspace inventory.');return}try{await procurementActions.createProductStudioPurchasePlan(existing.id,lines);navigate('/suppliers?tab=plans')}catch(cause){setMessage(cause instanceof Error?cause.message:'Could not create the fragrance Procurement plan.')}}
 return <div className="beard-studio fragrance-studio">
  <Link className="back-link" to="/product-studio"><ArrowLeft size={14}/>Product Studio</Link>
  <header className="beard-studio-header"><div><span className="eyebrow">Guided product design / Fine Fragrance</span><input aria-label="Concept name" value={name} onChange={event=>setName(event.target.value)}/><p>Build the scent as a 100% fragrance concentrate, then deliberately dilute it into an alcohol-based finished Formula.</p><small>Formulation system: Alcohol-based · operational fragrance vertical slice</small></div><div><button className="button" disabled={data.pendingActions.includes('saveProductStudioConcept')} onClick={()=>void save()}>Save concept</button>{existing?.generatedFormulaId&&<Link className="button" to={`/formulas/${existing.generatedFormulaId}`}>Open generated Formula</Link>}</div></header>
  <nav className="studio-steps" aria-label="Fragrance design steps">{['Brief','Direction','Palette','Concentrate','Dilution','Readiness','Handoff'].map((step,index)=><span key={step}><b>{index+1}</b>{step}</span>)}</nav>
  <section className="studio-goals"><div className="studio-section-heading"><div><span className="eyebrow">1 / olfactive brief</span><h2>What should it smell and feel like?</h2><p>Describe the desired experience before choosing materials. Existing stock must not dictate the creative brief.</p></div><Link className="button ghost" to="/scent-house/studio"><Sparkles size={14}/>Explore in Scent Studio</Link></div><textarea value={brief} onChange={event=>setBrief(event.target.value)} rows={4}/></section>
  <section className="scent-builder"><div><span className="eyebrow">2 / olfactive direction</span><h2>Choose the character</h2><p>Directions are intent labels, not claims about a smelled result.</p></div><div className="goal-chips">{fragranceDirections.map(direction=><button key={direction} aria-pressed={directions.includes(direction)} onClick={()=>setDirections(current=>current.includes(direction)?current.filter(item=>item!==direction):[...current,direction])}>{directions.includes(direction)&&<Check size={12}/>} {direction}</button>)}</div></section>
  <div className="studio-workbench"><section className="ingredient-picker"><div className="studio-section-heading"><div><span className="eyebrow">3 / workspace fragrance palette</span><h2>Build the concentrate palette</h2><p>Only adopted workspace fragrance materials are available here. Missing aroma chemicals, musks, amber woods, leather materials or other gaps should go to Procurement rather than being silently substituted.</p></div></div><div className="studio-ingredient-grid">{materials.map(material=>{const stock=inventoryReadiness([{ingredientId:material.id,role:'fragrance_material',essential:true}],data)[0];return <article key={material.id} className="studio-ingredient-card"><div><span className="eyebrow">{material.category}</span><h3>{material.commonName}</h3><p>{material.description||material.inciName}</p></div><dl><div><dt>Inventory</dt><dd>{stock?.available>0?`${stock.available.toFixed(2)} ${material.defaultUnit}`:'No usable lot'}</dd></div><div><dt>Status</dt><dd>{material.status}</dd></div></dl><footer><Link to={`/ingredients/${material.id}`}>Details</Link><button disabled={selected.some(item=>item.ingredientId===material.id)} onClick={()=>add(material.id)}><Plus size={13}/>{selected.some(item=>item.ingredientId===material.id)?'Added':'Add'}</button></footer></article>})}</div>{!materials.length&&<div className="studio-empty"><p>No adopted fragrance materials exist in the workspace yet. Use Ingredients or Procurement before attempting a Formula.</p></div>}</section>
   <aside className="composition-board"><div className="basket-heading"><ShoppingBasket/><div><span className="eyebrow">4 / fragrance concentrate</span><h2>{selected.length} {selected.length===1?'material':'materials'}</h2><small>The concentrate is normalized to 100%. Finished-product concentration is handled separately.</small></div></div>{selected.length?selected.map((selection,index)=>{const material=data.ingredients.find(item=>item.id===selection.ingredientId)!;return <article key={selection.ingredientId}><span>{index+1}</span><div><strong>{material.commonName}</strong><label>Concentrate % <input type="number" min="0.01" step="0.01" value={percentages[selection.ingredientId]??normalized[selection.ingredientId]??0} onChange={event=>setPercentages(current=>({...current,[selection.ingredientId]:Number(event.target.value)}))}/></label><small>Normalized: {(normalized[selection.ingredientId]??0).toFixed(2)}%</small></div><button aria-label={`Remove ${material.commonName}`} onClick={()=>remove(selection.ingredientId)}><X size={14}/></button></article>}):<div className="studio-empty"><p>Add at least two fragrance materials to begin building an accord or concentrate.</p></div>}</aside>
  </div>
  <section className="analysis-panel"><div className="studio-section-heading"><div><span className="eyebrow">5 / finished dilution</span><h2>Choose finished fragrance concentration</h2><p>This is separate from the 100% concentrate composition above.</p></div></div><div className="goal-chips">{fragranceConcentrations.map(option=><button key={option.label} aria-pressed={targetConcentration===option.value} onClick={()=>setTargetConcentration(option.value)}>{targetConcentration===option.value&&<Check size={12}/>} {option.label} · {option.value}%</button>)}</div><label>Custom concentration % <input type="number" min="1" max="40" step="0.1" value={targetConcentration} onChange={event=>setTargetConcentration(Number(event.target.value))}/></label><div className="finding-list"><article className={`finding ${alcohol?'information':'caution'}`}>{alcohol?<FlaskConical/>:<TriangleAlert/>}<div><span>{alcohol?'carrier adopted':'carrier missing'}</span><h3>{alcohol?alcohol.commonName:"Perfumer's alcohol / cosmetic-grade ethanol needed"}</h3><p>{alcohol?`The finished draft can be built as ${100-targetConcentration}% alcohol carrier + ${targetConcentration}% fragrance concentrate.`:'The creative concentrate can be developed now, but finished Formula handoff is blocked until an appropriate alcohol carrier exists as a documented workspace Ingredient.'}</p></div></article></div>{finishedFormula&&<p><strong>Finished Formula preview:</strong> {finishedFormula.lines[0].percentage}% {alcohol?.commonName} + {targetConcentration}% fragrance concentrate = 100%.</p>}</section>
  <section className="readiness-panel-studio"><div className="studio-section-heading"><div><span className="eyebrow">6 / real workspace comparison</span><h2>Development readiness</h2></div></div><div className="readiness-columns"><article><h3>Fragrance materials</h3>{readiness.length?readiness.map(item=><div className={`readiness-row ${item.state}`} key={item.id}><span>{item.state}</span><div><strong>{item.name}</strong><small>{item.available.toFixed(2)} available · Supplier Product is not physical stock.</small></div><Link to={`/ingredients/${item.id}`}>Open</Link></div>):<p>No materials selected.</p>}</article><article><h3>Alcohol carrier</h3><div className={`readiness-row ${alcohol?'ready':'missing'}`}><span>{alcohol?'ready':'missing'}</span><div><strong>{alcohol?.commonName??"Perfumer's alcohol"}</strong><small>{alcohol?'Workspace Ingredient adopted. Confirm actual lot, grade, SDS, flash point and supplier documentation before Lab use.':'Procurement can source a documented cosmetic/perfumery-grade carrier.'}</small></div><Link to={alcohol?`/ingredients/${alcohol.id}`:'/ingredients'}>Review</Link></div></article><article><h3>Safety & evidence</h3><div className="readiness-row review"><span>review</span><div><strong>IFRA · allergens · solubility · stability</strong><small>No safe maximum, IFRA compliance, skin suitability or finished-product stability is inferred by Product Studio. These remain controlled review items.</small></div><Link to="/compliance">Review</Link></div></article></div></section>
  <section className="procedure-panel"><span className="eyebrow">7 / controlled handoff</span><h2>Move deliberate work downstream</h2><p>Save the concept first. Procurement may be created while the palette is incomplete. Formula handoff requires at least two fragrance materials and an adopted alcohol carrier.</p><div className="studio-handoff-actions"><button className="button" onClick={()=>void handoffProcurement()}>Create Procurement plan</button><button className="button primary" onClick={()=>void handoffFormula()}>Create editable Formula</button></div>{message&&<p role="status">{message}</p>}</section>
 </div>
}
