import{useMemo,useState}from'react'
import{ArrowLeft,ArrowRight,FlaskConical,Plus,X}from'lucide-react'
import{Link,useNavigate,useSearchParams}from'react-router-dom'
import type{FormulaProcessStep,Ingredient,ProductStudioSelection}from'../../types/domain'
import{useFormulaData}from'../formulas/state/FormulaDataContext'
import{formulationIssues}from'../formulas/domain/multiPhaseLogic'
import{formulationArchetypes,productTemplates}from'./domain/formulationEngine'
import{bicarbonateFreeGuidance,classifyDeodorantIngredient,compareDeodorantVariants,deodorantRoles,evaluationFieldsForPackaging,formulaPercentageTotal,naturalDeodorantPhases,naturalDeodorantProcess,orderedPhases,rolePhysicalFormIssues,validDeodorantScore,type DeodorantVariant}from'./domain/naturalDeodorant'
import{availableIngredientQuantity}from'./domain/productStudio'
import{packagingComponentBalance}from'../packaging/domain/packagingLogic'

const goalOptions=['Firm stick','Soft jar format','Easy glide','Controlled payoff','Low drag','Low residue','Low powderiness','Low greasiness','Dry finish','Odour-control intent','Sensitive-skin positioning','Bicarbonate-free intent','Fragrance-free','Scented','Warm-climate firmness','Cold-climate usability','Stain-resistance intent']
const packagingOptions=['Twist-up stick','Push-up tube','Jar','Other','Unknown']

export function NaturalDeodorantStudioPage(){
 const data=useFormulaData(),navigate=useNavigate(),[params]=useSearchParams(),existing=data.productStudioConcepts.find(item=>item.id===params.get('concept')&&item.productType==='natural_deodorant')
 const initialLines=useMemo(()=>existing?.selectedIngredients.map(selection=>{const ingredient=data.ingredients.find(item=>item.id===selection.ingredientId),classified=ingredient&&classifyDeodorantIngredient(ingredient);return{ingredientId:selection.ingredientId,role:selection.role,phase:String((existing.analysis.phases as Record<string,string>|undefined)?.[selection.ingredientId]??classified?.phase??'A'),percentage:Number((existing.analysis.percentages as Record<string,number>|undefined)?.[selection.ingredientId]??0)}})??[],[data.ingredients,existing])
 const[name,setName]=useState(existing?.name??'Natural Deodorant concept'),[goals,setGoals]=useState(existing?.desiredProperties??[]),[packagingIntent,setPackagingIntent]=useState(String(existing?.analysis.packagingIntent??'Unknown')),[notes,setNotes]=useState(existing?.notes??''),[lines,setLines]=useState(initialLines),[process,setProcess]=useState<FormulaProcessStep[]>((existing?.analysis.manufacturingProcess as FormulaProcessStep[]|undefined)??naturalDeodorantProcess.map(step=>({...step}))),[variants,setVariants]=useState<DeodorantVariant[]>((existing?.analysis.variants as DeodorantVariant[]|undefined)??[]),[message,setMessage]=useState('')
 const template=productTemplates.natural_deodorant,archetype=formulationArchetypes[template.archetypeId],phases=orderedPhases(naturalDeodorantPhases),total=formulaPercentageTotal(lines),formulaIssues=formulationIssues(archetype.capabilities,naturalDeodorantPhases,lines,process),selectedIngredients=lines.map(line=>data.ingredients.find(item=>item.id===line.ingredientId)).filter((item):item is Ingredient=>!!item),bicarbonateIssues=bicarbonateFreeGuidance(goals.includes('Bicarbonate-free intent'),selectedIngredients),roleIssues=rolePhysicalFormIssues(lines,data.ingredients),issues=[...formulaIssues,...bicarbonateIssues,...roleIssues],packagingTerms=packagingIntent==='Jar'?['jar']:packagingIntent==='Twist-up stick'?['stick','twist']:packagingIntent==='Push-up tube'?['tube','push']:[],matchingPackaging=packagingTerms.length?data.packagingComponents.filter(component=>packagingTerms.some(term=>`${component.name} ${component.category}`.toLowerCase().includes(term))):[],packagingStock=matchingPackaging.reduce((sum,component)=>sum+packagingComponentBalance(component,data.packagingInventoryLots,data.packagingInventoryMovements),0),evaluationFields=evaluationFieldsForPackaging(packagingIntent)
 const add=(ingredientId:string)=>{const ingredient=data.ingredients.find(item=>item.id===ingredientId);if(!ingredient||lines.some(line=>line.ingredientId===ingredientId))return;const classified=classifyDeodorantIngredient(ingredient);setLines(current=>[...current,{ingredientId,role:classified.role,phase:classified.phase,percentage:0}])}
 const save=async()=>{const selections:ProductStudioSelection[]=lines.map(line=>({ingredientId:line.ingredientId,role:line.role,essential:true}));try{const concept=await data.saveProductStudioConcept({id:existing?.id,name,productType:'natural_deodorant',intentMode:'design',desiredProperties:goals,selectedIngredients:selections,scentDirections:goals.includes('Fragrance-free')?['Fragrance-free']:goals.includes('Scented')?['Scented']:[],candidateSubstitutes:{},notes,analysis:{packagingIntent,phases:Object.fromEntries(lines.map(line=>[line.ingredientId,line.phase])),percentages:Object.fromEntries(lines.map(line=>[line.ingredientId,line.percentage])),physicalForms:Object.fromEntries(selectedIngredients.map(ingredient=>[ingredient.id,classifyDeodorantIngredient(ingredient).physicalForm])),phaseDefinitions:naturalDeodorantPhases,manufacturingProcess:process,variants},generatedProductId:existing?.generatedProductId,generatedFormulaId:existing?.generatedFormulaId,generatedFormulaVersionId:existing?.generatedFormulaVersionId,procurementPlanId:existing?.procurementPlanId});setMessage('Natural Deodorant concept saved. No inventory or packaging stock changed.');if(!existing)navigate(`/product-studio/natural-deodorant?concept=${concept.id}`,{replace:true})}catch(cause){setMessage(cause instanceof Error?cause.message:'The concept could not be saved. Try again.')}}
 const handoff=async()=>{if(!existing)return setMessage('Save the concept before creating a Formula.');if(issues.length)return setMessage(issues.join(' '));if(!lines.length)return setMessage('Add at least one structured workspace Ingredient.');try{const result=await data.createFormulaFromStudio(existing.id,{productName:name,formulaName:`${name} — Studio Draft`,description:`Natural Deodorant development intent for ${packagingIntent.toLowerCase()} packaging. Physical observations do not establish efficacy, safety, stability, or compliance.`,lines,phaseDefinitions:naturalDeodorantPhases,manufacturingProcess:process});navigate(`/formulas/${result.formulaId}`)}catch{setMessage('The Formula could not be saved. Stay here and try again.')}}
 const addVariant=()=>setVariants(current=>[...current,{id:crypto.randomUUID(),name:`Variant ${String.fromCharCode(65+current.length)}`,changes:['Record one controlled wax, butter, oil, powder, bicarbonate, glide, cooling, fill, packaging, or fragrance change.'],evaluation:{}}])
 return <div className="beard-studio deodorant-studio"><Link className="back-link" to="/product-studio"><ArrowLeft size={14}/>Product Studio</Link>
  <header className="beard-studio-header"><div><span className="eyebrow">Guided product design / Natural Deodorant</span><input aria-label="Concept name" value={name} onChange={event=>setName(event.target.value)}/><p>{template.description}</p><small>Formulation system: {archetype.displayName} · {archetype.maturity}</small></div><button className="button" disabled={data.pendingActions.includes('saveProductStudioConcept')} onClick={()=>void save()}>Save concept</button></header>
  <nav className="studio-steps" aria-label="Natural Deodorant design steps">{['Intent','Format','Phases','Formula','Guidance','Process','Variants','Handoff'].map((step,index)=><span key={step}><b>{index+1}</b>{step}</span>)}</nav>
  <section className="studio-goals"><div className="studio-section-heading"><div><span className="eyebrow">1–2 / development intent</span><h2>Target properties and packaging intent</h2><p>These are development targets, not validated product claims.</p></div></div><div className="goal-chips">{goalOptions.map(goal=><button key={goal} aria-pressed={goals.includes(goal)} onClick={()=>setGoals(current=>current.includes(goal)?current.filter(item=>item!==goal):[...current,goal])}>{goal}</button>)}</div><label className="packaging-intent">Packaging intent<select value={packagingIntent} onChange={event=>setPackagingIntent(event.target.value)}>{packagingOptions.map(option=><option key={option}>{option}</option>)}</select><small>Planning intent only. {packagingTerms.length?matchingPackaging.length?`${matchingPackaging.length} advisory name/category match(es); ${packagingStock} recorded physical units. Compatibility still requires review.`:'No advisory Packaging Component match or physical stock is recorded.':'Packaging compatibility and stock are unknown.'}</small></label></section>
  <section className="panel"><div className="studio-section-heading"><div><span className="eyebrow">3–4 / authoritative structure</span><h2>Structured formula composition</h2><p>Powders are treated as dispersed materials, never silently as dissolved.</p></div><strong className={total===100?'studio-state ready':'studio-state review'}>{total.toFixed(2)}%</strong></div>
   <div className="phase-definition-grid">{phases.map(phase=><article key={phase.code}><strong>Phase {phase.code} — {phase.name}</strong><span>Temperature unknown until supported</span><p>{phase.instructions}</p></article>)}</div>
   <label>Add workspace Ingredient<select value="" onChange={event=>add(event.target.value)}><option value="">Choose…</option>{data.ingredients.filter(ingredient=>ingredient.status!=='Archived'&&!lines.some(line=>line.ingredientId===ingredient.id)).map(ingredient=><option value={ingredient.id} key={ingredient.id}>{ingredient.commonName} · {ingredient.category}</option>)}</select></label>
   <div className="butter-lines deodorant-lines">{lines.map(line=>{const ingredient=data.ingredients.find(item=>item.id===line.ingredientId),classification=ingredient&&classifyDeodorantIngredient(ingredient),supplier=ingredient?(data.supplierProducts.find(product=>product.ingredientId===ingredient.id&&product.isPreferred)??data.supplierProducts.find(product=>product.ingredientId===ingredient.id)):undefined,stock=ingredient&&availableIngredientQuantity(ingredient.id,data.inventoryLots,data.inventoryMovements,new Date().toISOString().slice(0,10),ingredient.defaultUnit);return <div key={line.ingredientId}><div><strong>{ingredient?.commonName}</strong><small>{classification?.physicalForm??'unknown'} · {classification?.guidance.join(' ')||'Classification based on available workspace metadata.'} Stock: {stock??'unknown'} {ingredient?.defaultUnit}. Supplier Product: {supplier?.productName??'not recorded'}.</small></div><select aria-label={`Phase for ${ingredient?.commonName}`} value={line.phase} onChange={event=>setLines(current=>current.map(item=>item===line?{...item,phase:event.target.value}:item))}>{phases.map(phase=><option value={phase.code} key={phase.code}>Phase {phase.code}</option>)}</select><label>Percentage<input type="number" min="0" max="100" step=".1" value={line.percentage} onChange={event=>setLines(current=>current.map(item=>item===line?{...item,percentage:Number(event.target.value)}:item))}/></label><select aria-label={`Role for ${ingredient?.commonName}`} value={line.role} onChange={event=>setLines(current=>current.map(item=>item===line?{...item,role:event.target.value}:item))}>{deodorantRoles.map(role=><option key={role} value={role}>{role.replaceAll('_',' ')}</option>)}</select><button aria-label={`Remove ${ingredient?.commonName}`} onClick={()=>setLines(current=>current.filter(item=>item!==line))}><X size={14}/></button></div>})}</div>
   {issues.length>0&&<div className="form-error" role="alert">{issues.map(issue=><p key={issue}>{issue}</p>)}</div>}
  </section>
  <section className="procedure-panel"><span className="eyebrow">5–6 / draft guidance</span><h2>Draft solid/stick manufacturing process</h2><p>No universal melting, addition, or filling temperature is assumed. Lab records actual conditions separately.</p><ol>{process.map(step=><li key={step.order}><strong>{step.order}. {step.title}</strong> — {step.instruction}<label><input type="checkbox" checked={step.critical} onChange={event=>setProcess(current=>current.map(item=>item.order===step.order?{...item,critical:event.target.checked}:item))}/> Critical step</label><label>Editable completion criteria<input value={step.completionCriteria??''} onChange={event=>setProcess(current=>current.map(item=>item.order===step.order?{...item,completionCriteria:event.target.value}:item))}/></label></li>)}</ol></section>
  <section className="panel"><div className="studio-section-heading"><div><span className="eyebrow">7 / Development Experiment preview</span><h2>Variants and structured physical observations</h2><p>Odour-control observations are user perception, not proof of efficacy. Format-specific prompts follow the selected packaging intent.</p></div><button className="button" onClick={addVariant}><Plus size={14}/>Add variant</button></div>{compareDeodorantVariants(variants).map(variant=><article className="butter-variant" key={variant.id}><input value={variant.name} onChange={event=>setVariants(current=>current.map(item=>item.id===variant.id?{...item,name:event.target.value}:item))}/><textarea value={variant.changes.join('\n')} onChange={event=>setVariants(current=>current.map(item=>item.id===variant.id?{...item,changes:event.target.value.split('\n')}:item))}/><div>{evaluationFields.map(field=><label key={field}>{field.replace(/[A-Z]/g,letter=>` ${letter.toLowerCase()}`)}<input type="number" min="1" max="5" value={variant.evaluation?.[field]??''} onChange={event=>{if(!event.target.value)return;const score=Number(event.target.value);if(!validDeodorantScore(score))return setMessage('Evaluation scores must be finite values from 1 to 5.');setVariants(current=>current.map(item=>item.id===variant.id?{...item,evaluation:{...item.evaluation,[field]:score}}:item))}}/></label>)}</div></article>)}</section>
  <section className="studio-handoff"><div><span className="eyebrow">8 / controlled handoff</span><h2>Concept → Formula → Lab → Testing → Candidate</h2><p>The preview below is generated only from structured records. Context notes never become Formula Lines.</p></div><div className="handoff-preview"><strong>Structured Formula to be created:</strong>{lines.length?<><ul>{lines.map(line=><li key={line.ingredientId}>{data.ingredients.find(item=>item.id===line.ingredientId)?.commonName} — {line.percentage}% · Phase {line.phase}</li>)}</ul><p>{lines.length} ingredients · Total {total}% · Packaging intent: {packagingIntent}</p></>:<p>No structured composition yet.</p>}</div><label>Context notes — not used as Formula ingredients<textarea value={notes} onChange={event=>setNotes(event.target.value)}/></label>{/%/.test(notes)&&<p className="notes-reminder">Percentages written in notes do not change the structured Formula.</p>}<div>{!existing?.generatedFormulaId&&<button className="button primary" disabled={data.pendingActions.includes('createFormulaFromStudio')} onClick={()=>void handoff()}><FlaskConical size={14}/>Create Draft Formula</button>}{existing?.generatedProductId&&existing.generatedFormulaVersionId&&<Link className="button" to={`/development/new?productType=natural_deodorant&productId=${existing.generatedProductId}&formulaVersionId=${existing.generatedFormulaVersionId}`}>Create Development Experiment</Link>}{existing?.generatedFormulaId&&<Link className="button" to={`/lab?formula=${existing.generatedFormulaId}`}>Prepare Lab Batch <ArrowRight size={14}/></Link>}</div>{message&&<p role="status">{message}</p>}</section>
 </div>
}
