import{describe,expect,it}from'vitest'
import{readFileSync}from'node:fs'
const entry=readFileSync(new URL('ProductStudioPage.tsx',import.meta.url),'utf8'),studio=readFileSync(new URL('BeardOilStudioPage.tsx',import.meta.url),'utf8'),butter=readFileSync(new URL('BeardButterStudioPage.tsx',import.meta.url),'utf8'),deodorant=readFileSync(new URL('NaturalDeodorantStudioPage.tsx',import.meta.url),'utf8'),registry=readFileSync(new URL('domain/formulationEngine.ts',import.meta.url),'utf8'),css=readFileSync(new URL('../../styles/index.css',import.meta.url),'utf8'),context=readFileSync(new URL('../formulas/state/FormulaDataContext.tsx',import.meta.url),'utf8')
describe('Product Studio UI contracts',()=>{
 it('provides the four intent-first entry actions',()=>['Make Something Today','Design a Product','Explore Ingredients','Follow a Proven Formula'].forEach(label=>expect(entry).toContain(label)))
 it('contains Make Today, structured composition, immediate analysis and inventory comparison',()=>{expect(studio).toContain("mode==='make_today'");expect(studio).toContain('Structured formula composition');expect(studio).toContain('aria-live="polite"');expect(studio).toContain('Inventory, equipment and packaging')})
 it('persists drafts through FormulaDataContext rather than component localStorage',()=>{expect(studio).toContain('saveProductStudioConcept');expect(context).toContain('commitState("saveProductStudioConcept"');expect(studio).not.toContain('localStorage')})
 it('hands off through existing Formula and Procurement domains',()=>{expect(studio).toContain('createFormulaFromStudio');expect(studio).toContain('createProductStudioPurchasePlan');expect(studio).toContain('/formulas/');expect(studio).toContain('/suppliers?tab=plans')})
 it('hides advanced finding evidence by default',()=>{expect(studio).toContain('useState(false)');expect(studio).toContain('aria-expanded={details}');expect(studio).toContain('{details&&<>')})
 it('keeps the 390px composition, comparison and actions usable without card scrolling',()=>{expect(css).toContain('@media(max-width:480px)');expect(css).toContain('.studio-entry-actions,.studio-ready-grid,.studio-concepts,.studio-ingredient-grid,.finding-list,.predicted-observed,.scent-builder{grid-template-columns:1fr}');expect(css).toContain('.composition-board{position:static');expect(css).toContain('.studio-handoff>div:last-of-type{position:sticky')})
 it('provides a responsive multi-phase Beard Butter workflow with Formula, Development and Lab handoff',()=>{expect(registry).toContain("route:'/product-studio/beard-butter'");expect(butter).toContain('Multi-phase composition');expect(butter).toContain('draft manufacturing process');expect(butter).toContain('Variants and structured evaluation');expect(butter).toContain('createFormulaFromStudio');expect(butter).toContain('/development/new?productType=beard_butter');expect(butter).toContain('/lab?formula=');expect(css).toContain('.butter-lines>div{grid-template-columns:1fr 1fr}')})
 it('shows subordinate formulation-system information and resolves handoff through the registry',()=>{expect(studio).toContain('Formulation system:');expect(butter).toContain('Formulation system:');expect(entry).toContain('resolveProductTemplate');expect(context).toContain('resolveTemplateArchetype');expect(context).not.toContain("concept.productType==='beard_butter'")})
 it('awaits authoritative Formula persistence before navigating with the Formula ID',()=>{expect(studio).toContain('await data.createFormulaFromStudio');expect(studio).toContain('navigate(`/formulas/${result.formulaId}`)');expect(studio.indexOf('await data.createFormulaFromStudio')).toBeLessThan(studio.indexOf('navigate(`/formulas/${result.formulaId}`)'));expect(studio).toContain('The Formula could not be saved. Stay here and try again.');expect(context).toContain('await commitState("createFormulaFromStudio"')})
 it('previews only structured records and distinguishes them from contextual notes',()=>{expect(studio).toContain('Structured formula to be created:');expect(studio).toContain('formula.lines.map');expect(studio).toContain('Context notes — not used as formula ingredients');expect(studio).toContain('Percentages written in notes do not change the structured formula.');expect(css).toContain('.composition-board.has-error')})
 it('provides a responsive Natural Deodorant workflow through shared handoffs',()=>{expect(entry).toContain('Design Natural Deodorant');expect(deodorant).toContain("productType:'natural_deodorant'");expect(deodorant).toContain('Structured Formula to be created:');expect(deodorant).toContain('Context notes — not used as Formula ingredients');expect(deodorant).toContain('createFormulaFromStudio');expect(deodorant).toContain('productType=natural_deodorant');expect(deodorant).toContain('/lab?formula=');expect(deodorant).toContain('setProcess');expect(deodorant).toContain('evaluationFieldsForPackaging');expect(deodorant).toContain('advisory name/category match');expect(deodorant).toContain('Create exploratory Draft Formula');expect(deodorant).toContain('Prepare Lab Batch blocked');expect(deodorant).toContain('You have unsaved concept changes. Save them before creating or updating the Formula.');expect(deodorant).not.toContain('<strong>{step.order}. {step.title}</strong>');expect(css).toContain('.deodorant-lines>div>div{min-width:0}');expect(css).toContain('.deodorant-studio .procedure-panel li label{display:grid')})
})
