import{Link}from'react-router-dom'
import{Beaker,BookOpen,FlaskConical,PackageCheck,Sparkles}from'lucide-react'
import{useFormulaData}from'../formulas/state/FormulaDataContext'
import{inventoryReadiness,maximumBatchSize}from'./domain/productStudio'

export function ProductStudioPage(){
 const data=useFormulaData(),beardFormulas=data.formulas.filter(formula=>data.products.find(product=>product.id===formula.productId)?.name.toLowerCase().includes('beard oil'))
 const makeable=beardFormulas.map(formula=>{const version=data.formulaVersions.filter(v=>v.formulaId===formula.id&&['Approved','Candidate'].includes(v.status)).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))[0];if(!version)return null;const selected=data.formulaLines.filter(line=>line.formulaVersionId===version.id).map(line=>({ingredientId:line.ingredientId,role:line.formulationRole??'liquid_base',essential:true}));const readiness=inventoryReadiness(selected,data),max=maximumBatchSize(readiness);return{formula,version,readiness,max,ready:readiness.every(item=>item.state==='ready')}}).filter(Boolean)
 return <div className="product-studio-entry"><header className="studio-hero"><span className="eyebrow">Product Studio / guided workshop</span><h1>What shall we make?</h1><p>Begin with intent, explore what a combination may feel and smell like, then hand deliberate work into Koalafrog’s existing Formula, Lab and Procurement records.</p></header>
 <section className="studio-entry-actions" aria-label="Product Studio actions">
  <Link to="/product-studio/beard-oil?mode=make"><PackageCheck/><span><strong>Make Something Today</strong><small>Start with stock, equipment and packaging already recorded.</small></span></Link>
  <Link to="/product-studio/beard-oil?mode=design"><Sparkles/><span><strong>Design a Product</strong><small>Build a Beard Oil direction from desired properties.</small></span></Link>
  <Link to="/product-studio/beard-butter"><Beaker/><span><strong>Design Beard Butter</strong><small>Build a heat-processed, multi-phase butter and draft process.</small></span></Link>
  <Link to="/ingredients/reference"><BookOpen/><span><strong>Explore Ingredients</strong><small>Browse curated reference knowledge before adoption.</small></span></Link>
  <Link to="/formulas"><FlaskConical/><span><strong>Follow a Proven Formula</strong><small>Use an existing Candidate or Approved internal formula.</small></span></Link>
 </section>
 <section className="studio-section"><div className="studio-section-heading"><div><span className="eyebrow">Beard Oil vertical slice</span><h2>Workshop readiness</h2></div><Link className="button" to="/product-studio/beard-oil?mode=make">Review all readiness</Link></div><div className="studio-ready-grid">{makeable.length?makeable.map(item=><article className="studio-ready-card" key={item!.version.id}><Beaker/><div><span className={`studio-state ${item!.ready?'ready':'review'}`}>{item!.ready?'Ready to make':'Almost makeable'}</span><h3>{item!.formula.name} · {item!.version.version}</h3><p>{item!.ready?`Maximum realistic starting batch: ${item!.max} g`:`${item!.readiness.filter(x=>x.state!=='ready').length} material requirement(s) need attention.`}</p></div><Link to={`/formulas/${item!.formula.id}`}>Open Formula</Link></article>):<article className="studio-empty"><h3>No Candidate or Approved Beard Oil formula yet</h3><p>Design a direction and create an editable Draft first.</p></article>}</div></section>
 {data.productStudioConcepts.length>0&&<section className="studio-section"><div className="studio-section-heading"><div><span className="eyebrow">Repository-backed drafts</span><h2>Continue a concept</h2></div></div><div className="studio-concepts">{[...data.productStudioConcepts].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map(concept=><Link key={concept.id} to={`/product-studio/${concept.productType==='beard_butter'?'beard-butter':'beard-oil'}?${concept.productType==='beard_butter'?'':`mode=${concept.intentMode==='make_today'?'make':'design'}&`}concept=${concept.id}`}><strong>{concept.name}</strong><span>{concept.desiredProperties.join(' · ')||'Direction not chosen'}</span><small>{concept.selectedIngredients.length} ingredients · updated {concept.updatedAt.slice(0,10)}</small></Link>)}</div></section>}
 <section className="studio-coming"><span className="eyebrow">Architecture ready for expansion</span><p>Beard Balm · Deodorant · Perfume · Face Oil · Lip Balm <strong>Coming later</strong></p></section>
 </div>
}
