import{Link}from'react-router-dom'
import{Beaker,BookOpen,FlaskConical,PackageCheck,Sparkles}from'lucide-react'
import{useFormulaData}from'../formulas/state/FormulaDataContext'
import{inventoryReadiness,maximumBatchSize}from'./domain/productStudio'
import{formulationArchetypes,productTemplates,resolveProductTemplate}from'./domain/formulationEngine'

export function ProductStudioPage(){
 const data=useFormulaData(),beardFormulas=data.formulas.filter(formula=>data.products.find(product=>product.id===formula.productId)?.name.toLowerCase().includes('beard oil'))
 const makeable=beardFormulas.map(formula=>{const version=data.formulaVersions.filter(v=>v.formulaId===formula.id&&['Approved','Candidate'].includes(v.status)).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))[0];if(!version)return null;const selected=data.formulaLines.filter(line=>line.formulaVersionId===version.id).map(line=>({ingredientId:line.ingredientId,role:line.formulationRole??'liquid_base',essential:true}));const readiness=inventoryReadiness(selected,data),max=maximumBatchSize(readiness);return{formula,version,readiness,max,ready:readiness.every(item=>item.state==='ready')}}).filter(Boolean)
 return <div className="product-studio-entry"><header className="studio-hero"><span className="eyebrow">Product Studio / guided workshop</span><h1>What shall we make?</h1><p>Begin with intent, explore what a combination may feel and smell like, then hand deliberate work into Koalafrog’s existing Formula, Lab and Procurement records.</p></header>
 <section className="studio-entry-actions" aria-label="Product Studio actions">
  <Link to={`${productTemplates.beard_oil.route}?mode=make`}><PackageCheck/><span><strong>Make Something Today</strong><small>Start with stock, equipment and packaging already recorded. Formulation system: {formulationArchetypes.simple_liquid.displayName}.</small></span></Link>
  <Link to={`${productTemplates.beard_oil.route}?mode=design`}><Sparkles/><span><strong>Design a Product</strong><small>Build a Beard Oil direction from desired properties. Formulation system: {formulationArchetypes.simple_liquid.displayName}.</small></span></Link>
  <Link to={productTemplates.beard_butter.route}><Beaker/><span><strong>Design Beard Butter</strong><small>Build a heat-processed, multi-phase butter and draft process. Formulation system: {formulationArchetypes.anhydrous_multiphase.displayName}.</small></span></Link>
  <Link to={productTemplates.natural_deodorant.route}><Sparkles/><span><strong>Design Natural Deodorant</strong><small>Build an anhydrous heated stick or jar concept with explicit powder dispersion and setting controls. Formulation system: {formulationArchetypes.solid_or_stick.displayName}.</small></span></Link>
  <Link to="/ingredients/reference"><BookOpen/><span><strong>Explore Ingredients</strong><small>Browse curated reference knowledge before adoption.</small></span></Link>
  <Link to="/formulas"><FlaskConical/><span><strong>Follow a Proven Formula</strong><small>Use an existing Candidate or Approved internal formula.</small></span></Link>
 </section>
 <section className="studio-section"><div className="studio-section-heading"><div><span className="eyebrow">Beard Oil vertical slice</span><h2>Workshop readiness</h2></div><Link className="button" to="/product-studio/beard-oil?mode=make">Review all readiness</Link></div><div className="studio-ready-grid">{makeable.length?makeable.map(item=><article className="studio-ready-card" key={item!.version.id}><Beaker/><div><span className={`studio-state ${item!.ready?'ready':'review'}`}>{item!.ready?'Ready to make':'Almost makeable'}</span><h3>{item!.formula.name} · {item!.version.version}</h3><p>{item!.ready?`Maximum realistic starting batch: ${item!.max} g`:`${item!.readiness.filter(x=>x.state!=='ready').length} material requirement(s) need attention.`}</p></div><Link to={`/formulas/${item!.formula.id}`}>Open Formula</Link></article>):<article className="studio-empty"><h3>No Candidate or Approved Beard Oil formula yet</h3><p>Design a direction and create an editable Draft first.</p></article>}</div></section>
 {data.productStudioConcepts.length>0&&<section className="studio-section"><div className="studio-section-heading"><div><span className="eyebrow">Repository-backed drafts</span><h2>Continue a concept</h2></div></div><div className="studio-concepts">{[...data.productStudioConcepts].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map(concept=>{const resolved=resolveProductTemplate(concept.productType);if(!resolved.ok)return <article className="studio-empty" role="alert" key={concept.id}><strong>{concept.name}</strong><p>{resolved.error}. This concept was not opened using a guessed workflow.</p></article>;const template=resolved.value,archetype=formulationArchetypes[template.archetypeId],query=template.id==='beard_oil'?`mode=${concept.intentMode==='make_today'?'make':'design'}&`:'';return <Link key={concept.id} to={`${template.route}?${query}concept=${concept.id}`}><strong>{concept.name}</strong><span>{concept.desiredProperties.join(' · ')||'Direction not chosen'}</span><small>{template.displayName} · {archetype.displayName} · {concept.selectedIngredients.length} ingredients · updated {concept.updatedAt.slice(0,10)}</small></Link>})}</div></section>}
 <section className="studio-coming"><span className="eyebrow">Formulation capabilities</span><p>{Object.values(formulationArchetypes).filter(item=>item.maturity==='planned').map(item=>item.displayName).join(' · ')} <strong>Planned — no operational workflow yet</strong></p></section>
 </div>
}
