import {describe,expect,it}from'vitest'
import type{SupplierDiscount,SupplierShippingRule}from'../../domain/procurement'
import{BASKET_STRATEGIES,calculateBasketTotals,calculateDiscount,calculateShipping,currencyRateFreshness,rankScenarioMetrics,scenarioStale,type BasketLineInput,type ScenarioMetrics}from'./basketScenarios'
const line=(x:Partial<BasketLineInput>={}):BasketLineInput=>({id:'l',supplierId:'s',supplierProductId:'p',productName:'Oil',ingredientName:'Oil',requiredQuantity:850,unit:'g',packageSize:1,packageUnit:'kg',packageCount:1,purchasedQuantity:1000,surplus:150,unitPrice:100,currency:'NOK',stockState:'in_stock',priceVerifiedAt:'2026-07-20',stockVerifiedAt:'2026-07-20',warnings:[],...x})
const discount=(x:Partial<SupplierDiscount>={}):SupplierDiscount=>({id:'d',supplier_id:'s',name:'First',discount_type:'percentage',percentage:10,fixed_amount:null,currency:null,coupon_code:null,minimum_order_value:null,maximum_discount:null,first_purchase_only:false,requires_newsletter:false,valid_from:null,expires_at:null,status:'available',source_url:null,evidence_notes:'',verified_at:'2026-07-20',used_at:null,created_at:'',updated_at:'',...x})
const shipping=(x:Partial<SupplierShippingRule>={}):SupplierShippingRule=>({id:'r',supplier_id:'s',destination_country_code:'NO',destination_region:null,shipping_method:'Standard',currency:'NOK',flat_rate:50,free_shipping_threshold:null,minimum_order_value:null,delivery_estimate_min_days:2,delivery_estimate_max_days:5,tax_handling:'included',duty_handling:'excluded',tax_estimate:null,duty_estimate:null,status:'active',source_url:null,evidence_notes:'',verified_at:'2026-07-20',created_at:'',updated_at:'',...x})
describe('production basket commercial calculations',()=>{
 it('applies percentage and fixed discounts with thresholds, caps, inclusions, and exclusions',()=>{expect(calculateDiscount({discount:discount(),lines:[line()],currency:'NOK'}).applied).toBe(10);expect(calculateDiscount({discount:discount({discount_type:'fixed_amount',percentage:null,fixed_amount:30,currency:'NOK',maximum_discount:20}),lines:[line()],currency:'NOK'}).applied).toBe(20);expect(calculateDiscount({discount:discount({minimum_order_value:101}),lines:[line()],currency:'NOK'}).state).toBe('ineligible');expect(calculateDiscount({discount:discount(),lines:[line()],currency:'NOK',excludedProductIds:['p']}).applied).toBe(0)})
 it('does not apply used, unconfirmed, or expired first-order savings',()=>{expect(calculateDiscount({discount:discount({first_purchase_only:true,used_at:'2026-07-01'}),lines:[line()],currency:'NOK'}).state).toBe('ineligible');expect(calculateDiscount({discount:discount({verified_at:null}),lines:[line()],currency:'NOK'}).state).toBe('potential');expect(calculateDiscount({discount:discount({expires_at:'2026-07-01'}),lines:[line()],currency:'NOK',now:new Date('2026-07-27')}).state).toBe('ineligible')})
 it('calculates fixed/free/weight shipping and preserves checkout or unknown states',()=>{expect(calculateShipping({rule:shipping(),subtotal:100,postDiscountSubtotal:90,currency:'NOK',destinationCountry:'NO',totalWeightKg:1,now:new Date('2026-07-27')}).amount).toBe(50);expect(calculateShipping({rule:shipping({free_shipping_threshold:90}),subtotal:100,postDiscountSubtotal:90,currency:'NOK',destinationCountry:'NO',totalWeightKg:1,thresholdBasis:'post_discount',now:new Date('2026-07-27')}).amount).toBe(0);expect(calculateShipping({rule:shipping({flat_rate:null}),subtotal:100,postDiscountSubtotal:90,currency:'NOK',destinationCountry:'NO',totalWeightKg:2,weightTiers:[{maxKg:3,amount:70}]}).amount).toBe(70);expect(calculateShipping({rule:shipping(),subtotal:100,postDiscountSubtotal:90,currency:'NOK',destinationCountry:'NO',totalWeightKg:null,checkoutOnly:true}).state).toBe('checkout_verification_required');expect(calculateShipping({subtotal:100,postDiscountSubtotal:100,currency:'NOK',destinationCountry:'NO',totalWeightKg:null}).state).toBe('unknown')})
 it('keeps unknown tax/import out of confirmed totals but reports known minimum',()=>expect(calculateBasketTotals({currency:'NOK',merchandise:100,confirmedDiscount:10,estimatedDiscount:0,shipping:50,shippingState:'confirmed',tax:null,taxState:'not_applicable',duty:null,dutyState:'import_verification_required',handling:null,handlingState:'unknown'})).toMatchObject({knownMinimum:140,confirmedTotal:null,estimatedTotal:null,unknownComponents:2}))
 it('distinguishes fresh and stale currency rates',()=>{expect(currencyRateFreshness('2026-07-20T00:00:00Z',new Date('2026-07-27'))).toBe('current');expect(currencyRateFreshness('2026-01-01T00:00:00Z',new Date('2026-07-27'))).toBe('stale')})
 it('ranks all six strategies deterministically and breaks ties by strategy and id',()=>{const metrics=BASKET_STRATEGIES.map((strategy,i):ScenarioMetrics=>({id:`s${i}`,strategy,supplierCount:i%2+1,lineCount:1,knownMinimum:100+i,estimatedTotal:100+i,surplusCost:i,discountSaving:i,uncertaintyCount:0,staleCount:0,documentationCoverage:1,stockCoverage:1,leadTimeDays:3}));expect(rankScenarioMetrics(metrics)).toHaveLength(6);expect(rankScenarioMetrics(metrics)).toEqual(rankScenarioMetrics([...metrics].reverse()))})
 it('marks only draft scenarios stale and preserves published history',()=>{expect(scenarioStale(2,3,false)).toBe(true);expect(scenarioStale(2,3,true)).toBe(false)})
})
