import {describe,expect,it}from'vitest'
import type{SupplierDiscount,SupplierShippingRule}from'../../domain/procurement'
import{BASKET_STRATEGIES,calculateBasketTotals,calculateDiscount,calculateShipping,currencyRateFreshness,rankScenarioMetrics,scenarioStale,type BasketLineInput,type ScenarioMetrics}from'./basketScenarios'
const line=(x:Partial<BasketLineInput>={}):BasketLineInput=>({id:'l',supplierId:'s',supplierProductId:'p',productName:'Oil',ingredientName:'Oil',requiredQuantity:850,unit:'g',packageSize:1,packageUnit:'kg',packageCount:1,purchasedQuantity:1000,surplus:150,unitPrice:100,currency:'NOK',stockState:'in_stock',priceVerifiedAt:'2026-07-20',stockVerifiedAt:'2026-07-20',warnings:[],...x})
const discount=(x:Partial<SupplierDiscount>={}):SupplierDiscount=>({id:'d',supplier_id:'s',name:'First',discount_type:'percentage',percentage:10,fixed_amount:null,currency:null,coupon_code:null,minimum_order_value:null,maximum_discount:null,first_purchase_only:false,requires_newsletter:false,valid_from:null,expires_at:null,status:'available',source_url:null,evidence_notes:'',verified_at:'2026-07-20',used_at:null,created_at:'',updated_at:'',...x})
const shipping=(x:Partial<SupplierShippingRule>={}):SupplierShippingRule=>({id:'r',supplier_id:'s',destination_country_code:'NO',destination_region:null,shipping_method:'Standard',currency:'NOK',flat_rate:50,free_shipping_threshold:null,minimum_order_value:null,delivery_estimate_min_days:2,delivery_estimate_max_days:5,tax_handling:'included',duty_handling:'excluded',tax_estimate:null,duty_estimate:null,status:'active',source_url:null,evidence_notes:'',verified_at:'2026-07-20',created_at:'',updated_at:'',...x})
describe('production basket commercial calculations',()=>{
 it('applies percentage and fixed discounts with thresholds, caps, inclusions, and exclusions',()=>{expect(calculateDiscount({discount:discount(),lines:[line()],currency:'NOK'}).applied).toBe(10);expect(calculateDiscount({discount:discount({discount_type:'fixed_amount',percentage:null,fixed_amount:30,currency:'NOK',maximum_discount:20}),lines:[line()],currency:'NOK'}).applied).toBe(20);expect(calculateDiscount({discount:discount({minimum_order_value:101}),lines:[line()],currency:'NOK'}).state).toBe('ineligible');expect(calculateDiscount({discount:discount(),lines:[line()],currency:'NOK',excludedProductIds:['p']}).applied).toBe(0)})
 it('does not apply used, unconfirmed, or expired first-order savings',()=>{expect(calculateDiscount({discount:discount({first_purchase_only:true,used_at:'2026-07-01'}),lines:[line()],currency:'NOK'}).state).toBe('ineligible');expect(calculateDiscount({discount:discount({verified_at:null}),lines:[line()],currency:'NOK'}).state).toBe('potential');expect(calculateDiscount({discount:discount({expires_at:'2026-07-01'}),lines:[line()],currency:'NOK',now:new Date('2026-07-27')}).state).toBe('ineligible')})
 it('calculates fixed/free/weight shipping and preserves checkout or unknown states',()=>{expect(calculateShipping({rule:shipping(),subtotal:100,postDiscountSubtotal:90,currency:'NOK',destinationCountry:'NO',totalWeightKg:1,now:new Date('2026-07-27')}).amount).toBe(50);expect(calculateShipping({rule:shipping({free_shipping_threshold:90}),subtotal:100,postDiscountSubtotal:90,currency:'NOK',destinationCountry:'NO',totalWeightKg:1,thresholdBasis:'post_discount',now:new Date('2026-07-27')}).amount).toBe(0);expect(calculateShipping({rule:shipping({flat_rate:null}),subtotal:100,postDiscountSubtotal:90,currency:'NOK',destinationCountry:'NO',totalWeightKg:2,weightTiers:[{maxKg:3,amount:70}]}).amount).toBe(70);expect(calculateShipping({rule:shipping(),subtotal:100,postDiscountSubtotal:90,currency:'NOK',destinationCountry:'NO',totalWeightKg:null,checkoutOnly:true}).state).toBe('checkout_verification_required');expect(calculateShipping({subtotal:100,postDiscountSubtotal:100,currency:'NOK',destinationCountry:'NO',totalWeightKg:null}).state).toBe('unknown')})
 it('keeps unknown tax/import out of confirmed totals but reports known minimum',()=>expect(calculateBasketTotals({currency:'NOK',merchandise:100,confirmedDiscount:10,estimatedDiscount:0,shipping:50,shippingState:'confirmed',tax:null,taxState:'not_applicable',duty:null,dutyState:'import_verification_required',handling:null,handlingState:'unknown'})).toMatchObject({knownMinimum:140,confirmedTotal:null,estimatedTotal:null,unknownComponents:2}))
 it('distinguishes fresh and stale currency rates',()=>{expect(currencyRateFreshness('2026-07-20T00:00:00Z',new Date('2026-07-27'))).toBe('current');expect(currencyRateFreshness('2026-01-01T00:00:00Z',new Date('2026-07-27'))).toBe('stale')})
 it('ranks all six strategies deterministically and breaks ties by strategy and id',()=>{const metrics=BASKET_STRATEGIES.map((strategy,i):ScenarioMetrics=>({id:`s${i}`,strategy,supplierCount:i%2+1,lineCount:1,knownMinimum:100+i,estimatedTotal:100+i,surplusCost:i,discountSaving:i,uncertaintyCount:0,staleCount:0,documentationCoverage:1,stockCoverage:1,leadTimeDays:3}));expect(rankScenarioMetrics(metrics)).toHaveLength(6);expect(rankScenarioMetrics(metrics)).toEqual(rankScenarioMetrics([...metrics].reverse()))})
 it('preserves fractional discount, shipping, and mixed-package arithmetic',()=>{const lines=[line({packageCount:3,unitPrice:10.25}),line({id:'l2',supplierProductId:'p2',packageCount:2,unitPrice:4.125})];expect(calculateDiscount({discount:discount({percentage:12.5}),lines,currency:'NOK',confirmed:true}).applied).toBeCloseTo(4.875);expect(calculateShipping({rule:shipping({flat_rate:10.25}),subtotal:39,postDiscountSubtotal:34.125,currency:'NOK',destinationCountry:'NO',totalWeightKg:1,remoteAreaFee:.5,dangerousGoodsFee:.25}).amount).toBe(11);expect(calculateBasketTotals({currency:'NOK',merchandise:39,confirmedDiscount:4.875,estimatedDiscount:0,shipping:11,shippingState:'confirmed',tax:0,taxState:'not_applicable',duty:0,dutyState:'not_applicable',handling:0,handlingState:'not_applicable'}).confirmedTotal).toBeCloseTo(45.125)})
 it('handles maximum realistic ranking values and rejects unsafe or infinite arithmetic',()=>{const realistic:ScenarioMetrics={id:'large',strategy:'fewest_suppliers',supplierCount:10000,lineCount:100000,knownMinimum:1_000_000_000_000,estimatedTotal:1_000_000_000_000,surplusCost:100_000_000,discountSaving:1_000_000,uncertaintyCount:1000,staleCount:1000,documentationCoverage:.5,stockCoverage:.5,leadTimeDays:3650};expect(rankScenarioMetrics([realistic])[0].rankingScore).toBe(11_000_000_000_000);expect(()=>rankScenarioMetrics([{...realistic,supplierCount:Number.MAX_SAFE_INTEGER}])).toThrow(/supported numeric range/);expect(()=>calculateDiscount({discount:discount(),lines:[line({packageCount:Number.MAX_VALUE,unitPrice:2})],currency:'NOK'})).toThrow(/supported numeric range/)})
 it('uses stable strategy then id ordering for exact score ties',()=>{const base:ScenarioMetrics={id:'b',strategy:'minimum_cash',supplierCount:1,lineCount:1,knownMinimum:100,estimatedTotal:100,surplusCost:0,discountSaving:0,uncertaintyCount:0,staleCount:0,documentationCoverage:1,stockCoverage:1,leadTimeDays:1};const tied=[base,{...base,id:'a'},{...base,id:'z',strategy:'balanced' as const}];expect(rankScenarioMetrics(tied).map(item=>item.id)).toEqual(['a','b','z'])})
 it('marks only draft scenarios stale and preserves published history',()=>{expect(scenarioStale(2,3,false)).toBe(true);expect(scenarioStale(2,3,true)).toBe(false)})
})
