import {useEffect,useMemo,useRef,useState} from 'react'
import {Camera,ChevronLeft,ImagePlus,ShieldCheck,Trash2,X} from 'lucide-react'
import {BeardPhotoVisionAgent} from '../../../intelligence/Agents/BeardPhotoVisionAgent'
import {beardPhotoViews,canDecodeBeardPhoto,validateBeardPhotoFile,type BeardPhotoAnalysisResult,type BeardPhotoItem,type BeardPhotoRecommendation,type BeardPhotoView,type RecommendationReviewStatus,type SelectedBeardPhoto} from '../../../intelligence/Vision/beardPhotoAnalysis'
import {BeardPhotoAnalysisError,finishBeardAnalysisReview} from '../../../intelligence/Vision/beardPhotoClient'
import type {BeardStudioState} from '../../../types/beardStudio'
import {beardTargetStyles,deriveGroomingSummary,generateTrimPlan,rankRecommendations,reviewCounts,targetFromProfile,targetStyleLabel,type BeardAnalysisTarget} from '../domain/beardPhotoIntelligenceV2'
import {BeardPhotoSupportDiagnosticPanel} from './BeardPhotoSupportDiagnosticPanel'

const labels:Record<BeardPhotoView,string>={front:'Front',left_profile:'Left profile',right_profile:'Right profile',under_chin:'Under chin / neckline'}
const progressStages=['Preparing images','Uploading privately','Analyzing visible beard characteristics','Validating response','Preparing review']
const requiredViews=beardPhotoViews.slice(0,3)

export function BeardPhotoAnalysisFlow({state,workspaceId}:{state:BeardStudioState;workspaceId?:string}) {
  const profile=state.profiles.find(item=>item.status==='Active')
  const [open,setOpen]=useState(false),[step,setStep]=useState(1)
  const [photos,setPhotos]=useState<Partial<Record<BeardPhotoView,SelectedBeardPhoto>>>({}),[consent,setConsent]=useState(false)
  const [submitting,setSubmitting]=useState(false),[stage,setStage]=useState(''),[result,setResult]=useState<BeardPhotoAnalysisResult>()
  const [target,setTarget]=useState<BeardAnalysisTarget>(()=>targetFromProfile(profile))
  const [error,setError]=useState(''),[supportId,setSupportId]=useState(''),[cleanupWarning,setCleanupWarning]=useState('')
  const controller=useRef<AbortController|undefined>(undefined),photosRef=useRef(photos),agent=useMemo(()=>new BeardPhotoVisionAgent(),[])
  useEffect(()=>{photosRef.current=photos},[photos])
  useEffect(()=>()=>{Object.values(photosRef.current).forEach(photo=>photo&&URL.revokeObjectURL(photo.previewUrl));controller.current?.abort()},[])
  const selected=Object.values(photos).filter(Boolean) as SelectedBeardPhoto[],ready=requiredViews.every(view=>photos[view])
  const choose=async(view:BeardPhotoView,file?:File)=>{setError('');if(!file)return;const problem=validateBeardPhotoFile(file);if(problem||!await canDecodeBeardPhoto(file)){setError(problem??'The selected image could not be decoded. Choose another photo.');return}setPhotos(current=>{if(current[view])URL.revokeObjectURL(current[view]!.previewUrl);return{...current,[view]:{view,file,previewUrl:URL.createObjectURL(file)}}})}
  const remove=(view:BeardPhotoView)=>setPhotos(current=>{if(current[view])URL.revokeObjectURL(current[view]!.previewUrl);const next={...current};delete next[view];return next})
  const close=()=>{if(submitting)return;setOpen(false);setStep(1);setResult(undefined);setError('');setSupportId('');setCleanupWarning('')}
  const analyze=async()=>{if(!workspaceId||!profile||!ready||!consent){setError(!workspaceId?'Beard photo analysis requires the hosted workspace.':!profile?'An active Beard Studio profile is required.':!ready?'Front, left profile and right profile photos are required.':'Confirm consent and expectations before analysis.');return}setSubmitting(true);setError('');setSupportId('');setStep(4);controller.current=new AbortController();try{const response=await agent.analyzePhotos({workspaceId,profileId:profile.id,targetStyle:target,photos:selected,analysisId:crypto.randomUUID(),idempotencyKey:crypto.randomUUID(),signal:controller.current.signal,onStage:setStage});setResult(response.result);setCleanupWarning(response.cleanupWarning??'');setStep(5);setPhotos(current=>{Object.values(current).forEach(photo=>photo&&URL.revokeObjectURL(photo.previewUrl));return{}})}catch(cause){const controlled=cause instanceof BeardPhotoAnalysisError?cause:undefined;setSupportId(controlled?.correlationId??'');setError(`${controlled?.message??'Beard photo analysis failed.'}${controlled?.correlationId?` Support ID: ${controlled.correlationId}`:''}`);setStep(3)}finally{setSubmitting(false);controller.current=undefined}}
  const review=async(item:BeardPhotoRecommendation,status:RecommendationReviewStatus)=>{if(!result)return;setError('');setResult({...result,recommendations:result.recommendations.map(current=>current.id===item.id?{...current,status}:current)})}
  if(!open)return <button className="button primary beard-photo-launch" onClick={()=>setOpen(true)}><Camera size={16}/>Analyze Beard Photos</button>
  return <section className="beard-photo-flow" aria-labelledby="beard-photo-title"><header><div><span className="eyebrow">Private vision workflow</span><h2 id="beard-photo-title">Analyze Beard Photos</h2><p>AI estimates visible grooming characteristics. It does not perform calibrated measurement or change Beard Studio records.</p></div><button className="icon-button" aria-label="Close photo analysis" disabled={submitting} onClick={close}><X/></button></header>
    {step<5&&<ol className="photo-stepper" aria-label="Analysis progress">{['Guidance','Photos','Consent','Analysis'].map((name,index)=><li key={name} className={step>=index+1?'active':''}>{index+1} {name}</li>)}</ol>}
    {step===1&&<div className="photo-guidance"><h3>Capture guidance</h3><ul><li>Use a dry beard in normal indoor lighting.</li><li>Keep a neutral expression and the camera approximately level with your face.</li><li>Show the entire beard without a beauty filter.</li></ul><p>This is visual grooming guidance—not clinical or laboratory-grade measurement.</p><button className="button primary" onClick={()=>setStep(2)}>Choose photos</button></div>}
    {step===2&&<div><div className="photo-view-grid">{beardPhotoViews.map(view=><article key={view} className={photos[view]?'selected':''}><header><strong>{labels[view]}</strong><small>{requiredViews.includes(view)?'Required':'Optional'}</small></header>{photos[view]?<><img src={photos[view]!.previewUrl} alt={`${labels[view]} beard photo preview`}/><div><label className="button"><ImagePlus/>Replace<input type="file" accept="image/jpeg,image/png,image/webp" capture="user" onChange={event=>void choose(view,event.target.files?.[0])}/></label><button className="button" onClick={()=>remove(view)}><Trash2/>Remove</button></div></>:<label className="photo-drop"><Camera/><span>Capture or upload</span><input type="file" accept="image/jpeg,image/png,image/webp" capture="user" onChange={event=>void choose(view,event.target.files?.[0])}/></label>}</article>)}</div>{error&&<p className="form-error" role="alert">{error}</p>}<footer><button className="button" onClick={()=>setStep(1)}><ChevronLeft/>Guidance</button><button className="button primary" disabled={!ready} onClick={()=>setStep(3)}>Review target and consent</button></footer></div>}
    {step===3&&<div className="photo-consent"><ShieldCheck/><h3>Target and consent</h3><label className="target-style-field"><span>Target beard style</span><select aria-label="Target beard style" value={target.value} onChange={event=>{const value=event.target.value as BeardAnalysisTarget['value'];setTarget({value,label:value.replaceAll('_',' ')})}}>{beardTargetStyles.map(value=><option key={value} value={value}>{value.replaceAll('_',' ')}</option>)}</select></label>{target.value==='custom'&&<label className="target-style-field"><span>Custom target</span><input value={target.customLabel??''} onChange={event=>setTarget({...target,customLabel:event.target.value})}/></label>}<label><input type="checkbox" checked={consent} onChange={event=>setConsent(event.target.checked)}/><span>I confirm these photos contain my face and beard; they will be sent to the configured AI provider; results are estimates and grooming recommendations rather than objective measurements; and no Beard Studio record will change automatically.</span></label><details><summary>How photo privacy works</summary><p>Photos are uploaded to private, owner-scoped temporary storage, sent server-side to the configured provider, and scheduled for deletion after the analysis attempt. Validated results may be retained without source images.</p></details><p className="paid-notice">Submitting may incur provider usage. One analysis runs only after you press confirmation.</p>{error&&<p className="form-error" role="alert">{error}</p>}{workspaceId&&supportId&&<BeardPhotoSupportDiagnosticPanel workspaceId={workspaceId} supportId={supportId}/>}<footer><button className="button" onClick={()=>setStep(2)}><ChevronLeft/>Photos</button><button className="button primary" disabled={!consent||submitting} onClick={()=>void analyze()}>Confirm and analyze</button></footer></div>}
    {step===4&&<div className="photo-progress" role="status"><span className="photo-spinner"/><h3>{stage||progressStages[0]}</h3><ol>{progressStages.map(item=><li key={item} className={progressStages.indexOf(item)<=progressStages.indexOf(stage)?'done':''}>{item}</li>)}</ol><p>No Beard Studio record is being changed.</p></div>}
    {step===5&&result&&<BeardPhotoReview result={result} target={target} tool={state.tools.find(item=>item.primary&&item.status==='active')} workspaceId={workspaceId} cleanupWarning={cleanupWarning} error={error} onReview={review} onClose={close}/>}
  </section>
}

export function BeardPhotoReview({result,target,tool,workspaceId,persistedSummary,persistedPlan,cleanupWarning='',error='',onReview,onClose}:{result:BeardPhotoAnalysisResult;target?:BeardAnalysisTarget|null;tool:BeardStudioState['tools'][number]|undefined;workspaceId?:string;persistedSummary?:ReturnType<typeof deriveGroomingSummary>|null;persistedPlan?:ReturnType<typeof generateTrimPlan>|null;cleanupWarning?:string;error?:string;onReview:(item:BeardPhotoRecommendation,status:RecommendationReviewStatus)=>Promise<void>;onClose:()=>void}) {
  const recordedTarget=target===undefined?null:target
  const summary=persistedSummary??deriveGroomingSummary(result,recordedTarget),ranked=rankRecommendations(result.recommendations,recordedTarget),counts=reviewCounts(result.recommendations),plan=persistedPlan??generateTrimPlan(result,tool,recordedTarget)
  const [saving,setSaving]=useState(false),[saved,setSaved]=useState(''),[finishError,setFinishError]=useState('')
  const finish=async()=>{if(!workspaceId)return;setSaving(true);setSaved('');setFinishError('');try{await finishBeardAnalysisReview(workspaceId,result.analysisId,result.recommendations,summary,plan);setSaved('Review decisions and trim-plan snapshot saved. Length Map and Trim Recipes were not changed.')}catch(cause){setFinishError(cause instanceof BeardPhotoAnalysisError&&cause.code==='SNAPSHOT_TARGET_MISMATCH'?'Review could not be saved because its historical target did not match. Nothing was changed. Please reopen the analysis and try again.':'Review could not be saved. Nothing was changed. Please try again.')}finally{setSaving(false)}}
  return <div className="beard-photo-review">{cleanupWarning&&<p className="form-error" role="alert">{cleanupWarning}</p>}
    <section className="grooming-summary"><span className="eyebrow">Overall assessment</span><h3>{summary.overallAssessment}</h3><p><strong>Target:</strong> {targetStyleLabel(target)}</p><div className="summary-columns"><div><h4>Strengths</h4><ul>{summary.strengths.map(x=><li key={x}>{x}</li>)}</ul></div><div><h4>Highest-impact improvements</h4><ol>{summary.highestImpactImprovements.map(x=><li key={x.recommendationId}>{x.title}</li>)}</ol></div></div><dl className="summary-metrics"><div><dt>Estimated trim time</dt><dd>{summary.estimatedTrimMinutes} min</dd></div><div><dt>Difficulty</dt><dd>{summary.difficulty}</dd></div><div><dt>Confidence</dt><dd>{summary.confidence}</dd></div></dl><p className="photo-caveat">{summary.photoQualityCaveat}</p></section>
    <section><h3>{persistedPlan?'Saved trim plan':'Active trim-plan preview'}</h3><p><strong>Planning target:</strong> {targetStyleLabel(plan.targetStyle)}</p><ol className="trim-plan">{plan.steps.map(step=><li key={step.id}><h4>{step.title}</h4><p><strong>{step.region}</strong> · {step.tool}</p>{step.attachmentOrComb&&<p>Attachment: {step.attachmentOrComb}</p>}{step.guardSetting&&<p>Setting: {step.guardSetting}</p>}<p>{step.technique}</p>{step.fallbackWording&&<p>{step.fallbackWording}</p>}{step.direction&&<p>Direction: {step.direction}</p>}<small>Caution: {step.caution}</small><small>Expected: {step.expectedResult}</small>{step.recommendationIds.length>0&&<small>Supported by: {step.recommendationIds.join(', ')}</small>}</li>)}</ol></section>
    <section className="review-counts" aria-label="Review decision counts"><strong>{counts.accepted_for_planning} accepted</strong><strong>{counts.undecided} undecided</strong><strong>{counts.dismissed} dismissed</strong><p>Accepted items enter the plan. Dismissed and undecided items remain in the analysis but stay outside the active plan.</p></section>
    <details open><summary>Recommendations and decisions</summary><div className="ai-review-list">{ranked.map(item=><RecommendationCard key={item.id} item={item} evidence={[...result.observations,...result.symmetry,...result.densityDistribution,...result.lineAssessment]} onReview={onReview}/>)}</div></details>
    <details><summary>Observations, symmetry, density and lines</summary><ItemSection title="Observations" items={result.observations}/><ItemSection title="Symmetry" items={result.symmetry}/><ItemSection title="Density distribution" items={result.densityDistribution}/><ItemSection title="Line review" items={result.lineAssessment}/></details>
    <details><summary>Limitations and technical provenance</summary><ul>{[...result.limitations,...result.unknowns,...result.safetyFlags].map(item=><li key={item}>{item}</li>)}</ul><p>{result.provider} · {result.model} · {result.promptVersion} · Support ID {result.correlationId}</p></details>
    {error&&<p className="form-error" role="alert">{error}</p>}{finishError&&<p className="form-error" role="alert">{finishError}</p>}{saved&&<p className="save-confirmation" role="status">{saved}</p>}<footer><p>Finish Review saves decisions and a deterministic plan snapshot only.</p><button className="button primary" disabled={!workspaceId||saving} onClick={()=>void finish()}>{saving?'Saving…':'Finish review'}</button><button className="button" onClick={onClose}>Close</button></footer>
  </div>
}
function RecommendationCard({item,evidence,onReview}:{item:ReturnType<typeof rankRecommendations>[number];evidence:BeardPhotoItem[];onReview:(item:BeardPhotoRecommendation,status:RecommendationReviewStatus)=>Promise<void>}) {const views=[...new Set(evidence.filter(x=>item.supportingObservationKeys.includes(x.observationKey)).flatMap(x=>x.supportingViews))];return <article><span>{item.priorityLabel} · {Math.round(item.confidence*100)}% confidence</span><h4>{item.title}</h4><p>{item.reason}</p><p><strong>Expected benefit:</strong> {item.expectedBenefit}</p><small>Views: {views.map(view=>labels[view]).join(', ')||'No visible support'} · planning proposal only</small><div><button className="button" aria-pressed={item.status==='accepted_for_planning'} onClick={()=>void onReview(item,'accepted_for_planning')}>Accept for planning</button><button className="button" aria-pressed={item.status==='dismissed'} onClick={()=>void onReview(item,'dismissed')}>Dismiss</button><button className="button" aria-pressed={item.status==='undecided'} onClick={()=>void onReview(item,'undecided')}>Leave undecided</button></div></article>}
function ItemSection({title,items}:{title:string;items:BeardPhotoItem[]}) {return <section><h3>{title}</h3>{items.length?<div className="ai-review-list">{items.map(item=><article key={item.observationKey}><span>{item.category} · {Math.round(item.confidence*100)}% confidence</span><p>{item.statement}</p><small>Views: {item.supportingViews.map(view=>labels[view]).join(', ')}</small></article>)}</div>:<p>Unknown from the supplied views.</p>}</section>}
