import type { FinishedGoodsBatch,FinishedGoodsMovement,FinishedGoodsMovementType,InventoryUnit,ProductionRun } from '../../../types/domain'
import { areUnitsCompatible,convertUnit } from '../../inventory/domain/inventoryLogic'
const code=(name:string)=>name.split(/\s+/).filter(w=>!['signature','original','daily','koalafrog'].includes(w.toLowerCase())).map(w=>w[0]).join('').slice(0,2).toUpperCase()||'FG'
export function generateFinishedGoodsNumber(product:string,existing:string[],date=new Date()){const stamp=`${String(date.getFullYear()).slice(-2)}${String(date.getMonth()+1).padStart(2,'0')}${String(date.getDate()).padStart(2,'0')}`;const prefix=`KF-FG-${code(product)}-${stamp}-`;const next=Math.max(0,...existing.filter(n=>n.startsWith(prefix)).map(n=>Number(n.slice(prefix.length))||0))+1;return`${prefix}${String(next).padStart(2,'0')}`}
const direction=(type:FinishedGoodsMovementType)=>type==='ProductionReceipt'||type==='Adjustment'?1:-1
export function finishedGoodsBalance(batch:FinishedGoodsBatch,movements:FinishedGoodsMovement[]){return Math.round(movements.filter(m=>m.finishedGoodsBatchId===batch.id).reduce((s,m)=>s+convertUnit(m.type==='Adjustment'?m.quantity:Math.abs(m.quantity)*direction(m.type),m.unit,batch.unit),0)*10000)/10000}
export function validateFinishedGoodsMovement(batch:FinishedGoodsBatch,movements:FinishedGoodsMovement[],input:{type:FinishedGoodsMovementType;quantity:number;unit:InventoryUnit}){if(!Number.isFinite(input.quantity)||input.quantity===0)return'Quantity must be non-zero.';if(!areUnitsCompatible(input.unit,batch.unit))return'Incompatible unit.';if(input.type!=='Adjustment'&&input.quantity<0)return'Use a positive quantity.';const change=convertUnit(input.type==='Adjustment'?input.quantity:-Math.abs(input.quantity),input.unit,batch.unit);if(input.type!=='ProductionReceipt'&&finishedGoodsBalance(batch,movements)+change<0)return'Movement exceeds available Finished Goods.';return null}
export function registeredProductionOutput(runId:string,batches:FinishedGoodsBatch[]){return batches.filter(b=>b.productionRunId===runId).reduce((s,b)=>s+b.initialQuantity,0)}
export function remainingProductionOutput(run:ProductionRun,batches:FinishedGoodsBatch[]){return Math.max(0,(run.actualUnitsProduced??0)-registeredProductionOutput(run.id,batches))}
export function validateFinishedGoodsOutput(run:ProductionRun,batches:FinishedGoodsBatch[],quantity:number){if(run.actualUnitsProduced==null)return'Production Run must record actual units produced.';if(!Number.isFinite(quantity)||quantity<=0)return'Finished Goods quantity must be greater than zero.';if(quantity>remainingProductionOutput(run,batches))return'Finished Goods quantity exceeds remaining unregistered Production output.';return null}
export function finishedGoodsCostBasis(productionCostPerUnit:number|undefined,quantity:number,packagingCost:number|undefined,manualPackagingCost:number,physicalPackagingCommitted=packagingCost!=null){if(productionCostPerUnit==null)return{total:undefined,perUnit:undefined,warning:'Production cost is incomplete.'};if(physicalPackagingCommitted&&packagingCost==null)return{total:undefined,perUnit:undefined,warning:'Actual packaging consumption has incomplete acquisition-cost coverage; manual Packaging Cost Lines are excluded.'};const physical=packagingCost??manualPackagingCost;const total=productionCostPerUnit*quantity+physical;return{total,perUnit:quantity?total/quantity:undefined,warning:packagingCost!=null&&manualPackagingCost>0?'Actual packaging inventory cost is authoritative; overlapping manual Packaging Cost Lines are excluded.':undefined}}
