\timing on
begin;
set local session_replication_role=replica;
insert into public.packaging_runs(id,workspace_id,owner_id,production_output_id,production_run_id,formula_version_id,product_id,packaging_specification_version_id,run_sequence,internal_run_code,run_label,planned_bulk_quantity,planned_bulk_unit,planned_bulk_normalized_quantity,planned_bulk_normalized_unit,planned_unit_count,nominal_fill_quantity,nominal_fill_unit,target_packaging_format,location,product_name_snapshot,formula_version_snapshot,production_output_code_snapshot,packaging_specification_name_snapshot,packaging_specification_version_snapshot,packaging_specification_snapshot,bulk_cost_confidence,status,revision,creation_idempotency_key,creation_payload_fingerprint,created_by)
select gen_random_uuid(),'00000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000002',gen_random_uuid(),'perf-run-'||g,'perf-v','perf-p','perf-pkg',g,'PKG-PERF-'||g,'Performance Run',100,'g',100,'g',10,10,'g','Bottle','Packaging','Performance Product','1.0','OUT-'||g,'Bottle','1.0','{}','complete','completed',5,gen_random_uuid(),'perf','00000000-0000-0000-0000-000000000002' from generate_series(1,10000) g;
insert into public.packaged_output_reconciliations(workspace_id,owner_id,packaging_run_id,production_output_id,reconciliation_version,total_packaged_quantity,accepted_quantity,rejected_quantity,damaged_quantity,sample_quantity,retention_quantity,unresolved_variance,unit,equation_difference,state,recorded_by,recorded_at,idempotency_key,payload_fingerprint)
select workspace_id,owner_id,id,production_output_id,1,10,10,0,0,0,0,0,'pcs',0,'reconciled',owner_id,now(),gen_random_uuid(),'perf' from public.packaging_runs where internal_run_code like 'PKG-PERF-%';
insert into public.finished_goods_lots(workspace_id,owner_id,packaging_run_id,production_output_id,production_run_id,formula_id,formula_version_id,product_id,packaging_specification_version_id,packaged_output_reconciliation_id,internal_lot_code,consumer_batch_code,lot_sequence,lot_label,quantity,unit,normalized_quantity,nominal_fill_quantity,nominal_fill_unit,manufacturing_date,shelf_life_basis,product_snapshot,formula_snapshot,packaging_snapshot,label_snapshot,cost_snapshot,genealogy_snapshot,location,creation_idempotency_key,creation_payload_fingerprint,created_by,quarantined_by,quarantined_at)
select r.workspace_id,r.owner_id,r.id,r.production_output_id,r.production_run_id,'perf-f',r.formula_version_id,r.product_id,r.packaging_specification_version_id,q.id,'FG-PERF-'||g,'KF-PERF-'||g,1+((g-1)/10000)::integer,'Performance Lot',1,'pcs',1,10,'g',current_date,'Unknown','{}','{}','{}','{}','{}',jsonb_build_object('edges',jsonb_build_array(r.id,r.production_output_id,r.production_run_id)),'Quarantine',gen_random_uuid(),'perf',r.owner_id,r.owner_id,now()
from generate_series(1,25000) g join lateral(select * from public.packaging_runs where internal_run_code='PKG-PERF-'||(1+((g-1)%10000)) limit 1) r on true join public.packaged_output_reconciliations q on q.packaging_run_id=r.id;
insert into public.finished_goods_quarantines(workspace_id,owner_id,finished_goods_lot_id,packaging_run_id,quantity,unit,quarantine_reason,location,entered_by,entered_at,remaining_quantity,provenance)
select workspace_id,owner_id,id,packaging_run_id,quantity,unit,'Performance quarantine','Quarantine',owner_id,now(),quantity,genealogy_snapshot from public.finished_goods_lots where internal_lot_code like 'FG-PERF-%';
insert into public.finished_goods_lot_events(workspace_id,owner_id,finished_goods_lot_id,packaging_run_id,production_output_id,production_run_id,product_id,formula_version_id,event_type,quantity,unit,consumer_batch_code,actor_id,occurred_at,policy_versions,revision,event_key)
select l.workspace_id,l.owner_id,l.id,l.packaging_run_id,l.production_output_id,l.production_run_id,l.product_id,l.formula_version_id,case e when 1 then 'finished_goods_lot_created' else 'finished_goods_lot_quarantined' end,l.quantity,l.unit,l.consumer_batch_code,l.owner_id,now(),'{}',1,'perf:'||l.id||':'||e from public.finished_goods_lots l cross join generate_series(1,2)e where l.internal_lot_code like 'FG-PERF-%';
analyze public.packaged_output_reconciliations;analyze public.finished_goods_lots;analyze public.finished_goods_quarantines;analyze public.finished_goods_lot_events;
explain(analyze,buffers) select * from public.packaged_output_reconciliations where workspace_id='00000000-0000-0000-0000-000000000001' and packaging_run_id=(select id from public.packaging_runs where internal_run_code='PKG-PERF-5000') order by reconciliation_version desc limit 1;
explain(analyze,buffers) select coalesce(sum(quantity),0) from public.finished_goods_lots where workspace_id='00000000-0000-0000-0000-000000000001' and packaging_run_id=(select id from public.packaging_runs where internal_run_code='PKG-PERF-5000');
explain(analyze,buffers) select * from public.finished_goods_lots where workspace_id='00000000-0000-0000-0000-000000000001' and packaging_run_id=(select id from public.packaging_runs where internal_run_code='PKG-PERF-5000') order by lot_sequence;
explain(analyze,buffers) select id from public.finished_goods_lots where workspace_id='00000000-0000-0000-0000-000000000001' and consumer_batch_code='KF-PERF-12500';
explain(analyze,buffers) select l.*,q.* from public.finished_goods_lots l join public.finished_goods_quarantines q on q.workspace_id=l.workspace_id and q.finished_goods_lot_id=l.id where l.workspace_id='00000000-0000-0000-0000-000000000001' and l.internal_lot_code='FG-PERF-12500';
explain(analyze,buffers) select * from public.finished_goods_lot_events where workspace_id='00000000-0000-0000-0000-000000000001' and finished_goods_lot_id=(select id from public.finished_goods_lots where internal_lot_code='FG-PERF-12500') order by occurred_at,id;
rollback;
