import { BookOpen, ChevronLeft, ChevronRight, Search } from 'lucide-react'
import { Link, useLocation, useParams, useSearchParams } from 'react-router-dom'
import { bibleArticles, bibleById, searchBible } from './bible/bibleContent'

export function BiblePage(){
 const {articleId}=useParams(),location=useLocation(),[params,setParams]=useSearchParams(),query=params.get('q')??''
 const article=articleId?bibleById.get(articleId):undefined,returnTo=params.get('from')
 if(articleId&&!article)return <section className="panel bible-empty"><h1>Article not found</h1><p>This Bible link is invalid or the article was removed.</p><Link className="button ghost" to="/knowledge/bible">Open the table of contents</Link></section>
 if(article)return <Article article={article} returnTo={returnTo}/>
 const results=query?searchBible(query):[],sections=[...new Set(bibleArticles.map(item=>item.section))]
 return <div className="bible-page"><header className="bible-hero"><div><span className="eyebrow">Living operations manual</span><h1>Koalafrog Bible</h1><p>Repository-verified guidance for planning, execution, evidence, and safe workshop operation.</p></div><Link className="button primary" to="/knowledge/bible/start-here">Start here</Link></header><label className="bible-search"><Search size={17}/><input value={query} onChange={event=>setParams(event.target.value?{q:event.target.value}:{})} placeholder="Search titles, terms, statuses, workflows…" aria-label="Search Koalafrog Bible"/></label>{query?<section aria-label="Bible search results"><p className="bible-result-count">{results.length} result{results.length===1?'':'s'} for “{query}”</p><div className="bible-results">{results.length?results.map(({article:item,excerpt,matchedKeywords})=><Link key={item.id} to={`/knowledge/bible/${item.id}`} state={{from:location.pathname+location.search}}><span>{item.section}</span><h2>{item.title}</h2><p>{excerpt}</p>{matchedKeywords.length>0&&<small>{matchedKeywords.join(' · ')}</small>}</Link>):<section className="panel bible-empty"><h2>No matching guidance</h2><p>Try a module, status, glossary term, or action such as “inventory adjustment”.</p></section>}</div></section>:<div className="bible-toc">{sections.map(section=><section key={section}><h2>{section}</h2>{bibleArticles.filter(item=>item.section===section).map(item=><Link key={item.id} to={`/knowledge/bible/${item.id}`}><BookOpen size={15}/><div><strong>{item.title}</strong><span>{item.summary}</span></div><small>{item.status}</small></Link>)}</section>)}</div>}</div>
}

function Article({article,returnTo}:{article:(typeof bibleArticles)[number];returnTo:string|null}){
 const index=bibleArticles.findIndex(item=>item.id===article.id),previous=bibleArticles[index-1],next=bibleArticles[index+1]
 return <article className="bible-article"><nav className="bible-breadcrumbs" aria-label="Breadcrumb"><Link to="/knowledge">Knowledge</Link><span>›</span><Link to="/knowledge/bible">Koalafrog Bible</Link><span>›</span><span>{article.section}</span></nav>{returnTo?.startsWith('/')&&<Link className="bible-return" to={returnTo}><ChevronLeft size={14}/>Back to module</Link>}<header><span className="eyebrow">{article.section} · {article.status}</span><h1>{article.title}</h1><p>{article.summary}</p><dl><div><dt>Last verified</dt><dd>{article.lastVerified}</dd></div><div><dt>Core records</dt><dd>{article.entities.join(', ')}</dd></div></dl></header><div className="bible-article-layout"><aside aria-label="Article contents"><strong>On this page</strong>{article.content.map(block=><a key={block.heading} href={`#${slug(block.heading)}`}>{block.heading}</a>)}</aside><div className="bible-body">{article.content.map(block=><section key={block.heading} id={slug(block.heading)}><h2>{block.heading}</h2><p>{block.body}</p>{block.items&&<ul>{block.items.map(item=><li key={item}>{item}</li>)}</ul>}</section>)}</div></div>{article.relatedArticles.length>0&&<section className="bible-related"><h2>Related Bible articles</h2><div>{article.relatedArticles.map(id=>{const item=bibleById.get(id);return item&&<Link key={id} to={`/knowledge/bible/${id}`}>{item.title}<ChevronRight size={14}/></Link>})}</div></section>}<nav className="bible-pager" aria-label="Article navigation">{previous?<Link to={`/knowledge/bible/${previous.id}`}><ChevronLeft size={15}/><span>Previous<small>{previous.title}</small></span></Link>:<span/>}{next&&<Link to={`/knowledge/bible/${next.id}`}><span>Next<small>{next.title}</small></span><ChevronRight size={15}/></Link>}</nav></article>
}
const slug=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')
