/* eslint-disable react-hooks/set-state-in-effect -- repository hydration and editor reset synchronize external records */
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, Archive, Copy, Pin } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { useActiveWorkspace } from "../../platform/startup/ActiveWorkspaceContext";
import { IntelligenceReport } from "../scent-house/ScentStudioPage";
import { loadKnowledge, saveKnowledgeReference } from "./data/knowledgeRepository";
import { buildIntelligenceLibrary } from "./domain/knowledge";
import { useFormulaData } from "../formulas/state/FormulaDataContext";
import type { IntelligenceResponse } from "../intelligence/domain/intelligenceContract";

export function IntelligenceThreadPage(){
 const {threadId=""}=useParams(),workspace=useActiveWorkspace(),domain=useFormulaData();const [loaded,setLoaded]=useState<Awaited<ReturnType<typeof loadKnowledge>>>(),[error,setError]=useState(""),[title,setTitle]=useState(""),[note,setNote]=useState(""),[tags,setTags]=useState("");
 const refresh=useCallback(async()=>{if(!workspace)return;try{setLoaded(await loadKnowledge(workspace.workspaceId));setError("")}catch(cause){setError(cause instanceof Error?cause.message:"Thread unavailable.")}},[workspace]);useEffect(()=>void refresh(),[refresh]);
 const item=useMemo(()=>loaded?buildIntelligenceLibrary(loaded.threads,loaded.runs,loaded.references).find(x=>x.thread.id===threadId):undefined,[loaded,threadId]);
 useEffect(()=>{if(item){setTitle(item.reference?.title??"");setNote(item.reference?.user_note??"");setTags(item.reference?.tags.join(", ")??"")}},[item]);
 if(error)return <section className="panel knowledge-state" role="alert"><h2>Thread unavailable</h2><p>{error}</p></section>;if(!item)return <section className="panel knowledge-state"><p>Loading Intelligence thread…</p></section>;
 const save=async(patch?:{pinned?:boolean;archived?:boolean})=>{if(!workspace)return;try{await saveKnowledgeReference({workspaceId:workspace.workspaceId,threadId,current:item.reference,title,userNote:note,tags:tags.split(","),isPinned:patch?.pinned??item.reference?.is_pinned,archived:patch?.archived??!!item.reference?.archived_at});await refresh()}catch(cause){setError(cause instanceof Error?cause.message:"Knowledge reference could not be saved.")}};
 const latest=item.latestRun,selection=latest?.context_selection;const reopen=new URLSearchParams({threadId,...(typeof selection?.productId==="string"?{productId:selection.productId}:{}),...(typeof selection?.formulaVersionId==="string"?{formulaVersionId:selection.formulaVersionId}:{}),...(((selection?.selectedIngredientIds as string[]|undefined)??[]).length?{ingredients:((selection?.selectedIngredientIds as string[]).join(","))}:{}),...(((selection?.conceptMaterials as string[]|undefined)??[]).length?{concepts:((selection?.conceptMaterials as string[]).join(","))}:{})});
 return <div className="knowledge-detail"><Link className="back-link" to="/knowledge"><ArrowLeft size={14}/>Knowledge</Link><header><div><span className="eyebrow">Intelligence Library / authoritative history</span><h1>{item.displayTitle}</h1><p>{item.completedRuns} completed analyses · created {new Date(item.thread.created_at).toLocaleString()}</p></div><div className="action-row"><button className="button ghost" onClick={()=>save({pinned:!item.reference?.is_pinned})}><Pin size={14}/>{item.reference?.is_pinned?"Unpin":"Pin"}</button><button className="button ghost" onClick={()=>save({archived:!item.reference?.archived_at})}><Archive size={14}/>{item.reference?.archived_at?"Unarchive":"Archive"}</button><Link className="button primary" to={`/scent-house/studio?${reopen}`}>Continue in Scent Studio</Link></div></header>
 <section className="panel knowledge-editor"><label>Custom title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder={item.thread.title}/></label><label>Private note<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><label>Tags<input value={tags} onChange={e=>setTags(e.target.value)} placeholder="woods, first concept"/></label><button className="button primary" onClick={()=>save()}>Save organization</button></section>
 {latest?.response_payload&&<button className="button ghost copy-report" onClick={()=>navigator.clipboard.writeText(humanReadableReport(latest.response_payload!))}><Copy size={14}/>Copy latest human-readable report</button>}
 {latest&&<section className="panel thread-current-context"><h2>Latest historical selection</h2><p>{selection?.productId?`Product · ${domain.products.find(item=>item.id===selection.productId)?.name??selection.productId}`:"No Product selected"} · {selection?.formulaVersionId?`Formula Version · ${domain.formulaVersions.find(item=>item.id===selection.formulaVersionId)?.version??selection.formulaVersionId}`:"No Formula Version selected"}</p><p>Workspace Materials · {((selection?.selectedIngredientIds as string[]|undefined)??[]).map(id=>domain.ingredients.find(item=>item.id===id)?.commonName??id).join(", ")||"None"}</p></section>}
 <section className="conversation">{item.runs.map(run=>{const historical=run.context_selection;return <article key={run.id} className={`conversation-run ${run.status}`}><section className="panel user-question"><span className="eyebrow">User question · {new Date(run.created_at).toLocaleString()}</span><div><h2>{run.user_prompt}</h2><button className="icon-button" aria-label="Copy original question" onClick={()=>navigator.clipboard.writeText(run.user_prompt)}><Copy size={14}/></button></div><ContextReceipt selection={historical} manifest={run.context_manifest}/></section>{run.status==="completed"&&run.response_payload?<><IntelligenceReport report={run.response_payload} handoff={{workspaceId:workspace?.workspaceId,threadId:item.thread.id,runId:run.id,productId:typeof historical.productId==='string'?historical.productId:undefined,formulaVersionId:typeof historical.formulaVersionId==='string'?historical.formulaVersionId:undefined}}/><section className="panel provenance"><h3>Provenance</h3><dl><div><dt>Prompt</dt><dd>{run.prompt_version}</dd></div><div><dt>Schema</dt><dd>{run.response_schema_version??"Not recorded"}</dd></div><div><dt>Context</dt><dd>v{run.context_version}</dd></div><div><dt>Provider / model</dt><dd>{run.provider_name??"Not recorded"} · {run.model_name??"Not recorded"}</dd></div><div><dt>Usage</dt><dd>{run.total_tokens==null?"Unavailable":`${run.total_tokens} tokens`}</dd></div><div><dt>Estimated cost</dt><dd>{run.estimated_cost_usd==null?"Cost unavailable":`$${run.estimated_cost_usd.toFixed(4)} · ${run.pricing_snapshot_version??"snapshot not recorded"}`}</dd></div></dl></section></>:<section className="panel run-status"><strong>{run.status==="failed"?"Analysis did not complete":"Analysis in progress"}</strong><p>{run.error_code?friendlyStatus(run.error_code):"No validated report is stored for this run."}</p></section>}</article>})}</section>
 </div>
}
function ContextReceipt({selection,manifest}:{selection:Record<string,unknown>;manifest:Record<string,unknown>}){const concepts=(selection.conceptMaterials as string[]|undefined)??[],ingredients=(selection.selectedIngredientIds as string[]|undefined)??[];return <div className="context-receipt"><strong>Historical context receipt</strong><span>{selection.productId?1:0} Product</span><span>{selection.formulaVersionId?1:0} Formula Version</span><span>{ingredients.length} Workspace Materials</span><span>{concepts.length} Concept Materials</span><span>{(manifest.scentMemoryCheckpointIds as string[]|undefined)?.length??0} Scent Memory observations</span>{concepts.length>0&&<p>Concept Materials: {concepts.join(", ")}</p>}</div>}
const friendlyStatus=(code:string)=>code==="INVALID_PROVIDER_RESPONSE"?"The provider response did not pass Koalafrog validation.":code==="PROVIDER_FAILURE"?"The provider could not complete this analysis.":"The analysis did not complete."
const humanReadableReport=(report:IntelligenceResponse)=>[report.title,report.summary,"",...report.claims.map(claim=>`${claim.kind.toUpperCase()}: ${claim.text}${claim.evidenceRefs.length?`\nEvidence: ${claim.evidenceRefs.map(ref=>ref.label).join(", ")}`:""}`),"","Directions",...report.directions.map(direction=>`${direction.name}: ${direction.predictedEffect}`),"","Experiments",...report.experiments.map(experiment=>`${experiment.name}: ${experiment.hypothesis}`),"","Limitations",...report.limitations].join("\n")
