export const LIVE_RESEARCH_SCHEMA_VERSION=1 as const
export type LiveFieldState='unknown'|'inferred'|'reported'|'verified'
export interface LiveResearchInputItem{id:string;name:string;category:string;quantity:number;unit:string;requiredSpecifications:string[];acceptableSubstitutes:string[];neededBy:string|null;priority:string;notes:string}
export interface LiveResearchRequest{schemaVersion:1;workspaceId:string;jobId:string;requestId:string;deliveryCountry:string;documentationRequirements:string[];preferredSuppliers:string[];excludedSuppliers:string[];items:LiveResearchInputItem[]}
export interface LiveFieldEvidence{field:string;state:LiveFieldState;sourceUrl:string|null;snippet:string|null}
export interface LiveCandidate{requestedItemId:string;supplierName:string;supplierType:'manufacturer'|'distributor'|'specialist_cosmetic_supplier'|'marketplace'|'unknown';productTitle:string;sourceUrl:string;packageQuantity:number|null;packageUnit:string|null;itemPrice:number|null;currency:string|null;moq:number|null;shippingCost:number|null;deliveryEstimateDays:number|null;stockStatus:'unknown'|'in_stock'|'limited'|'backorder'|'out_of_stock';coaAvailability:'unknown'|'available'|'unavailable'|'partial';sdsAvailability:'unknown'|'available'|'unavailable'|'partial';technicalDocumentAvailability:'unknown'|'available'|'unavailable'|'partial';firstOrderDiscount:number|null;sourceDate:string;evidence:LiveFieldEvidence[];sourceNotes:string;confidence:'low'|'medium'|'high'|'unknown'}
export interface LiveResearchResponse{schemaVersion:1;partial:boolean;candidates:LiveCandidate[];providerNotes:string}
export const liveResearchResponseJsonSchema={type:'object',additionalProperties:false,required:['schemaVersion','partial','candidates','providerNotes'],properties:{schemaVersion:{type:'integer',const:LIVE_RESEARCH_SCHEMA_VERSION},partial:{type:'boolean'},providerNotes:{type:'string'},candidates:{type:'array',maxItems:20,items:{type:'object',additionalProperties:false,required:['requestedItemId','supplierName','supplierType','productTitle','sourceUrl','packageQuantity','packageUnit','itemPrice','currency','moq','shippingCost','deliveryEstimateDays','stockStatus','coaAvailability','sdsAvailability','technicalDocumentAvailability','firstOrderDiscount','sourceDate','evidence','sourceNotes','confidence'],properties:{requestedItemId:{type:'string'},supplierName:{type:'string'},supplierType:{type:'string',enum:['manufacturer','distributor','specialist_cosmetic_supplier','marketplace','unknown']},productTitle:{type:'string'},sourceUrl:{type:'string'},packageQuantity:{type:['number','null']},packageUnit:{type:['string','null']},itemPrice:{type:['number','null']},currency:{type:['string','null']},moq:{type:['number','null']},shippingCost:{type:['number','null']},deliveryEstimateDays:{type:['integer','null']},stockStatus:{type:'string',enum:['unknown','in_stock','limited','backorder','out_of_stock']},coaAvailability:{type:'string',enum:['unknown','available','unavailable','partial']},sdsAvailability:{type:'string',enum:['unknown','available','unavailable','partial']},technicalDocumentAvailability:{type:'string',enum:['unknown','available','unavailable','partial']},firstOrderDiscount:{type:['number','null']},sourceDate:{type:'string'},sourceNotes:{type:'string'},confidence:{type:'string',enum:['low','medium','high','unknown']},evidence:{type:'array',items:{type:'object',additionalProperties:false,required:['field','state','sourceUrl','snippet'],properties:{field:{type:'string'},state:{type:'string',enum:['unknown','inferred','reported','verified']},sourceUrl:{type:['string','null']},snippet:{type:['string','null']}}}}}}}}} as const
const suspiciousHosts=['localhost','127.0.0.1','0.0.0.0','example.com','example.test']
export function safeSourceUrl(value:string){try{const url=new URL(value);return['http:','https:'].includes(url.protocol)&&!suspiciousHosts.some(host=>url.hostname===host||url.hostname.endsWith(`.${host}`))&&!url.username&&!url.password}catch{return false}}
const numberOrNull=(value:unknown)=>value==null?null:typeof value==='number'&&Number.isFinite(value)&&value>=0?value:null
const textOrNull=(value:unknown)=>typeof value==='string'&&value.trim()?value.trim():null
function validSourceDate(value:unknown,today:Date){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value))return null;const[year,month,day]=value.split('-').map(Number),date=new Date(Date.UTC(year,month-1,day));if(date.getUTCFullYear()!==year||date.getUTCMonth()!==month-1||date.getUTCDate()!==day||date.getTime()>today.getTime())return null;return value}
export function freshnessFromSourceDate(value:string,today=new Date()):'fresh'|'aging'|'stale'{const checked=Date.parse(`${value}T00:00:00Z`),current=Date.UTC(today.getUTCFullYear(),today.getUTCMonth(),today.getUTCDate()),age=Math.max(0,Math.floor((current-checked)/86400000));return age<=7?'fresh':age<=30?'aging':'stale'}
function normalizedEvidence(value:unknown):LiveFieldEvidence[]{if(!Array.isArray(value))return[];return value.filter(entry=>entry&&typeof entry==='object').map(entry=>{const raw=entry as Record<string,unknown>,field=textOrNull(raw.field),requestedState=['unknown','inferred','reported','verified'].includes(String(raw.state))?String(raw.state)as LiveFieldState:'unknown',candidateUrl=textOrNull(raw.sourceUrl),sourceUrl=candidateUrl&&safeSourceUrl(candidateUrl)?candidateUrl:null,snippet=textOrNull(raw.snippet),state=requestedState==='verified'&&(!sourceUrl||!snippet)?'reported':requestedState;return{field:field??'',state,sourceUrl,snippet}}).filter(evidence=>evidence.field)}
export function validateLiveResearchResponse(value:unknown,itemIds:string[],today=new Date()):LiveResearchResponse{if(!value||typeof value!=='object')throw new Error('LIVE_RESPONSE_MALFORMED');const raw=value as Record<string,unknown>;if(raw.schemaVersion!==1||typeof raw.partial!=='boolean'||!Array.isArray(raw.candidates)||typeof raw.providerNotes!=='string')throw new Error('LIVE_RESPONSE_MALFORMED');const candidates=raw.candidates.map((entry,index)=>{if(!entry||typeof entry!=='object')throw new Error(`LIVE_CANDIDATE_${index}_MALFORMED`);const c=entry as Record<string,unknown>,sourceUrl=String(c.sourceUrl??'');if(!itemIds.includes(String(c.requestedItemId))||!safeSourceUrl(sourceUrl)||!String(c.supplierName??'').trim()||!String(c.productTitle??'').trim())throw new Error(`LIVE_CANDIDATE_${index}_UNSAFE`);const evidence=normalizedEvidence(c.evidence),date=validSourceDate(c.sourceDate,today)??today.toISOString().slice(0,10),docs=(key:string)=>['available','unavailable','partial'].includes(String(c[key]))&&evidence.some(e=>e.field===key&&e.sourceUrl&&e.snippet)?String(c[key])as'available'|'unavailable'|'partial':'unknown';return{requestedItemId:String(c.requestedItemId),supplierName:String(c.supplierName).trim().slice(0,200),supplierType:['manufacturer','distributor','specialist_cosmetic_supplier','marketplace'].includes(String(c.supplierType))?c.supplierType as LiveCandidate['supplierType']:'unknown',productTitle:String(c.productTitle).trim().slice(0,300),sourceUrl,packageQuantity:numberOrNull(c.packageQuantity),packageUnit:textOrNull(c.packageUnit)?.toLowerCase()??null,itemPrice:numberOrNull(c.itemPrice),currency:/^[A-Za-z]{3}$/.test(String(c.currency??''))?String(c.currency).toUpperCase():null,moq:numberOrNull(c.moq),shippingCost:numberOrNull(c.shippingCost),deliveryEstimateDays:Number.isInteger(c.deliveryEstimateDays)&&Number(c.deliveryEstimateDays)>=0?Number(c.deliveryEstimateDays):null,stockStatus:['in_stock','limited','backorder','out_of_stock'].includes(String(c.stockStatus))?c.stockStatus as LiveCandidate['stockStatus']:'unknown',coaAvailability:docs('coaAvailability'),sdsAvailability:docs('sdsAvailability'),technicalDocumentAvailability:docs('technicalDocumentAvailability'),firstOrderDiscount:numberOrNull(c.firstOrderDiscount),sourceDate:date,evidence,sourceNotes:String(c.sourceNotes??'').slice(0,1000),confidence:evidence.some(e=>e.state==='verified'&&e.sourceUrl&&e.snippet)&&['medium','high'].includes(String(c.confidence))?c.confidence as'medium'|'high':['low','unknown'].includes(String(c.confidence))?c.confidence as'low'|'unknown':'low'}satisfies LiveCandidate});return{schemaVersion:1,partial:raw.partial,candidates,providerNotes:String(raw.providerNotes).slice(0,1000)}}
export function buildLiveResearchPrompt(request:LiveResearchRequest){return`Research current procurement offers for a private cosmetics workshop. Prefer manufacturers, established distributors, and specialist cosmetic suppliers. Marketplace listings must be flagged. Never guess unavailable fields or certification/document claims. Separate product price, shipping, tax/duty, MOQ, and package size. Every non-unknown claim needs field evidence with a current source URL and short snippet. Generated text alone is not verified evidence. Do not recommend a cheapest option and do not perform purchasing.\n\nStructured request:\n${JSON.stringify(request)}`}
