export type ExperimentStatus='draft'|'ready_for_review'|'approved'|'handed_off'|'in_progress'|'completed'|'cancelled'|'archived'
export type ExperimentType='scent_direction'|'formula_adjustment'|'ingredient_comparison'|'formula_comparison'|'process_adjustment'|'stability_observation'|'general_development'
export interface ExperimentChange{id:string;variant_id:string;ingredient_id:string|null;concept_material_name:string|null;change_type:string;qualitative_guidance:string|null;current_value:number|null;proposed_value:number|null;unit:string|null;rationale:string;display_order:number}
export interface ExperimentVariant{id:string;name:string;purpose:string;is_control:boolean;display_order:number;status:string;linked_formula_version_id:string|null;linked_lab_batch_id:string|null;changes:ExperimentChange[]}
export interface ObservationPrompt{id:string;variant_id:string|null;checkpoint_type:string|null;prompt:string;category:string;display_order:number;is_required:boolean}
export interface DevelopmentExperiment{id:string;workspace_id:string;title:string;experiment_type:ExperimentType;status:ExperimentStatus;objective:string;hypothesis:string;product_id:string|null;base_formula_version_id:string|null;source_intelligence_thread_id:string|null;source_intelligence_run_id:string|null;source_response_item_type:'direction'|'experiment'|null;source_response_item_id:string|null;user_rationale:string|null;acceptance_criteria:string|null;notes:string|null;conclusion:string|null;outcome_summary:string|null;hypothesis_outcome:string|null;preferred_variant_id:string|null;next_step:string|null;revision:number;created_at:string;updated_at:string;variants:ExperimentVariant[];observationPrompts:ObservationPrompt[]}
export interface ExperimentPlan{title:string;experimentType:ExperimentType;objective:string;hypothesis:string;productId?:string;baseFormulaVersionId?:string;sourceThreadId?:string;sourceRunId?:string;sourceItemType?:'direction'|'experiment';sourceItemId?:string;userRationale?:string;acceptanceCriteria?:string;notes?:string;idempotencyKey:string;variants:Array<{id:string;name:string;purpose:string;isControl:boolean;displayOrder:number;changes:Array<{ingredientId?:string;conceptMaterialName?:string;changeType:string;qualitativeGuidance?:string;currentValue?:number;proposedValue?:number;unit?:string;rationale:string;displayOrder:number}>}>;observationPrompts:Array<{checkpointType?:string;prompt:string;category:string;displayOrder:number;isRequired:boolean}>}
export const transitionTargets:Record<ExperimentStatus,ExperimentStatus[]>={draft:['ready_for_review','cancelled','archived'],ready_for_review:['draft','approved','cancelled'],approved:['handed_off','in_progress','cancelled'],handed_off:['in_progress','completed','cancelled'],in_progress:['completed','cancelled'],completed:['archived'],cancelled:['archived'],archived:[]}
export function reviewIssues(experiment:DevelopmentExperiment){const issues:string[]=[];if(!experiment.title.trim())issues.push('Add a title.');if(!experiment.objective.trim()&&!experiment.hypothesis.trim())issues.push('Add an objective or hypothesis.');if(!experiment.variants.length)issues.push('Add at least one variant.');if(experiment.variants.some(v=>v.changes.some(c=>c.concept_material_name&&!c.ingredient_id&&c.proposed_value!==null)))issues.push('Map quantitative Concept Materials to Workspace Ingredients before approval.');return issues}
export function canFormulaHandoff(experiment:DevelopmentExperiment,variant:ExperimentVariant){return !!experiment.base_formula_version_id&&['approved','handed_off'].includes(experiment.status)&&!variant.changes.some(c=>c.concept_material_name&&!c.ingredient_id)}
export function formulaDiff(variant:ExperimentVariant){return variant.changes.map(c=>({material:c.ingredient_id??c.concept_material_name??'Unknown material',before:c.current_value,after:c.proposed_value,unit:c.unit,action:c.change_type}))}
export function copilotItems(experiments:DevelopmentExperiment[]){return experiments.filter(e=>!['archived','cancelled'].includes(e.status)).flatMap(e=>e.variants.map(v=>({experimentId:e.id,variantId:v.id,title:e.title,variant:v.name,status:e.status,next:e.status==='completed'?'Capture the outcome in Scent Memory.':v.linked_lab_batch_id?'Continue the linked Lab Batch.':e.status==='approved'?'Choose an explicit handoff.':'Review and advance the plan.'}))) }
