import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'

const edge = readFileSync('supabase/functions/analyze-beard-photos/index.ts', 'utf8')
const client = readFileSync('src/intelligence/Vision/beardPhotoClient.ts', 'utf8')
const prompt = readFileSync('supabase/functions/_shared/beardPhotoPrompt.ts', 'utf8')
const migration = readFileSync('supabase/migrations/20260721140000_beard_photo_analysis.sql', 'utf8')
const provenanceMigration = readFileSync('supabase/migrations/20260721210000_beard_photo_attempt_provenance.sql', 'utf8')
const semanticMigration = readFileSync('supabase/migrations/20260722090000_beard_semantic_diagnostics.sql', 'utf8')
const guardStrategyMigration = readFileSync('supabase/migrations/20260722100000_beard_guard_strategy_semantics.sql', 'utf8')
const semanticV3Constraints = readFileSync('supabase/migrations/20260722101000_beard_semantic_v3_constraints.sql', 'utf8')
const persistenceDiagnostics = readFileSync('supabase/migrations/20260722110000_beard_persistence_diagnostics.sql', 'utf8')
const observationKeysMigration = readFileSync('supabase/migrations/20260722130000_beard_observation_keys.sql', 'utf8')
const supportDiagnosticMigration = readFileSync('supabase/migrations/20260722190000_beard_support_diagnostic_lookup.sql', 'utf8')
const runtime = readFileSync('supabase/functions/_shared/beardPhotoRuntime.ts', 'utf8')

describe('beard photo intelligence boundaries', () => {
  it('authenticates, scopes workspace access, and verifies storage ownership', () => {
    expect(edge).toContain('auth.getUser')
    expect(edge).toMatch(/\.eq\("owner_id", userId\)/)
    expect(edge).toMatch(/const prefix =/)
    expect(edge).toMatch(/\.eq\("lifecycle_state", "active"\)/)
  })

  it('keeps provider credentials server-side and bounds provider execution', () => {
    expect(edge).toContain('Deno.env.get("OPENAI_API_KEY")')
    expect(edge).not.toMatch(/VITE_.*OPENAI/)
    expect(runtime).toContain('BEARD_PROVIDER_TIMEOUT_DEFAULT_MS = 110_000')
    expect(runtime).toContain('BEARD_PROVIDER_TIMEOUT_MIN_MS = 60_000')
    expect(runtime).toContain('BEARD_PROVIDER_TIMEOUT_MAX_MS = 120_000')
    expect(runtime).toContain('controller.abort()')
    expect(edge).toContain('OPENAI_BEARD_VISION_TIMEOUT_MS')
    expect(edge).toMatch(/store: false/)
    expect(edge).toContain('Deno.env.get("OPENAI_BEARD_VISION_MODEL")')
    expect(edge).not.toContain('gpt-5.6-terra')
    expect(edge).toContain('ALLOWED_MODELS.has(model)')
  })

  it('has rate limiting, idempotency, strict validation, and no mock fallback', () => {
    expect(edge).toContain('idempotencyKey')
    expect(edge).toContain('RATE_LIMITED')
    expect(edge).toContain('validateBeardPhotoAnalysisResult')
    expect(client).not.toMatch(/mock|demo/i)
    expect(edge).not.toMatch(/createSignedUrl|signedUrl/)
    expect(migration).toContain('unique (workspace_id, owner_user_id, idempotency_key)')
    expect(migration).toContain('pg_advisory_xact_lock')
    expect(migration).toContain('intelligence_analyses_one_active_per_owner')
    expect(provenanceMigration).toContain('provider_attempt_count=provider_attempt_count+1')
    expect(provenanceMigration).toContain("and status='staging'")
    expect(semanticMigration).toContain("semantic_rule_version='beard-semantic-safety-v2'")
    expect(semanticMigration).toContain("candidate_prompt_version <> 'beard-photo-analysis-v2'")
    expect(guardStrategyMigration).toContain("semantic_rule_version='beard-semantic-safety-v3'")
    expect(guardStrategyMigration).toContain("candidate_prompt_version <> 'beard-photo-analysis-v3'")
    expect(observationKeysMigration).toContain("candidate_prompt_version <> 'beard-photo-analysis-v4'")
    expect(semanticV3Constraints).toContain("'beard-semantic-safety-v2'")
    expect(semanticV3Constraints).toContain("'beard-semantic-safety-v3'")
    expect(edge.indexOf('begin_beard_provider_attempt')).toBeLessThan(edge.indexOf('.download('))
    expect(edge).toContain('status: "staging"')
  })

  it('restricts browser origins to production and localhost development', () => {
    expect(edge).toContain('https://koalafrog-hq.pages.dev')
    expect(edge).toContain('allowedOrigin(origin)')
    expect(edge).toContain('"Vary": "Origin"')
  })

  it('instructs the provider not to infer identity, health, or exact measurements', () => {
    expect(prompt).toMatch(/Never identify the person/i)
    expect(prompt).toMatch(/health.*medical conditions/i)
    expect(prompt).toMatch(/Never claim exact millimeter length/i)
    expect(prompt).toMatch(/cannot diagnose a medical condition/i)
    expect(prompt).toMatch(/Existing recipe and Length Map values/i)
    expect(prompt).toMatch(/guard number is an equipment instruction/i)
    expect(prompt).toMatch(/proposed guard experiment/i)
    expect(prompt).toMatch(/never guarantee the exact physical length/i)
    expect(prompt).toMatch(/observationKey/)
    expect(prompt).toMatch(/lowercase snake_case/)
    expect(prompt).toMatch(/not database IDs/)
    expect(prompt).toMatch(/supportingObservationKeys/)
  })

  it('persists only server-owned allowlisted failure metadata', () => {
    expect(edge).toContain('Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")')
    expect(edge).toContain('toDurableBeardFailureDiagnostic')
    expect(edge).toMatch(/\.eq\(\s*"owner_user_id",\s*userId/)
    expect(edge).toMatch(/\.eq\("correlation_id", correlationId\)/)
    expect(semanticMigration).toContain('failure_json_path')
    expect(semanticMigration).toContain('failure_trace_complete_check')
    expect(semanticMigration).toMatch(/revoke insert\([\s\S]*failure_stage[\s\S]*from authenticated/)
    expect(semanticMigration).toMatch(/revoke update\([\s\S]*failure_stage[\s\S]*from authenticated/)
    expect(semanticMigration).not.toMatch(/update public\.intelligence_analyses[\s\S]*failure_json_path=/)
  })

  it('logs only the safe stage envelope and never sensitive request material', () => {
    expect(edge).toContain('console.info(beardStageLog')
    expect(runtime).not.toMatch(/filename|objectPath|prompt|responseBody|authorization|email|apiKey|imageData/i)
    expect(edge).not.toMatch(/console\.(?:log|debug|warn|error)/)
    expect(edge).not.toMatch(/console\.info\((?!beardStageLog)/)
  })

  it('keeps the browser on the normal invocation lifecycle without a shorter client timeout or retry', () => {
    expect(client).toContain("supabase.functions.invoke('analyze-beard-photos'")
    expect(client).not.toMatch(/setTimeout|timeoutMs|retry/i)
    expect(edge).not.toMatch(/retry\s*[:=]|for\s*\([^)]*retry/i)
  })

  it('returns the timeout support ID and always reaches cleanup after provider execution', () => {
    expect(edge).toContain('error instanceof ProviderError')
    expect(edge).toMatch(/safeError\([\s\S]*correlationId/)
    expect(edge.indexOf('provider.analyzeBeardPhotos')).toBeLessThan(edge.indexOf('const removed = await client.storage'))
    expect(edge.indexOf('status: "failed"')).toBeLessThan(edge.indexOf('const removed = await client.storage'))
    expect(edge).not.toContain('req.signal')
  })

  it('persists no partial domain result when semantic validation fails and still reaches cleanup', () => {
    expect(edge.indexOf('() => validateBeardPhotoSemantics(typed)')).toBeLessThan(edge.indexOf('persist_beard_analysis_result'))
    expect(edge.indexOf('toDurableBeardFailureDiagnostic')).toBeLessThan(edge.indexOf('const removed = await client.storage'))
    expect(edge.indexOf('result = undefined')).toBeLessThan(edge.indexOf('const removed = await client.storage'))
  })

  it('persists results atomically with metadata-only database diagnostics', () => {
    expect(edge).toContain('trustedClient.rpc("persist_beard_analysis_result"')
    expect(edge).not.toContain('client.from("intelligence_observations")')
    expect(edge).not.toContain('"intelligence_recommendations",\n    ).insert')
    expect(persistenceDiagnostics).toContain('exception when others')
    expect(persistenceDiagnostics).toContain('get stacked diagnostics')
    expect(persistenceDiagnostics).toContain('returned_sqlstate')
    expect(persistenceDiagnostics).toContain('constraint_name')
    expect(persistenceDiagnostics).toContain("'beard-persistence-diagnostic-v1'")
    expect(persistenceDiagnostics).not.toMatch(/message_text|pg_exception_detail|pg_exception_hint/i)
    expect(persistenceDiagnostics).toMatch(/revoke all on function public\.persist_beard_analysis_result[\s\S]*from public,anon,authenticated/)
    expect(persistenceDiagnostics).toMatch(/grant execute on function public\.persist_beard_analysis_result[\s\S]*to service_role/)
  })

  it('maps provider keys to server ids and normalized relationships without browser writes', () => {
    expect(edge).toContain('schema_version: 2')
    expect(edge).toContain('contract_version: BEARD_PHOTO_CONTRACT_VERSION')
    expect(edge).toContain('trustedClient.from("intelligence_analyses")')
    expect(edge).toContain('trustedClient.from("intelligence_analysis_inputs")')
    expect(observationKeysMigration).toContain('provider_observation_key')
    expect(observationKeysMigration).toContain('observation_id_by_key')
    expect(observationKeysMigration).toContain('gen_random_uuid()')
    expect(observationKeysMigration).toContain('supportingObservationKeys')
    expect(observationKeysMigration).toContain('intelligence_recommendation_observations')
    expect(observationKeysMigration).toContain("revoke insert on table public.intelligence_observations from authenticated")
    expect(observationKeysMigration).toContain("grant select on table public.intelligence_recommendation_observations")
    expect(observationKeysMigration).not.toMatch(/message_text|pg_exception_detail|pg_exception_hint/i)
  })

  it('exposes only an owner-scoped metadata allowlist for support lookup', () => {
    expect(supportDiagnosticMigration).toContain('lookup_beard_analysis_support_diagnostic')
    expect(supportDiagnosticMigration).toContain('a.owner_user_id=current_owner')
    expect(supportDiagnosticMigration).toContain("a.status='failed'")
    expect(supportDiagnosticMigration).toContain('candidate_support_id !~*')
    expect(supportDiagnosticMigration).toMatch(/revoke all on function public\.lookup_beard_analysis_support_diagnostic\(uuid,text\)[\s\S]*from public,anon,service_role/)
    expect(supportDiagnosticMigration).toMatch(/grant execute on function public\.lookup_beard_analysis_support_diagnostic\(uuid,text\)[\s\S]*to authenticated/)
    expect(supportDiagnosticMigration).not.toMatch(/object_path|mime_type|byte_size|statement|reason|context_manifest/)
    expect(supportDiagnosticMigration).not.toMatch(/'resultPayload'|'providerUsage'|a\.result_payload\s*[,)]|a\.provider_usage\s*[,)]/)
    expect(supportDiagnosticMigration).not.toMatch(/message_text|pg_exception_detail|pg_exception_hint|createSignedUrl|signedUrl/i)
  })
})
