import { ArrowRight, Beaker, Box, FlaskConical, Leaf, Plus } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { SectionHeader } from '../../components/ui/SectionHeader'
import { StatusPill } from '../../components/ui/StatusPill'
import { useFormulaData } from '../formulas/state/FormulaDataContext'
import { ingredientBalance, stockState } from '../inventory/domain/inventoryLogic'
import { dashboardActionTarget, type DashboardAction } from './dashboardActions'

const quickActions:{label:string;action:DashboardAction;icon:typeof Box}[]=[{label:'New Product',action:'product',icon:Box},{label:'New Formula',action:'formula',icon:Beaker},{label:'Start Batch',action:'batch',icon:FlaskConical},{label:'Add Ingredient',action:'ingredient',icon:Leaf},{label:'Record Test',action:'test',icon:Plus}]
export function DashboardPage(){const data=useFormulaData();const navigate=useNavigate();const active=data.products.filter(p=>p.status==='Active');const low=data.ingredients.filter(i=>['Low','Out of Stock'].includes(stockState(i,data.inventoryLots,data.inventoryMovements)));const batches=[...data.labBatches].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,3);const tests=[...data.testSessions].filter(s=>s.status==='Planned'||s.status==='Active').sort((a,b)=>(a.dueDate??'9999').localeCompare(b.dueDate??'9999')).slice(0,4);return <><header className="dashboard-hero"><div><span className="eyebrow">Workspace overview</span><h1>Koalafrog HQ</h1><p>{active.length||batches.length||tests.length?'Your current workshop records and next actions.':'Your workspace is ready for its first Product, Formula, Ingredient, or Lab Batch.'}</p></div></header><section className="quick-actions" aria-label="Quick actions">{quickActions.map(({label,action,icon:Icon})=><button key={action} onClick={()=>navigate(dashboardActionTarget(action))}><Icon size={17}/><span>{label}</span></button>)}</section><div className="dashboard-grid">
<section className="panel span-8"><SectionHeader title="Active development" detail={`${active.length} products currently moving`} action={<Link className="text-button" to="/products">All products <ArrowRight size={15}/></Link>}/><div className="development-list">{active.map(product=><article key={product.id}><div className="dev-title"><span className="category-dot"/><div><strong>{product.name}</strong><small>{product.category}</small></div><StatusPill tone="green">{product.developmentStage}</StatusPill></div></article>)}{!active.length&&<p className="empty-state">No active Products yet. Create a Product to begin development.</p>}</div></section>
<section className="panel span-4 attention-panel"><SectionHeader title="Material attention" detail="Lot-derived stock signals"/><strong className="attention-number">{low.length}</strong><span>materials at or below reorder</span><div>{low.slice(0,4).map(item=><p key={item.id}><span>{item.commonName}</span><b>{ingredientBalance(item,data.inventoryLots,data.inventoryMovements)} {item.defaultUnit}</b></p>)}</div><Link className="text-button" to="/ingredients">Review ingredients <ArrowRight size={15}/></Link></section>
<section className="panel span-7"><SectionHeader title="Recent Lab Batches" detail="Latest work from the bench"/><div className="compact-list">{batches.map(batch=><article key={batch.id}><div className="round-icon"><FlaskConical size={16}/></div><div><strong>{batch.batchNumber}</strong><small>{data.products.find(p=>p.id===batch.productId)?.name??'Product unavailable'}</small></div><StatusPill tone={batch.status==='Completed'?'green':batch.status==='In Progress'?'blue':'neutral'}>{batch.status}</StatusPill></article>)}{!batches.length&&<p className="empty-state">No Lab Batches have been recorded.</p>}</div></section>
<section className="panel span-5"><SectionHeader title="Upcoming Testing" detail="Planned and active sessions"/><div className="test-list">{tests.map(test=><article key={test.id}><div><strong>{test.dueDate??'—'}</strong></div><span><b>{test.name}</b><small>{test.status}</small></span></article>)}{!tests.length&&<p className="empty-state">No testing sessions are scheduled.</p>}</div></section>
</div></>}
