import type { PackagingAllocation,PackagingComponent,PackagingInventoryLot,PackagingInventoryMovement,PackagingMovementType,PackagingSpecificationLine,PackagingSpecificationStatus,PackagingSpecificationVersion,PackagingSupplierProduct,InventoryUnit } from '../../../types/domain'
import { areUnitsCompatible,convertUnit } from '../../inventory/domain/inventoryLogic'

const direction=(type:PackagingMovementType)=>type==='Receipt'||type==='Adjustment'?1:-1
export const signedPackagingQuantity=(m:Pick<PackagingInventoryMovement,'type'|'quantity'>)=>m.type==='Adjustment'?m.quantity:Math.abs(m.quantity)*direction(m.type)
export function packagingLotBalance(lot:PackagingInventoryLot,movements:PackagingInventoryMovement[]){return Math.round(movements.filter(m=>m.packagingInventoryLotId===lot.id).reduce((s,m)=>s+convertUnit(signedPackagingQuantity(m),m.unit,lot.unit),0)*10000)/10000}
export function validatePackagingMovement(lot:PackagingInventoryLot,movements:PackagingInventoryMovement[],input:Pick<PackagingInventoryMovement,'type'|'quantity'|'unit'>){if(!Number.isFinite(input.quantity)||input.quantity===0)return'Quantity must be a non-zero number.';if(!areUnitsCompatible(input.unit,lot.unit))return`Movement unit must be compatible with ${lot.unit}.`;if(input.type!=='Adjustment'&&input.quantity<0)return'Use a positive quantity.';const change=convertUnit(signedPackagingQuantity(input),input.unit,lot.unit);if(packagingLotBalance(lot,movements)+change<0)return'Movement exceeds available packaging stock.';return null}
export function generatePackagingLotNumber(existing:string[],date=new Date()){const stamp=`${String(date.getFullYear()).slice(-2)}${String(date.getMonth()+1).padStart(2,'0')}${String(date.getDate()).padStart(2,'0')}`;const prefix=`KF-PKG-${stamp}-`;const next=Math.max(0,...existing.filter(n=>n.startsWith(prefix)).map(n=>Number(n.slice(prefix.length))||0))+1;return`${prefix}${String(next).padStart(3,'0')}`}
export function packagingComponentBalance(component:PackagingComponent,lots:PackagingInventoryLot[],movements:PackagingInventoryMovement[]){return lots.filter(l=>l.packagingComponentId===component.id&&!['Disposed','Archived'].includes(l.status)).reduce((s,l)=>s+convertUnit(packagingLotBalance(l,movements),l.unit,component.defaultUnit),0)}
export function packagingStockState(component:PackagingComponent,lots:PackagingInventoryLot[],movements:PackagingInventoryMovement[]){const linked=lots.filter(l=>l.packagingComponentId===component.id);if(!linked.length)return'No Inventory Data';const balance=packagingComponentBalance(component,lots,movements);if(balance<=0)return'Out of Stock';if(component.reorderThreshold!=null&&balance<=component.reorderThreshold)return'Low';return'In Stock'}
export function packagingRequirements(lines:PackagingSpecificationLine[],units:number){return lines.map(line=>({...line,requiredQuantity:Math.round(line.quantityPerUnit*units*10000)/10000}))}
export function packagingShortage(required:number,available:number){return Math.max(0,Math.round((required-available)*10000)/10000)}
export const packagingTransitions:Record<PackagingSpecificationStatus,PackagingSpecificationStatus[]>={Draft:['Candidate'],Candidate:['Approved','Retired'],Approved:['Retired'],Retired:[]}
export function duplicatePackagingVersion(source:PackagingSpecificationVersion,lines:PackagingSpecificationLine[],versions:PackagingSpecificationVersion[],idFactory:()=>string=()=>crypto.randomUUID()){const now=new Date().toISOString();const numeric=Math.max(...versions.map(v=>Number(v.version.replace(/^v/,''))||0),0)+.1;const version={...source,id:idFactory(),version:`v${numeric.toFixed(1)}`,status:'Draft' as const,derivedFromVersionId:source.id,createdAt:now,updatedAt:now};return{version,lines:lines.map(line=>({...line,id:idFactory(),packagingSpecificationVersionId:version.id}))}}
export function packagingLotUnitCost(lot:PackagingInventoryLot,targetUnit:InventoryUnit){if(lot.totalAcquisitionCost==null||lot.acquisitionCostCurrency!=='NOK'||lot.openingQuantity<=0||!areUnitsCompatible(lot.unit,targetUnit))return undefined;return lot.totalAcquisitionCost/convertUnit(lot.openingQuantity,lot.unit,targetUnit)}
export function weightedPackagingUnitCost(componentId:string,targetUnit:InventoryUnit,lots:PackagingInventoryLot[],movements:PackagingInventoryMovement[],suppliers:PackagingSupplierProduct[]){const eligible=lots.flatMap(l=>{if(l.packagingComponentId!==componentId||l.status!=='Active'||l.acquisitionCostCurrency!=='NOK'||!areUnitsCompatible(l.unit,targetUnit))return[];const available=packagingLotBalance(l,movements),cost=packagingLotUnitCost(l,targetUnit);return available>0&&cost!=null?[{quantity:convertUnit(available,l.unit,targetUnit),cost}]:[]});const quantity=eligible.reduce((s,x)=>s+x.quantity,0);if(quantity>0)return{unitCost:eligible.reduce((s,x)=>s+x.quantity*x.cost,0)/quantity,source:'Weighted packaging inventory'};const supplier=suppliers.find(s=>s.packagingComponentId===componentId&&s.isPreferred&&s.currency==='NOK'&&s.packageQuantity>0&&areUnitsCompatible(s.packageUnit,targetUnit));return supplier?{unitCost:supplier.price/convertUnit(supplier.packageQuantity,supplier.packageUnit,targetUnit),source:'Preferred packaging supplier'}:undefined}
export function packagingAllocationError(allocation:PackagingAllocation,lot:PackagingInventoryLot,movements:PackagingInventoryMovement[]){if(allocation.packagingInventoryMovementId)return'Allocation is already committed.';if(allocation.quantity<=0)return'Allocation must be greater than zero.';if(!areUnitsCompatible(allocation.unit,lot.unit))return'Allocation unit is incompatible.';if(convertUnit(allocation.quantity,allocation.unit,lot.unit)>packagingLotBalance(lot,movements))return'Allocation exceeds available packaging stock.';return null}
