import { useMemo,useState } from 'react'
import { Box,Plus,Search } from 'lucide-react'
import { Link,useNavigate } from 'react-router-dom'
import { PageHeader } from '../../components/ui/PageHeader'
import { SectionHeader } from '../../components/ui/SectionHeader'
import { StatusPill } from '../../components/ui/StatusPill'
import type{InventoryUnit,PackagingComponentStatus}from'../../types/domain'
import { useFormulaData } from '../formulas/state/FormulaDataContext'
import { packagingComponentBalance,packagingStockState } from './domain/packagingLogic'

const statuses:PackagingComponentStatus[]=['planned','to_source','candidate','specification_required','selected','ordered','received','active','rejected','discontinued']
const value=(form:FormData,name:string)=>String(form.get(name)??'').trim()
const optionalNumber=(form:FormData,name:string)=>value(form,name)===''?undefined:Number(value(form,name))
const label=(text:string)=>text.replaceAll('_',' ')

export function PackagingPage(){
 const d=useFormulaData(),navigate=useNavigate(),[creating,setCreating]=useState(false),[message,setMessage]=useState('')
 const[search,setSearch]=useState(''),[category,setCategory]=useState('All'),[status,setStatus]=useState('All')
 const rows=useMemo(()=>d.packagingComponents.filter(c=>c.name.toLowerCase().includes(search.toLowerCase())&&(category==='All'||c.category===category)&&(status==='All'||c.status===status)),[d.packagingComponents,search,category,status])
 const create=(form:HTMLFormElement)=>{const data=new FormData(form),capacity=optionalNumber(data,'capacity'),capacityUnit=value(data,'capacityUnit') as InventoryUnit|'';if((capacity==null)!=(capacityUnit===''))return setMessage('Record nominal volume and unit together, or leave both unknown.');const component=d.createPackagingComponent({name:value(data,'name'),category:value(data,'category'),description:value(data,'description')||undefined,defaultUnit:'pcs',colour:value(data,'colour')||undefined,material:value(data,'material')||undefined,capacity,capacityUnit:capacityUnit||undefined,notes:undefined,status:value(data,'status') as PackagingComponentStatus,intendedProductUse:value(data,'intendedProductUse')||undefined,neckClosureSpecification:value(data,'neckClosureSpecification')||undefined,closureType:value(data,'closureType')||undefined,specificationNotes:value(data,'specificationNotes')||undefined,sourcingNotes:value(data,'sourcingNotes')||undefined,operationalNotes:value(data,'operationalNotes')||undefined,ownershipState:'not_owned',stockState:'not_recorded'});navigate(`/packaging/components/${component.id}`)}
 const createSpec=()=>{const product=d.products[0],name=window.prompt('Packaging Specification name','Retail Packaging');if(product&&name){const spec=d.createPackagingSpecification(product.id,name,'New packaging direction.');navigate(`/packaging/specifications/${spec.id}`)}}
 return <><PageHeader eyebrow="Planning, sourcing and physical components" title="Packaging" description="Planning records never count as stock. Physical availability comes only from Packaging Inventory lots and movements." action={<div className="action-row"><button className="button ghost" onClick={createSpec}><Plus size={14}/>Create Specification</button><button className="button primary" onClick={()=>setCreating(x=>!x)}><Box size={14}/>Plan Component</button></div>}/>
 {creating&&<form className="panel procurement-detail-form" onSubmit={event=>{event.preventDefault();create(event.currentTarget)}}><h2>Packaging planning record</h2><label>Component name<input name="name" required/></label><label>Component type<input name="category" required placeholder="Bottle, closure, label or outer packaging"/></label><label>Status<select name="status" defaultValue="planned">{statuses.map(item=><option value={item} key={item}>{label(item)}</option>)}</select></label><label>Intended product use<input name="intendedProductUse"/></label><label>Nominal volume<input name="capacity" type="number" min="0.000001" step="any"/></label><label>Volume unit<select name="capacityUnit" defaultValue=""><option value="">Unknown</option><option>ml</option><option>L</option></select></label><label>Material<input name="material"/></label><label>Colour<input name="colour"/></label><label>Neck or closure specification<input name="neckClosureSpecification"/></label><label>Closure type<input name="closureType"/></label><label className="wide">Description<textarea name="description"/></label><label className="wide">Specification notes<textarea name="specificationNotes"/></label><label className="wide">Sourcing notes<textarea name="sourcingNotes"/></label><label className="wide">Operational notes<textarea name="operationalNotes"/></label>{message&&<p className="form-error" role="alert">{message}</p>}<button className="button primary">Save planning record</button></form>}
 <div className="inventory-filters"><label className="search-field"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search packaging components"/></label><select value={category} onChange={e=>setCategory(e.target.value)}><option>All</option>{[...new Set(d.packagingComponents.map(c=>c.category))].map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option>{statuses.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></div>
 <section className="panel"><SectionHeader title="Packaging Component Library" detail={`${rows.length} planning and physical records`}/><div className="packaging-library">{rows.map(c=>{const balance=packagingComponentBalance(c,d.packagingInventoryLots,d.packagingInventoryMovements),stock=packagingStockState(c,d.packagingInventoryLots,d.packagingInventoryMovements),preferred=d.packagingSupplierProducts.find(s=>s.packagingComponentId===c.id&&s.isPreferred);return <Link to={`/packaging/components/${c.id}`} key={c.id}><div><span className="eyebrow">{c.category} · {c.material||'Material not recorded'}</span><h3>{c.name}</h3><p>{c.capacity?`${c.capacity} ${c.capacityUnit} · `:''}{c.colour||'Colour not recorded'}</p></div><strong>{balance} {c.defaultUnit}</strong><span>{preferred?.supplierName??(c.status==='active'?'No preferred supplier':`Planning · ${label(c.status)}`)}</span><StatusPill tone={stock==='In Stock'?'green':stock==='Low'?'amber':'neutral'}>{stock}</StatusPill></Link>})}</div></section>
 <section className="panel packaging-spec-list"><SectionHeader title="Packaging Specifications" detail="Versioned Product packaging intent"/>{d.packagingSpecifications.map(s=>{const versions=d.packagingSpecificationVersions.filter(v=>v.packagingSpecificationId===s.id),approved=versions.find(v=>v.status==='Approved');return <Link to={`/packaging/specifications/${s.id}`} key={s.id}><div><span className="eyebrow">{d.products.find(p=>p.id===s.productId)?.name}</span><h3>{s.name}</h3><p>{s.description}</p></div><strong>{approved?`${approved.version} Approved`:'No Approved version'}</strong><span>{versions.length} versions</span></Link>})}</section></>
}
