import { ArrowLeft,Plus } from 'lucide-react'
import { useState } from 'react'
import { Link,useLocation,useParams } from 'react-router-dom'
import { PageHeader } from '../../components/ui/PageHeader'
import { SectionHeader } from '../../components/ui/SectionHeader'
import { StatusPill } from '../../components/ui/StatusPill'
import type{InventoryUnit,PackagingComponentStatus}from'../../types/domain'
import { useFormulaData } from '../formulas/state/FormulaDataContext'
import { runPreferredSupplierProductAction } from '../ingredients/supplierProductPreference'
import { packagingComponentBalance,packagingLotBalance,packagingStockState } from './domain/packagingLogic'
import {OperationReceiptPanel}from'../../components/ui/OperationReceiptPanel'
import {isOwnerOperationReceipt}from'../../platform/operations/ownerOperationReceipt'
import {useActiveWorkspace}from'../../platform/startup/ActiveWorkspaceContext'

const statuses:PackagingComponentStatus[]=['planned','to_source','candidate','specification_required','selected','ordered','received','active','rejected','discontinued']
const text=(form:FormData,name:string)=>String(form.get(name)??'').trim()
const optionalNumber=(form:FormData,name:string)=>text(form,name)===''?undefined:Number(text(form,name))

export function PackagingComponentDetailPage(){
 const{packagingComponentId}=useParams(),location=useLocation(),workspace=useActiveWorkspace(),d=useFormulaData(),c=d.packagingComponents.find(x=>x.id===packagingComponentId),candidate=(location.state as{operationReceipt?:unknown}|null)?.operationReceipt,[receipt,setReceipt]=useState(()=>isOwnerOperationReceipt(candidate,{entityType:'packaging_component',recordId:packagingComponentId,workspaceId:workspace?.workspaceId})?candidate:undefined),[editing,setEditing]=useState(false),[pending,setPending]=useState(''),[error,setError]=useState('')
 if(!c)return <div className="empty-state"><h1>Packaging Component not found</h1></div>
 const lots=d.packagingInventoryLots.filter(l=>l.packagingComponentId===c.id),suppliers=d.packagingSupplierProducts.filter(s=>s.packagingComponentId===c.id),balance=packagingComponentBalance(c,d.packagingInventoryLots,d.packagingInventoryMovements)
 const save=async(form:HTMLFormElement)=>{const data=new FormData(form),capacity=optionalNumber(data,'capacity'),capacityUnit=text(data,'capacityUnit') as InventoryUnit|'';if((capacity==null)!=(capacityUnit===''))return setError('Record nominal volume and unit together, or leave both unknown.');setError('');setPending('update');try{const result=await d.updatePackagingComponent(c.id,{name:text(data,'name'),category:text(data,'category'),status:text(data,'status') as PackagingComponentStatus,intendedProductUse:text(data,'intendedProductUse')||undefined,capacity,capacityUnit:capacityUnit||undefined,material:text(data,'material')||undefined,colour:text(data,'colour')||undefined,neckClosureSpecification:text(data,'neckClosureSpecification')||undefined,closureType:text(data,'closureType')||undefined,specificationNotes:text(data,'specificationNotes')||undefined,sourcingNotes:text(data,'sourcingNotes')||undefined,operationalNotes:text(data,'operationalNotes')||undefined});if(!isOwnerOperationReceipt(result,{entityType:'packaging_component',recordId:c.id,workspaceId:workspace?.workspaceId}))throw new Error('The confirmed update receipt did not match this Packaging Component.');setReceipt(result);setEditing(false)}catch(cause){setError(cause instanceof Error?cause.message:'Packaging Component persistence could not be confirmed. Review the entered values and retry.')}finally{setPending('')}}
 const receive=()=>{const quantity=Number(window.prompt('Received quantity'));if(quantity>0)d.receivePackagingStock({packagingComponentId:c.id,receivedDate:new Date().toISOString().slice(0,10),openingQuantity:quantity,unit:c.defaultUnit,location:'Packaging / location to verify',notes:''})}
 const mark=async(id:string)=>{if(pending)return;try{await runPreferredSupplierProductAction(id,d.markPackagingSupplierPreferred,setPending,setError)}catch{return}}
 return <><Link className="back-link" to="/packaging"><ArrowLeft size={14}/>Packaging</Link>{receipt&&<OperationReceiptPanel result={{state:'confirmed',receipt}} onDismiss={()=>setReceipt(undefined)}/>}<PageHeader eyebrow={`${c.category} / ${c.status.replaceAll('_',' ')}`} title={c.name} description={c.description||'Packaging planning record. Unknown fields remain not recorded.'} action={<div className="action-row"><button className="button ghost" onClick={()=>setEditing(x=>!x)}>Edit planning record</button><button className="button primary" onClick={receive}><Plus size={14}/>Receive Stock</button></div>}/>
 {editing&&<form className="panel procurement-detail-form" onSubmit={event=>{event.preventDefault();void save(event.currentTarget)}}><h2>Edit packaging planning record</h2><label>Name<input name="name" required defaultValue={c.name}/></label><label>Component type<input name="category" required defaultValue={c.category}/></label><label>Status<select name="status" defaultValue={c.status}>{statuses.map(item=><option value={item} key={item}>{item.replaceAll('_',' ')}</option>)}</select></label><label>Intended product use<input name="intendedProductUse" defaultValue={c.intendedProductUse}/></label><label>Nominal volume<input name="capacity" type="number" min="0.000001" step="any" defaultValue={c.capacity}/></label><label>Volume unit<select name="capacityUnit" defaultValue={c.capacityUnit??''}><option value="">Unknown</option><option>ml</option><option>L</option></select></label><label>Material<input name="material" defaultValue={c.material}/></label><label>Colour<input name="colour" defaultValue={c.colour}/></label><label>Neck or closure specification<input name="neckClosureSpecification" defaultValue={c.neckClosureSpecification}/></label><label>Closure type<input name="closureType" defaultValue={c.closureType}/></label><label className="wide">Specification notes<textarea name="specificationNotes" defaultValue={c.specificationNotes}/></label><label className="wide">Sourcing notes<textarea name="sourcingNotes" defaultValue={c.sourcingNotes}/></label><label className="wide">Operational notes<textarea name="operationalNotes" defaultValue={c.operationalNotes}/></label>{error&&<p role="alert" className="form-error">{error}</p>}<button className="button primary" disabled={pending==='update'}>{pending==='update'?'Confirming persistence…':'Save changes'}</button></form>}
 <div className="ingredient-detail-grid"><section className="panel identity-card"><SectionHeader title="Planning identity"/><dl><div><dt>Status</dt><dd><StatusPill tone={c.status==='active'?'green':'neutral'}>{c.status.replaceAll('_',' ')}</StatusPill></dd></div><div><dt>Ownership</dt><dd>{c.ownershipState.replaceAll('_',' ')}</dd></div><div><dt>Material / colour</dt><dd>{c.material||'Unknown'} · {c.colour||'Unknown'}</dd></div><div><dt>Capacity</dt><dd>{c.capacity?`${c.capacity} ${c.capacityUnit}`:'Not recorded'}</dd></div><div><dt>Closure</dt><dd>{c.neckClosureSpecification||c.closureType||'Not recorded'}</dd></div><div><dt>Notes</dt><dd>{c.operationalNotes||'No operational notes'}</dd></div></dl></section><section className="panel inventory-summary"><strong>{balance} <small>{c.defaultUnit}</small></strong><StatusPill tone={balance>0?'green':'neutral'}>{packagingStockState(c,d.packagingInventoryLots,d.packagingInventoryMovements)}</StatusPill><p>{lots.filter(l=>l.status==='Active').length} active lots</p><small>A planning record alone never counts as physical stock.</small></section></div>
 <section className="panel"><SectionHeader title="Active lots" detail="Balances derive from immutable Packaging Movements"/>{lots.map(l=><article className="packaging-detail-row" key={l.id}><div><strong>{l.internalLotNumber}</strong><small>{l.receivedDate} · {l.location}</small></div><b>{packagingLotBalance(l,d.packagingInventoryMovements)} {l.unit}</b></article>)}{!lots.length&&<p>No physical packaging stock recorded.</p>}</section>
 <section className="panel"><SectionHeader title="Supplier Products"/>{suppliers.map(s=><article className="packaging-detail-row" key={s.id}><div><strong>{s.supplierName} — {s.productName}</strong><small>{s.supplierSku||'No SKU'}</small></div><b>{s.packageQuantity==null?'Package unknown':`${s.packageQuantity} ${s.packageUnit}`}</b><span>{s.price==null?'Price unknown':`${s.price} ${s.currency}`}</span>{s.isPreferred?<StatusPill tone="green">Preferred</StatusPill>:<button className="text-button" disabled={Boolean(pending)} onClick={()=>void mark(s.id)}>{pending===s.id?'Saving…':'Mark preferred'}</button>}</article>)}{!suppliers.length&&<p>No supplier products recorded.</p>}</section></>
}
