import { useState } from 'react'
import { ArrowLeft, Check, Copy, FlaskConical, LockKeyhole, Save, ShieldCheck } from 'lucide-react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { PageHeader } from '../../components/ui/PageHeader'
import { StatusPill } from '../../components/ui/StatusPill'
import { SectionHeader } from '../../components/ui/SectionHeader'
import type { FormulaVersionStatus } from '../../types/domain'
import { formatDate } from '../../utils/format'
import { BatchScaler } from './components/BatchScaler'
import { FormulaBuilder } from './components/FormulaBuilder'
import { formulaTotalsExactly100, multiPhaseIssues } from './domain/multiPhaseLogic'
import { useFormulaData } from './state/FormulaDataContext'
import { productTemplates } from '../product-studio/domain/formulationEngine'

export function FormulaDetailPage() {
  const { formulaId } = useParams(); const [params, setParams] = useSearchParams()
  const { formulas, formulaVersions, formulaLines, products, ingredients, productStudioConcepts, labBatches, labObservations, productionRuns, saveVersion, transitionVersion, duplicateAsDraft } = useFormulaData()
  const directVersion=formulaVersions.find(item=>item.id===formulaId);const resolvedFormulaId=directVersion?.formulaId??formulaId
  const formula = formulas.find((item) => item.id === resolvedFormulaId); const versions = formulaVersions.filter((item) => item.formulaId === resolvedFormulaId).sort((a,b) => b.createdAt.localeCompare(a.createdAt))
  const selected = directVersion??versions.find((item) => item.id === params.get('version')) ?? versions[0]; const lines = formulaLines.filter((line) => line.formulaVersionId === selected?.id)
  const versionBatches = labBatches.filter((batch) => batch.formulaVersionId === selected?.id)
  const versionRuns=productionRuns.filter(run=>run.formulaVersionId===selected?.id)
  const [description, setDescription] = useState(selected?.description ?? ''); const [characteristics, setCharacteristics] = useState(selected?.targetCharacteristics ?? '')
  if (!formula || !selected) return <div className="empty-state"><h1>Formula not found</h1><Link to="/formulas">Return to formulas</Link></div>
  const product = products.find((item) => item.id === formula.productId); const valid = formulaTotalsExactly100(lines)
  const origin=productStudioConcepts.find(concept=>concept.generatedFormulaId===formula.id),originTemplate=origin&&productTemplates[origin.productType],ingredientReferencesValid=lines.length>0&&lines.every(line=>ingredients.some(ingredient=>ingredient.id===line.ingredientId))
  const observed=versionBatches.some(batch=>labObservations.some(observation=>observation.labBatchId===batch.id&&observation.observedAt))
  const phaseIssues=selected.phaseDefinitions?.length?multiPhaseIssues(selected.phaseDefinitions,lines,selected.manufacturingProcess):[]
  const selectVersion = (id: string) => { const next = versions.find((v) => v.id === id)!; setParams({ version: id }); setDescription(next.description); setCharacteristics(next.targetCharacteristics) }
  const duplicate = () => { const created = duplicateAsDraft(selected.id); if (created) { setParams({ version: created.id }); setDescription(created.description); setCharacteristics(created.targetCharacteristics) } }
  const transition = (status: FormulaVersionStatus) => { if (status === 'Candidate' && !valid) return; transitionVersion(selected.id, status) }
  return <>
    <Link className="back-link" to="/formulas"><ArrowLeft size={14} />Formula library</Link>
    <PageHeader eyebrow={`${product?.name} / Development Workspace`} title={formula.name} description={selected.status==='Draft'?'Development Draft':formula.description} action={<Link className="button ghost" to={`/knowledge?tab=scent-memory&formulaVersionId=${selected.id}`}>Record Scent Memory</Link>} />
    {origin&&originTemplate&&<section className="formula-origin"><div><span className="eyebrow">Created from {originTemplate.displayName} Product Studio</span><strong>{origin.name}</strong><p>Context from the concept remains separate from the authoritative Formula composition.</p></div><Link className="button ghost" to={`${originTemplate.route}?concept=${origin.id}`}>Back to concept</Link></section>}
    <nav className="development-journey" aria-label="Development journey">{['Concept','Formula','Lab','Testing','Candidate'].map(step=><span key={step} className={step==='Formula'?'current':step==='Concept'&&origin?'complete':step==='Lab'&&versionBatches.length?'complete':step==='Testing'&&observed?'complete':step==='Candidate'&&selected.status!=='Draft'?'complete':''}>{step}</span>)}</nav>
    <div className="formula-workspace"><aside className="version-rail panel"><div><span className="eyebrow">Version history</span><strong>{versions.length} recorded</strong></div>{versions.map((version) => <button className={version.id === selected.id ? 'active' : ''} key={version.id} onClick={() => selectVersion(version.id)}><span>{version.version}</span><StatusPill tone={version.status === 'Draft' ? 'amber' : version.status === 'Approved' ? 'green' : version.status === 'Retired' ? 'neutral' : 'blue'}>{version.status}</StatusPill><small>{formatDate(version.updatedAt.slice(0,10))}</small></button>)}</aside>
      <div className="formula-main"><section className="version-banner"><div><span className="eyebrow">Formula composition</span><h2>Formula {selected.version} · {selected.status}</h2></div><StatusPill tone={selected.status === 'Draft' ? 'amber' : selected.status === 'Approved' ? 'green' : selected.status === 'Retired' ? 'neutral' : 'blue'}>{selected.status === 'Draft' ? <Save size={12} /> : <LockKeyhole size={12} />}{selected.status}</StatusPill><p>{lines.length} structured {lines.length===1?'ingredient':'ingredients'} · {selected.status === 'Draft' ? 'Editable working version' : 'Frozen for traceability'}</p><div className="version-actions">{selected.status === 'Draft' ? <><button className="button ghost" onClick={() => saveVersion(selected.id, { description, targetCharacteristics: characteristics })}><Save size={15} />Save changes</button><button className="button primary" disabled={!valid} title={!valid ? 'Formula must total exactly 100%' : ''} onClick={() => transition('Candidate')}><ShieldCheck size={15} />Promote to Candidate</button></> : <><button className="button ghost" onClick={duplicate}><Copy size={15} />Duplicate as New Draft</button>{selected.status === 'Candidate' && <button className="button primary" onClick={() => transition('Approved')}><Check size={15} />Approve</button>}{selected.status !== 'Retired' && <button className="button ghost" onClick={() => transition('Retired')}>Retire</button>}</>}</div></section>
        <section className="panel formula-readiness"><div><span className="eyebrow">Development readiness</span><h2>Next practical step</h2><p>Candidate records development maturity only. It does not mean safety-approved, stable, compliant, or launch-ready.</p></div><ul><li className={valid?'ready':'review'}>Formula total {valid?'valid':'needs attention'}</li><li className={ingredientReferencesValid?'ready':'review'}>Ingredient references {ingredientReferencesValid?'valid':'need attention'}</li><li className="ready">Formula saved</li><li className={versionBatches.length?'ready':'pending'}>{versionBatches.length?'Lab Batch created':'Lab Batch not yet created'}</li><li className={observed?'ready':'pending'}>{observed?'Physical testing recorded':'Physical testing not yet recorded'}</li></ul><Link className="button primary" to={`/lab/start/${formula.id}`}><FlaskConical size={15}/>Prepare Lab Batch</Link></section>
        {origin?.notes&&<section className="panel concept-context"><SectionHeader title="Context notes from Product Studio" detail="Not used as Formula ingredients or percentages"/><p>{origin.notes}</p></section>}
        <section className="formula-notes panel"><label>Version description<textarea disabled={selected.status !== 'Draft'} value={description} onChange={(e) => setDescription(e.target.value)} /></label><label>Target characteristics<textarea disabled={selected.status !== 'Draft'} value={characteristics} onChange={(e) => setCharacteristics(e.target.value)} /></label></section>
        {!!selected.phaseDefinitions?.length&&<section className="panel phase-definition-grid"><SectionHeader title="Formula phases" detail="Ordered process intent for this exact version"/>{phaseIssues.length>0&&<div className="form-error" role="alert">{phaseIssues.join(' ')}</div>}{[...selected.phaseDefinitions].sort((a,b)=>a.order-b.order).map(phase=><article key={phase.code}><strong>Phase {phase.code} — {phase.name}</strong><span>{phase.minimumTemperature!=null?`${phase.minimumTemperature}–`:phase.maximumTemperature!=null?'≤ ':''}{phase.maximumTemperature??phase.targetTemperature??'Not established'}{(phase.maximumTemperature??phase.targetTemperature)!=null?' °C':''}</span><p>{phase.instructions||phase.notes}</p></article>)}</section>}
        {!!selected.manufacturingProcess?.length&&<section className="panel procedure-panel"><SectionHeader title="Draft manufacturing process" detail="Execution is recorded in Lab, not on the Formula"/><ol>{[...selected.manufacturingProcess].sort((a,b)=>a.order-b.order).map(step=><li key={step.order}><strong>{step.title}</strong> — {step.instruction}{step.critical?' Critical.':''}</li>)}</ol></section>}
        <FormulaBuilder version={selected} lines={lines} /><BatchScaler lines={lines} />
        <section className="panel linked-testing"><SectionHeader title="Lab history" detail="Batches created from this exact version" />{versionBatches.map((batch)=><Link to={`/lab/${batch.id}`} key={batch.id}><strong>{batch.batchNumber}</strong><span>{batch.status} · {batch.purpose}</span></Link>)}{!versionBatches.length&&<p className="empty-copy">No Lab Batches reference this version.</p>}</section>
        <section className="panel linked-testing"><SectionHeader title="Production history" detail="Controlled runs sourced from this exact immutable version" action={<Link className="text-button" to="/costing">Cost planning</Link>}/>{versionRuns.map(run=><Link to={`/production/${run.id}`} key={run.id}><strong>{run.productionRunNumber}</strong><span>{run.status} · {run.purpose}</span></Link>)}{!versionRuns.length&&<p className="empty-copy">No Production Runs reference this version.</p>}</section>
        <p className="development-disclaimer">Development mock formulation data only. No safety, performance, regulatory, or commercial approval is implied.</p>
      </div>
    </div>
  </>
}
