import { createContext, useContext, useEffect, useMemo, useState } from 'react'
import type { CostLine, Formula, FormulaLine, FormulaState, FormulaVersion, FormulaVersionStatus, Ingredient, InventoryLot, InventoryMovement, InventoryUnit, LabBatch, LabBatchAllocation, LabBatchLine, LabBatchStatus, LabObservation, ProductionRun, ProductionRunAllocation, ProductionRunLine, ProductionRunStatus, SupplierProduct, TestResponse, TestSession, TestTemplate, Tester } from '../../../types/domain'
import { formulaRepository } from '../data/formulaRepository'
import { canTransition, duplicateVersion } from '../domain/formulaLogic'
import { generateLotNumber, validateMovement } from '../../inventory/domain/inventoryLogic'
import { canTransitionBatch, createBatchLines, generateBatchNumber, quantityVariance, validateAllocation } from '../../lab/domain/labLogic'
import { allocationCostSnapshot, canTransitionProduction, createProductionLines, generateProductionRunNumber, productionVariance, validateProductionAllocation } from '../../production/domain/productionLogic'

interface FormulaDataValue extends FormulaState {
  updateLine(versionId: string, lineId: string, patch: Partial<FormulaLine>): void
  addLine(versionId: string, ingredientId: string): void
  removeLine(versionId: string, lineId: string): void
  moveLine(versionId: string, lineId: string, direction: -1 | 1): void
  saveVersion(versionId: string, patch: Partial<FormulaVersion>): void
  transitionVersion(versionId: string, status: FormulaVersionStatus): void
  duplicateAsDraft(versionId: string): FormulaVersion | undefined
  createFormula(productId: string, name: string, description: string): Formula
  createIngredient(input: Omit<Ingredient, 'id' | 'createdAt' | 'updatedAt'>): Ingredient
  updateIngredient(id: string, patch: Partial<Ingredient>): void
  archiveIngredient(id: string): void
  saveSupplierProduct(input: Omit<SupplierProduct, 'id' | 'createdAt' | 'updatedAt'> & { id?: string }): SupplierProduct
  markSupplierPreferred(id: string): void
  receiveStock(input: Omit<InventoryLot, 'id' | 'internalLotNumber' | 'createdAt' | 'updatedAt' | 'status'>): InventoryLot
  addMovement(input: Omit<InventoryMovement, 'id' | 'createdAt'>): InventoryMovement
  createLabBatch(input:{productId:string;formulaId:string;formulaVersionId:string;plannedBatchSize:number;plannedBatchUnit:InventoryUnit;purpose:string;notes:string}):LabBatch
  updateBatchLine(id:string,patch:Partial<LabBatchLine>):void
  addAllocation(lineId:string):void
  updateAllocation(id:string,patch:Partial<LabBatchAllocation>):void
  commitBatchConsumption(batchId:string):string[]
  transitionBatch(id:string,status:LabBatchStatus):void
  updateLabBatch(id:string,patch:Partial<LabBatch>):void
  addProcessStep(batchId:string,instruction:string):void
  updateProcessStep(id:string,patch:Partial<FormulaState['processSteps'][number]>):void
  addObservation(input:Omit<LabObservation,'id'|'createdAt'>):void
  createTester(displayName:string,notes:string):Tester
  createTestTemplate(name:string,questions:string[]):TestTemplate
  createTestSession(input:Omit<TestSession,'id'|'createdAt'>):TestSession
  addTestResponse(input:Omit<TestResponse,'id'|'submittedAt'>):TestResponse
  updateInventoryLot(id:string,patch:Partial<InventoryLot>):void
  createProductionRun(input:{productId:string;formulaId:string;formulaVersionId:string;plannedBatchSize:number;plannedBatchUnit:InventoryUnit;plannedUnits?:number;purpose:string;notes:string}):ProductionRun
  updateProductionRun(id:string,patch:Partial<ProductionRun>):void
  transitionProductionRun(id:string,status:ProductionRunStatus):void
  updateProductionLine(id:string,patch:Partial<ProductionRunLine>):void
  addProductionAllocation(lineId:string):void
  updateProductionAllocation(id:string,patch:Partial<ProductionRunAllocation>):void
  commitProductionConsumption(runId:string):string[]
  addProductionStep(runId:string,instruction:string):void
  updateProductionStep(id:string,patch:Partial<FormulaState['productionProcessSteps'][number]>):void
  addCostLine(input:Omit<CostLine,'id'|'createdAt'|'updatedAt'>):void
}
const FormulaDataContext = createContext<FormulaDataValue | null>(null)
const uid = () => crypto.randomUUID()

export function FormulaDataProvider({ children }: { children: React.ReactNode }) {
  const [state, setState] = useState<FormulaState>(() => formulaRepository.load())
  useEffect(() => formulaRepository.save(state), [state])

  const value = useMemo<FormulaDataValue>(() => ({ ...state,
    updateLine(versionId, lineId, patch) { setState((current) => ({ ...current, formulaLines: current.formulaLines.map((line) => line.formulaVersionId === versionId && line.id === lineId ? { ...line, ...patch } : line), formulaVersions: current.formulaVersions.map((version) => version.id === versionId ? { ...version, updatedAt: new Date().toISOString() } : version) })) },
    addLine(versionId, ingredientId) { setState((current) => ({ ...current, formulaLines: [...current.formulaLines, { id: uid(), formulaVersionId: versionId, ingredientId, percentage: 0, phase: 'Phase A', sortOrder: current.formulaLines.filter((line) => line.formulaVersionId === versionId).length + 1, notes: '' }] })) },
    removeLine(versionId, lineId) { setState((current) => ({ ...current, formulaLines: current.formulaLines.filter((line) => !(line.formulaVersionId === versionId && line.id === lineId)) })) },
    moveLine(versionId, lineId, direction) { setState((current) => { const lines = current.formulaLines.filter((line) => line.formulaVersionId === versionId).sort((a,b) => a.sortOrder-b.sortOrder); const index = lines.findIndex((line) => line.id === lineId); const target = index + direction; if (target < 0 || target >= lines.length) return current; [lines[index], lines[target]] = [lines[target], lines[index]]; const orders = new Map(lines.map((line, i) => [line.id, i + 1])); return { ...current, formulaLines: current.formulaLines.map((line) => line.formulaVersionId === versionId ? { ...line, sortOrder: orders.get(line.id)! } : line) } }) },
    saveVersion(versionId, patch) { setState((current) => ({ ...current, formulaVersions: current.formulaVersions.map((version) => version.id === versionId && version.status === 'Draft' ? { ...version, ...patch, updatedAt: new Date().toISOString() } : version) })) },
    transitionVersion(versionId, status) { setState((current) => { const source = current.formulaVersions.find((item) => item.id === versionId); if (!source || !canTransition(source.status, status)) return current; const version = { ...source, status, approvedAt: status === 'Approved' ? new Date().toISOString() : source.approvedAt, updatedAt: new Date().toISOString() }; return { ...current, formulaVersions: current.formulaVersions.map((item) => item.id === versionId ? version : item), products: current.products.map((product) => product.id !== current.formulas.find((formula) => formula.id === source.formulaId)?.productId ? product : { ...product, currentDevelopmentFormulaVersionId: status === 'Candidate' ? versionId : product.currentDevelopmentFormulaVersionId, currentApprovedFormulaVersionId: status === 'Approved' ? versionId : product.currentApprovedFormulaVersionId }) } }) },
    duplicateAsDraft(versionId) { const source = state.formulaVersions.find((item) => item.id === versionId); if (!source) return; const result = duplicateVersion(source, state.formulaLines.filter((line) => line.formulaVersionId === versionId), state.formulaVersions, uid); setState((current) => ({ ...current, formulaVersions: [...current.formulaVersions, result.version], formulaLines: [...current.formulaLines, ...result.lines] })); return result.version },
    createFormula(productId, name, description) { const now = new Date().toISOString(); const formula: Formula = { id: uid(), productId, name, description, createdAt: now, updatedAt: now }; const version: FormulaVersion = { id: uid(), formulaId: formula.id, version: 'v0.1', status: 'Draft', description: 'Initial formula version.', targetCharacteristics: '', createdAt: now, updatedAt: now }; setState((current) => ({ ...current, formulas: [...current.formulas, formula], formulaVersions: [...current.formulaVersions, version] })); return formula },
    createIngredient(input) { const now = new Date().toISOString(); const ingredient = { ...input, id: uid(), createdAt: now, updatedAt: now }; setState((current) => ({ ...current, ingredients: [...current.ingredients, ingredient] })); return ingredient },
    updateIngredient(id, patch) { setState((current) => ({ ...current, ingredients: current.ingredients.map((item) => item.id === id ? { ...item, ...patch, id, updatedAt: new Date().toISOString() } : item) })) },
    archiveIngredient(id) { setState((current) => ({ ...current, ingredients: current.ingredients.map((item) => item.id === id ? { ...item, status: 'Archived', updatedAt: new Date().toISOString() } : item) })) },
    saveSupplierProduct(input) { const now = new Date().toISOString(); const product: SupplierProduct = { ...input, id: input.id ?? uid(), createdAt: now, updatedAt: now }; setState((current) => ({ ...current, supplierProducts: input.id ? current.supplierProducts.map((item) => item.id === input.id ? { ...product, createdAt: item.createdAt } : item) : [...current.supplierProducts, product] })); return product },
    markSupplierPreferred(id) { setState((current) => { const selected = current.supplierProducts.find((item) => item.id === id); if (!selected) return current; return { ...current, supplierProducts: current.supplierProducts.map((item) => item.ingredientId === selected.ingredientId ? { ...item, isPreferred: item.id === id, updatedAt: new Date().toISOString() } : item) } }) },
    receiveStock(input) { const now = new Date().toISOString(); if (!Number.isFinite(input.openingQuantity) || input.openingQuantity <= 0) throw new Error('Opening quantity must be greater than zero.'); const lot: InventoryLot = { ...input, id: uid(), internalLotNumber: generateLotNumber(state.inventoryLots.map((item) => item.internalLotNumber), new Date(`${input.receivedDate}T12:00:00`)), status: 'Active', createdAt: now, updatedAt: now }; const receipt: InventoryMovement = { id: uid(), inventoryLotId: lot.id, type: 'Receipt', quantity: lot.openingQuantity, unit: lot.unit, reason: 'Stock received', notes: 'Initial receipt recorded with lot creation.', occurredAt: `${input.receivedDate}T12:00:00.000Z`, createdAt: now }; setState((current) => ({ ...current, inventoryLots: [...current.inventoryLots, lot], inventoryMovements: [...current.inventoryMovements, receipt] })); return lot },
    addMovement(input) { const lot = state.inventoryLots.find((item) => item.id === input.inventoryLotId); if (!lot) throw new Error('Inventory lot not found.'); const error = validateMovement(lot, state.inventoryMovements, input); if (error) throw new Error(error); const movement = { ...input, id: uid(), createdAt: new Date().toISOString() }; setState((current) => ({ ...current, inventoryMovements: [...current.inventoryMovements, movement] })); return movement },
    createLabBatch(input){const now=new Date().toISOString();const product=state.products.find((p)=>p.id===input.productId);const version=state.formulaVersions.find((v)=>v.id===input.formulaVersionId);if(!product||!version||version.formulaId!==input.formulaId)throw new Error('Select a valid product, formula, and version.');if(version.status==='Retired')throw new Error('Retired versions require a deliberate historical workflow.');if(!Number.isFinite(input.plannedBatchSize)||input.plannedBatchSize<=0)throw new Error('Planned size must be greater than zero.');const id=uid();const batch:LabBatch={...input,id,batchNumber:generateBatchNumber(product.name,state.labBatches.map((b)=>b.batchNumber),new Date()),status:'Planned',createdAt:now,updatedAt:now,summary:'',targetCharacteristics:version.targetCharacteristics};const lines=createBatchLines(id,state.formulaLines.filter((l)=>l.formulaVersionId===version.id),state.ingredients,input.plannedBatchSize,input.plannedBatchUnit,uid);const steps=version.processInstructions?[{id:uid(),labBatchId:id,stepNumber:1,instruction:version.processInstructions,status:'Pending' as const,notes:''}]:[];setState((current)=>({...current,labBatches:[...current.labBatches,batch],labBatchLines:[...current.labBatchLines,...lines],processSteps:[...current.processSteps,...steps]}));return batch},
    updateBatchLine(id,patch){setState((current)=>{const line=current.labBatchLines.find((l)=>l.id===id);const batch=current.labBatches.find((b)=>b.id===line?.labBatchId);if(!line||!batch||batch.status==='Completed'||batch.status==='Archived')return current;const next={...line,...patch};if(patch.actualQuantity!==undefined)next.variance=quantityVariance(patch.actualQuantity,line.plannedQuantity);return{...current,labBatchLines:current.labBatchLines.map((l)=>l.id===id?next:l)}})},
    addAllocation(lineId){const line=state.labBatchLines.find((l)=>l.id===lineId);if(!line)return;setState((current)=>({...current,labBatchAllocations:[...current.labBatchAllocations,{id:uid(),labBatchLineId:lineId,quantity:0,unit:line.unit}]}))},
    updateAllocation(id,patch){setState((current)=>({...current,labBatchAllocations:current.labBatchAllocations.map((a)=>a.id===id&&!a.inventoryMovementId?{...a,...patch}:a)}))},
    commitBatchConsumption(batchId){const lines=state.labBatchLines.filter((l)=>l.labBatchId===batchId);const allocations=state.labBatchAllocations.filter((a)=>lines.some((l)=>l.id===a.labBatchLineId)&&!a.inventoryMovementId);const errors:string[]=[];if(!allocations.length)return['No uncommitted lot allocations remain.'];for(const line of lines.filter((item)=>item.status==='Weighed')){const allocated=allocations.filter((a)=>a.labBatchLineId===line.id).reduce((sum,a)=>sum+a.quantity,0);if(line.actualQuantity!=null&&Math.abs(allocated-line.actualQuantity)>.0001)errors.push(`${line.ingredientNameSnapshot}: allocations must total the actual quantity (${line.actualQuantity} ${line.unit}).`)}if(errors.length)return errors;const newMovements:InventoryMovement[]=[];const movementByAllocation=new Map<string,string>();for(const allocation of allocations){const line=lines.find((l)=>l.id===allocation.labBatchLineId)!;const lot=state.inventoryLots.find((l)=>l.id===allocation.inventoryLotId);if(!lot){errors.push(`${line.ingredientNameSnapshot}: select an inventory lot.`);continue}const error=validateAllocation(line,allocation,lot,[...state.inventoryMovements,...newMovements]);if(error){errors.push(`${line.ingredientNameSnapshot}: ${error}`);continue}const movementId=uid();newMovements.push({id:movementId,inventoryLotId:lot.id,type:'Consumption',quantity:allocation.quantity,unit:allocation.unit,reason:`Lab batch ${state.labBatches.find((b)=>b.id===batchId)?.batchNumber}`,referenceType:'LabBatch',referenceId:batchId,notes:line.notes,occurredAt:new Date().toISOString(),createdAt:new Date().toISOString()});movementByAllocation.set(allocation.id,movementId)}if(errors.length)return errors;setState((current)=>({...current,inventoryMovements:[...current.inventoryMovements,...newMovements],labBatchAllocations:current.labBatchAllocations.map((a)=>movementByAllocation.has(a.id)?{...a,inventoryMovementId:movementByAllocation.get(a.id)}:a)}));return[]},
    transitionBatch(id,status){setState((current)=>{const batch=current.labBatches.find((b)=>b.id===id);if(!batch||!canTransitionBatch(batch.status,status))return current;const now=new Date().toISOString();return{...current,labBatches:current.labBatches.map((b)=>b.id===id?{...b,status,startedAt:status==='In Progress'?now:b.startedAt,completedAt:status==='Completed'?now:b.completedAt,updatedAt:now}:b)}})},
    updateLabBatch(id,patch){setState((current)=>({...current,labBatches:current.labBatches.map((b)=>b.id===id&&!['Completed','Archived'].includes(b.status)?{...b,...patch,id,updatedAt:new Date().toISOString()}:b)}))},
    addProcessStep(batchId,instruction){setState((current)=>({...current,processSteps:[...current.processSteps,{id:uid(),labBatchId:batchId,stepNumber:current.processSteps.filter((s)=>s.labBatchId===batchId).length+1,instruction,status:'Pending',notes:''}]}))},
    updateProcessStep(id,patch){setState((current)=>({...current,processSteps:current.processSteps.map((s)=>s.id===id?{...s,...patch,completedAt:patch.status==='Completed'?new Date().toISOString():s.completedAt}:s)}))},
    addObservation(input){setState((current)=>({...current,labObservations:[...current.labObservations,{...input,id:uid(),createdAt:new Date().toISOString()}]}))},
    createTester(displayName,notes){const now=new Date().toISOString();const tester:Tester={id:uid(),displayName,notes,status:'Active',createdAt:now,updatedAt:now};setState((c)=>({...c,testers:[...c.testers,tester]}));return tester},
    createTestTemplate(name,questions){const now=new Date().toISOString();const template:TestTemplate={id:uid(),name,description:'Internal development evaluation.',questions:questions.map((prompt,index)=>({id:uid(),prompt,type:'Numeric Rating',sortOrder:index+1})),createdAt:now,updatedAt:now};setState((c)=>({...c,testTemplates:[...c.testTemplates,template]}));return template},
    createTestSession(input){const session:TestSession={...input,id:uid(),createdAt:new Date().toISOString()};setState((c)=>({...c,testSessions:[...c.testSessions,session]}));return session},
    addTestResponse(input){const response:TestResponse={...input,id:uid(),submittedAt:new Date().toISOString()};setState((c)=>({...c,testResponses:[...c.testResponses,response]}));return response},
    updateInventoryLot(id,patch){setState(c=>({...c,inventoryLots:c.inventoryLots.map(l=>l.id===id?{...l,...patch,id,updatedAt:new Date().toISOString()}:l)}))},
    createProductionRun(input){const now=new Date().toISOString();const product=state.products.find(p=>p.id===input.productId);const version=state.formulaVersions.find(v=>v.id===input.formulaVersionId);if(!product||!version||version.formulaId!==input.formulaId)throw new Error('Select a valid product, formula, and version.');if(version.status!=='Approved')throw new Error('Only Approved Formula Versions may be used for Production Runs.');if(!Number.isFinite(input.plannedBatchSize)||input.plannedBatchSize<=0)throw new Error('Planned size must be greater than zero.');const id=uid();const run:ProductionRun={...input,id,productionRunNumber:generateProductionRunNumber(product.name,state.productionRuns.map(r=>r.productionRunNumber)),status:'Planned',createdAt:now,updatedAt:now,summary:''};const lines=createProductionLines(id,state.formulaLines.filter(l=>l.formulaVersionId===version.id),state.ingredients,input.plannedBatchSize,input.plannedBatchUnit,uid);const steps=version.processInstructions?[{id:uid(),productionRunId:id,stepNumber:1,instruction:version.processInstructions,status:'Pending' as const,notes:''}]:[];setState(c=>({...c,productionRuns:[...c.productionRuns,run],productionRunLines:[...c.productionRunLines,...lines],productionProcessSteps:[...c.productionProcessSteps,...steps]}));return run},
    updateProductionRun(id,patch){setState(c=>({...c,productionRuns:c.productionRuns.map(r=>r.id===id&&!['Completed','Archived'].includes(r.status)?{...r,...patch,id,formulaVersionId:r.status==='Planned'?(patch.formulaVersionId??r.formulaVersionId):r.formulaVersionId,updatedAt:new Date().toISOString()}:r)}))},
    transitionProductionRun(id,status){setState(c=>{const run=c.productionRuns.find(r=>r.id===id);if(!run||!canTransitionProduction(run.status,status))return c;const now=new Date().toISOString();return{...c,productionRuns:c.productionRuns.map(r=>r.id===id?{...r,status,startedAt:status==='In Progress'?now:r.startedAt,completedAt:status==='Completed'?now:r.completedAt,updatedAt:now}:r)}})},
    updateProductionLine(id,patch){setState(c=>{const line=c.productionRunLines.find(l=>l.id===id);const run=c.productionRuns.find(r=>r.id===line?.productionRunId);if(!line||!run||!['Planned','In Progress'].includes(run.status))return c;const next={...line,...patch};if(patch.actualQuantity!==undefined)next.variance=productionVariance(patch.actualQuantity,line.plannedQuantity);return{...c,productionRunLines:c.productionRunLines.map(l=>l.id===id?next:l)}})},
    addProductionAllocation(lineId){const line=state.productionRunLines.find(l=>l.id===lineId);if(line)setState(c=>({...c,productionRunAllocations:[...c.productionRunAllocations,{id:uid(),productionRunLineId:lineId,quantity:0,unit:line.unit}]}))},
    updateProductionAllocation(id,patch){setState(c=>({...c,productionRunAllocations:c.productionRunAllocations.map(a=>a.id===id&&!a.inventoryMovementId?{...a,...patch}:a)}))},
    commitProductionConsumption(runId){const lines=state.productionRunLines.filter(l=>l.productionRunId===runId);const allocations=state.productionRunAllocations.filter(a=>lines.some(l=>l.id===a.productionRunLineId)&&!a.inventoryMovementId);const errors:string[]=[];if(!allocations.length)return['No uncommitted lot allocations remain.'];for(const line of lines.filter(l=>l.status==='Weighed')){const allocated=allocations.filter(a=>a.productionRunLineId===line.id).reduce((s,a)=>s+a.quantity,0);if(line.actualQuantity!=null&&Math.abs(allocated-line.actualQuantity)>.0001)errors.push(`${line.ingredientNameSnapshot}: allocations must total ${line.actualQuantity} ${line.unit}.`)}if(errors.length)return errors;const movements:InventoryMovement[]=[];const committed=new Map<string,{movementId:string;unitCostSnapshot?:number;costCurrencySnapshot?:string}>();for(const a of allocations){const line=lines.find(l=>l.id===a.productionRunLineId)!;const lot=state.inventoryLots.find(l=>l.id===a.inventoryLotId);if(!lot){errors.push(`${line.ingredientNameSnapshot}: select an inventory lot.`);continue}const error=validateProductionAllocation(line,a,lot,[...state.inventoryMovements,...movements]);if(error){errors.push(`${line.ingredientNameSnapshot}: ${error}`);continue}const movementId=uid();movements.push({id:movementId,inventoryLotId:lot.id,type:'Consumption',quantity:a.quantity,unit:a.unit,reason:`Production run ${state.productionRuns.find(r=>r.id===runId)?.productionRunNumber}`,referenceType:'ProductionRun',referenceId:runId,notes:line.notes,occurredAt:new Date().toISOString(),createdAt:new Date().toISOString()});committed.set(a.id,{movementId,...allocationCostSnapshot(lot,a.unit)})}if(errors.length)return errors;setState(c=>({...c,inventoryMovements:[...c.inventoryMovements,...movements],productionRunAllocations:c.productionRunAllocations.map(a=>{const saved=committed.get(a.id);return saved?{...a,inventoryMovementId:saved.movementId,unitCostSnapshot:saved.unitCostSnapshot,costCurrencySnapshot:saved.costCurrencySnapshot}:a})}));return[]},
    addProductionStep(productionRunId,instruction){setState(c=>({...c,productionProcessSteps:[...c.productionProcessSteps,{id:uid(),productionRunId,stepNumber:c.productionProcessSteps.filter(s=>s.productionRunId===productionRunId).length+1,instruction,status:'Pending',notes:''}]}))},
    updateProductionStep(id,patch){setState(c=>({...c,productionProcessSteps:c.productionProcessSteps.map(s=>s.id===id?{...s,...patch,completedAt:patch.status==='Completed'?new Date().toISOString():s.completedAt}:s)}))},
    addCostLine(input){const now=new Date().toISOString();setState(c=>({...c,costLines:[...c.costLines,{...input,id:uid(),createdAt:now,updatedAt:now}]}))},
  }), [state])
  return <FormulaDataContext.Provider value={value}>{children}</FormulaDataContext.Provider>
}

// eslint-disable-next-line react-refresh/only-export-components
export function useFormulaData() { const value = useContext(FormulaDataContext); if (!value) throw new Error('FormulaDataProvider is required'); return value }
