import { useState } from 'react'
import { Archive, ArrowLeft, Edit3, MapPin, Plus, Star } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { PageHeader } from '../../components/ui/PageHeader'
import { SectionHeader } from '../../components/ui/SectionHeader'
import { StatusPill } from '../../components/ui/StatusPill'
import { formatDate, formatMoney } from '../../utils/format'
import { useFormulaData } from '../formulas/state/FormulaDataContext'
import { expiryState, ingredientBalance, lotBalance, stockState } from '../inventory/domain/inventoryLogic'
import { ReceiveStockForm } from '../inventory/components/ReceiveStockForm'
import { IngredientForm } from './components/IngredientForm'
import { SupplierProductForm } from './components/SupplierProductForm'
import { runPreferredSupplierProductAction } from './supplierProductPreference'
import { cosingStatus } from './domain/ingredientMetadata'

export function IngredientDetailPage(){const {ingredientId}=useParams();const data=useFormulaData();const [edit,setEdit]=useState(false);const [receive,setReceive]=useState(false);const [supplierForm,setSupplierForm]=useState<string>();const[pendingPreferred,setPendingPreferred]=useState(''),[preferenceError,setPreferenceError]=useState('');const ingredient=data.ingredients.find((i)=>i.id===ingredientId);if(!ingredient)return <div className="empty-state"><h1>Ingredient not found</h1></div>;const lots=data.inventoryLots.filter((l)=>l.ingredientId===ingredient.id);const suppliers=data.supplierProducts.filter((p)=>p.ingredientId===ingredient.id);const balance=ingredientBalance(ingredient,data.inventoryLots,data.inventoryMovements);const state=stockState(ingredient,data.inventoryLots,data.inventoryMovements);const nextDate=lots.map((l)=>l.expiryDate??l.bestBeforeDate).filter(Boolean).sort()[0];const markPreferred=async(id:string)=>{if(pendingPreferred)return;try{await runPreferredSupplierProductAction(id,data.markSupplierPreferred,setPendingPreferred,setPreferenceError)}catch{return}}
return <><Link className="back-link" to="/ingredients"><ArrowLeft size={14}/>Ingredient library</Link><PageHeader eyebrow={`${ingredient.category} / Raw-material workspace`} title={ingredient.commonName} description={ingredient.description} action={<div className="action-row"><Link className="button ghost" to={`/knowledge?tab=scent-memory&ingredientId=${ingredient.id}`}>Record Scent Memory</Link><button className="button ghost" onClick={()=>setEdit(true)}><Edit3 size={15}/>Edit</button><button className="button primary" onClick={()=>setReceive(true)}><Plus size={15}/>Receive stock</button></div>}/>
<div className="ingredient-detail-grid"><section className="panel identity-card"><SectionHeader title="Identity"/><dl><div><dt>Common name</dt><dd>{ingredient.commonName}</dd></div><div><dt>Exact INCI name</dt><dd>{ingredient.inciName}</dd></div><div><dt>Category</dt><dd>{ingredient.category}</dd></div><div><dt>Default unit</dt><dd>{ingredient.defaultUnit}</dd></div><div><dt>Status</dt><dd><StatusPill tone={ingredient.status==='Active'?'green':'neutral'}>{ingredient.status}</StatusPill></dd></div></dl>{ingredient.status!=='Archived'&&<button className="text-button danger" onClick={()=>data.archiveIngredient(ingredient.id)}><Archive size={14}/>Archive ingredient</button>}</section><section className="panel inventory-summary"><SectionHeader title="Inventory summary"/><strong>{balance} <small>{ingredient.defaultUnit}</small></strong><StatusPill tone={state==='In Stock'?'green':state==='Low'?'amber':'neutral'}>{state}</StatusPill><div><span>Active lots<b>{lots.filter((l)=>l.status==='Active').length}</b></span><span>Reorder threshold<b>{ingredient.reorderThreshold??'—'} {ingredient.defaultUnit}</b></span><span>Nearest dated lot<b>{nextDate?formatDate(nextDate):'No date recorded'}</b></span></div></section></div>
<div className="ingredient-detail-grid"><section className="panel"><SectionHeader title="CosIng functions" detail={cosingStatus(ingredient).replaceAll('_',' ')}/>{ingredient.cosingFunctions?.length?<div className="metadata-tags">{ingredient.cosingFunctions.map(item=><span key={item}>{item}</span>)}</div>:<p>No verified CosIng functions recorded.</p>}{ingredient.cosingVerifiedAt&&<p>Verified {formatDate(ingredient.cosingVerifiedAt)}</p>}{ingredient.cosingSourceReference&&<p>Source: {ingredient.cosingSourceReference}</p>}{ingredient.functions.length&&<p className="legacy-metadata">Legacy Functions preserved for review: {ingredient.functions.join(' · ')}</p>}<small>Informational CosIng classification only. This does not prove safety, legality, suitability, or market approval.</small></section><section className="panel"><SectionHeader title="Technical behaviour"/><p>{ingredient.description||'No technical description recorded.'}</p><p>{ingredient.notes||'No technical notes recorded.'}</p><small>Technical knowledge is not automatically Lab or sensory evidence.</small></section></div>
<section className="panel"><SectionHeader title="Formula usage" detail="Version-specific human-authored roles"/>{data.formulaLines.filter(line=>line.ingredientId===ingredient.id).map(line=>{const version=data.formulaVersions.find(item=>item.id===line.formulaVersionId),formula=data.formulas.find(item=>item.id===version?.formulaId);return <article className="packaging-detail-row" key={line.id}><div><strong>{formula?.name??'Formula'} · {version?.version}</strong><small>{version?.status} · {line.percentage}%</small></div><span>{line.formulationRole||'No formulation role recorded.'}</span></article>})}{!data.formulaLines.some(line=>line.ingredientId===ingredient.id)&&<p>This Ingredient is not used in a Formula Version.</p>}</section>
<section className="panel lots-section"><SectionHeader title="Inventory lots" detail="Physical receipts and their remaining movement-derived balance" action={<button className="text-button" onClick={()=>setReceive(true)}><Plus size={14}/>Receive stock</button>}/><div className="lot-cards">{lots.map((lot)=>{const current=lotBalance(lot,data.inventoryMovements);const expiry=expiryState(lot,new Date('2026-07-14T12:00:00'));return <Link to={`/inventory/lots/${lot.id}`} key={lot.id}><div><span className="eyebrow">{lot.status}</span><h3>{lot.internalLotNumber}</h3><p>{lot.supplierLotNumber??'No supplier lot number'}</p></div><dl><div><dt>Remaining</dt><dd>{current} / {lot.openingQuantity} {lot.unit}</dd></div><div><dt>Received</dt><dd>{formatDate(lot.receivedDate)}</dd></div><div><dt>Location</dt><dd><MapPin size={11}/>{lot.location}</dd></div></dl><StatusPill tone={expiry==='Expired'?'red':expiry==='Expiring Soon'?'amber':'green'}>{expiry}</StatusPill></Link>})}{!lots.length&&<p className="empty-copy">No physical stock has been received.</p>}</div></section>
<section className="panel supplier-section"><SectionHeader title="Supplier products" detail="Purchasable source records—not purchase orders" action={<button className="text-button" onClick={()=>setSupplierForm('new')}><Plus size={14}/>Add supplier product</button>}/>{preferenceError&&<p className="form-error" role="alert">{preferenceError}</p>}<div className="supplier-products">{suppliers.map((p)=><article key={p.id}><div><span className="eyebrow">{p.supplierName}</span><h3>{p.productName}</h3><p>{p.supplierSku??'No supplier SKU'}</p></div><strong>{p.packageQuantity} {p.packageUnit}</strong><span>{formatMoney(p.price,p.currency)}</span><div className="supplier-actions"><button className="text-button" onClick={()=>setSupplierForm(p.id)}>Edit</button>{p.isPreferred?<StatusPill tone="green"><Star size={11}/>Preferred</StatusPill>:<button className="text-button" disabled={Boolean(pendingPreferred)} onClick={()=>void markPreferred(p.id)}>{pendingPreferred===p.id?'Saving…':'Mark preferred'}</button>}</div></article>)}</div></section>
{edit&&<IngredientForm ingredient={ingredient} onClose={()=>setEdit(false)}/>} {receive&&<ReceiveStockForm ingredientId={ingredient.id} onClose={()=>setReceive(false)}/>} {supplierForm&&<SupplierProductForm ingredientId={ingredient.id} product={suppliers.find((item)=>item.id===supplierForm)} onClose={()=>setSupplierForm(undefined)}/>}</>}
