import{describe,expect,it}from'vitest'
import{readFileSync}from'node:fs'
const css=readFileSync(new URL('../../styles/index.css',import.meta.url),'utf8')
const supplierProductForm=readFileSync(new URL('components/SupplierProductForm.tsx',import.meta.url),'utf8')
const unitForms=['components/IngredientForm.tsx','components/SupplierProductForm.tsx','../inventory/components/ReceiveStockForm.tsx','../inventory/components/MovementForm.tsx'].map(path=>readFileSync(new URL(path,import.meta.url),'utf8'))
const executionForms=['../lab/components/StartBatchForm.tsx','../production/components/CreateProductionRunForm.tsx'].map(path=>readFileSync(new URL(path,import.meta.url),'utf8'))
describe('Ingredient metadata responsive contracts',()=>{it('keeps the 390px Ingredient form single-column and the Formula editor horizontally usable',()=>{expect(css).toContain('@media(max-width:760px)');expect(css).toContain('.form-grid{grid-template-columns:1fr}');expect(css).toContain('.builder-table{overflow-x:auto}');expect(css).toContain('@media(max-width:820px)');expect(css).toContain('.builder-columns,.builder-line{min-width:930px}')})})
describe('milligram form controls',()=>{it('offers units in canonical order on forms that accept raw-material weight',()=>unitForms.forEach(source=>expect(source).toContain("['mg','g','kg','ml','L','pcs']")))})
describe('milligram execution controls',()=>{it('offers mg before g and kg in Lab and Production',()=>executionForms.forEach(source=>expect(source).toContain('<option>mg</option><option>g</option><option>kg</option>')))})
describe('Supplier Product progressive disclosure',()=>{
 it('opens in Quick Mode with essential commercial fields and an explicit Advanced toggle',()=>{expect(supplierProductForm).toContain("useState(false)");expect(supplierProductForm).toContain("aria-label=\"Quick Mode essential fields\"");expect(supplierProductForm).toContain("advanced?'Hide Advanced':'Show Advanced'");['supplierName','productName','supplierSku','packageQuantity','packageUnit','price','currency','grade','supplierGrade','origin','shelfLifeMonths','storageRequirements','productStatus','operationalNotes','preferred'].forEach(name=>expect(supplierProductForm).toContain(`name="${name}"`))})
 it('keeps overrides, verification, and supporting notes behind Advanced while preserving hidden edit values',()=>{expect(supplierProductForm).toContain('{advanced&&<div id="supplier-product-advanced"');expect(supplierProductForm).toContain('Supplier-specific technical identity');expect(supplierProductForm).toContain('Verification checklist');expect(supplierProductForm).toContain('Legacy General Notes remain preserved');expect(supplierProductForm).toContain('{!advanced&&<div hidden')})
 it('presents inherited Ingredient knowledge as read-only context',()=>{expect(supplierProductForm).toContain('aria-label="Inherited Ingredient information"');expect(supplierProductForm).toContain('Botanical / INCI name');expect(supplierProductForm).toContain('Typical formula roles');expect(supplierProductForm).toContain('CosIng functions')})
 it('keeps Quick and Advanced layouts single-column at 390px',()=>{expect(css).toContain('@media(max-width:480px)');expect(css).toContain('.verification-grid,.supplier-product-filters,.supplier-inherited-card,.supplier-inherited-card dl,.supplier-save-preview{grid-template-columns:1fr}');expect(css).toContain('.supplier-product-form{width:calc(100vw - 16px)')})
})
