import { describe, expect, it } from 'vitest'
import { formulaSeed } from '../../data/formulaSeed'
import { BACKUP_FORMAT, createBackup, validateBackup } from './backup'
import { APPLICATION_VERSION, WORKSPACE_SCHEMA } from '../version'
describe('Koalafrog backup', () => {
  it('exports the build-time application version without changing schema or format versions',()=>{const backup=createBackup(formulaSeed);expect(backup.applicationVersion).toBe(APPLICATION_VERSION);expect(backup.workspace.sourceSchema).toBe(WORKSPACE_SCHEMA);expect(backup.format).toBe(BACKUP_FORMAT)})
  it('accepts older application-version metadata without using it as a schema compatibility gate',()=>{const backup=createBackup(formulaSeed);backup.applicationVersion='0.1.0';expect(validateBackup(backup).valid).toBe(true);expect(backup.workspace.sourceSchema).toBe('koalafrog-hq:workspace:v9')})
  it('exports version, counts, records, Storage, and Development history', () => { const backup = createBackup(formulaSeed, [{ documentId: 'd', bucket: 'b', objectPath: 'o', fileName: 'f.pdf', size: 10 }], 'owner', { threads: [], runs: [], knowledgeReferences: [], scentMemorySessions: [], scentMemoryCheckpoints: [], developmentExperiments: [{ id: 'e' }], developmentExperimentVariants: [], developmentExperimentChanges: [], developmentObservationPrompts: [], developmentStatusEvents: [], developmentHandoffs: [] }); expect(backup.format).toBe(BACKUP_FORMAT); expect(backup.entityCounts.products).toBe(formulaSeed.products.length); expect(backup.entityCounts.developmentExperiments).toBe(1); expect(backup.storageManifest).toHaveLength(1); expect(backup).not.toHaveProperty('password') })
  it('validates portable backups and rejects malformed input', () => { expect(validateBackup(createBackup(formulaSeed)).valid).toBe(true); expect(validateBackup({ format: 'wrong' }).valid).toBe(false); expect(validateBackup(null).valid).toBe(false) })
  it('rejects record/count disagreement', () => { const backup = createBackup(formulaSeed); backup.entityCounts.products += 1; expect(validateBackup(backup)).toMatchObject({ valid: false, errors: ['Entity count mismatch for products.'] }) })
  it('includes CosIng metadata, legacy functions, and Formula Line roles',()=>{const state=structuredClone(formulaSeed);Object.assign(state.ingredients[0],{cosingFunctions:['SKIN CONDITIONING'],cosingVerificationStatus:'verified_from_cosing',cosingVerifiedAt:'2026-07-16',cosingSourceReference:'CosIng exact INCI entry'});state.formulaLines[0].formulationRole='Primary lightweight carrier';const backup=createBackup(state);expect(backup.records.ingredients[0]).toMatchObject({functions:formulaSeed.ingredients[0].functions,cosingFunctions:['SKIN CONDITIONING'],cosingVerificationStatus:'verified_from_cosing'});expect(backup.records.formulaLines[0].formulationRole).toBe('Primary lightweight carrier')})
  it('preserves milligram units without rewriting them',()=>{const state=structuredClone(formulaSeed);state.ingredients[0].defaultUnit='mg';state.supplierProducts[0].packageUnit='mg';state.supplierProducts[0].packageQuantity=500;state.inventoryLots[0].unit='mg';state.inventoryMovements[0].unit='mg';const backup=createBackup(state);expect(validateBackup(backup).valid).toBe(true);expect(backup.records.ingredients[0].defaultUnit).toBe('mg');expect(backup.records.supplierProducts[0].packageUnit).toBe('mg');expect(backup.records.inventoryLots[0].unit).toBe('mg')})
  it('preserves Supplier Product intelligence and its authoritative relationships',()=>{const state=structuredClone(formulaSeed);Object.assign(state.supplierProducts[0],{supplierId:'supplier-backup',grade:'Cosmetic Grade',supplierGrade:'CG-70',declaredInci:'TOCOPHEROL',categorySnapshot:'Antioxidant',defaultInventoryUnit:'mg',cosingFunctionsSnapshot:['ANTIOXIDANT'],researchProfileSnapshot:'Reference profile',referenceEntryId:'tocopherol',origin:'Norway',processingMethod:'Distilled',productStatus:'reviewing',operationalNotes:'Order chilled',verificationNotes:'CoA needs review',notes:'Legacy/general note',verification:{inci:'reviewed',supplierSpecification:'reviewed',sds:'unknown',coa:'needs_review',allergenInformation:'unknown',shelfLife:'reviewed',origin:'reviewed',extractionMethod:'unknown',processingMethod:'reviewed',ifra:'not_applicable',cosing:'reviewed'}});state.inventoryLots[0].supplierProductId=state.supplierProducts[0].id;const backup=createBackup(state),product=backup.records.supplierProducts[0];expect(product).toMatchObject({supplierId:'supplier-backup',grade:'Cosmetic Grade',supplierGrade:'CG-70',defaultInventoryUnit:'mg',operationalNotes:'Order chilled',verificationNotes:'CoA needs review',notes:'Legacy/general note'});expect(product.verification).toMatchObject({inci:'reviewed',coa:'needs_review',ifra:'not_applicable'});expect(backup.records.inventoryLots[0].supplierProductId).toBe(product.id)})
  it('round-trips repository-backed Product Studio concepts and handoff links',()=>{const state=structuredClone(formulaSeed);state.productStudioConcepts.push({id:'studio-1',name:'Light Beard Oil',productType:'beard_oil',intentMode:'design',desiredProperties:['Lightweight'],selectedIngredients:[{ingredientId:'i1',role:'liquid_base',essential:true}],scentDirections:['Scent-free'],candidateSubstitutes:{i9:['i1']},notes:'Draft concept',analysis:{predicted:true},generatedProductId:'p1',generatedFormulaId:'f-bo-original',generatedFormulaVersionId:'fv-bo-02',createdAt:'2026-07-18',updatedAt:'2026-07-18'});const backup=createBackup(state);expect(validateBackup(backup).valid).toBe(true);expect(backup.records.productStudioConcepts[0]).toMatchObject({name:'Light Beard Oil',selectedIngredients:[{ingredientId:'i1',role:'liquid_base',essential:true}],generatedFormulaVersionId:'fv-bo-02'})})
})
