import{describe,expect,it}from'vitest'
import{formulaSeed}from'../../data/formulaSeed'
import{createEmptyIngredientKnowledgeProfile}from'../../features/ingredients/domain/ingredientKnowledge'
import{createBackup,validateBackup}from'./backup'
import{BACKUP_FORMAT,WORKSPACE_SCHEMA}from'../version'

describe('Ingredient Knowledge backup compatibility',()=>{
  it('accepts an old backup whose records have no knowledge collections',()=>{const backup=createBackup(formulaSeed)as unknown as{records:Record<string,unknown>;entityCounts:Record<string,number>};delete backup.records.ingredientKnowledgeProfiles;delete backup.records.ingredientKnowledgeRoles;delete backup.records.ingredientKnowledgeCompatibility;delete backup.records.ingredientKnowledgeEvidence;delete backup.entityCounts.ingredientKnowledgeProfiles;delete backup.entityCounts.ingredientKnowledgeRoles;delete backup.entityCounts.ingredientKnowledgeCompatibility;delete backup.entityCounts.ingredientKnowledgeEvidence;expect(validateBackup(backup).valid).toBe(true)})
  it('round-trips states, endpoints, relations, evidence, and unknown prediction inputs',()=>{const state=structuredClone(formulaSeed),profile=createEmptyIngredientKnowledgeProfile('i1','2026-07-20T12:00:00.000Z');profile.id='knowledge-backup';profile.identity.veganStatus={state:'not_applicable',confidence:'verified'};profile.physicalProperties.physicalForm={state:'review_required',confidence:'conflicting',notes:'Supplier grades conflict'};profile.sensoryProfile.slip={state:'known',value:0,confidence:'observed',notes:'10% internal balm observation'};profile.sensoryProfile.drag={state:'known',value:10,confidence:'observed',sourceReference:'observation-10'};state.ingredientKnowledgeProfiles=[profile];state.ingredientKnowledgeEvidence=[{id:'e1',ingredientKnowledgeProfileId:profile.id,sourceType:'supplier_document',provenance:'supplier_specific',title:'Specification A',summary:'Grade-specific statement.',notes:'',confidence:'conflicting',createdAt:profile.createdAt,updatedAt:profile.updatedAt},{id:'e2',ingredientKnowledgeProfileId:profile.id,sourceType:'internal_observation',provenance:'internal',title:'Bench observation',summary:'Contextual only.',notes:'',confidence:'observed',createdAt:profile.createdAt,updatedAt:profile.updatedAt}];state.ingredientKnowledgeRoles=[{id:'r1',ingredientKnowledgeProfileId:profile.id,role:'slip_modifier',level:'secondary',context:'10% balm',evidenceIds:['e2'],confidence:'observed',notes:'',createdAt:profile.createdAt,updatedAt:profile.updatedAt}];state.ingredientKnowledgeCompatibility=[{id:'c1',ingredientKnowledgeProfileId:profile.id,targetType:'ingredient',targetId:'i2',targetLabel:'Argan Oil',context:'One anhydrous trial',rating:'review_required',evidenceIds:['e2'],confidence:'conflicting',notes:'Directional evidence only.',createdAt:profile.createdAt,updatedAt:profile.updatedAt}];const backup=createBackup(state),restored=structuredClone(backup.records);expect(validateBackup(backup).valid).toBe(true);expect(backup.format).toBe(BACKUP_FORMAT);expect(backup.workspace.sourceSchema).toBe(WORKSPACE_SCHEMA);expect(restored.ingredientKnowledgeProfiles[0].sensoryProfile).toMatchObject({slip:{state:'known',value:0},drag:{state:'known',value:10}});expect(restored.ingredientKnowledgeEvidence).toHaveLength(2);expect(restored.ingredientKnowledgeCompatibility[0]).toMatchObject({targetId:'i2',rating:'review_required',confidence:'conflicting'});expect(Object.values(restored.ingredientKnowledgeProfiles[0].predictionInputs).every(field=>field.state==='unknown')).toBe(true)})
})
