import type { FormulaLine, FormulaVersionStatus, Ingredient, InventoryLot, InventoryMovement, InventoryUnit, ProductionRun, ProductionRunAllocation, ProductionRunLine, ProductionRunStatus } from '../../../types/domain'
import { convertUnit, lotBalance } from '../../inventory/domain/inventoryLogic'
import { lotUnitCost } from '../../costing/domain/costingLogic'

const code=(name:string)=>name.split(/\s+/).filter(w=>!['signature','original','daily','koalafrog'].includes(w.toLowerCase())).map(w=>w[0]).join('').slice(0,2).toUpperCase()||'PR'
export function requireApprovedProductionSource(status:FormulaVersionStatus){if(status!=='Approved')throw new Error('Only Approved Formula Versions may be used for Production Runs.')}
export function generateProductionRunNumber(productName:string,existing:string[],date=new Date()){const stamp=`${String(date.getFullYear()).slice(-2)}${String(date.getMonth()+1).padStart(2,'0')}${String(date.getDate()).padStart(2,'0')}`;const prefix=`KF-PR-${code(productName)}-${stamp}-`;const next=Math.max(0,...existing.filter(n=>n.startsWith(prefix)).map(n=>Number(n.slice(prefix.length))||0))+1;return`${prefix}${String(next).padStart(2,'0')}`}
export const plannedProductionQuantity=(percentage:number,size:number)=>Math.round(percentage*size/100*10000)/10000
export const productionVariance=(actual:number|undefined,planned:number)=>actual==null?undefined:Math.round((actual-planned)*10000)/10000
export function productionYieldVariance(actual:number|undefined,planned:number){if(actual==null)return undefined;const amount=productionVariance(actual,planned)!;return{amount,percentage:planned?Math.round(amount/planned*10000)/100:undefined}}
export function createProductionLines(runId:string,lines:FormulaLine[],ingredients:Ingredient[],size:number,unit:InventoryUnit,idFactory:()=>string=()=>crypto.randomUUID()):ProductionRunLine[]{return[...lines].sort((a,b)=>a.sortOrder-b.sortOrder).map(l=>({id:idFactory(),productionRunId:runId,formulaLineId:l.id,ingredientId:l.ingredientId,ingredientNameSnapshot:ingredients.find(i=>i.id===l.ingredientId)?.commonName??'Unknown ingredient',phase:l.phase,plannedPercentage:l.percentage,plannedQuantity:plannedProductionQuantity(l.percentage,size),unit,notes:l.notes,status:'Pending'}))}
export const productionTransitions:Record<ProductionRunStatus,ProductionRunStatus[]>={'Planned':['In Progress','Aborted'],'In Progress':['Completed','Aborted'],'Completed':['Archived'],'Aborted':['Archived'],'Archived':[]}
export const canTransitionProduction=(from:ProductionRunStatus,to:ProductionRunStatus)=>productionTransitions[from].includes(to)
export function productionCompletionWarnings(run:ProductionRun,lines:ProductionRunLine[],allocations:ProductionRunAllocation[]){const own=lines.filter(l=>l.productionRunId===run.id);const warnings:string[]=[];if(own.some(l=>l.status==='Pending'))warnings.push('Some material lines are pending.');if(own.some(l=>l.status==='Weighed'&&l.actualQuantity==null))warnings.push('Some weighed lines have no actual quantity.');if(own.some(l=>l.status==='Weighed'&&!allocations.some(a=>a.productionRunLineId===l.id&&a.inventoryMovementId)))warnings.push('Some consumption is uncommitted.');if(own.some(l=>l.status==='Skipped'))warnings.push('One or more material lines were skipped.');if(run.actualYield==null)warnings.push('Actual yield is missing.');if(run.actualUnitsProduced==null)warnings.push('Actual finished unit count is missing.');if(own.some(l=>Math.abs(l.variance??0)>l.plannedQuantity*.05))warnings.push('A material variance exceeds 5%.');return warnings}
export function validateProductionAllocation(line:ProductionRunLine,a:ProductionRunAllocation,lot:InventoryLot,movements:InventoryMovement[]){if(a.inventoryMovementId)return'This allocation is already committed.';if(line.status!=='Weighed'||line.actualQuantity==null)return'Record actual weigh-in first.';if(lot.ingredientId!==line.ingredientId)return'Selected lot belongs to another ingredient.';if(a.quantity<=0||!Number.isFinite(a.quantity))return'Allocation must be greater than zero.';let required:number;try{required=convertUnit(a.quantity,a.unit,lot.unit)}catch{return`Allocation unit is incompatible with ${lot.unit}.`}if(required>lotBalance(lot,movements))return'Allocation exceeds available stock.';return null}
export function allocationCostSnapshot(lot:InventoryLot,unit:InventoryUnit){const cost=lotUnitCost(lot,unit);return{unitCostSnapshot:cost,costCurrencySnapshot:cost==null?undefined:lot.acquisitionCostCurrency}}
