import {describe,expect,it} from'vitest'
import type {BeardPhotoAnalysisResult,BeardPhotoRecommendation} from'../../../intelligence/Vision/beardPhotoAnalysis'
import type {GroomingTool} from'../../../types/beardStudio'
import {deriveGroomingSummary,generateTrimPlan,mapToolInstruction,rankRecommendations,targetStyleLabel}from'./beardPhotoIntelligenceV2'
const rec=(id:string,title:string,status:'undecided'|'accepted_for_planning'|'dismissed'='undecided',priority:'low'|'medium'|'high'='medium',guard:string|null='Try a 7 mm guard on the sides as a starting point.'):BeardPhotoRecommendation=>({id,title,reason:'Improve the side transition.',confidence:.8,priority,expectedBenefit:'A cleaner transition.',supportingObservationKeys:['strong_chin'],affectedZones:['sides'],toolConstraints:[],proposedGuardStrategy:guard,status,provenance:'ai'})
const result=(recommendations:BeardPhotoRecommendation[]):BeardPhotoAnalysisResult=>({analysisId:crypto.randomUUID(),schemaVersion:2,contractVersion:'beard-photo-result-contract-v2',promptVersion:'v6',provider:'openai',model:'gpt-5',createdAt:'2026-07-27T10:00:00Z',provenance:'ai',status:'completed',photoQuality:{overall:'suitable',perView:[],issues:[],retakeRecommended:false},observations:[{observationKey:'strong_chin',category:'density',statement:'The chin appears strong and full.',confidence:.9,supportingViews:['front'],evidenceDescription:'front',limitations:[],relatedBeardZones:['chin'],provenance:'ai'}],symmetry:[],densityDistribution:[],lineAssessment:[],recommendations,limitations:[],unknowns:[],safetyFlags:[],correlationId:crypto.randomUUID()})
const tool:GroomingTool={id:'t',name:'Philips Beard Trimmer 7000',brand:'Philips',model:'BT7665/15',type:'beard trimmer',minimumLengthMm:.4,maximumLengthMm:20,adjustmentIncrementMm:.2,attachments:[{id:'a',name:'Integrated adjustable comb'},{id:'l',name:'Long-length comb'},{id:'f',name:'Fade comb'},{id:'d',name:'Detail trimmer'}],washable:false,notes:'',primary:true,status:'active',createdAt:'',updatedAt:''}
describe('Beard Intelligence v2 deterministic derivation',()=>{
 it('derives summary and safe legacy target fallback',()=>{const summary=deriveGroomingSummary(result([rec('b','Shape sides','undecided','high')]),{value:'fuller_chin_soft_side_fade',label:'Fuller chin with soft side fade'});expect(summary.strengths[0]).toContain('strong');expect(summary.highestImpactImprovements[0].recommendationId).toBe('b');expect(targetStyleLabel()).toBe('No target style recorded')})
 it('uses stable priority and title/id tie breaking',()=>{expect(rankRecommendations([rec('b','Zulu'),rec('a','Alpha')]).map(x=>x.id)).toEqual(['a','b']);expect(rankRecommendations([rec('x','High','undecided','high')])[0].priorityLabel).toBe('Highest impact')})
 it('maps verified Philips capabilities and falls back safely',()=>{expect(mapToolInstruction(rec('a','Sides'),tool).technique).toBe('Set the adjustable comb to 7 mm.');expect(mapToolInstruction(rec('a','Chin','undecided','medium','Try a 12 mm guard on the chin.'),tool).technique).toBe('Use the long-length comb for 12 mm.');expect(mapToolInstruction(rec('a','Lip line'),tool).technique).toContain('detail trimmer');expect(mapToolInstruction(rec('a','Fade transition', 'undecided','medium',null),tool).attachmentOrComb).toBe('Fade comb');expect(mapToolInstruction(rec('a','Sides','undecided','medium','Try a 25 mm guard.'),tool).supported).toBe(false);expect(mapToolInstruction(rec('a','Sides'),undefined).supported).toBe(false);expect(mapToolInstruction(rec('a','Sides'),{...tool,attachments:[]}).supported).toBe(false)})
 it('includes only accepted recommendations plus universal guidance',()=>{const plan=generateTrimPlan(result([rec('accepted','Sides','accepted_for_planning'),rec('dismissed','Chin','dismissed'),rec('undecided','Line')]),tool);expect(plan.steps.flatMap(x=>x.recommendationIds)).toEqual(['accepted']);expect(plan.steps.filter(x=>x.universal).map(x=>x.id)).toEqual(['prepare','final-check'])})
 it('embeds historical target and equipment so profile and tool changes cannot reinterpret snapshots',()=>{const target={value:'structured_full_beard' as const,label:'Structured full beard'},plan=generateTrimPlan(result([rec('accepted','Sides','accepted_for_planning')]),tool,target);const changedTool={...tool,name:'Different tool',model:'NEW',attachments:[]};expect(plan.targetStyle).toEqual(target);expect(plan.steps[1].tool).toContain('Philips');expect(plan.steps[1].attachmentOrComb).toBe('Integrated adjustable comb');expect(generateTrimPlan(result([rec('accepted','Sides','accepted_for_planning')]),changedTool,target).steps[1].tool).toContain('Different tool');expect(deriveGroomingSummary(result([]),target).targetStyle).toEqual(target)})
 it('keeps historical target and snapshots stable across ten reopen cycles and a profile target change',()=>{const historical={value:'short_boxed_beard' as const,label:'Short boxed beard'},current={value:'rugged_full_beard' as const,label:'Rugged full beard'},source=result([rec('accepted','Sides','accepted_for_planning')]),summary=deriveGroomingSummary(source,historical),plan=generateTrimPlan(source,tool,historical),persisted=JSON.stringify({summary,plan,supportId:source.correlationId,createdAt:source.createdAt});let reopened=persisted;for(let index=0;index<10;index++)reopened=JSON.stringify(JSON.parse(reopened));expect(reopened).toBe(persisted);expect(JSON.parse(reopened).plan.targetStyle).toEqual(historical);expect(JSON.parse(reopened).plan.targetStyle).not.toEqual(current)})
 it('updates a changed decision deterministically and removes obsolete plan steps',()=>{const source=result([rec('first','Sides','accepted_for_planning'),rec('second','Chin','dismissed')]),before=generateTrimPlan(source,tool,null),after=generateTrimPlan({...source,recommendations:source.recommendations.map(item=>item.id==='first'?{...item,status:'dismissed'}:item)},tool,null);expect(before.steps.flatMap(step=>step.recommendationIds)).toEqual(['first']);expect(after.steps.flatMap(step=>step.recommendationIds)).toEqual([]);expect(new Set(after.steps.map(step=>step.id)).size).toBe(after.steps.length)})
})
