import{expect,test}from'@playwright/test'
import{signIn}from'./ingredientKnowledge.helpers'

test('creates, edits, refreshes and gates a blank Benchmark Lab Draft',async({page})=>{
 await signIn(page)
 await page.goto('/product-studio')
 await page.getByRole('link',{name:/Design Natural Deodorant/}).click()
 await expect(page).toHaveURL(/product-studio\/benchmark-lab\/new/)
 await expect(page.getByRole('heading',{name:'Create development project'})).toBeVisible()
 await expect(page.getByText('Research Progress',{exact:true})).toBeVisible()
 await expect(page.getByText('0%',{exact:true})).toBeVisible()
 await expect(page.locator('.research-summary').getByText('Idea',{exact:true})).toBeVisible()
 await expect(page.getByText('Open research questions',{exact:true})).toBeVisible()
 await expect(page.getByText('No formula, percentage, supplier, procurement, inventory')).toBeVisible()
 await page.getByText('View exact ordered label declaration').click()
 const inci=page.locator('.ordered-inci-disclosure li')
 await expect(inci).toHaveCount(17)
 await expect(inci.first()).toContainText('PROPYLENE GLYCOL')
 await expect(inci.nth(1)).toContainText('AQUA/WATER')
 await expect(page.getByText('Percentages remain Unknown.')).toBeVisible()
 await expect(page.getByText('userNeed',{exact:true})).toHaveCount(0)
 await expect(page.getByText('What user need should this product solve?')).toBeVisible()
 await expect(page.getByText('Known hypothesis value')).toHaveCount(0)
 await expect(page.getByRole('columnheader')).toHaveCount(0)
 await expect(page.getByText('Benchmark observation',{exact:true})).toBeVisible()
 const requirement=page.locator('.requirements-grid article').first()
 await expect(requirement.getByText('No supported suggested candidates yet.')).toBeVisible()
 await requirement.getByLabel('Search the full Reference Library').fill('propylene glycol')
 await expect(requirement.getByRole('button',{name:/Propylene Glycol/})).toBeVisible()
 await page.screenshot({path:'test-results/benchmark-lab-desktop.png',fullPage:true})
 await page.getByLabel('Working title').fill('Koalafrog Benchmark Lab E2E')
 await page.getByRole('button',{name:'Create development project'}).click()
 await expect(page).toHaveURL(/benchmark-lab\/.+/)
 await page.getByLabel('glide state').selectOption('scored')
 await page.getByLabel('glide score').fill('9')
 await expect(page.getByLabel('glide: Excellent, 9 out of 10',{exact:true})).toContainText('9/10')
 await page.getByLabel('drag state').selectOption('scored')
 await page.getByLabel('drag score').fill('2')
 await expect(page.getByLabel('drag: Minimal, 2 out of 10',{exact:true})).toContainText('Minimal')
 await page.getByLabel('glide observation note').fill('Almost no drag.')
 await page.getByLabel('Glide target state').selectOption('known')
 await page.getByLabel('Glide target value').fill('9/10')
 await page.getByLabel('Glide priority').selectOption('critical')
 await page.getByLabel('Open questions').first().fill('Which system evidence is still needed?')
 await expect(page.getByText('Open research questions',{exact:true}).locator('..')).toContainText('1')
 const importance=requirement.getByLabel('Continuous phase / solvent system importance')
 const reviewStatus=requirement.getByLabel('Continuous phase / solvent system review status')
 const readinessBeforeImportance=await page.locator('.readiness-checks>.complete').count()
 await importance.selectOption('required')
 await expect(page.locator('.readiness-checks>.complete')).toHaveCount(readinessBeforeImportance)
 await expect(page.getByText('0 reviewed',{exact:true})).toBeVisible()
 await reviewStatus.selectOption('reviewed')
 await expect(page.locator('.readiness-checks>.complete')).toHaveCount(readinessBeforeImportance+1)
 await expect(page.getByText('1 reviewed',{exact:true})).toBeVisible()
 const readinessCount=await page.locator('.readiness-checks>.complete').count()
 await expect(page.locator('.readiness-summary>strong')).toHaveText(`${readinessCount} of 6 readiness checks complete`)
 await page.getByRole('button',{name:'Save project'}).click()
 await expect(page.getByRole('status')).toContainText('Development project saved')
 await page.goto('/product-studio')
 await expect(page.getByRole('link',{name:/Continue research · Koalafrog Benchmark Lab E2E/})).toContainText('Research Progress')
 await page.getByRole('link',{name:/Continue research · Koalafrog Benchmark Lab E2E/}).click()
 await page.reload()
 await expect(page.getByLabel('glide score')).toHaveValue('9')
 await expect(page.getByLabel('glide observation note')).toHaveValue('Almost no drag.')
 await expect(page.getByLabel('Open questions').first()).toHaveValue('Which system evidence is still needed?')
 await expect(page.getByText('Open research questions',{exact:true}).locator('..')).toContainText('1')
 await expect(page.getByLabel('Glide target value')).toHaveValue('9/10')
 await expect(page.getByLabel('firmness state')).toHaveValue('not_tested')
 await expect(page.getByLabel('Continuous phase / solvent system importance')).toHaveValue('required')
 await expect(page.getByLabel('Continuous phase / solvent system review status')).toHaveValue('reviewed')
 await expect(page.getByRole('button',{name:'Start Draft Formula'})).toBeDisabled()
 await page.getByLabel(/acknowledge unresolved items/).check()
 await page.getByRole('button',{name:'Save project'}).click()
 await expect(page.getByRole('status')).toContainText('Development project saved')
 await page.reload()
 await expect(page.getByLabel(/acknowledge unresolved items/)).toBeChecked()
 await page.getByRole('button',{name:'Start Draft Formula'}).click()
 await expect(page).toHaveURL(/benchmark-lab\/.+/)
 await expect(page.getByRole('link',{name:/Continue to formulation/})).toBeVisible()
 await page.getByRole('link',{name:/Continue to formulation/}).click()
 await expect(page).toHaveURL(/product-studio\/natural-deodorant\?concept=/)
 await expect(page.getByRole('navigation',{name:'Natural Deodorant workflow'})).toContainText('Research')
 await expect(page.getByRole('navigation',{name:'Natural Deodorant workflow'})).toContainText('Formulation')
 await page.getByRole('link',{name:'Open Development Workspace'}).click()
 await expect(page.getByRole('button',{name:'Add ingredient'})).toBeVisible()
})
