import{expect,test}from'@playwright/test'
import{signIn}from'./ingredientKnowledge.helpers'

test('Benchmark Lab remains usable at 390px and protects dirty navigation',async({page})=>{
 await signIn(page)
 await page.goto('/product-studio/benchmark-lab/new')
 await expect(page.getByRole('navigation',{name:'Benchmark Lab progress'})).toBeVisible()
 await expect(page.getByText('Research Progress',{exact:true})).toBeVisible()
 await expect(page.locator('.research-summary')).toBeVisible()
 await expect(page.getByRole('button',{name:/Formula Readiness/})).toBeVisible()
 await page.getByRole('button',{name:/Observations/}).click()
 await expect(page.locator('#observations')).toBeInViewport()
 await expect(page.getByLabel('Working title')).toBeVisible()
 await page.getByLabel('glide state').selectOption('scored')
 await expect(page.getByLabel('glide: Very low, 1 out of 10',{exact:true})).toBeVisible()
 const requirement=page.locator('.requirements-grid article').first()
 await expect(requirement.locator('.requirement-identity')).toContainText('Solvent / continuous phase')
 const readinessBeforeReview=await page.locator('.readiness-checks>.complete').count()
 await requirement.getByLabel('Continuous phase / solvent system importance').selectOption('required')
 await expect(page.locator('.readiness-checks>.complete')).toHaveCount(readinessBeforeReview)
 await requirement.getByLabel('Continuous phase / solvent system review status').selectOption('reviewed')
 await expect(page.locator('.readiness-checks>.complete')).toHaveCount(readinessBeforeReview+1)
 await expect(page.getByText('1 reviewed',{exact:true})).toBeVisible()
 await expect(page.locator('.readiness-summary')).toContainText(/of 6 readiness checks complete/)
 await page.getByLabel('Working title').fill('Unsaved mobile Benchmark Lab')
 await page.getByRole('main').getByRole('link',{name:'Product Studio'}).click()
 await expect(page.getByRole('dialog')).toContainText('Unsaved Benchmark Lab changes')
 await page.getByRole('button',{name:'Stay'}).click()
 await expect(page.getByLabel('Working title')).toHaveValue('Unsaved mobile Benchmark Lab')
 await page.screenshot({path:'test-results/benchmark-lab-mobile.png',fullPage:true})
 const width=await page.locator('.benchmark-lab').evaluate(element=>element.scrollWidth)
 expect(width).toBeLessThanOrEqual(390)
})
