import{createClient}from'@supabase/supabase-js'
import{expect,test,type Page}from'@playwright/test'
import{addCompatibility,addEvidence,addRole,createIngredient,openKnowledge,owner,signIn}from'./ingredientKnowledge.helpers'

const unique=(label:string)=>`${label} ${owner().runId.slice(0,8)}`
const operationalTables=['inventory_lots','inventory_movements','formulas','formula_versions','lab_batches','packaging_components','production_runs']as const
async function operationalWriteCounts(){
 const credentials=owner(),client=createClient(credentials.url,credentials.publishableKey,{auth:{persistSession:false}})
 const auth=await client.auth.signInWithPassword({email:credentials.email,password:credentials.password})
 expect(auth.error).toBeNull()
 return Object.fromEntries(await Promise.all(operationalTables.map(async table=>{
  const result=await client.from(table).select('id',{count:'exact',head:true})
  expect(result.error,table).toBeNull()
  return[table,result.count??0]as const
 })))
}
async function assertNoOperationalWrites(baseline:Record<string,number>){
 const current=await operationalWriteCounts()
 for(const table of operationalTables)expect(current[table],table).toBe(baseline[table])
}
async function buildLinkedAggregate(page:Page,currentId:string,targetId:string,evidenceTitle:string){
 await openKnowledge(page,currentId)
 await page.getByRole('button',{name:'Identity'}).click()
 await page.locator('#identity-inci-state').selectOption('known')
 await page.locator('#identity-inci-value').fill('CERA ALBA E2E')
 await page.locator('#identity-inci-confidence').selectOption('supported')
 await page.getByRole('button',{name:'Physical'}).click()
 await page.locator('#physical-density-state').selectOption('known')
 await page.locator('#physical-density-value').fill('0.96')
 await page.locator('#physical-density-unit').fill('g/ml')
 await page.locator('#physical-density-lower').fill('0.94')
 await page.locator('#physical-density-upper').fill('0.98')
 await addEvidence(page,evidenceTitle)
 await addRole(page,evidenceTitle)
 await addCompatibility(page,targetId,evidenceTitle)
}

test('desktop full aggregate, persistence, and linked Evidence deletion',async({page})=>{
 await signIn(page)
 const operationalBaseline=await operationalWriteCounts()
 const currentName=unique('Desktop current'),targetName=unique('Desktop target'),evidenceTitle=unique('Supplier specification')
 const currentId=await createIngredient(page,currentName),targetId=await createIngredient(page,targetName,'SIMMONDSIA CHINENSIS SEED OIL')
 await buildLinkedAggregate(page,currentId,targetId,evidenceTitle)
 await page.getByRole('button',{name:'Identity'}).click()
 await expect(page.locator('#identity-inci-value')).toHaveValue('CERA ALBA E2E')
 const priorFocus=page.getByRole('link',{name:'Dashboard',exact:true})
 await priorFocus.focus()
 await priorFocus.click()
 const dialog=page.getByRole('dialog',{name:'Leave without saving?'})
 await expect(dialog).toBeVisible()
 await expect(dialog).toHaveAccessibleDescription(/discarded/)
 await expect(page.getByRole('button',{name:'Stay and continue editing'})).toBeFocused()
 await page.keyboard.press('Tab')
 await expect(page.getByRole('button',{name:'Discard changes and leave'})).toBeFocused()
 await page.keyboard.press('Tab')
 await expect(page.getByRole('button',{name:'Stay and continue editing'})).toBeFocused()
 await page.keyboard.press('Escape')
 await expect(dialog).toBeHidden()
 await expect(priorFocus).toBeFocused()
 await page.getByRole('button',{name:'Save knowledge'}).click()
 await expect(page.getByText(/^Saved\. This does not imply/)).toBeVisible()
 await expect(page.getByRole('button',{name:'Save knowledge'})).toBeDisabled()
 await page.reload()
 await page.getByRole('button',{name:'Physical'}).click()
 await expect(page.locator('#physical-density-value')).toHaveValue('0.96')
 await expect(page.locator('#physical-density-unit')).toHaveValue('g/ml')
 await page.getByRole('button',{name:'Functions'}).click()
 await expect(page.locator('#role-0-context')).toHaveValue('Anhydrous solid stick')
 await expect(page.getByLabel(new RegExp(evidenceTitle))).toBeChecked()
 await page.getByRole('button',{name:'Compatibility'}).click()
 await expect(page.locator('#compatibility-0-target')).toHaveValue(targetId)
 await expect(page.getByLabel(new RegExp(evidenceTitle))).toBeChecked()
 await page.getByRole('button',{name:'Evidence'}).click()
 await page.getByRole('button',{name:new RegExp(`Delete evidence ${evidenceTitle}`)}).click()
 await expect(page.getByText(/Remove links from 1 Role and 1 Compatibility/)).toBeVisible()
 await page.getByRole('button',{name:'Functions'}).click()
 await page.getByLabel(new RegExp(evidenceTitle)).uncheck()
 await page.getByRole('button',{name:'Compatibility'}).click()
 await page.getByLabel(new RegExp(evidenceTitle)).uncheck()
 await page.getByRole('button',{name:'Evidence'}).click()
 await page.getByRole('button',{name:new RegExp(`Delete evidence ${evidenceTitle}`)}).click()
 await expect(page.getByRole('button',{name:new RegExp(`Delete evidence ${evidenceTitle}`)})).toHaveCount(0)
 await page.getByRole('button',{name:'Save knowledge'}).click()
 await expect(page.getByText(/^Saved\./)).toBeVisible()
 await page.reload()
 await page.getByRole('button',{name:'Evidence'}).click()
 await expect(page.getByText(evidenceTitle)).toHaveCount(0)
 await page.getByRole('button',{name:'Functions'}).click()
 await expect(page.locator('#role-0-context')).toHaveValue('Anhydrous solid stick')
 await page.getByRole('button',{name:'Compatibility'}).click()
 await expect(page.locator('#compatibility-0-target')).toHaveValue(targetId)
 await assertNoOperationalWrites(operationalBaseline)
})

test('validation failure retains values and deliberate discard abandons them',async({page})=>{
 await signIn(page)
 const id=await createIngredient(page,unique('Validation current'))
 await openKnowledge(page,id)
 await page.getByRole('button',{name:'Physical'}).click()
 await page.locator('#physical-density-state').selectOption('known')
 await page.locator('#physical-density-value').fill('1.2')
 await page.getByRole('button',{name:'Save knowledge'}).click()
 await expect(page.getByText(/^Not saved\./)).toBeVisible()
 await expect(page.locator('.form-error[role="alert"]')).toContainText('Review the highlighted fields')
 await expect(page.locator('#physical-density-error')).toContainText('require a unit')
 await expect(page.locator('#physical-density-state')).toHaveAttribute('aria-describedby','physical-density-error')
 await expect(page.locator('#physical-density-state')).toBeFocused()
 await expect(page.locator('#physical-density-value')).toHaveValue('1.2')
 await page.locator('#physical-density-unit').fill('g/ml')
 await page.getByRole('link',{name:'Dashboard',exact:true}).click()
 await page.getByRole('button',{name:'Discard changes and leave'}).click()
 await expect(page).toHaveURL('/')
 await openKnowledge(page,id)
 await page.getByRole('button',{name:'Physical'}).click()
 await expect(page.locator('#physical-density-state')).toHaveValue('unknown')
})

test('@stale real two-page stale conflict preserves local and remote state',async({browser})=>{
 const contextA=await browser.newContext(),contextB=await browser.newContext()
 const pageA=await contextA.newPage(),pageB=await contextB.newPage()
 try{
  await signIn(pageA)
  const id=await createIngredient(pageA,unique('Stale current'))
  await openKnowledge(pageA,id)
  await pageA.getByRole('button',{name:'Identity'}).click()
  await pageA.locator('#identity-inci-state').selectOption('known')
  await pageA.locator('#identity-inci-value').fill('BASELINE')
  await pageA.locator('#identity-inci-confidence').selectOption('supported')
  await pageA.getByRole('button',{name:'Save knowledge'}).click()
  await expect(pageA.getByText(/^Saved\./)).toBeVisible()
  await signIn(pageB)
  await openKnowledge(pageB,id)
  await pageB.getByRole('button',{name:'Identity'}).click()
  await pageA.locator('#identity-inci-value').fill('REMOTE A')
  await pageA.getByRole('button',{name:'Save knowledge'}).click()
  await expect(pageA.getByText(/^Saved\./)).toBeVisible()
  await pageB.locator('#identity-inci-value').fill('LOCAL B')
  await pageB.getByRole('button',{name:'Save knowledge'}).click()
  await expect(pageB.getByText(/^Stale-write conflict\./)).toBeVisible()
  await expect(pageB.getByText('Remote change detected')).toBeVisible()
  await expect(pageB.locator('#identity-inci-value')).toHaveValue('LOCAL B')
  await expect(pageB.getByText(/sql|postgres|stack trace|service role/i)).toHaveCount(0)
  await pageB.getByRole('link',{name:'Dashboard',exact:true}).click()
  await expect(pageB.getByRole('dialog',{name:'Leave without saving?'})).toBeVisible()
  await pageB.getByRole('button',{name:'Discard changes and leave'}).click()
  await openKnowledge(pageB,id)
  await pageB.getByRole('button',{name:'Identity'}).click()
  await expect(pageB.locator('#identity-inci-value')).toHaveValue('REMOTE A')
 }finally{await contextA.close();await contextB.close()}
})
