import{expect,test}from'@playwright/test'
import{addCompatibility,addEvidence,addRole,createIngredient,openKnowledge,owner,signIn}from'./ingredientKnowledge.helpers'

test('authenticated 390 px critical aggregate interaction',async({page})=>{
 expect(page.viewportSize()).toEqual({width:390,height:844})
 await signIn(page)
 const suffix=owner().runId.slice(0,8),currentId=await createIngredient(page,`Mobile current ${suffix}`),targetId=await createIngredient(page,`Mobile target ${suffix}`,'SIMMONDSIA CHINENSIS SEED OIL'),evidenceTitle=`Mobile evidence with a deliberately long wrapping title ${suffix}`
 await openKnowledge(page,currentId)
 await page.getByRole('button',{name:'Identity'}).click()
 await page.locator('#identity-inci-state').selectOption('known')
 await page.locator('#identity-inci-value').fill('CERA ALBA MOBILE')
 await page.getByRole('button',{name:'Physical'}).click()
 await page.locator('#physical-density-state').selectOption('known')
 await page.locator('#physical-density-value').fill('0.95')
 await page.locator('#physical-density-unit').fill('g/ml')
 await addEvidence(page,evidenceTitle)
 await addRole(page,evidenceTitle)
 await addCompatibility(page,targetId,evidenceTitle)
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true)
 await page.getByRole('button',{name:'Open navigation'}).click()
 await page.getByRole('link',{name:'Dashboard',exact:true}).click()
 const dialog=page.getByRole('dialog',{name:'Leave without saving?'})
 await expect(dialog).toBeVisible()
 await expect(dialog).toBeInViewport()
 await expect(page.getByRole('button',{name:'Stay and continue editing'})).toBeInViewport()
 await expect(page.getByRole('button',{name:'Discard changes and leave'})).toBeInViewport()
 await page.getByRole('button',{name:'Stay and continue editing'}).click()
 await page.getByRole('button',{name:'Save knowledge'}).click()
 await expect(page.getByText(/^Saved\./)).toBeVisible()
 await page.reload()
 await page.getByRole('button',{name:'Functions'}).click()
 await expect(page.getByLabel(new RegExp(evidenceTitle))).toBeChecked()
 await page.getByRole('button',{name:'Compatibility'}).click()
 await expect(page.getByLabel(new RegExp(evidenceTitle))).toBeChecked()
 await page.getByRole('button',{name:'Evidence'}).click()
 const deletion=page.getByRole('button',{name:new RegExp(`Delete evidence ${evidenceTitle}`)})
 await deletion.scrollIntoViewIfNeeded()
 await expect(deletion).toBeInViewport()
 await deletion.click()
 await expect(page.getByText(/Remove links from 1 Role and 1 Compatibility/)).toBeVisible()
 await expect(page.getByRole('button',{name:'Open navigation'})).toBeVisible()
 await page.getByRole('button',{name:'Open navigation'}).click()
 await expect(page.getByRole('navigation',{name:'Primary navigation'})).toBeVisible()
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true)
})
