import{expect,test}from'@playwright/test'
import{signIn}from'./ingredientKnowledge.helpers'

test('owner creates a procurement request and requested item without placing an order',async({page})=>{
 await signIn(page)
 await page.goto('/procurement')
 await expect(page.getByRole('heading',{name:'Procurement'})).toBeVisible()
 await expect(page.getByText(/never places orders or makes payments/i)).toBeVisible()
 const title=`E2E pilot materials ${Date.now()}`
 await page.getByRole('button',{name:'New request'}).click()
 const requestForm=page.locator('form.procurement-request-form')
 await requestForm.getByLabel('Request title').fill(title)
 await requestForm.getByLabel('Category').fill('raw_material')
 await requestForm.getByLabel('Priority').selectOption('high')
 await page.getByRole('button',{name:'Save request'}).click()
 await page.getByRole('link',{name:new RegExp(title)}).click()
 await expect(page.getByRole('heading',{name:title})).toBeVisible()
 await page.getByRole('button',{name:'Add requested item'}).click()
 const itemForm=page.locator('form.procurement-detail-form')
 await itemForm.getByLabel('Name').fill('Jojoba oil')
 await itemForm.getByLabel('Category').fill('carrier_oil')
 await itemForm.getByLabel('Quantity').fill('2500')
 await itemForm.getByLabel('Unit').fill('ml')
 await itemForm.getByLabel('Required specifications').fill('Cosmetic grade\nCOA preferred')
 await page.getByRole('button',{name:'Save item'}).click()
 await expect(page.getByRole('heading',{name:'Jojoba oil'})).toBeVisible()
 await expect(page.getByText('No offers recorded. Unknown values are expected during early research.')).toBeVisible()
 await expect(page.getByText('No recommendation yet')).toBeVisible()
 await expect(page.getByText('ordered',{exact:true})).toBeVisible()
 await expect(page.getByRole('button',{name:/Move to ordered/})).toHaveCount(0)
 await page.getByRole('button',{name:'Start research'}).click()
 await expect(page.getByText(/2 results · 2 awaiting review/)).toBeVisible()
 const candidates=page.locator('.candidate-inbox article')
 await expect(candidates).toHaveCount(2)
 await candidates.locator('button:not([disabled])').filter({hasText:'Accept'}).click()
 await expect(candidates).toHaveCount(1)
 await candidates.first().getByRole('button',{name:'Reject'}).click()
 await expect(page.getByText(/all reviewable candidates are processed|No candidates awaiting review/)).toBeVisible()
 await expect(page.getByText(/Nordic Lab Materials/)).toBeVisible()

 await page.route('**/functions/v1/procurement-live-research',async route=>{
  expect(route.request().headers().authorization).toMatch(/^Bearer [^\s]+$/)
  await route.fulfill({status:202,contentType:'application/json',body:JSON.stringify({accepted:true,status:'running'})})
 })
 await page.getByLabel('Provider').selectOption('live')
 await page.getByLabel('I understand live research sends this request to an approved external provider. Results may be incomplete and require review.').check()
 await page.getByRole('button',{name:'Start research'}).click()
 await expect(page.locator('.research-job').getByText('Live web research')).toBeVisible()
 await expect(page.locator('.research-job').getByText('running',{exact:true})).toBeVisible()
 await expect(page.getByText(/resp_|provider operation/i)).toHaveCount(0)
})
