import{expect,test}from'@playwright/test'
import{signIn}from'./ingredientKnowledge.helpers'
import{seedCommercialProvenanceFixture}from'./procurementCommercialProvenance.helpers'

test('owner creates, reads back and recommends a Supplier Product-linked Offer',async({page})=>{
 const fixture=await seedCommercialProvenanceFixture('Desktop')
 await signIn(page)
 await page.goto(`/procurement/${fixture.requestId}`)
 await page.getByRole('button',{name:'Add offer'}).click()

 const supplier=page.getByRole('combobox',{name:'Supplier',exact:true}),source=page.getByRole('combobox',{name:/^Supplier Product source, optional/})
 await supplier.focus()
 await expect(supplier).toBeFocused()
 await supplier.selectOption(fixture.supplierId)
 await page.keyboard.press('Tab')
 await expect(source).toBeFocused()
 await source.selectOption(`raw_material:${fixture.sourceId}`)

 const sourceIdentity=page.getByRole('region',{name:'Selected Supplier Product identity'})
 await expect(sourceIdentity).toContainText(fixture.productName)
 await expect(sourceIdentity).toContainText(fixture.supplierName)
 await expect(sourceIdentity).toContainText(fixture.sku)
 await expect(sourceIdentity).toContainText(fixture.sourceId)
 await expect(page.getByLabel('Package quantity')).toHaveValue('1')
 await expect(page.getByLabel('Item price')).toHaveValue('249')

 const observedTitle=`${fixture.productName} — checked snapshot`
 await page.getByLabel('Product title').fill(observedTitle)
 await page.getByLabel('Shipping cost').fill('79')
 await page.getByLabel('Stock').selectOption('in_stock')
 await expect(page.getByRole('region',{name:'Offer review summary'})).toContainText(observedTitle)
 let offerCreateRequests=0
 page.on('request',request=>{if(request.method()==='POST'&&request.url().includes('/rest/v1/procurement_supplier_offers'))offerCreateRequests+=1})
 await page.getByRole('button',{name:'Confirm and save Offer'}).evaluate(button=>{button.click();button.click()})

 const receipt=page.getByTestId('operation-receipt').filter({hasText:'procurement supplier offer'})
 await expect(receipt).toBeVisible()
 expect(offerCreateRequests).toBe(1)
 await expect(receipt).toContainText(fixture.sourceId)
 const persistedSource=page.getByTestId('offer-source-identity').filter({hasText:fixture.sourceId})
 await expect(persistedSource).toContainText(fixture.productName)
 await expect(page.getByRole('link',{name:observedTitle})).toBeVisible()

 await page.reload()
 await expect(page.getByTestId('offer-source-identity').filter({hasText:fixture.sourceId})).toContainText(fixture.productName)
 await page.getByRole('button',{name:'Record recommendation'}).click()
 const recommendation=page.locator('form.inline-recommendation')
 await recommendation.getByLabel('Summary').fill('Owner-reviewed linked source')
 await recommendation.getByLabel('Purchase quantity').fill('2')
 await recommendation.getByLabel('Rationale').fill('Canonical source and dated Offer snapshot reviewed.')
 await recommendation.getByRole('button',{name:'Save recommendation'}).click()
 await expect(page.getByRole('heading',{name:'Owner-reviewed linked source'})).toBeVisible()
})

test('failed Offer persistence preserves every entered value and emits no receipt',async({page})=>{
 const fixture=await seedCommercialProvenanceFixture('Failed persistence')
 await signIn(page)
 await page.goto(`/procurement/${fixture.requestId}`)
 await page.getByRole('button',{name:'Add offer'}).click()
 await page.getByRole('combobox',{name:'Supplier',exact:true}).selectOption(fixture.supplierId)
 await page.getByRole('combobox',{name:/^Supplier Product source, optional/}).selectOption(`raw_material:${fixture.sourceId}`)

 const entered={title:`${fixture.productName} — retry intact`,url:'https://example.test/retry-intact',country:'SE',quantity:'3.5',unit:'kg',price:'333.5',currency:'SEK',moq:'4',shipping:'55',tax:'12',delivery:'8',claims:'Organic, unverified',discount:'15',date:'2026-08-01',notes:'Preserve this dated observation for retry.'}
 await page.getByLabel('Product title').fill(entered.title)
 await page.getByLabel('Product URL').fill(entered.url)
 await page.getByLabel('Country').fill(entered.country)
 await page.getByLabel('Package quantity').fill(entered.quantity)
 await page.getByLabel('Package unit').fill(entered.unit)
 await page.getByLabel('Item price').fill(entered.price)
 await page.getByLabel('Currency').fill(entered.currency)
 await page.getByLabel('MOQ (packages)').fill(entered.moq)
 await page.getByLabel('Shipping cost').fill(entered.shipping)
 await page.getByLabel('Tax/duty estimate').fill(entered.tax)
 await page.getByLabel('Delivery estimate (days)').fill(entered.delivery)
 await page.getByLabel('Stock').selectOption('limited')
 await page.getByLabel('COA').selectOption('available')
 await page.getByLabel('SDS').selectOption('partial')
 await page.getByLabel('Technical documents').selectOption('unavailable')
 await page.getByLabel('Organic/certification claims').fill(entered.claims)
 await page.getByLabel('First-order discount').fill(entered.discount)
 await page.getByLabel('Date checked').fill(entered.date)
 await page.getByLabel('Confidence').selectOption('high')
 await page.getByLabel('Notes').fill(entered.notes)
 await page.route('**/rest/v1/procurement_supplier_offers*',async route=>{if(route.request().method()==='POST')await route.abort('failed');else await route.continue()})
 await page.getByRole('button',{name:'Confirm and save Offer'}).click()

 await expect(page.getByRole('alert')).toBeVisible()
 await expect(page.getByTestId('operation-receipt')).toHaveCount(0)
 await expect(page.getByRole('combobox',{name:'Supplier',exact:true})).toHaveValue(fixture.supplierId)
 await expect(page.getByRole('combobox',{name:/^Supplier Product source, optional/})).toHaveValue(`raw_material:${fixture.sourceId}`)
 await expect(page.getByLabel('Product title')).toHaveValue(entered.title)
 await expect(page.getByLabel('Product URL')).toHaveValue(entered.url)
 await expect(page.getByLabel('Country')).toHaveValue(entered.country)
 await expect(page.getByLabel('Package quantity')).toHaveValue(entered.quantity)
 await expect(page.getByLabel('Package unit')).toHaveValue(entered.unit)
 await expect(page.getByLabel('Item price')).toHaveValue(entered.price)
 await expect(page.getByLabel('Currency')).toHaveValue(entered.currency)
 await expect(page.getByLabel('MOQ (packages)')).toHaveValue(entered.moq)
 await expect(page.getByLabel('Shipping cost')).toHaveValue(entered.shipping)
 await expect(page.getByLabel('Tax/duty estimate')).toHaveValue(entered.tax)
 await expect(page.getByLabel('Delivery estimate (days)')).toHaveValue(entered.delivery)
 await expect(page.getByLabel('Stock')).toHaveValue('limited')
 await expect(page.getByLabel('COA')).toHaveValue('available')
 await expect(page.getByLabel('SDS')).toHaveValue('partial')
 await expect(page.getByLabel('Technical documents')).toHaveValue('unavailable')
 await expect(page.getByLabel('Organic/certification claims')).toHaveValue(entered.claims)
 await expect(page.getByLabel('First-order discount')).toHaveValue(entered.discount)
 await expect(page.getByLabel('Date checked')).toHaveValue(entered.date)
 await expect(page.getByLabel('Confidence')).toHaveValue('high')
 await expect(page.getByLabel('Notes')).toHaveValue(entered.notes)
 await expect(page.getByRole('region',{name:'Selected Supplier Product identity'})).toContainText(fixture.sku)
 await expect(page.getByRole('button',{name:'Confirm and save Offer'})).toBeEnabled()
})
