import { expect, test } from '@playwright/test'
import { signIn } from './ingredientKnowledge.helpers'

test('Suppliers owns the single supplier selection and profile edit flow', async ({ page }) => {
  await signIn(page)
  await page.goto('/suppliers')

  await expect(page.getByRole('heading', { name: 'Suppliers', exact: true })).toBeVisible()
  await expect(page.getByText(/canonical home for supplier identity/i)).toBeVisible()

  const supplierName = `Shell supplier ${Date.now()}`
  await page.getByRole('button', { name: 'New supplier' }).click()
  const createForm = page.locator('form.supplier-create')
  await createForm.getByLabel('Legal name').fill(supplierName)
  await createForm.getByLabel('Type').selectOption('raw_material')
  await createForm.getByRole('button', { name: 'Create supplier' }).click()

  await expect(page.getByRole('button', { name: new RegExp(supplierName) })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('heading', { name: 'Supplier intelligence' })).toBeVisible()
  await expect(page.locator('.supplier-intelligence').getByText(supplierName, { exact: true })).toBeVisible()
  await expect(page.locator('.supplier-intelligence').getByText('Country unknown', { exact: false })).toBeVisible()
  await expect(page.locator('.supplier-intelligence').getByText('Unknown', { exact: true }).first()).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Commercial Terms & Shipping' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Commercial terms', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Shipping rules' })).toBeVisible()
  await expect(page.locator('.supplier-commercial-workspace').getByLabel('Supplier')).toHaveCount(0)
  await expect(page.getByText('No saved discounts')).toBeVisible()
  await expect(page.getByText('No saved shipping rules')).toBeVisible()

  await page.getByRole('button', { name: 'Add discount' }).click()
  const discountForm = page.locator('.supplier-commercial-workspace form').filter({ hasText: 'Add discount' })
  await discountForm.getByLabel('Name').fill('Verified welcome offer')
  await discountForm.getByLabel('Percentage', { exact: true }).fill('5')
  await discountForm.getByLabel('Code').fill('5KORTING')
  await discountForm.getByLabel('First order only').check()
  await discountForm.getByRole('button', { name: 'Save discount' }).click()
  await expect(page.getByText('Verified welcome offer')).toBeVisible()
  await page.reload()
  await expect(page.getByText('Verified welcome offer')).toBeVisible()
  await expect(page.getByText(/5% · Code 5KORTING · First order only/)).toBeVisible()

  await page.getByRole('button', { name: 'Add shipping rule' }).click()
  const shippingForm = page.locator('.supplier-commercial-workspace form').filter({ hasText: 'Add shipping rule' })
  await shippingForm.getByLabel('Country').fill('NO')
  await shippingForm.getByLabel('Currency').fill('EUR')
  await shippingForm.getByLabel('VAT handling').selectOption('unknown')
  await shippingForm.getByLabel('Customs / duty handling').selectOption('unknown')
  await shippingForm.getByRole('button', { name: 'Save shipping rule' }).click()
  await expect(page.getByText(/Shipping Unknown · Tax Unknown · Duty Unknown/)).toBeVisible()
  await page.reload()
  await expect(page.getByText(/Shipping Unknown · Tax Unknown · Duty Unknown/)).toBeVisible()
  await expect(page.getByText(/VAT unknown · Customs \/ duty unknown/)).toBeVisible()

  await page.getByRole('button', { name: 'Edit supplier profile' }).click()
  await expect(page.getByRole('heading', { name: 'Edit supplier profile' })).toBeVisible()
  await expect(page.locator('.supplier-intelligence').getByText(supplierName, { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Cancel' }).click()
  await expect(page.locator('.supplier-intelligence').getByText(supplierName, { exact: true })).toBeVisible()

  await page.goto('/procurement')
  await expect(page.getByRole('heading', { name: 'Procurement' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Supplier intelligence' })).toHaveCount(0)
  await expect(page.locator('.purchasing-intelligence')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Cart scenarios' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Add discount' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Add shipping rule' })).toHaveCount(0)
})
