import { expect, test, type Locator } from '@playwright/test'
import { signIn } from './ingredientKnowledge.helpers'

async function fillPrintingSupplier(form: Locator, supplierName: string) {
  await form.getByLabel('Legal name').fill(supplierName)
  await form.getByLabel('Supplier type').selectOption('printing')
  await form.getByLabel('Website').fill('https://www.avery.no')
  await form.getByLabel('Country').fill('NO')
  await form.getByLabel('Default currency').fill('NOK')
  await expect(form.getByLabel('Status')).toHaveValue('research')
  await expect(form.getByLabel('Verification state')).toHaveValue('unknown')
  await expect(form.getByLabel('Preferred Supplier')).not.toBeChecked()
}

test('Suppliers owns the single supplier selection and profile edit flow', async ({ page }) => {
  await signIn(page)
  await page.goto('/suppliers')

  await expect(page.getByRole('heading', { name: 'Suppliers', exact: true })).toBeVisible()
  await expect(page.getByText(/canonical home for supplier identity/i)).toBeVisible()

  const supplierName = `Shell supplier ${Date.now()}`
  await page.getByRole('button', { name: 'New supplier' }).click()
  const createForm = page.locator('form.supplier-create')
  await fillPrintingSupplier(createForm, supplierName)
  await expect(createForm.getByRole('heading', { name: 'Review before creating' })).toBeVisible()
  const review = createForm.locator('.supplier-create-review')
  await expect(review.getByText(supplierName, { exact: true })).toBeVisible()
  await expect(review.getByText('printing', { exact: true })).toBeVisible()
  await expect(review.getByText('NO', { exact: true })).toBeVisible()
  await expect(review.getByText('NOK', { exact: true })).toBeVisible()
  await expect(review.getByText('No', { exact: true })).toBeVisible()
  await createForm.getByRole('button', { name: 'Create supplier' }).click()

  const receipt = page.getByTestId('operation-receipt')
  await expect(receipt.getByText(/CREATE confirmed for supplier/i)).toBeVisible()
  const supplierId = await receipt.locator('dd').first().innerText()
  expect(supplierId).toBeTruthy()
  await expect(page.getByRole('button', { name: new RegExp(supplierName) })).toHaveAttribute('aria-pressed', 'true')
  expect(new URL(page.url()).searchParams.get('supplier')).toBe(supplierId)
  await page.reload()
  await expect(page.getByTestId('operation-receipt')).toHaveCount(0)
  await expect(page.getByRole('button', { name: new RegExp(supplierName) })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('heading', { name: 'Supplier intelligence' })).toBeVisible()
  await expect(page.locator('.supplier-intelligence').getByText(supplierName, { exact: true })).toBeVisible()
  await expect(page.locator('.supplier-intelligence').getByText(/NO · printing · NOK/)).toBeVisible()
  await expect(page.locator('.supplier-intelligence').getByText('Unknown', { exact: true }).first()).toBeVisible()
  await expect(page.getByRole('link', { name: 'Open supplier website' })).toHaveAttribute('href', 'https://www.avery.no')

  await page.getByRole('button', { name: 'New supplier' }).click()
  const duplicateForm = page.locator('form.supplier-create')
  await fillPrintingSupplier(duplicateForm, supplierName)
  await duplicateForm.getByRole('button', { name: 'Create supplier' }).click()
  const duplicateReceipt = duplicateForm.getByTestId('operation-receipt')
  await expect(duplicateReceipt.getByRole('alert')).toContainText(/duplicate|already exists|conflict/i)
  await expect(duplicateForm.getByLabel('Legal name')).toHaveValue(supplierName)
  await expect(duplicateForm.getByLabel('Supplier type')).toHaveValue('printing')
  await expect(duplicateForm.getByLabel('Website')).toHaveValue('https://www.avery.no')
  await duplicateForm.getByRole('button', { name: 'Cancel' }).click()

  await expect(page.getByRole('heading', { name: 'Commercial Terms & Shipping' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Commercial terms', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Shipping rules' })).toBeVisible()
  await expect(page.locator('.supplier-commercial-workspace').getByLabel('Supplier')).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Documentation' })).toBeVisible()
  await expect(page.locator('.supplier-documentation').getByLabel('Supplier')).toHaveCount(0)
  await expect(page.getByText('No structured document records')).toBeVisible()
  await page.getByRole('button', { name: 'Add document record' }).click()
  const documentForm=page.locator('.supplier-document-form')
  await documentForm.getByLabel('Document type').selectOption('coa')
  await documentForm.getByLabel('Capability').selectOption('available_on_request')
  await documentForm.getByLabel('Checked date').fill('2026-07-26')
  await documentForm.getByRole('button',{name:'Save document record'}).click()
  await expect(page.getByText('Available on request',{exact:true})).toBeVisible()
  await expect(page.getByText('Unverified',{exact:true})).toBeVisible()
  await expect(page.getByText('No current evidence link')).toBeVisible()
  await page.reload()
  await expect(page.getByText('Available on request',{exact:true})).toBeVisible()
  await expect(page.getByRole('heading',{name:'Reliability'})).toBeVisible()
  await expect(page.getByRole('heading',{name:'History',exact:true})).toBeVisible()
  await expect(page.locator('.supplier-history').getByLabel('Supplier')).toHaveCount(0)
  await expect(page.getByText('No history',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Add history event'}).click()
  const eventForm=page.locator('.supplier-event-form')
  await eventForm.getByLabel('Event type').selectOption('communication')
  await eventForm.getByLabel('Title').fill('Asked for dispatch timing')
  await eventForm.getByLabel('Description').fill('Email sent to supplier contact.')
  await eventForm.getByRole('button',{name:'Save history event'}).click()
  await expect(page.getByText('Asked for dispatch timing')).toBeVisible()
  await expect(page.getByText('Limited history')).toBeVisible()
  await page.reload()
  await expect(page.getByText('Asked for dispatch timing')).toBeVisible()
  await expect(page.getByText('No saved discounts')).toBeVisible()
  await expect(page.getByText('No saved shipping rules')).toBeVisible()

  await page.getByRole('button', { name: 'Add discount' }).click()
  const discountForm = page.locator('.supplier-commercial-workspace form').filter({ hasText: 'Add discount' })
  await discountForm.getByLabel('Name').fill('Verified welcome offer')
  await discountForm.getByLabel('Percentage', { exact: true }).fill('5')
  await discountForm.getByLabel('Code').fill('5KORTING')
  await discountForm.getByLabel('First order only').check()
  await discountForm.getByRole('button', { name: 'Save discount' }).click()
  await expect(page.getByText('Verified welcome offer')).toBeVisible()
  await page.reload()
  await expect(page.getByText('Verified welcome offer')).toBeVisible()
  await expect(page.getByText(/5% · Code 5KORTING · First order only/)).toBeVisible()

  await page.getByRole('button', { name: 'Add shipping rule' }).click()
  const shippingForm = page.locator('.supplier-commercial-workspace form').filter({ hasText: 'Add shipping rule' })
  await shippingForm.getByLabel('Country').fill('NO')
  await shippingForm.getByLabel('Currency').fill('EUR')
  await shippingForm.getByLabel('VAT handling').selectOption('unknown')
  await shippingForm.getByLabel('Customs / duty handling').selectOption('unknown')
  await shippingForm.getByRole('button', { name: 'Save shipping rule' }).click()
  await expect(page.getByText(/Shipping Unknown · Tax Unknown · Duty Unknown/)).toBeVisible()
  await page.reload()
  await expect(page.getByText(/Shipping Unknown · Tax Unknown · Duty Unknown/)).toBeVisible()
  await expect(page.getByText(/VAT unknown · Customs \/ duty unknown/)).toBeVisible()

  await page.getByRole('button', { name: 'Edit supplier profile' }).click()
  await expect(page.getByRole('heading', { name: 'Edit supplier profile' })).toBeVisible()
  await expect(page.locator('.supplier-intelligence').getByText(supplierName, { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Cancel' }).click()
  await expect(page.locator('.supplier-intelligence').getByText(supplierName, { exact: true })).toBeVisible()

  await page.goto('/procurement')
  await expect(page.getByRole('heading', { name: 'Procurement' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Supplier intelligence' })).toHaveCount(0)
  await expect(page.locator('.purchasing-intelligence')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Cart scenarios' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Add discount' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Add shipping rule' })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Documentation' })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'History', exact: true })).toHaveCount(0)
})
