import { describe, expect, it } from 'vitest'
import type { FormulaLine, Ingredient, InventoryLot, InventoryMovement, LabBatch, LabBatchAllocation, LabBatchLine, TestQuestion, TestResponse } from '../../../types/domain'
import { aggregateNumericResults, canTransitionBatch, completionWarnings, createBatchLines, generateBatchNumber, observationDueState, plannedQuantity, quantityVariance, validOptionalMeasurement, validateAllocation, yieldVariance } from './labLogic'
const ingredient:Ingredient={id:'i1',commonName:'Jojoba Oil',inciName:'Simmondsia Chinensis Seed Oil',category:'Oil',functions:['Emollient'],description:'',defaultUnit:'g',notes:'',status:'Active',createdAt:'',updatedAt:''}
const formulaLine:FormulaLine={id:'fl1',formulaVersionId:'v1',ingredientId:'i1',percentage:60,phase:'Phase A',sortOrder:1,notes:'Formula note'}
const lot:InventoryLot={id:'lot1',ingredientId:'i1',internalLotNumber:'LOT',receivedDate:'2026-01-01',openingQuantity:100,unit:'g',location:'Shelf',status:'Active',notes:'',createdAt:'',updatedAt:''}
const receipt:InventoryMovement={id:'m1',inventoryLotId:'lot1',type:'Receipt',quantity:100,unit:'g',reason:'Receipt',notes:'',occurredAt:'',createdAt:''}
const line:LabBatchLine={id:'line1',labBatchId:'batch1',formulaLineId:'fl1',ingredientId:'i1',ingredientNameSnapshot:'Jojoba Oil',phase:'Phase A',plannedPercentage:60,plannedQuantity:60,actualQuantity:60,unit:'g',notes:'',status:'Weighed'}
const batch:LabBatch={id:'batch1',batchNumber:'KF-BO-260714-01',productId:'p1',formulaId:'f1',formulaVersionId:'v1',status:'In Progress',plannedBatchSize:100,plannedBatchUnit:'g',createdAt:'',updatedAt:'',purpose:'Test',notes:'',summary:'',targetCharacteristics:''}
describe('batch creation and snapshots',()=>{it('generates unique daily batch numbers',()=>expect(generateBatchNumber('Signature Beard Oil',['KF-BO-260714-01'],new Date('2026-07-14T12:00:00'))).toBe('KF-BO-260714-02'));it('scales canonical percentages',()=>expect(plannedQuantity(12.5,500)).toBe(62.5));it('copies an execution snapshot independent from source records',()=>{let n=0;const lines=createBatchLines('b1',[formulaLine],[ingredient],100,'g',()=>`id${++n}`);expect(lines[0]).toMatchObject({ingredientNameSnapshot:'Jojoba Oil',plannedQuantity:60,plannedPercentage:60,phase:'Phase A'});ingredient.commonName='Changed later';formulaLine.percentage=20;expect(lines[0].ingredientNameSnapshot).toBe('Jojoba Oil');expect(lines[0].plannedPercentage).toBe(60)})})
describe('execution math and lifecycle',()=>{it('calculates quantity and yield variances',()=>{expect(quantityVariance(59.8,60)).toBe(-.2);expect(yieldVariance(96.4,100)).toEqual({amount:-3.6,percentage:-3.6})});it('keeps optional measurements absent and rejects invalid recorded values',()=>{expect(validOptionalMeasurement(undefined,{minimum:0})).toBe(true);expect(validOptionalMeasurement(0,{minimum:0})).toBe(true);expect(validOptionalMeasurement(-1,{minimum:0})).toBe(false);expect(validOptionalMeasurement(Number.NaN)).toBe(false);expect(validOptionalMeasurement(2.5,{minimum:0,integer:true})).toBe(false);expect(validOptionalMeasurement(-5)).toBe(true)});it('allows controlled transitions only',()=>{expect(canTransitionBatch('Planned','In Progress')).toBe(true);expect(canTransitionBatch('Completed','In Progress')).toBe(false);expect(canTransitionBatch('Aborted','Archived')).toBe(true)});it('surfaces completion warnings without forcing perfection',()=>expect(completionWarnings({...batch,actualYield:undefined},[line],[])).toEqual(expect.arrayContaining([expect.stringContaining('uncommitted'),expect.stringContaining('yield')])) )})
describe('lot allocation and consumption protection',()=>{it('supports multiple allocations for one line',()=>{const a1:LabBatchAllocation={id:'a1',labBatchLineId:'line1',inventoryLotId:'lot1',quantity:40,unit:'g'};const a2={...a1,id:'a2',quantity:20};expect(validateAllocation(line,a1,lot,[receipt])).toBeNull();expect(validateAllocation(line,a2,lot,[receipt])).toBeNull();expect(a1.quantity+a2.quantity).toBe(60)});it('blocks over-consumption',()=>{const allocation:LabBatchAllocation={id:'a',labBatchLineId:'line1',inventoryLotId:'lot1',quantity:101,unit:'g'};expect(validateAllocation(line,allocation,lot,[receipt])).toContain('exceeds')});it('blocks duplicate committed allocation',()=>{const allocation:LabBatchAllocation={id:'a',labBatchLineId:'line1',inventoryLotId:'lot1',quantity:10,unit:'g',inventoryMovementId:'movement'};expect(validateAllocation(line,allocation,lot,[receipt])).toContain('already')})})
describe('observations and testing',()=>{it('derives due states',()=>{const today=new Date('2026-07-14T12:00:00');expect(observationDueState('2026-07-13',undefined,today)).toBe('Overdue');expect(observationDueState('2026-07-15',undefined,today)).toBe('Due');expect(observationDueState('2026-08-01',undefined,today)).toBe('Upcoming');expect(observationDueState('2026-07-01','2026-07-01',today)).toBe('Completed')});it('aggregates numeric feedback without significance claims',()=>{const questions:TestQuestion[]=[{id:'q1',prompt:'Absorption',type:'Numeric Rating',sortOrder:1}];const responses:TestResponse[]=[{id:'r1',testSessionId:'s',testerId:'t',answers:[{questionId:'q1',value:4}],overallNotes:'',submittedAt:''},{id:'r2',testSessionId:'s',testerId:'t2',answers:[{questionId:'q1',value:2}],overallNotes:'',submittedAt:''}];expect(aggregateNumericResults(questions,responses)[0]).toMatchObject({average:3,count:2})})})
