import type { BatchProcessStep, FormulaLine, FormulaVersion, Ingredient, InventoryLot, InventoryMovement, InventoryUnit, LabBatch, LabBatchAllocation, LabBatchLine, LabBatchStatus, TestQuestion, TestResponse } from '../../../types/domain'
import { convertUnit, lotBalance } from '../../inventory/domain/inventoryLogic'

export const batchCode = (productName:string) => productName.split(/\s+/).filter((word)=>!['signature','original','daily','koalafrog'].includes(word.toLowerCase())).map((word)=>word[0]).join('').slice(0,2).toUpperCase() || 'LB'
export function generateBatchNumber(productName:string, existing:string[], date=new Date()){const stamp=`${String(date.getFullYear()).slice(-2)}${String(date.getMonth()+1).padStart(2,'0')}${String(date.getDate()).padStart(2,'0')}`;const prefix=`KF-${batchCode(productName)}-${stamp}-`;const next=Math.max(0,...existing.filter((n)=>n.startsWith(prefix)).map((n)=>Number(n.slice(prefix.length))||0))+1;return `${prefix}${String(next).padStart(2,'0')}`}
export const plannedQuantity=(percentage:number,size:number)=>Math.round(percentage*size/100*10000)/10000
export const quantityVariance=(actual:number|undefined,planned:number)=>actual==null?undefined:Math.round((actual-planned)*10000)/10000
export function yieldVariance(actual:number|undefined,planned:number){if(actual==null)return undefined;const amount=Math.round((actual-planned)*10000)/10000;return{amount,percentage:Math.round(amount/planned*10000)/100}}
export function validOptionalMeasurement(value:number|undefined,{minimum,integer=false}:{minimum?:number;integer?:boolean}={}){return value===undefined||(Number.isFinite(value)&&(minimum===undefined||value>=minimum)&&(!integer||Number.isInteger(value)))}
export function createBatchLines(batchId:string,formulaLines:FormulaLine[],ingredients:Ingredient[],size:number,unit:InventoryUnit,idFactory:()=>string=()=>crypto.randomUUID()):LabBatchLine[]{return [...formulaLines].sort((a,b)=>a.sortOrder-b.sortOrder).map((line)=>({id:idFactory(),labBatchId:batchId,formulaLineId:line.id,ingredientId:line.ingredientId,ingredientNameSnapshot:ingredients.find((i)=>i.id===line.ingredientId)?.commonName??'Unknown ingredient',phase:line.phase,plannedPercentage:line.percentage,plannedQuantity:plannedQuantity(line.percentage,size),unit,notes:line.notes,status:'Pending'}))}
export function createBatchProcessSteps(batchId:string,version:FormulaVersion,idFactory:()=>string=()=>crypto.randomUUID()):BatchProcessStep[]{if(version.manufacturingProcess?.length)return[...version.manufacturingProcess].sort((a,b)=>a.order-b.order).map(step=>({id:idFactory(),labBatchId:batchId,stepNumber:step.order,title:step.title,instruction:step.instruction,phaseCode:step.phaseCode,targetTemperature:step.targetTemperature,minimumTemperature:step.minimumTemperature,maximumTemperature:step.maximumTemperature,durationMinutes:step.durationMinutes,mixingMethod:step.mixingMethod,mixingIntensity:step.mixingIntensity,completionCriteria:step.completionCriteria,critical:step.critical,operatorNote:step.operatorNote,status:'Pending',notes:''}));return version.processInstructions?[{id:idFactory(),labBatchId:batchId,stepNumber:1,instruction:version.processInstructions,status:'Pending',notes:''}]:[]}
export const allowedBatchTransitions:Record<LabBatchStatus,LabBatchStatus[]>={'Planned':['In Progress','Aborted'],'In Progress':['Completed','Aborted'],'Completed':['Archived'],'Aborted':['Archived'],'Archived':[]}
export const canTransitionBatch=(from:LabBatchStatus,to:LabBatchStatus)=>allowedBatchTransitions[from].includes(to)
export function completionWarnings(batch:LabBatch,lines:LabBatchLine[],allocations:LabBatchAllocation[]){const warnings:string[]=[];const batchLines=lines.filter((l)=>l.labBatchId===batch.id);if(batchLines.some((l)=>l.status==='Pending'))warnings.push('Some ingredient lines are still pending.');if(batchLines.some((l)=>l.status==='Weighed'&&l.actualQuantity==null))warnings.push('Some weighed lines have no actual quantity.');if(batchLines.some((l)=>l.status==='Weighed'&&!allocations.some((a)=>a.labBatchLineId===l.id&&a.inventoryMovementId)))warnings.push('Some weighed quantities have uncommitted consumption.');if(batch.actualYield==null)warnings.push('Actual final yield has not been recorded.');return warnings}
export function validateAllocation(line:LabBatchLine,allocation:LabBatchAllocation,lot:InventoryLot,movements:InventoryMovement[]){if(allocation.inventoryMovementId)return 'This allocation has already been committed.';if(line.status!=='Weighed'||line.actualQuantity==null)return 'Record the actual weighed quantity before committing consumption.';if(lot.ingredientId!==line.ingredientId)return 'Selected lot belongs to another ingredient.';if(allocation.quantity<=0||!Number.isFinite(allocation.quantity))return 'Allocation quantity must be greater than zero.';const required=convertUnit(allocation.quantity,allocation.unit,lot.unit);if(required>lotBalance(lot,movements))return 'Allocation exceeds available lot stock.';return null}
export function observationDueState(targetDate:string|undefined,observedAt:string|undefined,today=new Date()):'Completed'|'Overdue'|'Due'|'Upcoming'|'Unscheduled'{if(observedAt)return'Completed';if(!targetDate)return'Unscheduled';const days=(new Date(`${targetDate}T12:00:00`).getTime()-today.getTime())/86400000;if(days<0)return'Overdue';if(days<=1)return'Due';return'Upcoming'}
export function aggregateNumericResults(questions:TestQuestion[],responses:TestResponse[]){return questions.filter((q)=>q.type==='Numeric Rating').map((q)=>{const values=responses.flatMap((r)=>r.answers.filter((a)=>a.questionId===q.id&&typeof a.value==='number').map((a)=>a.value as number));return{questionId:q.id,prompt:q.prompt,count:values.length,average:values.length?Math.round(values.reduce((a,b)=>a+b,0)/values.length*100)/100:undefined}})}
