import { useState } from 'react'
import type { Ingredient, InventoryUnit } from '../../../types/domain'
import { useFormulaData } from '../../formulas/state/FormulaDataContext'
import { cosingStatus, normalizeCosingFunctions } from '../domain/ingredientMetadata'

export function IngredientForm({ ingredient, onClose }: { ingredient?: Ingredient; onClose: () => void }) {
  const { createIngredient, updateIngredient } = useFormulaData(); const [error, setError] = useState(''),[saving,setSaving]=useState(false)
  const submit = async(event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget),status=String(form.get('cosingStatus')) as Ingredient['cosingVerificationStatus']; const input = { commonName:String(form.get('commonName')).trim(), inciName:String(form.get('inciName')).trim(), category:String(form.get('category')).trim(), functions:ingredient?.functions??[], cosingFunctions:normalizeCosingFunctions(String(form.get('cosingFunctions'))),cosingVerificationStatus:status,cosingVerifiedAt:String(form.get('cosingVerifiedAt')).trim()||undefined,cosingSourceReference:String(form.get('cosingSourceReference')).trim()||undefined, description:String(form.get('description')).trim(), defaultUnit:String(form.get('defaultUnit')) as InventoryUnit, reorderThreshold: Number(form.get('reorderThreshold')) || undefined, notes:String(form.get('notes')).trim(), status: (ingredient?.status ?? 'Active') as Ingredient['status'] }; if (!input.commonName || !input.inciName) return setError('Common and INCI names are required.');if(status==='verified_from_cosing'&&(!input.cosingFunctions.length||!input.cosingVerifiedAt))return setError('Verified CosIng metadata requires at least one function and a verification date.');setSaving(true);try{if (ingredient) updateIngredient(ingredient.id, input); else createIngredient(input); onClose()}catch(cause){setError(cause instanceof Error?cause.message:'Could not save Ingredient.')}finally{setSaving(false)} }
  return <div className="modal-backdrop"><form className="workspace-modal ingredient-form" onSubmit={event=>void submit(event)}><span className="eyebrow">Material identity</span><h2>{ingredient ? 'Edit ingredient' : 'Add ingredient'}</h2><div className="form-grid"><label>Common name<input name="commonName" defaultValue={ingredient?.commonName} required /></label><label>Exact INCI name<input name="inciName" defaultValue={ingredient?.inciName} required /></label><label>Category<input name="category" defaultValue={ingredient?.category} required /></label><label>Default unit<select name="defaultUnit" defaultValue={ingredient?.defaultUnit ?? 'g'}>{['mg','g','kg','ml','L','pcs'].map((v)=><option key={v}>{v}</option>)}</select></label><fieldset className="span-2 metadata-fieldset"><legend>CosIng functions</legend><p>Copy functions from the exact active CosIng ingredient entry. These informational database classifications do not constitute safety or regulatory approval.</p><label>Functions, comma separated<input name="cosingFunctions" defaultValue={ingredient?.cosingFunctions?.join(', ')} placeholder="FRAGRANCE, SKIN CONDITIONING, PERFUMING" /></label><div className="form-grid"><label>Verification status<select name="cosingStatus" defaultValue={ingredient?cosingStatus(ingredient):'unverified'}><option value="unverified">Unverified</option><option value="needs_review">Needs review</option><option value="verified_from_cosing">Verified from CosIng</option></select></label><label>Verification date<input name="cosingVerifiedAt" type="date" defaultValue={ingredient?.cosingVerifiedAt?.slice(0,10)}/></label></div><label>Source reference<input name="cosingSourceReference" defaultValue={ingredient?.cosingSourceReference} placeholder="INCI entry identifier, reference, or stable URL"/></label>{ingredient?.functions.length?<p className="legacy-metadata">Preserved legacy Functions — unverified: {ingredient.functions.join(', ')}</p>:null}</fieldset><label>Reorder threshold<input name="reorderThreshold" type="number" min="0" step="0.1" defaultValue={ingredient?.reorderThreshold} /></label><label className="span-2">Technical behaviour<textarea name="description" defaultValue={ingredient?.description} placeholder="Viscosity, absorption, colour, odour, sensory feel, stability and practical drawbacks."/></label><label className="span-2">Technical notes<textarea name="notes" defaultValue={ingredient?.notes}/></label></div>{error && <p className="form-error" role="alert">{error}</p>}<footer><button type="button" className="button ghost" disabled={saving} onClick={onClose}>Cancel</button><button className="button primary" disabled={saving}>{saving?'Saving…':'Save ingredient'}</button></footer></form></div>
}
