import { useState } from 'react'
import type { Ingredient, InventoryUnit } from '../../../types/domain'
import { useFormulaData } from '../../formulas/state/FormulaDataContext'

export function IngredientForm({ ingredient, onClose }: { ingredient?: Ingredient; onClose: () => void }) {
  const { createIngredient, updateIngredient } = useFormulaData(); const [error, setError] = useState('')
  const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const input = { commonName:String(form.get('commonName')).trim(), inciName:String(form.get('inciName')).trim(), category:String(form.get('category')).trim(), functions:String(form.get('functions')).split(',').map((v)=>v.trim()).filter(Boolean), description:String(form.get('description')).trim(), defaultUnit:String(form.get('defaultUnit')) as InventoryUnit, reorderThreshold: Number(form.get('reorderThreshold')) || undefined, notes:String(form.get('notes')).trim(), status: (ingredient?.status ?? 'Active') as Ingredient['status'] }; if (!input.commonName || !input.inciName) return setError('Common and INCI names are required.'); if (ingredient) updateIngredient(ingredient.id, input); else createIngredient(input); onClose() }
  return <div className="modal-backdrop"><form className="workspace-modal" onSubmit={submit}><span className="eyebrow">Material identity</span><h2>{ingredient ? 'Edit ingredient' : 'Add ingredient'}</h2><div className="form-grid"><label>Common name<input name="commonName" defaultValue={ingredient?.commonName} required /></label><label>INCI name<input name="inciName" defaultValue={ingredient?.inciName} required /></label><label>Category<input name="category" defaultValue={ingredient?.category} required /></label><label>Functions<input name="functions" defaultValue={ingredient?.functions.join(', ')} placeholder="Emollient, Antioxidant" /></label><label>Default unit<select name="defaultUnit" defaultValue={ingredient?.defaultUnit ?? 'g'}>{['g','kg','ml','L','pcs'].map((v)=><option key={v}>{v}</option>)}</select></label><label>Reorder threshold<input name="reorderThreshold" type="number" min="0" step="0.1" defaultValue={ingredient?.reorderThreshold} /></label><label className="span-2">Description<textarea name="description" defaultValue={ingredient?.description}/></label><label className="span-2">Notes<textarea name="notes" defaultValue={ingredient?.notes}/></label></div>{error && <p className="form-error">{error}</p>}<footer><button type="button" className="button ghost" onClick={onClose}>Cancel</button><button className="button primary">Save ingredient</button></footer></form></div>
}
