import{useState}from'react'
import type{InventoryUnit,OperationalReviewState,SupplierProduct,SupplierProductVerification}from'../../../types/domain'
import{useFormulaData}from'../../formulas/state/FormulaDataContext'
import{useProcurement}from'../../procurement/useProcurement'
import{emptySupplierProductVerification,gradeSuggestions,inheritedSupplierProductProfile,supplierProductCompletion}from'../domain/supplierProductIntelligence'

const units:InventoryUnit[]=['mg','g','kg','ml','L','pcs']
const states:OperationalReviewState[]=['unknown','needs_review','reviewed','not_applicable']
const checks:[keyof SupplierProductVerification,string][]=[['inci','INCI reviewed'],['supplierSpecification','Supplier specification reviewed'],['sds','SDS available'],['coa','CoA available'],['allergenInformation','Allergen information reviewed'],['shelfLife','Shelf life reviewed'],['origin','Origin reviewed'],['extractionMethod','Extraction method reviewed'],['processingMethod','Processing method reviewed'],['ifra','IFRA applicability reviewed'],['cosing','CosIng reviewed']]
const text=(form:FormData,key:string)=>String(form.get(key)??'').trim()
const labelFor=(value:string)=>value.replaceAll('_',' ').replace(/^\w/,letter=>letter.toUpperCase())

export function SupplierProductForm({ingredientId,product,onClose}:{ingredientId:string;product?:SupplierProduct;onClose:()=>void}){
 const{saveSupplierProduct,ingredients}=useFormulaData(),{data:procurement}=useProcurement(),ingredient=ingredients.find(x=>x.id===ingredientId)
 const inherited=ingredient?inheritedSupplierProductProfile(ingredient,product):undefined
 const verification={...emptySupplierProductVerification(),...product?.verification}
 const[advanced,setAdvanced]=useState(false),[error,setError]=useState('')
 const[supplierName,setSupplierName]=useState(product?.supplierName??''),[supplierId,setSupplierId]=useState(product?.supplierId??'')
 const[currency,setCurrency]=useState(product?.currency??'NOK'),[origin,setOrigin]=useState(product?.origin??product?.countryCode??'')
 const suppliers=procurement?.suppliers.filter(s=>!s.archived_at)??[]
 const chooseSupplier=(name:string)=>{setSupplierName(name);const supplier=suppliers.find(item=>name===item.legal_name||name===item.trading_name);setSupplierId(supplier?.id??'');if(supplier&&!product){if(currency==='NOK'&&supplier.default_currency)setCurrency(supplier.default_currency);if(!origin&&supplier.country_code)setOrigin(supplier.country_code)}}
 const[values,setValues]=useState({supplierName,productName:product?.productName,packageQuantity:product?.packageQuantity,packageUnit:product?.packageUnit??inherited?.defaultInventoryUnit,price:product?.price,currency,grade:product?.grade,supplierGrade:product?.supplierGrade,origin,shelfLifeMonths:product?.shelfLifeMonths,storageRequirements:product?.storageRequirements,operationalNotes:product?.operationalNotes,verification,status:product?.productStatus??'research',preferred:product?.isPreferred??false})
 const refreshPreview=(form:HTMLFormElement)=>{const data=new FormData(form);setValues({supplierName:text(data,'supplierName'),productName:text(data,'productName'),packageQuantity:Number(data.get('packageQuantity')),packageUnit:text(data,'packageUnit') as InventoryUnit,price:Number(data.get('price')),currency:text(data,'currency'),grade:text(data,'grade'),supplierGrade:text(data,'supplierGrade'),origin:text(data,'origin'),shelfLifeMonths:Number(data.get('shelfLifeMonths')),storageRequirements:text(data,'storageRequirements'),operationalNotes:text(data,'operationalNotes'),verification:Object.fromEntries(checks.map(([key])=>[key,text(data,`verification-${key}`)])) as unknown as SupplierProductVerification,status:text(data,'productStatus') as NonNullable<SupplierProduct['productStatus']>,preferred:Boolean(data.get('preferred'))})}
 const completion=supplierProductCompletion(values),suggestions=gradeSuggestions(ingredient?.category??product?.categorySnapshot??'')
 const submit=(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget),quantity=Number(form.get('packageQuantity')),price=Number(form.get('price')),shelf=Number(form.get('shelfLifeMonths'));if(!Number.isFinite(quantity)||quantity<=0||!Number.isFinite(price)||price<=0)return setError('Enter a valid package quantity and price.');const nextVerification={...verification};for(const[key]of checks)nextVerification[key]=text(form,`verification-${key}`) as OperationalReviewState;saveSupplierProduct({id:product?.id,ingredientId,supplierName,productName:text(form,'productName'),supplierSku:text(form,'supplierSku')||undefined,packageQuantity:quantity,packageUnit:text(form,'packageUnit') as InventoryUnit,price,currency:currency.toUpperCase(),productUrl:text(form,'productUrl')||undefined,grade:text(form,'grade')||undefined,supplierGrade:text(form,'supplierGrade')||undefined,declaredInci:text(form,'declaredInci')||undefined,categorySnapshot:text(form,'categorySnapshot')||undefined,defaultInventoryUnit:text(form,'defaultInventoryUnit') as InventoryUnit,cosingFunctionsSnapshot:ingredient?.cosingFunctions??product?.cosingFunctionsSnapshot??[],researchProfileSnapshot:text(form,'researchProfileSnapshot')||undefined,referenceEntryId:ingredient?.referenceEntryId??product?.referenceEntryId,countryCode:text(form,'countryCode').toUpperCase()||undefined,origin:origin||undefined,extractionMethod:text(form,'extractionMethod')||undefined,processingMethod:text(form,'processingMethod')||undefined,shelfLifeMonths:shelf>0?shelf:undefined,storageRequirements:text(form,'storageRequirements')||undefined,productStatus:text(form,'productStatus') as SupplierProduct['productStatus'],verification:nextVerification,operationalNotes:text(form,'operationalNotes'),verificationNotes:text(form,'verificationNotes'),notes:text(form,'notes'),isPreferred:Boolean(form.get('preferred')),supplierId:supplierId||undefined});onClose()}
 return <div className="modal-backdrop"><form className="workspace-modal supplier-product-form" onSubmit={submit} onInput={event=>refreshPreview(event.currentTarget)}><header className="supplier-product-form-header"><div><span className="eyebrow">Ingredient → purchasable source</span><h2>{product?'Edit':'Add'} Supplier Product</h2><p className="modal-intro">Quick Mode asks only for this purchasable source. Ingredient knowledge stays inherited.</p></div><button type="button" className="button ghost advanced-toggle" aria-expanded={advanced} aria-controls="supplier-product-advanced" onClick={()=>setAdvanced(value=>!value)}>{advanced?'Hide Advanced':'Show Advanced'}</button></header>

 <section className="supplier-form-card quick-fields" aria-label="Quick Mode essential fields"><div className="section-copy"><span className="eyebrow">Quick Mode</span><h3>Core and commercial information</h3><p>Enough to compare, prefer and later receive this source.</p></div><div className="form-grid">
 <label>Supplier<input name="supplierName" list="supplier-options" value={supplierName} onChange={event=>chooseSupplier(event.target.value)} required/><datalist id="supplier-options">{suppliers.map(s=><option key={s.id} value={s.trading_name||s.legal_name}/>)}</datalist></label>
 <label>Product name<input name="productName" defaultValue={product?.productName} required/></label>
 <label>Supplier SKU<input name="supplierSku" defaultValue={product?.supplierSku}/></label>
 <label>Package size<input name="packageQuantity" type="number" min="0.000001" step="any" defaultValue={product?.packageQuantity} required/></label>
 <label>Package unit<select name="packageUnit" defaultValue={product?.packageUnit??inherited?.defaultInventoryUnit??'g'}>{units.map(x=><option key={x}>{x}</option>)}</select></label>
 <label>Price<input name="price" type="number" min="0" step="0.01" defaultValue={product?.price} required/></label>
 <label>Currency<input name="currency" value={currency} onChange={event=>setCurrency(event.target.value)} required/></label>
 <label title="A broad product grade such as Refined or Organic. Custom values are accepted.">Grade <span className="field-help">?</span><input name="grade" list="grade-options" defaultValue={product?.grade}/><datalist id="grade-options">{suggestions.map(x=><option key={x}>{x}</option>)}</datalist><small>{ingredient?.category||'Ingredient'} suggestions; custom grades remain available.</small></label>
 <label title="The supplier's exact commercial grade, strength or catalogue description.">Supplier grade <span className="field-help">?</span><input name="supplierGrade" defaultValue={product?.supplierGrade}/></label>
 <label>Country of origin<input name="origin" value={origin} onChange={event=>setOrigin(event.target.value)}/></label>
 <label>Shelf life (months)<input name="shelfLifeMonths" type="number" min="1" step="1" defaultValue={product?.shelfLifeMonths}/></label>
 <label>Storage<input name="storageRequirements" defaultValue={product?.storageRequirements}/></label>
 <label title="An internal workflow state, never a regulatory or safety status.">Operational status <span className="field-help">?</span><select name="productStatus" defaultValue={product?.productStatus??'research'}>{['research','reviewing','verified_operational','inactive','discontinued'].map(x=><option key={x} value={x}>{labelFor(x)}</option>)}</select></label>
 <label className="span-2">Operational notes<textarea name="operationalNotes" defaultValue={product?.operationalNotes}/></label>
 <label className="check-label"><input name="preferred" type="checkbox" defaultChecked={product?.isPreferred}/>Preferred option</label>
 </div></section>

 <section className="supplier-inherited-card" aria-label="Inherited Ingredient information"><div><span className="eyebrow">Inherited from Ingredient</span><h3>{ingredient?.commonName??'Ingredient identity'}</h3><p>These values are already known and are not required again.</p></div><dl><div><dt>Botanical / INCI name</dt><dd>{ingredient?.inciName||'Not recorded'}</dd></div><div><dt>Category</dt><dd>{ingredient?.category||'Not recorded'}</dd></div><div><dt>Inventory unit</dt><dd>{ingredient?.defaultUnit||'Not recorded'}</dd></div><div><dt>Typical technical behaviour</dt><dd>{ingredient?.description||'Not recorded'}</dd></div><div><dt>Typical formula roles</dt><dd>{ingredient?.functions.length?ingredient.functions.join(' · '):'Not recorded'}</dd></div><div><dt>CosIng functions</dt><dd>{ingredient?.cosingFunctions?.length?ingredient.cosingFunctions.join(' · '):'Not recorded'}</dd></div><div><dt>Ingredient identity</dt><dd>{ingredient?.referenceEntryId?'Reference-linked':'Workspace Ingredient'}</dd></div></dl></section>

 {advanced&&<div id="supplier-product-advanced" className="supplier-product-advanced">
 <section className="supplier-form-card"><div className="section-copy"><span className="eyebrow">Advanced / identity overrides</span><h3>Supplier-specific technical identity</h3><p>Only override inherited knowledge when this exact Supplier Product differs.</p></div><div className="form-grid"><label title="Use only when the supplier declares a materially different or more specific INCI.">Declared INCI override <span className="field-help">?</span><input name="declaredInci" defaultValue={inherited?.declaredInci}/></label><label>Category override<input name="categorySnapshot" defaultValue={inherited?.categorySnapshot}/></label><label>Inventory unit override<select name="defaultInventoryUnit" defaultValue={inherited?.defaultInventoryUnit??'g'}>{units.map(x=><option key={x}>{x}</option>)}</select></label><label>Supplier country code<input name="countryCode" maxLength={2} defaultValue={product?.countryCode}/></label><label className="span-2">Research profile override<textarea name="researchProfileSnapshot" defaultValue={inherited?.researchProfileSnapshot}/></label></div></section>
 <section className="supplier-form-card"><div className="section-copy"><span className="eyebrow">Advanced / methods</span><h3>Extraction and processing</h3><p>Only record product-specific methods stated meaningfully by the supplier; general Ingredient knowledge remains inherited.</p></div><div className="form-grid"><label title="Only record product-specific extraction. General Ingredient knowledge is inherited.">Extraction <span className="field-help">?</span><input name="extractionMethod" defaultValue={product?.extractionMethod}/></label><label title="Only complete this when the supplier specifies a meaningful processing method.">Processing <span className="field-help">?</span><input name="processingMethod" defaultValue={product?.processingMethod}/></label><label className="span-2">Product URL<input name="productUrl" type="url" defaultValue={product?.productUrl}/></label></div></section>
 <section className="supplier-form-card"><div className="section-copy"><span className="eyebrow">Advanced / operational review</span><h3>Verification checklist</h3><p>Used to track documentation review. This is operational only and never regulatory approval, safety, compliance, efficacy or authority qualification.</p></div><div className="verification-grid">{checks.map(([key,label])=><label key={key}>{label}<select name={`verification-${key}`} defaultValue={verification[key]}>{states.map(x=><option key={x} value={x}>{labelFor(x)}</option>)}</select></label>)}</div></section>
 <section className="supplier-form-card"><div className="section-copy"><span className="eyebrow">Advanced / notes</span><h3>Supporting notes</h3><p>Use only for information not represented elsewhere. Legacy General Notes remain preserved.</p></div><div className="form-grid"><label className="span-2">Verification notes<textarea name="verificationNotes" defaultValue={product?.verificationNotes}/></label><label className="span-2">General notes<textarea name="notes" defaultValue={product?.notes}/></label></div></section>
 </div>}

 {!advanced&&<div hidden aria-hidden="true"><input name="declaredInci" defaultValue={inherited?.declaredInci}/><input name="categorySnapshot" defaultValue={inherited?.categorySnapshot}/><input name="defaultInventoryUnit" defaultValue={inherited?.defaultInventoryUnit}/><input name="countryCode" defaultValue={product?.countryCode}/><textarea name="researchProfileSnapshot" defaultValue={inherited?.researchProfileSnapshot}/><input name="extractionMethod" defaultValue={product?.extractionMethod}/><input name="processingMethod" defaultValue={product?.processingMethod}/><input name="productUrl" defaultValue={product?.productUrl}/>{checks.map(([key])=><input key={key} name={`verification-${key}`} defaultValue={verification[key]}/>)}<textarea name="verificationNotes" defaultValue={product?.verificationNotes}/><textarea name="notes" defaultValue={product?.notes}/></div>}

 <section className="supplier-save-preview" aria-label="Supplier Product summary preview"><div><span className="eyebrow">Before saving</span><h3>{values.productName||'Product name not entered'}</h3><p>{values.supplierName||'Supplier not entered'} · {values.packageQuantity||'—'} {values.packageUnit||''} · {values.price||'—'} {values.currency}</p><p>{values.grade||values.supplierGrade||'Grade not recorded'} · {values.origin||'Origin not recorded'} · {labelFor(values.status)}{values.preferred?' · Preferred':''}</p></div><div className="supplier-progress" aria-label="Optional completion status">{Object.entries(completion).map(([key,value])=><div key={key}><span>{labelFor(key)}</span><strong>{value}%</strong><i><b style={{width:`${value}%`}}/></i></div>)}</div></section>
 <p className="completion-note">Completion is guidance only. This Supplier Product is usable without reaching 100%.</p>
 {error&&<p className="form-error" role="alert">{error}</p>}<footer><button type="button" className="button ghost" onClick={onClose}>Cancel</button><button className="button primary">Save Supplier Product</button></footer></form></div>
}
