import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'

describe('Beard Studio integration', () => {
  it('registers the grouped route and primary navigation without placeholders', () => {
    const app = readFileSync('src/app/App.tsx', 'utf8'), sidebar = readFileSync('src/components/layout/Sidebar.tsx', 'utf8')
    expect(app).toContain('path="grooming/beard-studio"')
    expect(app).toContain('path="trim"')
    expect(sidebar).toContain("to: '/grooming/beard-studio', label: 'Beard Studio'")
  })
  it('includes explicit narrow mobile safeguards and large Trim Mode targets', () => {
    const css = readFileSync('src/styles/index.css', 'utf8')
    expect(css).toContain('@media(max-width:410px)')
    expect(css).toContain('.touch-button{min-height:52px')
    expect(css).toContain('.page{overflow-x:hidden}')
    expect(css).toContain('@media(max-width:410px){.product-choice{grid-template-columns:1fr}')
  })
  it('reuses Koalafrog Products with explicit grooming usage roles', () => {
    const selector = readFileSync('src/features/beard-studio/components/GroomingProductSelector.tsx', 'utf8')
    expect(selector).toContain('useFormulaData')
    expect(selector).toContain('product.status !==')
    expect(selector).toContain('Usage role')
    expect(selector).toContain('No Koalafrog Products available')
  })
  it('keeps photo analysis explicit, reviewable, and separate from authoritative Beard data', () => {
    const flow = readFileSync('src/features/beard-studio/components/BeardPhotoAnalysisFlow.tsx', 'utf8')
    const support = readFileSync('src/features/beard-studio/components/BeardPhotoSupportDiagnosticPanel.tsx', 'utf8')
    const durableLookup = readFileSync('src/features/beard-studio/components/BeardAnalysisSupportLookup.tsx', 'utf8')
    const intelligence = readFileSync('src/features/beard-studio/components/BeardIntelligencePanel.tsx', 'utf8')
    expect(flow).toContain("front:'Front'")
    expect(flow).toContain('Left profile')
    expect(flow).toContain('Right profile')
    expect(flow).toContain('I confirm these photos contain my face and beard')
    expect(flow).toContain('Accept for planning')
    expect(flow).toContain('Dismiss')
    expect(flow).toContain('BeardPhotoSupportDiagnosticPanel')
    expect(support).toContain('Safe developer details')
    expect(support).not.toMatch(/providerOutput|resultPayload|imageUrl|signedUrl|prompt content/i)
    expect(intelligence).toContain('BeardAnalysisSupportLookup')
    expect(durableLookup).toContain("queryKey = 'beard-analysis-support'")
    expect(durableLookup).toContain('window.history.replaceState')
    expect(durableLookup).toContain('Reopen an analysis')
    expect(flow).not.toMatch(/saveBeardStudio|localStorage|workspace_records/)
  })
})
