/* eslint-disable react-hooks/set-state-in-effect -- authoritative source hydration initializes the review draft */
import { useEffect, useState } from 'react'
import { ArrowLeft, Save } from 'lucide-react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { useActiveWorkspace } from '../../platform/startup/ActiveWorkspaceContext'
import { loadKnowledge } from '../knowledge/data/knowledgeRepository'
import { developmentActions } from './actions/developmentExperimentActions'
import type { ExperimentPlan, ExperimentType } from './domain/developmentExperiment'
import { resolveIntelligenceSource, type ResolvedIntelligenceSource } from './intelligenceExperimentHandoff'
import { resolveProductTemplate } from '../product-studio/domain/formulationEngine'

export function ExperimentReviewPage(){
 const [params]=useSearchParams(),navigate=useNavigate(),workspace=useActiveWorkspace(),hasSource=!!params.get('runId')
 const linkedProductId=params.get('productId')||undefined,linkedFormulaVersionId=params.get('formulaVersionId')||undefined,resolvedTemplate=resolveProductTemplate(params.get('productType')??''),template=resolvedTemplate.ok?resolvedTemplate.value:undefined,isStructuredTemplate=!!template?.evaluationDimensions.length
 const [source,setSource]=useState<ResolvedIntelligenceSource>(),[sourceError,setSourceError]=useState(''),[loading,setLoading]=useState(hasSource)
 const processArchetype=template?.archetypeId==='anhydrous_multiphase'||template?.archetypeId==='solid_or_stick'
 const [sourceTitle,setTitle]=useState(hasSource?'':template?`${template.displayName} variant comparison`:'Untitled experiment'),[objective,setObjective]=useState(template?`Compare a controlled ${template.displayName} formulation or process change.`:''),[hypothesis,setHypothesis]=useState(''),[rationale,setRationale]=useState(''),[criteria,setCriteria]=useState(template?.evaluationDimensions.length?`Compare ${template.evaluationDimensions.join(', ')} using consistent observations.`:''),[saving,setSaving]=useState(false),[error,setError]=useState('')
 useEffect(()=>{if(!hasSource)return;if(!workspace){setSourceError('Canonical hosted workspace unavailable.');setLoading(false);return}let active=true;loadKnowledge(workspace.workspaceId).then(loaded=>resolveIntelligenceSource({workspaceId:params.get('workspaceId')??'',activeWorkspaceId:workspace.workspaceId,threadId:params.get('threadId')??'',runId:params.get('runId')??'',itemType:params.get('sourceItemType')??'',itemId:params.get('sourceItemId')??'',threads:loaded.threads,runs:loaded.runs})).then(resolved=>{if(!active)return;setSource(resolved);setTitle(resolved.name);setObjective(resolved.objective);setHypothesis(resolved.hypothesis);setSourceError('')}).catch(cause=>{if(active)setSourceError(cause instanceof Error?cause.message:'Source Intelligence suggestion unavailable.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[hasSource,params,workspace])
 const save=async()=>{if(hasSource&&!source){setError('A verified source suggestion is required.');return}setSaving(true);setError('');try{const variantId=crypto.randomUUID(),sourceType=source?.itemType;const plan:ExperimentPlan={title:sourceTitle,experimentType:(sourceType==='direction'?'scent_direction':processArchetype?'process_adjustment':'formula_adjustment')as ExperimentType,objective,hypothesis,productId:source?.productId??linkedProductId,baseFormulaVersionId:source?.formulaVersionId??linkedFormulaVersionId,sourceThreadId:hasSource?params.get('threadId')||undefined:undefined,sourceRunId:hasSource?params.get('runId')||undefined:undefined,sourceItemType:sourceType,sourceItemId:source?.itemId,userRationale:rationale,acceptanceCriteria:criteria,idempotencyKey:crypto.randomUUID(),variants:[{id:variantId,name:'Variant A',purpose:'First controlled trial',isControl:false,displayOrder:0,changes:(source?.changes??[]).map((change,index)=>({ingredientId:change.ingredientId,conceptMaterialName:change.ingredientId?undefined:change.materialName,changeType:change.action,qualitativeGuidance:change.guidance,rationale:change.reason,displayOrder:index}))}],observationPrompts:(isStructuredTemplate?template.evaluationDimensions:source?.observe??[]).map((prompt,index)=>({prompt,category:processArchetype?'physical':'scent',displayOrder:index,isRequired:true}))};const id=await developmentActions.create(plan);navigate(`/development/${id}`)}catch(cause){setError(cause instanceof Error?cause.message:'Experiment could not be saved.')}finally{setSaving(false)}}
 if(loading)return <section className="panel experiment-source-state"><h1>Verifying Intelligence suggestion…</h1><p>No Development record is being created.</p></section>
 if(sourceError)return <section className="panel experiment-source-state" role="alert"><h1>Experiment review unavailable</h1><p>{sourceError}</p><Link className="button ghost" to="/knowledge">Return to Knowledge</Link></section>
 return <div className="experiment-review"><Link className="back-link" to={hasSource?`/knowledge/intelligence/${params.get('threadId')}`:'/development'}><ArrowLeft size={14}/>{hasSource?'Intelligence thread':'Development'}</Link><header><span className="eyebrow">Review before persistence</span><h1>Review Experiment Plan</h1><p>No Development record exists until you press Save Experiment.</p></header><section className="panel experiment-form"><label>Title<input value={sourceTitle} onChange={event=>setTitle(event.target.value)}/></label><label>Objective<textarea value={objective} onChange={event=>setObjective(event.target.value)}/></label><label>Hypothesis<textarea value={hypothesis} onChange={event=>setHypothesis(event.target.value)}/></label><label>Your rationale<textarea value={rationale} onChange={event=>setRationale(event.target.value)}/></label><label>Acceptance criteria<textarea value={criteria} onChange={event=>setCriteria(event.target.value)}/></label><h2>Proposed changes</h2>{source?.changes.length?source.changes.map((change,index)=><p key={`${change.materialName}-${index}`}><strong>{change.action} {change.materialName}</strong> · {change.guidance} — {change.reason}</p>):<p>No quantitative changes were suggested. Refine this standalone plan after saving.</p>}{error&&<p role="alert">{error}</p>}<button className="button primary" disabled={saving||!sourceTitle.trim()||(!objective.trim()&&!hypothesis.trim())} onClick={save}><Save size={15}/>{saving?'Saving…':'Save Experiment'}</button></section></div>
}
