import { renderToStaticMarkup } from 'react-dom/server'
import { MemoryRouter } from 'react-router-dom'
import { describe, expect, it, vi } from 'vitest'
import { IntelligenceReport } from '../scent-house/ScentStudioPage'
import type { IntelligenceRunRecord, IntelligenceThreadRecord } from '../knowledge/domain/knowledge'
import type { IntelligenceResponse } from '../intelligence/domain/intelligenceContract'
import { buildExperimentReviewPath, resolveIntelligenceSource } from './intelligenceExperimentHandoff'

const report:IntelligenceResponse={schemaVersion:1,title:'Stored report',summary:'Summary',confidence:'medium',claims:[],scentProfile:{axes:{fresh:50,woody:50,spicy:50,dark:50,sweet:50,dry:50,warm:50,aromatic:50,smoky:50,leathery:50},dominantFamilies:[],opening:[],heart:[],base:[]},ingredientRoles:[],strengths:[],tensions:[],missingDimensions:[],directions:[{id:'direction-stable',name:'Stored direction',intent:'Stored objective',predictedEffect:'Stored prediction',tradeoffs:[],suggestedMaterials:[]}],experiments:[{id:'experiment-stable',name:'Stored experiment',hypothesis:'Stored hypothesis',changes:[],observe:['Stored checkpoint']}],questions:[],limitations:[]}
const thread:IntelligenceThreadRecord={id:'thread-1',mode:'scent_exploration',title:'Thread',created_at:'2026-01-01',updated_at:'2026-01-01'}
const run:IntelligenceRunRecord={id:'run-1',thread_id:thread.id,user_prompt:'Prompt',context_selection:{productId:'product-historical',formulaVersionId:'formula-historical'},context_manifest:{},response_payload:report,status:'completed',error_code:null,prompt_version:'v1',response_schema_version:1,context_version:1,provider_name:'openai',model_name:'model',input_tokens:null,output_tokens:null,total_tokens:null,cached_input_tokens:null,reasoning_tokens:null,estimated_cost_usd:null,pricing_snapshot_version:null,created_at:'2026-01-01',completed_at:'2026-01-01'}
const handoff={workspaceId:'workspace-1',threadId:thread.id,runId:run.id,productId:'product-historical',formulaVersionId:'formula-historical'}

describe('Intelligence-to-Experiment controls',()=>{
 it('renders Knowledge and Scent Studio actions for eligible directions and experiments',()=>{const html=renderToStaticMarkup(<MemoryRouter><IntelligenceReport report={report} handoff={handoff}/></MemoryRouter>);expect(html).toContain('Review direction as experiment');expect(html).toContain('Review suggested experiment')})
 it('passes exact workspace, thread, run, item, and historical context provenance',()=>{const path=buildExperimentReviewPath(handoff,'direction','direction-stable'),params=new URLSearchParams(path.split('?')[1]);expect(Object.fromEntries(params)).toMatchObject({workspaceId:'workspace-1',threadId:'thread-1',runId:'run-1',sourceItemType:'direction',sourceItemId:'direction-stable',productId:'product-historical',formulaVersionId:'formula-historical'})})
 it('building or rendering a Review action does not persist',()=>{const create=vi.fn();renderToStaticMarkup(<MemoryRouter><IntelligenceReport report={report} handoff={handoff}/></MemoryRouter>);buildExperimentReviewPath(handoff,'experiment','experiment-stable');expect(create).not.toHaveBeenCalled()})
 it('does not trust arbitrary rendered text and re-derives stored source content',()=>{const resolved=resolveIntelligenceSource({workspaceId:'workspace-1',activeWorkspaceId:'workspace-1',threadId:'thread-1',runId:'run-1',itemType:'experiment',itemId:'experiment-stable',threads:[thread],runs:[run]});expect(resolved).toMatchObject({name:'Stored experiment',hypothesis:'Stored hypothesis',productId:'product-historical',formulaVersionId:'formula-historical'});expect(buildExperimentReviewPath(handoff,'experiment','experiment-stable')).not.toContain('Stored+hypothesis')})
 it('renders a controlled state when stable item provenance is missing',()=>{const historical={...report,directions:[{...report.directions[0],id:''}]} as IntelligenceResponse,html=renderToStaticMarkup(<MemoryRouter><IntelligenceReport report={historical} handoff={handoff}/></MemoryRouter>);expect(html).toContain('historical suggestion does not contain complete stable provenance')})
 it('rejects another workspace owner and mismatched run/thread provenance',()=>{expect(()=>resolveIntelligenceSource({workspaceId:'other-workspace',activeWorkspaceId:'workspace-1',threadId:'thread-1',runId:'run-1',itemType:'direction',itemId:'direction-stable',threads:[thread],runs:[run]})).toThrow('workspace unavailable');expect(()=>resolveIntelligenceSource({workspaceId:'workspace-1',activeWorkspaceId:'workspace-1',threadId:'another-thread',runId:'run-1',itemType:'direction',itemId:'direction-stable',threads:[thread],runs:[run]})).toThrow('run unavailable')})
})
