import{describe,expect,it}from'vitest'
import type{FormulaVersion}from'../../../types/domain'
import{createBatchLines,createBatchProcessSteps}from'../../lab/domain/labLogic'
import{multiPhaseIssues,formulaTotalsExactly100}from'../../formulas/domain/multiPhaseLogic'
import{beardButterEvaluationFields,beardButterPhases,beardButterProcess,compareVariants,formulaPercentageTotal,orderedPhases,validEvaluationScore}from'./beardButter'

describe('Beard Butter multi-phase development',()=>{
 it('keeps phase order deterministic without requiring exactly three phases',()=>{expect(orderedPhases([beardButterPhases[2],beardButterPhases[0]]).map(x=>x.code)).toEqual(['A','C'])})
 it('uses a numeric tolerance for the 100 percent formula invariant',()=>{expect(formulaPercentageTotal([{percentage:72},{percentage:20},{percentage:8}])).toBe(100);expect(formulaTotalsExactly100([{percentage:33.3333},{percentage:33.3333},{percentage:33.3334}])).toBe(true);expect(formulaTotalsExactly100([{percentage:72},{percentage:20}])).toBe(false)})
 it('retains phase-aware lines and explicitly supplied process metadata in Lab handoff snapshots',()=>{const lines=createBatchLines('batch',[{id:'a',formulaVersionId:'v',ingredientId:'i',percentage:100,phase:'A',sortOrder:1,notes:''}],[{id:'i',commonName:'Butter',inciName:'BUTTER',category:'Butter',functions:[],description:'',defaultUnit:'g',notes:'',status:'Research',createdAt:'',updatedAt:''}],100,'g',()=> 'line');const process=beardButterProcess.map(step=>step.order===2?{...step,minimumTemperature:61,maximumTemperature:64,durationMinutes:8}:step);const version={id:'v',formulaId:'f',version:'v0.1',status:'Draft',description:'',targetCharacteristics:'',phaseDefinitions:beardButterPhases,manufacturingProcess:process,createdAt:'',updatedAt:''}as FormulaVersion,steps=createBatchProcessSteps('batch',version,(()=>{let n=0;return()=>`step-${++n}`})());expect(lines[0]).toMatchObject({phase:'A',plannedQuantity:100});expect(steps[1]).toMatchObject({stepNumber:2,phaseCode:'A',minimumTemperature:61,maximumTemperature:64,durationMinutes:8,critical:true});expect(steps.map(x=>x.stepNumber)).toEqual([1,2,3,4,5,6,7,8])})
 it('reports ambiguous phases, bad references, invalid ranges, ordering, and numeric values',()=>{const issues=multiPhaseIssues([{code:'A',name:'One',order:1,minimumTemperature:80,maximumTemperature:70},{code:'A',name:'Two',order:1}],[{phase:'missing',percentage:Number.NaN}],[{order:1,title:'One',instruction:'',phaseCode:'missing',durationMinutes:-1,critical:false},{order:1,title:'Two',instruction:'',critical:false}]);expect(issues).toEqual(expect.arrayContaining(['Phase codes must be unique.','Phase order values must be unique.','Phase A has an invalid temperature range.','Formula line references unknown phase missing.','Formula percentages must be finite values from 0 to 100.','Process step 1 references unknown phase missing.','Process step 1 has an invalid duration.','Process step order values must be unique.']))})
 it('keeps existing single-instruction and single-phase formulas valid',()=>{const version={id:'oil',formulaId:'f',version:'v1',status:'Draft',description:'',targetCharacteristics:'',processInstructions:'Blend at room temperature.',createdAt:'',updatedAt:''}as FormulaVersion;expect(createBatchProcessSteps('batch',version,()=> 'step')).toEqual([expect.objectContaining({stepNumber:1,instruction:'Blend at room temperature.'})])})
 it('compares variants with practical bounded numeric evaluation fields',()=>{const ranked=compareVariants([{id:'a',name:'More wax',changes:['Wax +2%'],evaluation:{overallResult:3}},{id:'b',name:'Controlled cooling',changes:['Slow cooling'],evaluation:{overallResult:5}}]);expect(ranked.map(x=>x.id)).toEqual(['b','a']);expect(beardButterEvaluationFields).toContain('graininess');expect(validEvaluationScore(1)).toBe(true);expect(validEvaluationScore(5)).toBe(true);expect(validEvaluationScore(0)).toBe(false);expect(validEvaluationScore(Number.POSITIVE_INFINITY)).toBe(false)})
})
