import type{KnowledgeConfidence,KnowledgeState,ProductStudioConcept}from'../../../types/domain'
import{benchmarkDeodorantConcept}from'./deodorantBenchmark'

export type BenchmarkScoreState='not_tested'|'unknown'|'not_applicable'|'scored'
export interface BenchmarkScore{state:BenchmarkScoreState;score?:number;notes:string}
export type TargetPriority='unreviewed'|'low'|'medium'|'high'|'critical'
export interface DevelopmentTarget{id:string;label:string;targetState:KnowledgeState;targetValue?:string;priority:TargetPriority;notes:string;evidenceSource:'development_brief';confidence:KnowledgeConfidence}
export interface DevelopmentConstraint{id:string;label:string;state:KnowledgeState;notes:string}
export interface SuccessCriterion{id:string;text:string;status:'suggestion'|'selected';notes:string}
export interface DevelopmentBrief{userNeed:string;intendedUse:string;intendedUser:string;usageContext:string;desiredPositioning:string;differentiation:string;constraints:DevelopmentConstraint[];targets:DevelopmentTarget[];successCriteria:SuccessCriterion[]}
export interface BenchmarkScorecard{evaluationDate?:string;evaluator:string;testContext:string;conditions:string;dataSource:'user_observation';notes:string;scores:Record<string,BenchmarkScore>;strongestCharacteristics:string;weakestCharacteristics:string;observations:string}
export interface SystemHypothesis{hypothesisText:string;physicalSystem:{state:KnowledgeState;value?:string};confidence:KnowledgeConfidence;evidenceSource:'internal_hypothesis'|'user_supplied_label';supportingObservations:string[];contradictingObservations:string[];openQuestions:string[];reviewStatus:'unreviewed'|'reviewed'|'needs_review';lastReviewedDate?:string}
export type RequirementStatus='required'|'optional'|'unresolved'
export type RequirementReviewStatus='not_reviewed'|'reviewed'|'research_needed'|'not_applicable'
export interface FunctionalRequirement{id:string;label:string;status:RequirementStatus;reviewStatus:RequirementReviewStatus;desiredOutcome:string;currentHypothesis:string;referenceCandidateIds:string[];rationale:string;evidenceSource:'internal_hypothesis'|'ingredient_knowledge'|'user_observation'|'unknown';confidence:KnowledgeConfidence;openQuestions:string}
export interface BenchmarkLabDocument{schemaVersion:1;projectStatus:'Idea'|'Play';workingTitle:string;productCategory:string;productFormat:string;benchmarkLink:{benchmarkId:string;role:'inspiration_performance_reference';sourceSnapshotId:string;notes:string};objective:string;brief:DevelopmentBrief;scorecard:BenchmarkScorecard;systemHypothesis:SystemHypothesis;functionalRequirements:FunctionalRequirement[];unresolvedAcknowledged:boolean}

export const scorecardDimensions=['firmness','glide','drag','payoff','ease of application','dry-down','tack','greasiness','residue','powderiness','skin comfort','transparency','colour','surface appearance','sweating or syneresis','crumbling','cracking','shape retention','packaging interaction','perceived deodorant performance','perceived odour control','white marks','transfer to clothing','longevity','initial fragrance intensity','dry-down fragrance intensity','projection','fragrance longevity','fragrance character','user preference','overall score','repurchase intention']as const
const targetLabels=['Stick firmness','Glide','Drag','Payoff','Dry-down speed','Tack','Greasiness','Residue','White marks','Crumbling','Sweating or syneresis','Structural stability','Fragrance intensity','Fragrance longevity','Skin comfort','Deodorant performance','Ease of application','Packaging compatibility']
const constraintLabels=['Aluminium-free','Baking-soda-free','Alcohol-free','Vegan','Natural-origin target','Fragrance-free','Essential-oil-free','Sensitive-skin target','Clear or translucent appearance','No white marks target']
const requirementLabels=['Continuous phase / solvent system','Primary stick-structuring system','Co-structuring support','Glide and sensory support','Deodorant-performance support','Fragrance system','Preservation or microbial-control strategy','Stability support','Film or residue-control function','Appearance or clarity control','Skin-conditioning support']

export function createBenchmarkScore(state:BenchmarkScoreState='not_tested',score?:number):BenchmarkScore{
 if(state==='scored'&&(!Number.isInteger(score)||score===undefined||score<1||score>10))throw new Error('Benchmark scores must be whole numbers from 1 to 10.')
 return{state,...(state==='scored'?{score}:{}),notes:''}
}
export function createBenchmarkLabDocument():BenchmarkLabDocument{
 return{schemaVersion:1,projectStatus:'Idea',workingTitle:'Koalafrog Deodorant Stick',productCategory:'Deodorant',productFormat:'Stick',benchmarkLink:{benchmarkId:benchmarkDeodorantConcept.id,role:'inspiration_performance_reference',sourceSnapshotId:`${benchmarkDeodorantConcept.id}@${benchmarkDeodorantConcept.updatedAt}`,notes:'Selected as inspiration and a performance reference; no formula composition is copied.'},objective:'Develop a distinct Koalafrog deodorant stick that preserves the benchmark’s desirable performance characteristics without creating a direct copy.',brief:{userNeed:'',intendedUse:'',intendedUser:'',usageContext:'',desiredPositioning:'',differentiation:'Distinct Koalafrog product; benchmark formula is not copied.',constraints:constraintLabels.map((label,index)=>({id:`constraint-${index+1}`,label,state:'unknown',notes:''})),targets:targetLabels.map((label,index)=>({id:`target-${index+1}`,label,targetState:'unknown',priority:'unreviewed',notes:'',evidenceSource:'development_brief',confidence:'unknown'})),successCriteria:[]},scorecard:{evaluator:'',testContext:'',conditions:'',dataSource:'user_observation',notes:'',scores:Object.fromEntries(scorecardDimensions.map(dimension=>[dimension,createBenchmarkScore()])),strongestCharacteristics:'',weakestCharacteristics:'',observations:''},systemHypothesis:{hypothesisText:'Aqueous glycol soap-gel stick structured primarily by sodium stearate, with supporting fatty materials, fragrance components, a deodorant-support ingredient and a polymeric sensory, appearance or film-forming component.',physicalSystem:{state:'known',value:'aqueous glycol soap-gel stick'},confidence:'assumed',evidenceSource:'user_supplied_label',supportingObservations:[],contradictingObservations:[],openQuestions:[],reviewStatus:'unreviewed'},functionalRequirements:requirementLabels.map((label,index)=>({id:`requirement-${index+1}`,label,status:'unresolved',reviewStatus:'not_reviewed',desiredOutcome:'',currentHypothesis:'',referenceCandidateIds:[],rationale:'',evidenceSource:'unknown',confidence:'unknown',openQuestions:''})),unresolvedAcknowledged:false}
}
export function createDevelopmentProjectFromBenchmark(name='Koalafrog Deodorant Stick',physicalSystem?:string,now=new Date().toISOString()):ProductStudioConcept{
 const benchmarkLab=createBenchmarkLabDocument();benchmarkLab.workingTitle=name
 benchmarkLab.systemHypothesis.physicalSystem=physicalSystem?.trim()?{state:'known',value:physicalSystem.trim()}:{state:'unknown'}
 return{id:crypto.randomUUID(),name,productType:'natural_deodorant',intentMode:'design',desiredProperties:[],selectedIngredients:[],scentDirections:[],candidateSubstitutes:{},notes:benchmarkLab.objective,analysis:{recordType:'development_project',benchmarkLab},createdAt:now,updatedAt:now}
}
export function benchmarkLabFrom(concept:ProductStudioConcept){
 const stored=concept.analysis.benchmarkLab as BenchmarkLabDocument|undefined
 if(!stored)return undefined
 const scores={...stored.scorecard.scores}
 for(const dimension of scorecardDimensions){const score=scores[dimension];scores[dimension]=score?{...score,notes:score.notes??''}:createBenchmarkScore()}
 return{...stored,scorecard:{...stored.scorecard,scores},functionalRequirements:stored.functionalRequirements.map(requirement=>({...requirement,reviewStatus:requirement.reviewStatus??'not_reviewed',openQuestions:requirement.openQuestions??''}))}
}
export function isRequirementReviewed(requirement:Pick<FunctionalRequirement,'reviewStatus'>){return requirement.reviewStatus==='reviewed'||requirement.reviewStatus==='not_applicable'}
export function benchmarkLabReadiness(document:BenchmarkLabDocument){const items=[{id:'concept',label:'Product concept defined',ready:Boolean(document.workingTitle.trim())},{id:'system',label:'Physical system selected or explicitly Unknown',ready:['known','unknown'].includes(document.systemHypothesis.physicalSystem.state)},{id:'constraints',label:'Key constraints reviewed',ready:document.brief.constraints.some(item=>item.state!=='unknown')},{id:'targets',label:'Critical development targets defined',ready:document.brief.targets.some(item=>item.priority==='critical'&&item.targetState==='known')},{id:'requirements',label:'Functional requirements reviewed',ready:document.functionalRequirements.some(isRequirementReviewed)},{id:'benchmark',label:'Benchmark linked',ready:document.benchmarkLink.benchmarkId===benchmarkDeodorantConcept.id}];return{items,ready:items.every(item=>item.ready)||document.unresolvedAcknowledged}}
export function benchmarkTargetComparison(document:BenchmarkLabDocument){return document.brief.targets.map(target=>{const key=target.label.toLowerCase(),observation=document.scorecard.scores[key];return{label:target.label,observation:observation??createBenchmarkScore(),target,priority:target.priority}})}
