import{describe,expect,it}from'vitest'
import{formulaSeed}from'../../../data/formulaSeed'
import{createBackup,validateBackup}from'../../../platform/backup/backup'
import{benchmarkDeodorantConcept,benchmarkDeodorantInci}from'./deodorantBenchmark'
import{benchmarkLabFrom,benchmarkLabReadiness,benchmarkTargetComparison,createBenchmarkLabDocument,createBenchmarkScore,createDevelopmentProjectFromBenchmark,type BenchmarkLabDocument,type FunctionalRequirement}from'./benchmarkLab'

describe('Benchmark Lab domain',()=>{
 it('creates a distinct development project linked only by benchmark identity and snapshot',()=>{const benchmarkBefore=structuredClone(benchmarkDeodorantConcept),project=createDevelopmentProjectFromBenchmark('Koalafrog Deodorant Stick','aqueous glycol soap-gel stick','2026-07-20T10:00:00.000Z'),document=benchmarkLabFrom(project)!;expect(project).toMatchObject({name:'Koalafrog Deodorant Stick',productType:'natural_deodorant',selectedIngredients:[]});expect(document.benchmarkLink).toMatchObject({benchmarkId:benchmarkDeodorantConcept.id,role:'inspiration_performance_reference'});expect(document.objective).toContain('without creating a direct copy');expect(benchmarkDeodorantConcept).toEqual(benchmarkBefore)})
 it('does not copy benchmark composition or create operational records',()=>{const before=structuredClone(formulaSeed),project=createDevelopmentProjectFromBenchmark(),after={...before,productStudioConcepts:[...before.productStudioConcepts,project]};expect(project.selectedIngredients).toEqual([]);expect(JSON.stringify(project)).not.toContain('PROPYLENE GLYCOL');expect(after.formulaLines).toEqual(before.formulaLines);expect(after.ingredients).toEqual(before.ingredients);expect(after.supplierProducts).toEqual(before.supplierProducts);expect(after.inventoryLots).toEqual(before.inventoryLots);expect(after.inventoryMovements).toEqual(before.inventoryMovements);expect(benchmarkDeodorantInci.find(line=>line.canonicalInci==='Benzyl Alcohol')?.productSpecificFunction).toBe('unknown')})
 it('models scored, Not tested, Unknown and Not applicable without treating zero as Unknown',()=>{expect(createBenchmarkScore()).toEqual({state:'not_tested',notes:''});expect(createBenchmarkScore('unknown')).toEqual({state:'unknown',notes:''});expect(createBenchmarkScore('not_applicable')).toEqual({state:'not_applicable',notes:''});expect(createBenchmarkScore('scored',1)).toMatchObject({state:'scored',score:1});expect(()=>createBenchmarkScore('scored',0)).toThrow('1 to 10');expect(()=>createBenchmarkScore('scored')).toThrow('1 to 10')})
 it('keeps observations, targets, hypotheses and candidates separate',()=>{const document=createBenchmarkLabDocument();document.scorecard.scores.glide=createBenchmarkScore('scored',9);const glide=document.brief.targets.find(item=>item.label==='Glide')!;glide.targetState='known';glide.targetValue='9/10';glide.priority='critical';const comparison=benchmarkTargetComparison(document).find(item=>item.label==='Glide');expect(comparison).toMatchObject({observation:{state:'scored',score:9},target:{targetValue:'9/10'},priority:'critical'});expect(document.systemHypothesis).toMatchObject({confidence:'assumed',evidenceSource:'user_supplied_label'});document.functionalRequirements[0].referenceCandidateIds=['aqua'];expect(document.functionalRequirements[0].referenceCandidateIds).toEqual(['aqua']);expect(document.brief.targets[0]).not.toHaveProperty('referenceCandidateIds')})
 it('allows readiness with explicitly acknowledged uncertainty rather than false certainty',()=>{const document=createBenchmarkLabDocument(),initial=benchmarkLabReadiness(document);expect(initial.ready).toBe(false);document.unresolvedAcknowledged=true;expect(benchmarkLabReadiness(document).ready).toBe(true);expect(document.brief.constraints.every(item=>item.state==='unknown')).toBe(true);expect(document.brief.targets.every(item=>item.targetState==='unknown')).toBe(true)})
 it('round-trips project, scorecard notes, target notes, brief, hypothesis, requirements and link through refresh and backup',()=>{const state=structuredClone(formulaSeed),project=createDevelopmentProjectFromBenchmark(),document=benchmarkLabFrom(project)!;document.scorecard.scores.glide={...createBenchmarkScore('scored',8),notes:'Almost no drag.'};document.brief.targets.find(item=>item.label==='Glide')!.notes='Preserve smooth application.';document.brief.userNeed='Reliable daily application';document.systemHypothesis.openQuestions=['What process is required?'];document.functionalRequirements[0].status='required';document.functionalRequirements[0].reviewStatus='reviewed';project.analysis.benchmarkLab=document;state.productStudioConcepts.push(project);const refreshed=structuredClone(state),backup=createBackup(refreshed),restored=structuredClone(backup.records),restoredProject=restored.productStudioConcepts.find(item=>item.id===project.id)!,restoredDocument=benchmarkLabFrom(restoredProject)!;expect(validateBackup(backup).valid).toBe(true);expect(restoredDocument.scorecard.scores.glide).toMatchObject({score:8,notes:'Almost no drag.'});expect(restoredDocument.brief.targets.find(item=>item.label==='Glide')?.notes).toBe('Preserve smooth application.');expect(restoredDocument.brief.userNeed).toBe('Reliable daily application');expect(restoredDocument.systemHypothesis.openQuestions).toEqual(['What process is required?']);expect(restoredDocument.functionalRequirements[0]).toMatchObject({status:'required',reviewStatus:'reviewed'});expect(restoredDocument.benchmarkLink.benchmarkId).toBe(benchmarkDeodorantConcept.id)})
 it('loads old Benchmark Lab documents with empty observation notes',()=>{const project=createDevelopmentProjectFromBenchmark(),stored=project.analysis.benchmarkLab as unknown as {scorecard:{scores:Record<string,{notes?:string}>}};delete stored.scorecard.scores.glide.notes;const loaded=benchmarkLabFrom(project)!;expect(loaded.scorecard.scores.glide.notes).toBe('')})
 it('loads legacy requirements without review state as Not reviewed without changing importance',()=>{const project=createDevelopmentProjectFromBenchmark(),stored=project.analysis.benchmarkLab as BenchmarkLabDocument;stored.functionalRequirements[0].status='required';delete (stored.functionalRequirements[0] as Partial<FunctionalRequirement>).reviewStatus;const loaded=benchmarkLabFrom(project)!;expect(loaded.functionalRequirements[0]).toMatchObject({status:'required',reviewStatus:'not_reviewed'});expect(benchmarkLabReadiness(loaded).items.find(item=>item.id==='requirements')?.ready).toBe(false)})
 it.each([
  ['not_reviewed',false],
  ['research_needed',false],
  ['reviewed',true],
  ['not_applicable',true],
 ] as const)('counts explicit requirement review state %s correctly',(reviewStatus,expected)=>{const document=createBenchmarkLabDocument();document.functionalRequirements[0].status='required';document.functionalRequirements[0].reviewStatus=reviewStatus;expect(benchmarkLabReadiness(document).items.find(item=>item.id==='requirements')?.ready).toBe(expected)})
 it('defines blank Formula lineage without ingredients, percentages, phases or process',()=>{const project=createDevelopmentProjectFromBenchmark(),document=benchmarkLabFrom(project)!;document.unresolvedAcknowledged=true;const blank={formulaLines:[],phaseDefinitions:undefined,manufacturingProcess:undefined,developmentNotes:`${document.benchmarkLink.benchmarkId} → ${project.id}`};expect(blank.formulaLines).toEqual([]);expect(blank).toMatchObject({phaseDefinitions:undefined,manufacturingProcess:undefined});expect(blank.developmentNotes).toContain(project.id)})
})
