import{describe,expect,it}from'vitest'
import{createBackup,validateBackup}from'../../../platform/backup/backup'
import{formulaSeed}from'../../../data/formulaSeed'
import{ingredientReferenceCatalog,validateReferenceCatalog}from'../../ingredients/reference/catalog'
import{benchmarkDeclarationNote,benchmarkDeodorantConcept,benchmarkDeodorantInci,benchmarkIngredientKnowledge}from'./deodorantBenchmark'

describe('deodorant stick benchmark reference',()=>{
 it('uses canonical de-duplicated references and preserves displayed aliases',()=>{expect(validateReferenceCatalog()).toEqual([]);expect(new Set(ingredientReferenceCatalog.map(entry=>entry.inciName.toLowerCase())).size).toBe(ingredientReferenceCatalog.length);expect(benchmarkDeodorantInci).toHaveLength(17);expect(benchmarkDeodorantInci.find(line=>line.canonicalInci==='Aqua')).toMatchObject({displayedName:'AQUA/WATER',displayedAlias:'Water'});expect(benchmarkDeodorantInci.find(line=>line.canonicalInci==='Parfum')).toMatchObject({displayedName:'PARFUM/FRAGRANCE',displayedAlias:'Fragrance'});expect(benchmarkDeodorantInci.every(line=>ingredientReferenceCatalog.some(entry=>entry.id===line.referenceEntryId&&entry.inciName===line.canonicalInci))).toBe(true)})
 it('round-trips exact label order while percentages and process remain unknown',()=>{const roundTrip=JSON.parse(JSON.stringify(benchmarkDeodorantConcept));expect(roundTrip.analysis.orderedInci.map((line:{displayedName:string})=>line.displayedName)).toEqual(benchmarkDeodorantInci.map(line=>line.displayedName));expect(roundTrip.analysis.exactPercentages).toEqual({state:'unknown'});expect(roundTrip.analysis.manufacturingProcess).toEqual({state:'unknown'});expect(roundTrip.analysis.declarationNote).toBe(benchmarkDeclarationNote)})
 it('does not turn label ingredients into Formula Lines or create operational side effects',()=>{const before=structuredClone(formulaSeed),state={...before,productStudioConcepts:[...before.productStudioConcepts,benchmarkDeodorantConcept]};expect(state.formulaLines).toEqual(before.formulaLines);expect(state.ingredients).toEqual(before.ingredients);expect(state.supplierProducts).toEqual(before.supplierProducts);expect(state.inventoryLots).toEqual(before.inventoryLots);expect(state.inventoryMovements).toEqual(before.inventoryMovements)})
 it('distinguishes declared fragrance constituents and preserves Benzyl Alcohol uncertainty',()=>{expect(benchmarkDeodorantInci.filter(line=>line.classification==='declared_fragrance_constituent')).toHaveLength(8);expect(benchmarkDeodorantInci.find(line=>line.canonicalInci==='Benzyl Alcohol')?.productSpecificFunction).toBe('unknown');expect(benchmarkIngredientKnowledge.find(item=>item.referenceEntryId==='benzyl-alcohol')).toMatchObject({confidence:'assumed',notes:expect.stringContaining('function is unknown')})})
 it('survives repository-shaped refresh and backup export/import',()=>{const state=structuredClone(formulaSeed);state.productStudioConcepts.push(benchmarkDeodorantConcept);const refresh=structuredClone(state),backup=createBackup(refresh),restored=structuredClone(backup.records);expect(validateBackup(backup).valid).toBe(true);expect(restored.productStudioConcepts[0]).toEqual(benchmarkDeodorantConcept)})
})
