import{describe,expect,it}from'vitest'
import{formulaSeed}from'../../../data/formulaSeed'
import type{Ingredient,InventoryLot,InventoryMovement,LabObservation,ProductStudioSelection}from'../../../types/domain'
import{analyzeCombination,availableIngredientQuantity,equipmentReadiness,formulaStartingPoint,inventoryReadiness,missingItemPlan,observedProfile,packagingReadiness,predictedProfile,rankIngredients,substituteSuggestions}from'./productStudio'

const selection=(...ids:string[]):ProductStudioSelection[]=>ids.map((ingredientId,index)=>({ingredientId,role:index?'supporting_carrier':'liquid_base',essential:index===0}))
const ingredient=(id:string,name:string,category='Carrier Oil'):Ingredient=>({id,commonName:name,inciName:name,category,functions:[],description:'Test profile',defaultUnit:'g',notes:'',status:'Active',createdAt:'',updatedAt:''})

describe('Beard Oil Product Studio rule pack',()=>{
 it('accepts a valid liquid base and reports explainable architecture fit',()=>{const findings=analyzeCombination(selection('i1'),formulaSeed.ingredients);expect(findings).toEqual([expect.objectContaining({id:'bo.architecture-fit',severity:'information',explanation:expect.any(String),evidence:['Jojoba Oil'],actions:expect.any(Array)})])})
 it('blocks a missing base',()=>expect(analyzeCombination([],formulaSeed.ingredients)).toContainEqual(expect.objectContaining({id:'bo.missing-liquid-base',severity:'blocking'})))
 it('identifies solid structurants in a liquid formula',()=>{const findings=analyzeCombination(selection('i3','i4'),formulaSeed.ingredients);expect(findings).toContainEqual(expect.objectContaining({id:'bo.solid-or-incompatible',severity:'blocking'}));expect(findings.find(x=>x.id==='bo.solid-or-incompatible')?.explanation).toContain('liquid')})
 it('warns about a heavy combination',()=>expect(analyzeCombination(selection('i9','i3'),formulaSeed.ingredients)).toContainEqual(expect.objectContaining({id:'bo.heavy-system',severity:'caution'})))
 it('warns when several oxidation-sensitive oils are selected',()=>{const ingredients=[ingredient('a','Rosehip Oil'),ingredient('b','Flax Oil')];expect(analyzeCombination(selection('a','b'),ingredients)).toContainEqual(expect.objectContaining({id:'bo.oxidation-load'}))})
 it('ranks Ingredients from desired properties with reasons instead of an opaque score',()=>{const ranked=rankIngredients(formulaSeed.ingredients,['Lightweight','Fast absorbing','Neutral base odour']);expect(ranked[0].fit.ingredient.commonName).toBe('Squalane');expect(ranked[0].reasons.join(' ')).toContain('lighter');expect(ranked[0].reasons.join(' ')).toContain('odour')})
 it('distinguishes stocked and unstocked Ingredients using movement-derived usable quantity',()=>{const ready=inventoryReadiness(selection('i1','i9'),formulaSeed,30,'2026-07-17');expect(ready.find(x=>x.id==='i1')).toMatchObject({state:'ready',available:500});expect(ready.find(x=>x.id==='i9')).toMatchObject({state:'missing',available:0})})
 it('calculates available quantities in the Ingredient unit and excludes expired lots',()=>{const lots:InventoryLot[]=[{id:'mg',ingredientId:'x',internalLotNumber:'X',receivedDate:'2026-01-01',openingQuantity:1000,unit:'mg',location:'Lab',status:'Active',expiryDate:'2027-01-01',notes:'',createdAt:'',updatedAt:''},{id:'expired',ingredientId:'x',internalLotNumber:'Y',receivedDate:'2025-01-01',openingQuantity:1,unit:'kg',location:'Lab',status:'Active',expiryDate:'2026-01-01',notes:'',createdAt:'',updatedAt:''}],movements:InventoryMovement[]=[{id:'r',inventoryLotId:'mg',type:'Receipt',quantity:1000,unit:'mg',reason:'Receipt',notes:'',occurredAt:'',createdAt:''},{id:'r2',inventoryLotId:'expired',type:'Receipt',quantity:1,unit:'kg',reason:'Receipt',notes:'',occurredAt:'',createdAt:''}];expect(availableIngredientQuantity('x',lots,movements,'2026-07-17','g')).toBe(1)})
 it('suggests same-role stocked substitutes with a prediction disclaimer',()=>{const suggestions=substituteSuggestions('i9',formulaSeed.ingredients,formulaSeed.inventoryLots,formulaSeed.inventoryMovements);expect(suggestions.map(x=>x.name)).toContain('Jojoba Oil');expect(suggestions[0].explanation).toContain('predicted')})
 it('reports missing owned equipment and missing physical packaging independently',()=>{const equipment=equipmentReadiness([]),packaging=packagingReadiness(formulaSeed.packagingComponents,[],[]);expect(equipment.filter(x=>x.level==='required').every(x=>x.state==='missing')).toBe(true);expect(packaging.state).toBe('missing');const plan=missingItemPlan([],equipment,packaging);expect(plan.equipment.length).toBeGreaterThan(0);expect(plan.packaging).toHaveLength(1)})
 it('creates explainable editable starting percentages totalling exactly 100%',()=>{for(const variant of ['lightweight','balanced','richer'] as const){const result=formulaStartingPoint(selection('i1','i2','i9','i5'),formulaSeed.ingredients,variant);expect(result.total).toBe(100);expect(result.lines.every(line=>line.explanation.includes('curated starting range'))).toBe(true)}})
 it('calculates a clearly labelled predicted profile',()=>{const profile=predictedProfile(selection('i1','i2'),formulaSeed.ingredients);expect(profile.label).toBe('PREDICTED PROFILE');expect(profile.explanation).toContain('Physical testing');expect(profile.liquidStability).toContain('Expected liquid')})
 it('keeps predicted and observed evidence separate',()=>{const predicted=predictedProfile(selection('i1'),formulaSeed.ingredients),none=observedProfile([]),recorded=observedProfile([{id:'obs',labBatchId:'batch',observationType:'Wear',observedAt:'2026-07-17',appearance:'Clear',texture:'Too greasy after 30 minutes',scent:'Quiet',stability:'',packaging:'',notes:'',createdAt:''} as LabObservation]);expect(predicted).not.toHaveProperty('evidenceIds');expect(none).toMatchObject({label:'OBSERVED',available:false});expect(recorded).toMatchObject({available:true,evidenceIds:['obs']});expect(recorded.summary[0]).toContain('Too greasy')})
})
