import type{ProcurementDocumentState,ProcurementStockState,RequestedItem,SupplierOffer}from'./procurement'
export type ResearchJobStatus='queued'|'running'|'partial'|'completed'|'failed'|'cancelled'
export type CandidateReviewStatus='pending'|'accepted'|'rejected'|'duplicate'|'merged'
export type FieldEvidenceState='unknown'|'inferred'|'reported'|'verified'
export interface FieldEvidence{state:FieldEvidenceState;sourceUrl?:string|null;snippet?:string|null}
export interface ResearchJob{id:string;procurement_request_id:string;provider:string;status:ResearchJobStatus;started_at:string|null;completed_at:string|null;cancellation_requested_at:string|null;provider_stopped_at:string|null;error_code:string|null;error_details:string|null;result_count:number;reviewed_count:number;retry_of_job_id:string|null;provider_request_id:string|null;correlation_id:string;attempt_count:number;created_at:string;updated_at:string}
export interface ProcurementProviderDiagnostic{job_id:string;provider_called:boolean;provider_stage:string|null;provider_started_at:string|null;provider_headers_at:string|null;provider_body_completed_at:string|null;provider_parse_completed_at:string|null;provider_validation_completed_at:string|null;provider_elapsed_ms:number|null;function_elapsed_ms:number|null;timeout_limit_ms:number|null;timeout_stage:'response_headers'|'response_body'|'parsing'|'validation'|'completion'|'unknown'|null;abort_source:'caller'|'application_deadline'|'none'|null;provider_http_status:number|null;usage_present:boolean|null;validated_candidate_count:number|null;terminal_error_code:string|null;diagnostic_version:number;created_at:string;updated_at:string}
export interface OfferCandidate{id:string;research_job_id:string;procurement_request_id:string;requested_item_id:string;supplier_name:string;matched_supplier_id:string|null;product_title:string;source_url:string;package_quantity:number|null;package_unit:string|null;item_price:number|null;currency:string|null;moq:number|null;shipping_cost:number|null;delivery_estimate_days:number|null;stock_status:ProcurementStockState;coa_availability:ProcurementDocumentState;sds_availability:ProcurementDocumentState;technical_document_availability:ProcurementDocumentState;first_order_discount:number|null;source_date:string;evidence_snippets:string[];source_notes:string;confidence:'low'|'medium'|'high'|'unknown';freshness:'fresh'|'aging'|'stale'|'unknown';field_states:Partial<Record<string,FieldEvidenceState>>;field_evidence:Record<string,FieldEvidence>;is_marketplace_listing:boolean;unresolved_fields:string[];review_status:CandidateReviewStatus;accepted_offer_id:string|null;duplicate_of_candidate_id:string|null;merged_into_offer_id:string|null;review_notes:string;reviewed_at:string|null;created_at:string;updated_at:string}
export const activeResearchStatuses:ResearchJobStatus[]=['queued','running']
export const terminalResearchStatuses:ResearchJobStatus[]=['partial','completed','failed','cancelled']
export const retryableResearchStatuses:ResearchJobStatus[]=['partial','failed','cancelled']
export const researchTransitions:Record<ResearchJobStatus,ResearchJobStatus[]>={queued:['running','cancelled'],running:['partial','completed','failed','cancelled'],partial:[],completed:[],failed:[],cancelled:[]}
export const canTransitionResearch=(from:ResearchJobStatus,to:ResearchJobStatus)=>researchTransitions[from].includes(to)
export const canRetryResearch=(status:ResearchJobStatus)=>retryableResearchStatuses.includes(status)
export function validResearchUrl(value:string){try{const url=new URL(value);return url.protocol==='https:'||url.protocol==='http:'}catch{return false}}
export function conservativeDuplicate(candidate:OfferCandidate,others:Array<OfferCandidate|SupplierOffer>){const normalized=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();return others.find(other=>{const title=normalized('product_title'in other?other.product_title:''),sameTitle=title===normalized(candidate.product_title);if(!sameTitle)return false;if('source_url'in other&&other.source_url)return other.source_url===candidate.source_url;return'product_url'in other&&other.product_url===candidate.source_url})}
export function candidateToOffer(candidate:OfferCandidate,supplierId:string|null):Omit<SupplierOffer,'id'|'created_at'|'updated_at'>{if(!supplierId)throw new Error('Supplier is required before acceptance.');if(!validResearchUrl(candidate.source_url))throw new Error('Candidate source URL is invalid.');if(candidate.package_quantity==null||!candidate.package_unit)throw new Error('Package size must be resolved before acceptance.');return{requested_item_id:candidate.requested_item_id,supplier_id:supplierId,source_supplier_product_domain:null,source_supplier_product_id:null,product_title:candidate.product_title,product_url:candidate.source_url,country_code:null,package_quantity:candidate.package_quantity,package_unit:candidate.package_unit,item_price:candidate.item_price,currency:candidate.currency,moq:candidate.moq,shipping_cost:candidate.shipping_cost,tax_duty_estimate:null,delivery_estimate_days:candidate.delivery_estimate_days,stock_status:candidate.stock_status,coa_availability:candidate.coa_availability,sds_availability:candidate.sds_availability,technical_document_availability:candidate.technical_document_availability,certification_claims:[],first_order_discount:candidate.first_order_discount,notes:`Research provenance: ${candidate.source_notes}\nEvidence: ${candidate.evidence_snippets.join(' | ')}`,date_checked:candidate.source_date,confidence:candidate.confidence}}
export function unresolvedFor(item:Pick<RequestedItem,'required_specifications'>,finding:Partial<OfferCandidate>){const required:(keyof OfferCandidate)[]=['source_url','package_quantity','package_unit','item_price','currency','shipping_cost','delivery_estimate_days'];return required.filter(key=>finding[key]==null||finding[key]==='').map(String).concat(item.required_specifications.length&&!finding.evidence_snippets?.length?['required_specification_evidence']:[])}
