import{describe,expect,it}from'vitest'
import{buildLiveResearchPrompt,safeSourceUrl,validateLiveResearchResponse,type LiveResearchRequest}from'./liveResearchContract'
const candidate={requestedItemId:'item-1',supplierName:'Established Oils AS',supplierType:'distributor',productTitle:'Refined jojoba oil 1 kg',sourceUrl:'https://supplier.test/products/jojoba',packageQuantity:1,packageUnit:'KG',itemPrice:249,currency:'nok',moq:1,shippingCost:null,deliveryEstimateDays:4,stockStatus:'in_stock',coaAvailability:'available',sdsAvailability:'available',technicalDocumentAvailability:'unknown',firstOrderDiscount:null,sourceDate:'2026-07-22',evidence:[{field:'coaAvailability',state:'reported',sourceUrl:'https://supplier.test/products/jojoba',snippet:'COA available on request.'},{field:'itemPrice',state:'verified',sourceUrl:'https://supplier.test/products/jojoba',snippet:'NOK 249.'}],sourceNotes:'Product page and commercial terms checked.',confidence:'high'}
const response={schemaVersion:1,partial:true,candidates:[candidate],providerNotes:'Shipping unresolved.'}
describe('live research contract',()=>{
 it('normalizes a sanitized recorded response',()=>{const result=validateLiveResearchResponse(response,['item-1'],new Date('2026-07-23'));expect(result.candidates[0]).toMatchObject({currency:'NOK',packageUnit:'kg',confidence:'high',coaAvailability:'available'});expect(result.partial).toBe(true)})
 it('rejects malformed and unsafe provider output',()=>{expect(()=>validateLiveResearchResponse({schemaVersion:2},['item-1'])).toThrow('LIVE_RESPONSE_MALFORMED');expect(()=>validateLiveResearchResponse({...response,candidates:[{...candidate,sourceUrl:'http://localhost/private'}]},['item-1'])).toThrow('LIVE_CANDIDATE_0_UNSAFE')})
 it('downgrades unsupported document claims',()=>{const result=validateLiveResearchResponse({...response,candidates:[{...candidate,evidence:[]}]},['item-1']);expect(result.candidates[0].coaAvailability).toBe('unknown');expect(result.candidates[0].sdsAvailability).toBe('unknown')})
 it('accepts http/https but rejects suspicious domains and credentials',()=>{expect(safeSourceUrl('https://supplier.test/item')).toBe(true);expect(safeSourceUrl('javascript:alert(1)')).toBe(false);expect(safeSourceUrl('https://user:pass@supplier.test/item')).toBe(false);expect(safeSourceUrl('https://example.com/item')).toBe(false)})
 it('constructs an explicit no-guess, no-purchase request',()=>{const request={schemaVersion:1,workspaceId:'w',jobId:'j',requestId:'q',deliveryCountry:'NO',documentationRequirements:['COA'],preferredSuppliers:['Direct supplier'],excludedSuppliers:['Bad supplier'],items:[]} satisfies LiveResearchRequest;const prompt=buildLiveResearchPrompt(request);expect(prompt).toContain('Never guess');expect(prompt).toContain('do not perform purchasing');expect(prompt).toContain('Direct supplier')})
})
