import{describe,expect,it}from'vitest'
import{buildLiveResearchPrompt,freshnessFromSourceDate,safeSourceUrl,validateLiveResearchResponse,type LiveResearchRequest}from'./liveResearchContract'
import response from'./fixtures/liveResearchResponse.v1.json'
const candidate=response.candidates[0]
describe('live research contract',()=>{
 it('normalizes a sanitized recorded response and preserves its historical date',()=>{const result=validateLiveResearchResponse(response,['item-1'],new Date('2026-07-23T12:00:00Z'));expect(result.candidates[0]).toMatchObject({currency:'NOK',packageUnit:'kg',confidence:'high',coaAvailability:'available',sourceDate:'2026-07-22'});expect(result.partial).toBe(true)})
 it('rejects malformed and unsafe provider output',()=>{expect(()=>validateLiveResearchResponse({schemaVersion:2},['item-1'])).toThrow('LIVE_RESPONSE_MALFORMED');expect(()=>validateLiveResearchResponse({...response,candidates:[{...candidate,sourceUrl:'http://localhost/private'}]},['item-1'])).toThrow('LIVE_CANDIDATE_0_UNSAFE')})
 it('downgrades unsupported document claims',()=>{const result=validateLiveResearchResponse({...response,candidates:[{...candidate,evidence:[]}]},['item-1']);expect(result.candidates[0].coaAvailability).toBe('unknown');expect(result.candidates[0].sdsAvailability).toBe('unknown')})
 it('keeps verified evidence only with a safe URL and non-empty snippet',()=>{const today=new Date('2026-07-23T12:00:00Z'),evidence={field:'itemPrice',state:'verified',sourceUrl:'https://supplier.test/item',snippet:'NOK 249'};const state=(override:Record<string,unknown>)=>validateLiveResearchResponse({...response,candidates:[{...candidate,evidence:[{...evidence,...override}]}]},['item-1'],today).candidates[0].evidence[0]?.state;expect(state({})).toBe('verified');expect(state({sourceUrl:'javascript:alert(1)'})).toBe('reported');expect(state({sourceUrl:null})).toBe('reported');expect(state({snippet:''})).toBe('reported');expect(state({field:null,state:{malformed:true}})).toBeUndefined()})
 it('preserves valid dates, falls back for malformed or impossible dates, and derives freshness from the preserved date',()=>{const today=new Date('2026-07-23T12:00:00Z'),date=(sourceDate:unknown)=>validateLiveResearchResponse({...response,candidates:[{...candidate,sourceDate}]},['item-1'],today).candidates[0].sourceDate;expect(date('2026-07-23')).toBe('2026-07-23');expect(date('2026-06-30')).toBe('2026-06-30');expect(date('23-07-2026')).toBe('2026-07-23');expect(date('2026-02-30')).toBe('2026-07-23');expect(freshnessFromSourceDate(date('2026-07-20'),today)).toBe('fresh');expect(freshnessFromSourceDate(date('2026-07-01'),today)).toBe('aging');expect(freshnessFromSourceDate(date('2026-05-01'),today)).toBe('stale')})
 it('accepts http/https but rejects suspicious domains and credentials',()=>{expect(safeSourceUrl('https://supplier.test/item')).toBe(true);expect(safeSourceUrl('javascript:alert(1)')).toBe(false);expect(safeSourceUrl('https://user:pass@supplier.test/item')).toBe(false);expect(safeSourceUrl('https://example.com/item')).toBe(false)})
 it('constructs an explicit no-guess, no-purchase request',()=>{const request={schemaVersion:1,workspaceId:'w',jobId:'j',requestId:'q',deliveryCountry:'NO',documentationRequirements:['COA'],preferredSuppliers:['Direct supplier'],excludedSuppliers:['Bad supplier'],items:[]} satisfies LiveResearchRequest;const prompt=buildLiveResearchPrompt(request);expect(prompt).toContain('Never guess');expect(prompt).toContain('do not perform purchasing');expect(prompt).toContain('Direct supplier')})
})
