export type SupplierStatus='research'|'candidate'|'approved_internal'|'active'|'paused'|'rejected'|'archived'
export interface Supplier{id:string;legal_name:string;trading_name:string|null;supplier_type:string;status:SupplierStatus;website_url:string|null;country_code:string|null;default_currency:string|null;default_lead_time_days:number|null;default_payment_terms:string|null;default_incoterm:string|null;minimum_order_value:number|null;internal_rating:number|null;internal_notes:string;is_preferred:boolean;verification_state:'unknown'|'needs_review'|'reviewed'|'rejected';archived_at:string|null;revision:number;created_at:string;updated_at:string}
export interface SupplierContact{id:string;supplier_id:string;name:string;role:string|null;email:string|null;phone:string|null;preferred_contact_method:string|null;notes:string;is_primary:boolean;archived_at:string|null}
export interface ResearchCandidate{id:string;candidate_name:string;candidate_type:string;source_url:string|null;source_title:string|null;country_code:string|null;currency:string|null;candidate_summary:string|null;claimed_capabilities:string[];evidence_notes:string|null;status:'unreviewed'|'reviewing'|'shortlisted'|'rejected'|'converted'|'archived';converted_supplier_id:string|null;rejection_reason:string|null;created_at:string}
export interface SupplierQuote{id:string;supplier_id:string;quote_reference:string|null;quote_date:string;valid_until:string|null;currency:string;shipping_cost:number|null;duties_estimate:number|null;tax_estimate:number|null;payment_fee:number|null;additional_cost:number|null;lead_time_days:number|null;status:string;internal_notes:string;revision:number;created_at:string}
export interface QuoteLine{id:string;quote_id:string;supplier_product_domain:string|null;supplier_product_id:string|null;description:string;quantity:number;unit:string;unit_price:number;line_discount:number;line_total:number;moq:number|null;order_multiple:number|null;lead_time_days:number|null;display_order:number}
export interface StockPolicy{id:string;inventory_domain:'raw_material'|'packaging';ingredient_id:string|null;supplier_product_id:string|null;packaging_component_id:string|null;packaging_supplier_product_id:string|null;policy_status:'draft'|'active'|'paused'|'archived';minimum_on_hand:number;target_on_hand:number;safety_stock:number|null;reorder_point:number|null;preferred_order_quantity:number|null;unit:string;expected_lead_time_days:number|null;is_basis_item:boolean;rationale:string}
export interface PurchasePlan{id:string;title:string;status:'draft'|'ready_for_review'|'approved_internal'|'ordered_external'|'partially_received'|'received'|'cancelled'|'archived';purpose:string;target_date:string|null;supplier_id:string|null;currency:string|null;internal_notes:string;estimated_merchandise_total:number|null;estimated_landed_total:number|null;revision:number;created_at:string;updated_at:string}
export interface PurchasePlanLine{id:string;purchase_plan_id:string;inventory_domain:'raw_material'|'packaging'|'equipment';supplier_product_id:string|null;description:string;planned_quantity:number;unit:string;pack_count:number|null;pack_size:number|null;estimated_unit_price:number|null;estimated_line_total:number|null;currency:string|null;requirement_reason:string|null;requirement_basis:Record<string,unknown>;received_quantity:number;display_order:number}
export interface EquipmentItem{id:string;name:string;equipment_type:string;status:string;manufacturer:string|null;model:string|null;serial_number:string|null;supplier_id:string|null;purchase_date:string|null;purchase_cost:number|null;purchase_currency:string|null;location:string|null;capacity_value:number|null;capacity_unit:string|null;precision_value:number|null;precision_unit:string|null;internal_notes:string;archived_at:string|null;revision:number;created_at:string;updated_at:string}
export interface EquipmentCapability{id:string;equipment_item_id:string;capability_type:string;minimum_value:number|null;maximum_value:number|null;precision:number|null;unit:string|null;notes:string}
export interface EquipmentPolicy{id:string;equipment_item_id:string;status:string;inspection_interval_days:number|null;calibration_interval_days:number|null;maintenance_interval_days:number|null;cleaning_required_before_use:boolean;cleaning_required_after_use:boolean;verification_notes:string;revision:number}
export interface EquipmentServiceEvent{id:string;equipment_item_id:string;event_type:string;performed_at:string;performed_by:string|null;result_status:string;notes:string;next_due_at:string|null;created_at:string}
export interface ProcessEquipmentRequirement{id:string;source_type:string;source_id:string;required_equipment_type:string|null;required_capability:string|null;minimum_capacity:number|null;required_precision:number|null;unit:string|null;quantity_required:number;requirement_level:'required'|'recommended'|'optional';notes:string}
export interface ProcurementData{suppliers:Supplier[];contacts:SupplierContact[];candidates:ResearchCandidate[];quotes:SupplierQuote[];quoteLines:QuoteLine[];stockPolicies:StockPolicy[];purchasePlans:PurchasePlan[];purchasePlanLines:PurchasePlanLine[];equipment:EquipmentItem[];capabilities:EquipmentCapability[];equipmentPolicies:EquipmentPolicy[];serviceEvents:EquipmentServiceEvent[];processRequirements:ProcessEquipmentRequirement[]}

export const emptyProcurementData=():ProcurementData=>({suppliers:[],contacts:[],candidates:[],quotes:[],quoteLines:[],stockPolicies:[],purchasePlans:[],purchasePlanLines:[],equipment:[],capabilities:[],equipmentPolicies:[],serviceEvents:[],processRequirements:[]})
export function quoteArithmetic(quote:SupplierQuote,lines:QuoteLine[]){const merchandise=lines.filter(x=>x.quote_id===quote.id).reduce((sum,x)=>sum+Number(x.quantity)*Number(x.unit_price)-Number(x.line_discount||0),0),components={merchandise,shipping:quote.shipping_cost,duties:quote.duties_estimate,tax:quote.tax_estimate,paymentFee:quote.payment_fee,additional:quote.additional_cost},missing=Object.entries(components).filter(([key,value])=>key!=='merchandise'&&value==null).map(([key])=>key),knownTotal=Object.values(components).reduce<number>((sum,value)=>sum+Number(value??0),0);return{components,missing,knownTotal,complete:missing.length===0}}
export function compareQuotes(quotes:SupplierQuote[],lines:QuoteLine[],rates:Record<string,number>,comparisonCurrency:string){return quotes.map(quote=>{const landed=quoteArithmetic(quote,lines),rate=quote.currency===comparisonCurrency?1:rates[`${quote.currency}:${comparisonCurrency}`];return{quote,nativeTotal:landed.knownTotal,comparisonTotal:rate==null?null:landed.knownTotal*rate,rate:rate??null,missing:rate==null&&quote.currency!==comparisonCurrency?[...landed.missing,'exchangeRate']:landed.missing}})}
export function requirement(input:{currentUsable:number;minimum:number;target:number;plannedDemand:number;openPlannedSupply:number;moq?:number;orderMultiple?:number}){const uncovered=Math.max(0,input.target+input.plannedDemand-input.currentUsable-input.openPlannedSupply),minimumGap=Math.max(0,input.minimum+input.plannedDemand-input.currentUsable-input.openPlannedSupply);let suggested=uncovered;if(suggested&&input.moq)suggested=Math.max(suggested,input.moq);if(suggested&&input.orderMultiple)suggested=Math.ceil(suggested/input.orderMultiple)*input.orderMultiple;return{uncovered,suggested,urgency:minimumGap>0?'below_minimum':uncovered>0?'planned_need':'covered',basis:{...input}}}
export function purchasePlanTransition(from:PurchasePlan['status'],to:PurchasePlan['status']){const allowed:{[K in PurchasePlan['status']]:PurchasePlan['status'][]}={draft:['ready_for_review','cancelled'],ready_for_review:['draft','approved_internal','cancelled'],approved_internal:['ordered_external','cancelled'],ordered_external:['partially_received','received','cancelled'],partially_received:['received','cancelled'],received:['archived'],cancelled:['archived'],archived:[]};return allowed[from].includes(to)}
export function equipmentReadiness(item:EquipmentItem,capabilities:EquipmentCapability[],policy:EquipmentPolicy|undefined,events:EquipmentServiceEvent[],requirement?:{capacity?:number;precision?:number;capability?:string}){const issues:string[]=[];if(!['available','in_use'].includes(item.status))issues.push(`Status is ${item.status.replaceAll('_',' ')}.`);if(requirement?.capability&&!capabilities.some(x=>x.equipment_item_id===item.id&&x.capability_type===requirement.capability))issues.push(`Missing ${requirement.capability} capability.`);if(requirement?.capacity!=null&&(item.capacity_value==null||item.capacity_value<requirement.capacity))issues.push(item.capacity_value==null?'Capacity not recorded.':'Capacity below requirement.');if(requirement?.precision!=null&&(item.precision_value==null||item.precision_value>requirement.precision))issues.push(item.precision_value==null?'Precision not recorded.':'Precision may be insufficient.');const now=Date.now(),latest=(type:string)=>events.filter(x=>x.equipment_item_id===item.id&&x.event_type===type).sort((a,b)=>b.performed_at.localeCompare(a.performed_at))[0];if(policy?.calibration_interval_days&&!latest('calibration'))issues.push('Calibration not yet recorded.');for(const type of ['calibration','maintenance','inspection']){const due=latest(type)?.next_due_at;if(due&&new Date(due).getTime()<=now)issues.push(`${type} is due.`)}if(policy?.cleaning_required_before_use&&!latest('cleaning'))issues.push('Cleaning record required before use.');return{state:issues.length?'review':'ready',issues,label:issues.length?'Operational readiness needs review.':'Operationally ready under recorded Koalafrog rules.'}}
export function procurementCopilot(data:ProcurementData){return[...data.candidates.filter(x=>x.status==='unreviewed').map(x=>({category:'Review suppliers',reason:`${x.candidate_name} awaits human review.`,sourceId:x.id})),...data.quotes.filter(x=>x.valid_until&&new Date(x.valid_until).getTime()-Date.now()<14*86400000&&!['expired','declined','archived'].includes(x.status)).map(x=>({category:'Review quotes',reason:`Quote ${x.quote_reference??x.id} expires soon.`,sourceId:x.id})),...data.equipment.flatMap(item=>{const readiness=equipmentReadiness(item,data.capabilities,data.equipmentPolicies.find(x=>x.equipment_item_id===item.id),data.serviceEvents);return readiness.issues.map(reason=>({category:'Equipment attention',reason:`${item.name}: ${reason}`,sourceId:item.id}))}),...data.purchasePlans.filter(x=>['ordered_external','partially_received'].includes(x.status)).map(x=>({category:'Receive orders',reason:`${x.title} has outstanding receipt work.`,sourceId:x.id}))]}
