export type SupplierStatus='research'|'candidate'|'approved_internal'|'active'|'paused'|'rejected'|'archived'
export interface Supplier{id:string;legal_name:string;trading_name:string|null;supplier_type:string;status:SupplierStatus;website_url:string|null;country_code:string|null;default_currency:string|null;default_lead_time_days:number|null;default_payment_terms:string|null;default_incoterm:string|null;minimum_order_value:number|null;internal_rating:number|null;internal_notes:string;is_preferred:boolean;verification_state:'unknown'|'needs_review'|'reviewed'|'rejected';archived_at:string|null;revision:number;created_at:string;updated_at:string}
export interface SupplierContact{id:string;supplier_id:string;name:string;role:string|null;email:string|null;phone:string|null;preferred_contact_method:string|null;notes:string;is_primary:boolean;archived_at:string|null}
export interface ResearchCandidate{id:string;candidate_name:string;candidate_type:string;source_url:string|null;source_title:string|null;country_code:string|null;currency:string|null;candidate_summary:string|null;claimed_capabilities:string[];evidence_notes:string|null;status:'unreviewed'|'reviewing'|'shortlisted'|'rejected'|'converted'|'archived';converted_supplier_id:string|null;rejection_reason:string|null;created_at:string}
export interface SupplierQuote{id:string;supplier_id:string;quote_reference:string|null;quote_date:string;valid_until:string|null;currency:string;shipping_cost:number|null;duties_estimate:number|null;tax_estimate:number|null;payment_fee:number|null;additional_cost:number|null;lead_time_days:number|null;status:string;internal_notes:string;revision:number;created_at:string}
export interface QuoteLine{id:string;quote_id:string;supplier_product_domain:string|null;supplier_product_id:string|null;description:string;quantity:number;unit:string;unit_price:number;line_discount:number;line_total:number;moq:number|null;order_multiple:number|null;lead_time_days:number|null;display_order:number}
export interface StockPolicy{id:string;inventory_domain:'raw_material'|'packaging';ingredient_id:string|null;supplier_product_id:string|null;packaging_component_id:string|null;packaging_supplier_product_id:string|null;policy_status:'draft'|'active'|'paused'|'archived';minimum_on_hand:number;target_on_hand:number;safety_stock:number|null;reorder_point:number|null;preferred_order_quantity:number|null;unit:string;expected_lead_time_days:number|null;is_basis_item:boolean;rationale:string}
export interface PurchasePlan{id:string;title:string;status:'draft'|'ready_for_review'|'approved_internal'|'ordered_external'|'partially_received'|'received'|'cancelled'|'archived';purpose:string;target_date:string|null;supplier_id:string|null;currency:string|null;internal_notes:string;estimated_merchandise_total:number|null;estimated_landed_total:number|null;revision:number;created_at:string;updated_at:string}
export interface PurchasePlanLine{id:string;purchase_plan_id:string;inventory_domain:'raw_material'|'packaging'|'equipment';supplier_product_id:string|null;description:string;planned_quantity:number;unit:string;pack_count:number|null;pack_size:number|null;estimated_unit_price:number|null;estimated_line_total:number|null;currency:string|null;requirement_reason:string|null;requirement_basis:Record<string,unknown>;received_quantity:number;display_order:number}
export interface EquipmentItem{id:string;name:string;equipment_type:string;status:string;manufacturer:string|null;model:string|null;serial_number:string|null;supplier_id:string|null;purchase_date:string|null;purchase_cost:number|null;purchase_currency:string|null;location:string|null;capacity_value:number|null;capacity_unit:string|null;precision_value:number|null;precision_unit:string|null;internal_notes:string;archived_at:string|null;revision:number;created_at:string;updated_at:string}
export interface EquipmentCapability{id:string;equipment_item_id:string;capability_type:string;minimum_value:number|null;maximum_value:number|null;precision:number|null;unit:string|null;notes:string}
export interface EquipmentPolicy{id:string;equipment_item_id:string;status:string;inspection_interval_days:number|null;calibration_interval_days:number|null;maintenance_interval_days:number|null;cleaning_required_before_use:boolean;cleaning_required_after_use:boolean;verification_notes:string;revision:number}
export interface EquipmentServiceEvent{id:string;equipment_item_id:string;event_type:string;performed_at:string;performed_by:string|null;result_status:string;notes:string;next_due_at:string|null;created_at:string}
export interface ProcessEquipmentRequirement{id:string;source_type:string;source_id:string;required_equipment_type:string|null;required_capability:string|null;minimum_capacity:number|null;required_precision:number|null;unit:string|null;quantity_required:number;requirement_level:'required'|'recommended'|'optional';notes:string}
export type ProcurementRequestStatus='needed'|'researching'|'recommended'|'ordered'|'received'
export type ProcurementPriority='low'|'normal'|'high'|'urgent'
export type ProcurementDocumentState='unknown'|'available'|'unavailable'|'partial'
export type ProcurementStockState='unknown'|'in_stock'|'limited'|'backorder'|'out_of_stock'
export interface ProcurementRequest{id:string;title:string;status:ProcurementRequestStatus;category:string;priority:ProcurementPriority;needed_by:string|null;notes:string;revision:number;created_at:string;updated_at:string}
export interface RequestedItem{id:string;procurement_request_id:string;name:string;category:string;requested_quantity:number;unit:string;intended_product_ids:string[];intended_formula_ids:string[];required_specifications:string[];acceptable_substitutes:string[];priority:ProcurementPriority;needed_by:string|null;notes:string;display_order:number;created_at:string;updated_at:string}
export interface SupplierOffer{id:string;requested_item_id:string;supplier_id:string;source_supplier_product_domain:'raw_material'|'packaging'|null;source_supplier_product_id:string|null;product_title:string;product_url:string|null;country_code:string|null;package_quantity:number;package_unit:string;item_price:number|null;currency:string|null;moq:number|null;shipping_cost:number|null;tax_duty_estimate:number|null;delivery_estimate_days:number|null;stock_status:ProcurementStockState;coa_availability:ProcurementDocumentState;sds_availability:ProcurementDocumentState;technical_document_availability:ProcurementDocumentState;certification_claims:string[];first_order_discount:number|null;notes:string;date_checked:string;confidence:'low'|'medium'|'high'|'unknown';created_at:string;updated_at:string}
export interface ProcurementRecommendation{id:string;procurement_request_id:string;requested_item_id:string;supplier_offer_id:string;summary:string;rationale:string;recommended_purchase_quantity:number|null;status:'draft'|'recommended'|'superseded';created_at:string;updated_at:string}

export type SupplierDiscountStatus='available'|'planned'|'used'|'expired'|'invalid'|'unknown'
export interface SupplierDiscount{id:string;supplier_id:string;name:string;discount_type:'percentage'|'fixed_amount'|'free_shipping'|'other';percentage:number|null;fixed_amount:number|null;currency:string|null;coupon_code:string|null;minimum_order_value:number|null;maximum_discount:number|null;first_purchase_only:boolean;requires_newsletter:boolean;valid_from:string|null;expires_at:string|null;status:SupplierDiscountStatus;source_url:string|null;evidence_notes:string;verified_at:string|null;used_at:string|null;created_at:string;updated_at:string}
export interface SupplierShippingRule{id:string;supplier_id:string;destination_country_code:string|null;destination_region:string|null;shipping_method:string|null;currency:string|null;flat_rate:number|null;free_shipping_threshold:number|null;minimum_order_value:number|null;delivery_estimate_min_days:number|null;delivery_estimate_max_days:number|null;tax_handling:'unknown'|'included'|'excluded'|'destination_checkout'|'import_due';duty_handling:'unknown'|'included'|'excluded'|'import_due';tax_estimate:number|null;duty_estimate:number|null;status:'active'|'needs_verification'|'inactive'|'expired';source_url:string|null;evidence_notes:string;verified_at:string|null;created_at:string;updated_at:string}
export type SupplierDocumentType='coa'|'sds'|'ifra'|'allergen_declaration'|'certificate'|'batch_traceability'
export type SupplierDocumentCapability='unknown'|'available'|'unavailable'|'available_on_request'|'not_applicable'
export type SupplierDocumentVerification='unverified'|'pending_review'|'verified'|'rejected'|'expired'
export interface SupplierDocumentRecord{id:string;supplier_id:string;document_type:SupplierDocumentType;document_subtype:string|null;capability_state:SupplierDocumentCapability;verification_state:SupplierDocumentVerification;evidence_url:string|null;document_title:string|null;issuer:string|null;issue_date:string|null;expiry_date:string|null;checked_date:string|null;source_reference:string|null;notes:string;scope_type:'supplier_wide';revision:number;archived_at:string|null;created_at:string;updated_at:string}
export type SupplierEventType='quote_received'|'quote_updated'|'purchase_planned'|'purchase_placed'|'order_confirmed'|'shipment_dispatched'|'shipment_received'|'partial_shipment'|'cancelled_order'|'refund'|'replacement_shipment'|'damaged_shipment'|'customs_issue'|'invoice_received'|'payment_completed'|'documentation_requested'|'documentation_received'|'documentation_rejected'|'communication'|'manual_note'
export interface SupplierEvent{id:string;supplier_id:string;event_type:SupplierEventType;occurred_at:string;expected_at:string|null;title:string;description:string;supplier_quote_id:string|null;procurement_request_id:string|null;supplier_offer_id:string|null;purchase_plan_id:string|null;supplier_document_record_id:string|null;revision:number;archived_at:string|null;created_at:string;updated_at:string}
export interface ProcurementCartScenario{id:string;supplier_id:string;name:string;destination_country_code:string;currency:string;shipping_rule_id:string|null;discount_id:string|null;manual_shipping_cost:number|null;manual_tax_estimate:number|null;manual_duty_estimate:number|null;payment_fee:number|null;additional_cost:number|null;status:'draft'|'ready_for_review'|'selected'|'superseded'|'archived';notes:string;calculated_at:string|null;created_at:string;updated_at:string}
export interface ProcurementCartScenarioItem{id:string;scenario_id:string;supplier_offer_id:string;requested_item_id:string;package_count:number;unit_price:number;line_discount:number;display_order:number;notes:string;created_at:string;updated_at:string}

import type{OfferCandidate,ProcurementProviderDiagnostic,ResearchJob}from'./assistedResearch'
export interface ProcurementData{suppliers:Supplier[];contacts:SupplierContact[];candidates:ResearchCandidate[];quotes:SupplierQuote[];quoteLines:QuoteLine[];stockPolicies:StockPolicy[];purchasePlans:PurchasePlan[];purchasePlanLines:PurchasePlanLine[];equipment:EquipmentItem[];capabilities:EquipmentCapability[];equipmentPolicies:EquipmentPolicy[];serviceEvents:EquipmentServiceEvent[];processRequirements:ProcessEquipmentRequirement[];requests:ProcurementRequest[];requestedItems:RequestedItem[];offers:SupplierOffer[];recommendations:ProcurementRecommendation[];supplierDiscounts:SupplierDiscount[];supplierShippingRules:SupplierShippingRule[];supplierDocuments:SupplierDocumentRecord[];supplierEvents:SupplierEvent[];cartScenarios:ProcurementCartScenario[];cartScenarioItems:ProcurementCartScenarioItem[];researchJobs:ResearchJob[];researchDiagnostics:ProcurementProviderDiagnostic[];offerCandidates:OfferCandidate[]}

export const emptyProcurementData=():ProcurementData=>({suppliers:[],contacts:[],candidates:[],quotes:[],quoteLines:[],stockPolicies:[],purchasePlans:[],purchasePlanLines:[],equipment:[],capabilities:[],equipmentPolicies:[],serviceEvents:[],processRequirements:[],requests:[],requestedItems:[],offers:[],recommendations:[],supplierDiscounts:[],supplierShippingRules:[],supplierDocuments:[],supplierEvents:[],cartScenarios:[],cartScenarioItems:[],researchJobs:[],researchDiagnostics:[],offerCandidates:[]})
export function quoteArithmetic(quote:SupplierQuote,lines:QuoteLine[]){const merchandise=lines.filter(x=>x.quote_id===quote.id).reduce((sum,x)=>sum+Number(x.quantity)*Number(x.unit_price)-Number(x.line_discount||0),0),components={merchandise,shipping:quote.shipping_cost,duties:quote.duties_estimate,tax:quote.tax_estimate,paymentFee:quote.payment_fee,additional:quote.additional_cost},missing=Object.entries(components).filter(([key,value])=>key!=='merchandise'&&value==null).map(([key])=>key),knownTotal=Object.values(components).reduce<number>((sum,value)=>sum+Number(value??0),0);return{components,missing,knownTotal,complete:missing.length===0}}
export function compareQuotes(quotes:SupplierQuote[],lines:QuoteLine[],rates:Record<string,number>,comparisonCurrency:string){return quotes.map(quote=>{const landed=quoteArithmetic(quote,lines),rate=quote.currency===comparisonCurrency?1:rates[`${quote.currency}:${comparisonCurrency}`];return{quote,nativeTotal:landed.knownTotal,comparisonTotal:rate==null?null:landed.knownTotal*rate,rate:rate??null,missing:rate==null&&quote.currency!==comparisonCurrency?[...landed.missing,'exchangeRate']:landed.missing}})}
export function requirement(input:{currentUsable:number;minimum:number;target:number;plannedDemand:number;openPlannedSupply:number;moq?:number;orderMultiple?:number}){const uncovered=Math.max(0,input.target+input.plannedDemand-input.currentUsable-input.openPlannedSupply),minimumGap=Math.max(0,input.minimum+input.plannedDemand-input.currentUsable-input.openPlannedSupply);let suggested=uncovered;if(suggested&&input.moq)suggested=Math.max(suggested,input.moq);if(suggested&&input.orderMultiple)suggested=Math.ceil(suggested/input.orderMultiple)*input.orderMultiple;return{uncovered,suggested,urgency:minimumGap>0?'below_minimum':uncovered>0?'planned_need':'covered',basis:{...input}}}
export function purchasePlanTransition(from:PurchasePlan['status'],to:PurchasePlan['status']){const allowed:{[K in PurchasePlan['status']]:PurchasePlan['status'][]}={draft:['ready_for_review','cancelled'],ready_for_review:['draft','approved_internal','cancelled'],approved_internal:['ordered_external','cancelled'],ordered_external:['partially_received','received','cancelled'],partially_received:['received','cancelled'],received:['archived'],cancelled:['archived'],archived:[]};return allowed[from].includes(to)}
export function equipmentReadiness(item:EquipmentItem,capabilities:EquipmentCapability[],policy:EquipmentPolicy|undefined,events:EquipmentServiceEvent[],requirement?:{capacity?:number;precision?:number;capability?:string}){const issues:string[]=[];if(!['available','in_use'].includes(item.status))issues.push(`Status is ${item.status.replaceAll('_',' ')}.`);if(requirement?.capability&&!capabilities.some(x=>x.equipment_item_id===item.id&&x.capability_type===requirement.capability))issues.push(`Missing ${requirement.capability} capability.`);if(requirement?.capacity!=null&&(item.capacity_value==null||item.capacity_value<requirement.capacity))issues.push(item.capacity_value==null?'Capacity not recorded.':'Capacity below requirement.');if(requirement?.precision!=null&&(item.precision_value==null||item.precision_value>requirement.precision))issues.push(item.precision_value==null?'Precision not recorded.':'Precision may be insufficient.');const now=Date.now(),latest=(type:string)=>events.filter(x=>x.equipment_item_id===item.id&&x.event_type===type).sort((a,b)=>b.performed_at.localeCompare(a.performed_at))[0];if(policy?.calibration_interval_days&&!latest('calibration'))issues.push('Calibration not yet recorded.');for(const type of ['calibration','maintenance','inspection']){const due=latest(type)?.next_due_at;if(due&&new Date(due).getTime()<=now)issues.push(`${type} is due.`)}if(policy?.cleaning_required_before_use&&!latest('cleaning'))issues.push('Cleaning record required before use.');return{state:issues.length?'review':'ready',issues,label:issues.length?'Operational readiness needs review.':'Operationally ready under recorded Koalafrog rules.'}}
export function procurementCopilot(data:ProcurementData){return[...data.candidates.filter(x=>x.status==='unreviewed').map(x=>({category:'Review suppliers',reason:`${x.candidate_name} awaits human review.`,sourceId:x.id})),...data.quotes.filter(x=>x.valid_until&&new Date(x.valid_until).getTime()-Date.now()<14*86400000&&!['expired','declined','archived'].includes(x.status)).map(x=>({category:'Review quotes',reason:`Quote ${x.quote_reference??x.id} expires soon.`,sourceId:x.id})),...data.equipment.flatMap(item=>{const readiness=equipmentReadiness(item,data.capabilities,data.equipmentPolicies.find(x=>x.equipment_item_id===item.id),data.serviceEvents);return readiness.issues.map(reason=>({category:'Equipment attention',reason:`${item.name}: ${reason}`,sourceId:item.id}))}),...data.purchasePlans.filter(x=>['ordered_external','partially_received'].includes(x.status)).map(x=>({category:'Receive orders',reason:`${x.title} has outstanding receipt work.`,sourceId:x.id}))]}

const convertible:Record<string,Record<string,number>>={mg:{mg:1,g:.001,kg:.000001},g:{mg:1000,g:1,kg:.001},kg:{mg:1e6,g:1000,kg:1},ml:{ml:1,L:.001},L:{ml:1000,L:1},pcs:{pcs:1}}
export function convertQuantity(quantity:number,from:string,to:string){return convertible[from]?.[to]==null?null:quantity*convertible[from][to]}
export function calculateOffer(item:RequestedItem,offer:SupplierOffer){
  const packageInRequestUnit=convertQuantity(offer.package_quantity,offer.package_unit,item.unit)
  const requiredInPackageUnit=convertQuantity(item.requested_quantity,item.unit,offer.package_unit)
  const purchaseQuantity=requiredInPackageUnit==null?null:Math.max(Math.ceil(requiredInPackageUnit/offer.package_quantity),offer.moq??1)
  const productSubtotal=purchaseQuantity==null||offer.item_price==null?null:purchaseQuantity*offer.item_price
  const landedKnown=productSubtotal==null?null:productSubtotal+(offer.shipping_cost??0)+(offer.tax_duty_estimate??0)-Math.min(offer.first_order_discount??0,productSubtotal)
  const landedComplete=productSubtotal!=null&&offer.shipping_cost!=null&&offer.tax_duty_estimate!=null
  const purchasedInRequestUnit=purchaseQuantity==null||packageInRequestUnit==null?null:purchaseQuantity*packageInRequestUnit
  const normalizedUnitPrice=packageInRequestUnit==null||offer.item_price==null?null:offer.item_price/packageInRequestUnit
  const requiredFields=[offer.country_code,offer.product_url,offer.item_price,offer.currency,offer.shipping_cost,offer.tax_duty_estimate,offer.delivery_estimate_days,offer.moq]
  const known=requiredFields.filter(value=>value!=null&&value!=='').length
  return{normalizedUnitPrice,quantityRequired:requiredInPackageUnit,purchaseQuantity,productSubtotal,estimatedLandedTotal:landedComplete?landedKnown:null,knownLandedTotal:landedKnown,effectiveLandedUnitCost:landedComplete&&purchasedInRequestUnit?landedKnown!/purchasedInRequestUnit:null,surplusQuantity:purchasedInRequestUnit==null?null:Math.max(0,purchasedInRequestUnit-item.requested_quantity),completeness:Math.round(known/requiredFields.length*100),confidence:offer.confidence}
}

export function calculateCartScenario(input:{scenario:ProcurementCartScenario;items:ProcurementCartScenarioItem[];discount?:SupplierDiscount|null;shippingRule?:SupplierShippingRule|null;now?:Date}){
  const merchandise=input.items.reduce((sum,item)=>sum+item.package_count*item.unit_price-Math.min(item.line_discount,item.package_count*item.unit_price),0)
  const discount=input.discount
  const now=input.now??new Date()
  const discountCurrencyMatches=!discount?.currency||discount.currency===input.scenario.currency
  const firstPurchaseAvailable=!discount?.first_purchase_only||discount.used_at==null
  const discountEligible=Boolean(discount&&discount.supplier_id===input.scenario.supplier_id&&['available','planned'].includes(discount.status)&&firstPurchaseAvailable&&discountCurrencyMatches&&(!discount.valid_from||new Date(discount.valid_from)<=now)&&(!discount.expires_at||new Date(discount.expires_at)>now)&&(discount.minimum_order_value==null||merchandise>=discount.minimum_order_value))
  let orderDiscount=0
  if(discountEligible&&discount){
    if(discount.discount_type==='percentage'&&discount.percentage!=null)orderDiscount=merchandise*discount.percentage/100
    if(discount.discount_type==='fixed_amount'&&discount.fixed_amount!=null)orderDiscount=discount.fixed_amount
    if(discount.maximum_discount!=null)orderDiscount=Math.min(orderDiscount,discount.maximum_discount)
    orderDiscount=Math.min(orderDiscount,merchandise)
  }
  const discountedMerchandise=merchandise-orderDiscount
  const rule=input.shippingRule
  const destinationMatches=Boolean(rule&&rule.supplier_id===input.scenario.supplier_id&&rule.status==='active'&&rule.currency===input.scenario.currency&&(
    rule.destination_country_code===input.scenario.destination_country_code||
    (!rule.destination_country_code&&rule.destination_region==='NO'&&input.scenario.destination_country_code==='NO')
  ))
  const applicableRule=destinationMatches?rule:null
  const freeShippingByRule=Boolean(applicableRule?.free_shipping_threshold!=null&&discountedMerchandise>=applicableRule.free_shipping_threshold)
  const freeShippingByDiscount=Boolean(discountEligible&&discount?.discount_type==='free_shipping')
  const shipping=input.scenario.manual_shipping_cost??(freeShippingByRule||freeShippingByDiscount?0:applicableRule?.flat_rate??null)
  const components={merchandise,orderDiscount,discountedMerchandise,shipping,tax:input.scenario.manual_tax_estimate??applicableRule?.tax_estimate??null,duty:input.scenario.manual_duty_estimate??applicableRule?.duty_estimate??null,paymentFee:input.scenario.payment_fee,additional:input.scenario.additional_cost}
  const nullableCosts=[['shipping',shipping],['tax',components.tax],['duty',components.duty],['paymentFee',components.paymentFee],['additional',components.additional]] as const
  const missing=nullableCosts.filter(([,value])=>value==null).map(([name])=>name)
  const knownTotal=discountedMerchandise+nullableCosts.reduce((sum,[,value])=>sum+Number(value??0),0)
  return{components,discountEligible,shippingRuleApplicable:destinationMatches,freeShipping:freeShippingByRule||freeShippingByDiscount,missing,knownTotal,landedTotal:missing.length===0?knownTotal:null,savings:orderDiscount,complete:missing.length===0}
}

export const procurementRequestTransitions:Record<ProcurementRequestStatus,ProcurementRequestStatus[]>={needed:['researching'],researching:['needed','recommended'],recommended:['researching','ordered'],ordered:['received'],received:[]}
export function canTransitionProcurementRequest(from:ProcurementRequestStatus,to:ProcurementRequestStatus){return procurementRequestTransitions[from].includes(to)}
