import{describe,expect,it,vi}from'vitest';import{compareQuotes,equipmentReadiness,procurementCopilot,purchasePlanTransition,quoteArithmetic,requirement,type EquipmentItem,type ProcurementData,type SupplierQuote}from'./procurement'
const quote={id:'q',supplier_id:'s',quote_reference:'Q1',quote_date:'2026-07-01',valid_until:'2026-07-20',currency:'NOK',shipping_cost:10,duties_estimate:5,tax_estimate:2,payment_fee:1,additional_cost:2,lead_time_days:3,status:'received',internal_notes:'',revision:1,created_at:''}as SupplierQuote
const line={id:'l',quote_id:'q',supplier_product_domain:'raw_material',supplier_product_id:'sp',description:'Oil',quantity:2,unit:'pack',unit_price:50,line_discount:10,line_total:90,moq:2,order_multiple:2,lead_time_days:3,display_order:0}
const equipment={id:'e',name:'Scale',equipment_type:'scale',status:'available',manufacturer:null,model:null,serial_number:null,supplier_id:null,purchase_date:null,purchase_cost:null,purchase_currency:null,location:'Lab',capacity_value:500,capacity_unit:'g',precision_value:.01,precision_unit:'g',internal_notes:'',archived_at:null,revision:1,created_at:'',updated_at:''}as EquipmentItem
describe('Phase 10A deterministic domain',()=>{
 it('calculates quote snapshots and all landed components',()=>expect(quoteArithmetic(quote,[line])).toMatchObject({knownTotal:110,complete:true,missing:[]}))
 it('surfaces missing shipping instead of inventing zero completeness',()=>expect(quoteArithmetic({...quote,shipping_cost:null},[line])).toMatchObject({knownTotal:100,complete:false,missing:['shipping']}))
 it('keeps native totals and refuses cross-currency comparison without a rate',()=>expect(compareQuotes([{...quote,currency:'EUR'}],[line],{},'NOK')[0]).toMatchObject({nativeTotal:110,comparisonTotal:null,rate:null}))
 it('uses an explicit manual comparison rate',()=>expect(compareQuotes([{...quote,currency:'EUR'}],[line],{'EUR:NOK':12},'NOK')[0].comparisonTotal).toBe(1320))
 it('computes uncovered target supply explainably',()=>expect(requirement({currentUsable:75,minimum:100,target:100,plannedDemand:10,openPlannedSupply:0})).toMatchObject({uncovered:35,urgency:'below_minimum'}))
 it('honours MOQ and order multiples',()=>expect(requirement({currentUsable:75,minimum:50,target:100,plannedDemand:0,openPlannedSupply:0,moq:30,orderMultiple:20}).suggested).toBe(40))
 it('open planned supply reduces a requirement without touching a ledger',()=>{const ledger=[{quantity:75}],before=structuredClone(ledger);expect(requirement({currentUsable:75,minimum:100,target:100,plannedDemand:10,openPlannedSupply:30}).uncovered).toBe(5);expect(ledger).toEqual(before)})
 it('validates the Purchase Plan lifecycle and requires explicit external order transition',()=>{expect(purchasePlanTransition('draft','ordered_external')).toBe(false);expect(purchasePlanTransition('approved_internal','ordered_external')).toBe(true)})
 it('warns rather than claiming readiness when calibration is missing',()=>expect(equipmentReadiness(equipment,[{id:'c',equipment_item_id:'e',capability_type:'weighs_mass',minimum_value:null,maximum_value:500,precision:.01,unit:'g',notes:''}],{id:'p',equipment_item_id:'e',status:'active',inspection_interval_days:null,calibration_interval_days:30,maintenance_interval_days:null,cleaning_required_before_use:false,cleaning_required_after_use:false,verification_notes:'',revision:1},[],{capacity:30,precision:.01,capability:'weighs_mass'})).toMatchObject({state:'review',issues:['Calibration not yet recorded.']}))
 it('rejects out-of-service equipment as operationally ready',()=>expect(equipmentReadiness({...equipment,status:'out_of_service'},[],undefined,[]).state).toBe('review'))
 it('treats service evidence as input without mutating it',()=>{const events=[{id:'x',equipment_item_id:'e',event_type:'cleaning',performed_at:'2026-07-16',performed_by:null,result_status:'recorded',notes:'',next_due_at:null,created_at:''}],copy=structuredClone(events);equipmentReadiness(equipment,[],undefined,events);expect(events).toEqual(copy)})
 it('Procurement Copilot is deterministic and makes no model call',()=>{const fetch=vi.spyOn(globalThis,'fetch');const data={suppliers:[],contacts:[],candidates:[{id:'c',candidate_name:'Candidate',status:'unreviewed'}],quotes:[],quoteLines:[],stockPolicies:[],purchasePlans:[],purchasePlanLines:[],equipment:[],capabilities:[],equipmentPolicies:[],serviceEvents:[],processRequirements:[]}as unknown as ProcurementData;expect(procurementCopilot(data)[0].category).toBe('Review suppliers');expect(fetch).not.toHaveBeenCalled();fetch.mockRestore()})
})
