export const supplierTypes=['raw_material','fragrance','packaging','equipment','laboratory','compliance_service','logistics','printing','general','mixed'] as const
export type SupplierType=typeof supplierTypes[number]
export const supplierStatuses=['research','candidate','approved_internal','active','paused','rejected','archived'] as const
export type SupplierStatus=typeof supplierStatuses[number]
export const supplierVerificationStates=['unknown','needs_review','reviewed','rejected'] as const
export type SupplierVerificationState=typeof supplierVerificationStates[number]
export interface Supplier{id:string;legal_name:string;trading_name:string|null;supplier_type:SupplierType;status:SupplierStatus;website_url:string|null;country_code:string|null;default_currency:string|null;default_lead_time_days:number|null;default_payment_terms:string|null;default_incoterm:string|null;minimum_order_value:number|null;internal_rating:number|null;internal_notes:string;is_preferred:boolean;verification_state:SupplierVerificationState;archived_at:string|null;revision:number;created_at:string;updated_at:string}
export interface SupplierCreateInput{legal_name:string;trading_name:string|null;supplier_type:SupplierType;status:SupplierStatus;website_url:string|null;country_code:string|null;default_currency:string|null;verification_state:SupplierVerificationState;internal_notes:string;is_preferred:boolean}
export interface SupplierContact{id:string;supplier_id:string;name:string;role:string|null;email:string|null;phone:string|null;preferred_contact_method:string|null;notes:string;is_primary:boolean;archived_at:string|null}
export interface ResearchCandidate{id:string;candidate_name:string;candidate_type:string;source_url:string|null;source_title:string|null;country_code:string|null;currency:string|null;candidate_summary:string|null;claimed_capabilities:string[];evidence_notes:string|null;status:'unreviewed'|'reviewing'|'shortlisted'|'rejected'|'converted'|'archived';converted_supplier_id:string|null;rejection_reason:string|null;created_at:string}
export interface SupplierQuote{id:string;supplier_id:string;quote_reference:string|null;quote_date:string;valid_until:string|null;currency:string;shipping_cost:number|null;duties_estimate:number|null;tax_estimate:number|null;payment_fee:number|null;additional_cost:number|null;lead_time_days:number|null;status:string;internal_notes:string;revision:number;created_at:string}
export interface QuoteLine{id:string;quote_id:string;supplier_product_domain:string|null;supplier_product_id:string|null;description:string;quantity:number;unit:string;unit_price:number;line_discount:number;line_total:number;moq:number|null;order_multiple:number|null;lead_time_days:number|null;display_order:number}
export interface StockPolicy{id:string;inventory_domain:'raw_material'|'packaging';ingredient_id:string|null;supplier_product_id:string|null;packaging_component_id:string|null;packaging_supplier_product_id:string|null;policy_status:'draft'|'active'|'paused'|'archived';minimum_on_hand:number;target_on_hand:number;safety_stock:number|null;reorder_point:number|null;preferred_order_quantity:number|null;unit:string;expected_lead_time_days:number|null;is_basis_item:boolean;rationale:string}
export type PurchasePlanStatus='draft'|'approved'|'verification_required'|'checkout_ready'|'superseded'|'cancelled'
export interface PurchasePlan{id:string;workspace_id:string;title:string;status:PurchasePlanStatus;purpose:string;target_date:string|null;supplier_id:string|null;currency:string|null;base_currency:string|null;source_type:string|null;internal_notes:string;estimated_merchandise_total:number|null;estimated_landed_total:number|null;known_minimum:number|null;supplier_count:number|null;line_count:number|null;placement_state:'unplaced';order_authorized:boolean;target_budget:number|null;absolute_stop:number|null;credible_range_minimum:number|null;credible_range_maximum:number|null;worst_credible_range_minimum:number|null;worst_credible_range_maximum:number|null;commercial_checked_at:string|null;revision:number;created_at:string;updated_at:string}
export interface PurchasePlanBasket{id:string;workspace_id:string;purchase_plan_id:string;supplier_id:string;supplier_name_snapshot:string;supplier_url_snapshot:string|null;currency:string;merchandise_subtotal:number|null;confirmed_discount:number|null;post_discount_subtotal:number|null;shipping:number|null;vat_adjustment:number|null;import_vat:number|null;customs:number|null;dangerous_goods_fee:number|null;handling:number|null;payment_fx:number|null;known_minimum:number|null;confirmed_total:number|null;commercial_checked_at:string|null;commercial_assumption_snapshot:Record<string,unknown>;created_at:string}
export interface PurchasePlanLine{id:string;workspace_id:string;purchase_plan_id:string;purchase_plan_basket_id:string|null;inventory_domain:'raw_material'|'packaging'|'equipment';supplier_product_id:string|null;packaging_component_id:string|null;source_kind:'supplier_product'|'packaging_supplier_product'|'packaging_component'|'manual'|'scenario_snapshot'|'legacy'|null;source_record_id:string|null;description:string;supplier_product_name_snapshot:string|null;supplier_sku_snapshot:string|null;planned_quantity:number;unit:string;pack_count:number|null;pack_size:number|null;estimated_unit_price:number|null;estimated_line_total:number|null;currency:string|null;product_url_snapshot:string|null;commercial_checked_at:string|null;commercial_evidence_snapshot:Record<string,unknown>;requirement_reason:string|null;requirement_basis:Record<string,unknown>;display_order:number;created_at:string}
export type DraftPlanSourceKind='supplier_product'|'packaging_supplier_product'|'packaging_component'|'manual'
export interface DraftPurchasePlanLineInput{sourceDomain:'raw_material'|'packaging'|'equipment';sourceKind:DraftPlanSourceKind;sourceRecordId:string|null;productTitle:string;sku:string|null;packageQuantity:number;packageUnit:string;purchaseQuantity:number;unitPrice:number|null;lineTotal:number|null;currency:string;sourceUrl:string|null;checkedAt:string;evidence:Record<string,unknown>}
export interface DraftPurchasePlanBasketInput{supplierId:string;currency:string;listSubtotal:number|null;verifiedDiscount:number|null;postDiscountSubtotal:number|null;shipping:number|null;vatAdjustment:number|null;importVat:number|null;duty:number|null;dangerousGoodsFee:number|null;brokerageHandling:number|null;paymentFx:number|null;knownMinimum:number|null;checkedAt:string;warnings:string[];evidence:Record<string,unknown>;lines:DraftPurchasePlanLineInput[]}
export interface DraftPurchasePlanInput{idempotencyKey:string;plan:{title:string;purpose:string;targetDate:string|null;baseCurrency:string;notes:string;targetBudget:number;absoluteStop:number;credibleRangeMinimum:number|null;credibleRangeMaximum:number|null;worstCredibleRangeMinimum:number|null;worstCredibleRangeMaximum:number|null;knownMerchandiseTotal:number|null;knownMinimum:number|null;estimatedLandedTotal:number|null;checkedAt:string;evidence:Record<string,unknown>};baskets:DraftPurchasePlanBasketInput[]}
export interface DraftPlanReceipt{schemaVersion:1;entityType:'purchase_plan'|'purchase_plan_basket';recordId:string;workspaceId:string;operation:'created'|'reused';persistedAt:string;naturalIdentity:Record<string,string>;status?:'draft';placementState?:'unplaced';orderAuthorized?:false;parentPlanId?:string;supplierId?:string;currency?:string}
export interface DraftPlanLineEvidence{recordId:string;workspaceId:string;parentPlanId:string;parentBasketId:string;sourceKind:DraftPlanSourceKind;sourceRecordId:string|null;sku:string|null;packageQuantity:number;packageUnit:string;purchaseQuantity:number;persistedAt:string}
export interface DraftPurchasePlanReceiptBundle{schemaVersion:1;operation:'created'|'reused';plan:DraftPlanReceipt&{status:'draft';placementState:'unplaced';orderAuthorized:false};baskets:DraftPlanReceipt[];lines:DraftPlanLineEvidence[]}
export interface DraftPurchasePlanAggregate{plan:PurchasePlan;baskets:PurchasePlanBasket[];lines:PurchasePlanLine[]}
export type PurchaseOrderStatus='draft'|'placed'|'supplier_confirmed'|'partially_confirmed'|'confirmation_exception'|'partially_shipped'|'shipped'|'cancelled'|'confirmed'|'partially_fulfilled'|'fulfilled'
export interface PurchaseOrder{id:string;supplier_id:string;source_purchase_plan_id:string;source_purchase_plan_revision:number;status:PurchaseOrderStatus;payment_status:string;confirmation_state:string;order_reference:string|null;supplier_order_number:string|null;external_order_date:string|null;currency:string|null;merchandise_subtotal:number|null;discount:number|null;shipping:number|null;tax:number|null;total:number|null;supplier_url_snapshot:string|null;order_url:string|null;notes:string;requires_receiving_review:boolean;revision:number;created_at:string;updated_at:string}
export interface PurchaseOrderLine{id:string;purchase_order_id:string;source_purchase_plan_line_id:string;supplier_product_id:string|null;canonical_ingredient_id:string|null;product_name_snapshot:string;package_size:number|null;package_unit:string|null;ordered_package_count:number|null;ordered_quantity:number;ordered_unit:string;unit_price:number|null;currency:string|null;line_subtotal:number|null;legacy_received_quantity:number|null;legacy_receiving_state:'unknown'|'partial'|'received'|null;notes:string}
export interface EquipmentItem{id:string;name:string;equipment_type:string;status:string;quantity:number|null;category:string|null;material:string|null;manufacturer:string|null;model:string|null;serial_number:string|null;supplier_id:string|null;purchase_date:string|null;purchase_cost:number|null;purchase_currency:string|null;location:string|null;capacity_value:number|null;capacity_unit:string|null;minimum_value:number|null;maximum_value:number|null;precision_value:number|null;precision_unit:string|null;primary_use:string|null;calibration_status:'not_applicable'|'not_recorded'|'to_verify'|'verified'|'calibrated'|'calibration_due'|'out_of_service';calibration_date:string|null;calibration_due_date:string|null;calibration_note:string|null;operational_notes:string|null;ownership_state:'candidate'|'planned'|'ordered'|'owned'|'not_owned';availability_state:'unknown'|'available'|'in_use'|'unavailable'|'out_of_service';internal_notes:string;archived_at:string|null;revision:number;created_at:string;updated_at:string}
export interface EquipmentCapability{id:string;equipment_item_id:string;capability_type:string;minimum_value:number|null;maximum_value:number|null;precision:number|null;unit:string|null;notes:string}
export interface EquipmentPolicy{id:string;equipment_item_id:string;status:string;inspection_interval_days:number|null;calibration_interval_days:number|null;maintenance_interval_days:number|null;cleaning_required_before_use:boolean;cleaning_required_after_use:boolean;verification_notes:string;revision:number}
export interface EquipmentServiceEvent{id:string;equipment_item_id:string;event_type:string;performed_at:string;performed_by:string|null;result_status:string;notes:string;next_due_at:string|null;created_at:string}
export interface ProcessEquipmentRequirement{id:string;source_type:string;source_id:string;formula_version_id:string|null;catalog_key:string|null;requirement_name:string|null;category:string|null;required_equipment_type:string|null;required_capability:string|null;minimum_capacity:number|null;required_precision:number|null;minimum_value:number|null;maximum_value:number|null;unit:string|null;required_material:string|null;quantity_required:number;requirement_level:'required'|'recommended'|'optional';preparation_instructions:string;notes:string;sort_order:number;revision:number;created_at:string;updated_at:string}
export type ProcurementRequestStatus='identified'|'researching'|'specification_required'|'quote_requested'|'planned'|'ready_to_order'|'ordered'|'partially_received'|'received'|'cancelled'|'rejected'
export type ProcurementPriority='low'|'normal'|'high'|'urgent'
export type ProcurementDocumentState='unknown'|'available'|'unavailable'|'partial'
export type ProcurementStockState='unknown'|'in_stock'|'limited'|'backorder'|'out_of_stock'
export interface ProcurementRequest{id:string;title:string;status:ProcurementRequestStatus;category:string;priority:ProcurementPriority;needed_by:string|null;notes:string;source_type?:string|null;source_id?:string|null;source_group?:string|null;source_registry_version?:string|null;revision:number;created_at:string;updated_at:string}
export interface RequestedItem{id:string;procurement_request_id:string;name:string;category:string;requested_quantity:number|null;unit:string|null;requirement_type?:string;reason?:string|null;status?:ProcurementRequestStatus;package_preference?:string|null;target_supplier_id?:string|null;target_supplier_product_domain?:'raw_material'|'packaging'|'equipment'|null;target_supplier_product_id?:string|null;decision_notes?:string|null;sourcing_notes?:string|null;source_target_id?:string|null;source_benchmark_ids?:string[];source_benchmark_ingredient_incis?:string[];source_functions?:string[];preferred_supplier_hint?:string|null;intended_product_ids:string[];intended_formula_ids:string[];required_specifications:string[];acceptable_substitutes:string[];priority:ProcurementPriority;needed_by:string|null;notes:string;display_order:number;created_at:string;updated_at:string}
export type SupplierProductSourceDomain='raw_material'|'packaging'
export interface SupplierProductSource{domain:SupplierProductSourceDomain;id:string;supplier_id:string;supplier_name:string;product_name:string;supplier_sku:string|null;package_quantity:number|null;package_unit:string|null;price:number|null;currency:string|null;product_url:string|null;country_code:string|null;lifecycle_status:string;product_status:string|null;discontinued:boolean;updated_at:string}
export interface SupplierOffer{id:string;requested_item_id:string;supplier_id:string;source_supplier_product_domain:SupplierProductSourceDomain|null;source_supplier_product_id:string|null;product_title:string;product_url:string|null;country_code:string|null;package_quantity:number;package_unit:string;item_price:number|null;currency:string|null;moq:number|null;shipping_cost:number|null;tax_duty_estimate:number|null;delivery_estimate_days:number|null;stock_status:ProcurementStockState;coa_availability:ProcurementDocumentState;sds_availability:ProcurementDocumentState;technical_document_availability:ProcurementDocumentState;certification_claims:string[];first_order_discount:number|null;notes:string;date_checked:string;confidence:'low'|'medium'|'high'|'unknown';created_at:string;updated_at:string}
export type SupplierOfferSourceLink={source_supplier_product_domain:null;source_supplier_product_id:null}|{source_supplier_product_domain:SupplierProductSourceDomain;source_supplier_product_id:string}
export type SupplierOfferCreateInput=Omit<SupplierOffer,'id'|'created_at'|'updated_at'|'source_supplier_product_domain'|'source_supplier_product_id'>&SupplierOfferSourceLink
export interface ProcurementRecommendation{id:string;procurement_request_id:string;requested_item_id:string;supplier_offer_id:string;summary:string;rationale:string;recommended_purchase_quantity:number|null;status:'draft'|'recommended'|'superseded';created_at:string;updated_at:string}

export type SupplierDiscountStatus='available'|'planned'|'used'|'expired'|'invalid'|'unknown'
export interface SupplierDiscount{id:string;supplier_id:string;name:string;discount_type:'percentage'|'fixed_amount'|'free_shipping'|'other';percentage:number|null;fixed_amount:number|null;currency:string|null;coupon_code:string|null;minimum_order_value:number|null;maximum_discount:number|null;first_purchase_only:boolean;requires_newsletter:boolean;valid_from:string|null;expires_at:string|null;status:SupplierDiscountStatus;source_url:string|null;evidence_notes:string;verified_at:string|null;used_at:string|null;created_at:string;updated_at:string}
export interface SupplierShippingRule{id:string;supplier_id:string;destination_country_code:string|null;destination_region:string|null;shipping_method:string|null;currency:string|null;flat_rate:number|null;free_shipping_threshold:number|null;minimum_order_value:number|null;delivery_estimate_min_days:number|null;delivery_estimate_max_days:number|null;tax_handling:'unknown'|'included'|'excluded'|'destination_checkout'|'import_due';duty_handling:'unknown'|'included'|'excluded'|'import_due';tax_estimate:number|null;duty_estimate:number|null;status:'active'|'needs_verification'|'inactive'|'expired';source_url:string|null;evidence_notes:string;verified_at:string|null;created_at:string;updated_at:string}
export type SupplierDocumentType='coa'|'sds'|'ifra'|'allergen_declaration'|'certificate'|'batch_traceability'
export type SupplierDocumentCapability='unknown'|'available'|'unavailable'|'available_on_request'|'not_applicable'
export type SupplierDocumentVerification='unverified'|'pending_review'|'verified'|'rejected'|'expired'
export interface SupplierDocumentRecord{id:string;supplier_id:string;document_type:SupplierDocumentType;document_subtype:string|null;capability_state:SupplierDocumentCapability;verification_state:SupplierDocumentVerification;evidence_url:string|null;document_title:string|null;issuer:string|null;issue_date:string|null;expiry_date:string|null;checked_date:string|null;source_reference:string|null;notes:string;scope_type:'supplier_wide';revision:number;archived_at:string|null;created_at:string;updated_at:string}
export type SupplierEventType='quote_received'|'quote_updated'|'purchase_planned'|'purchase_placed'|'order_confirmed'|'shipment_dispatched'|'shipment_received'|'partial_shipment'|'cancelled_order'|'refund'|'replacement_shipment'|'damaged_shipment'|'customs_issue'|'invoice_received'|'payment_completed'|'documentation_requested'|'documentation_received'|'documentation_rejected'|'communication'|'manual_note'
export interface SupplierEvent{id:string;supplier_id:string;event_type:SupplierEventType;occurred_at:string;expected_at:string|null;title:string;description:string;supplier_quote_id:string|null;procurement_request_id:string|null;supplier_offer_id:string|null;purchase_plan_id:string|null;purchase_order_id?:string|null;supplier_document_record_id:string|null;revision:number;archived_at:string|null;created_at:string;updated_at:string}
export interface ProcurementCartScenario{id:string;supplier_id:string;name:string;destination_country_code:string;currency:string;shipping_rule_id:string|null;discount_id:string|null;manual_shipping_cost:number|null;manual_tax_estimate:number|null;manual_duty_estimate:number|null;payment_fee:number|null;additional_cost:number|null;status:'draft'|'ready_for_review'|'selected'|'superseded'|'archived';notes:string;calculated_at:string|null;created_at:string;updated_at:string}
export interface ProcurementCartScenarioItem{id:string;scenario_id:string;supplier_offer_id:string;requested_item_id:string;package_count:number;unit_price:number;line_discount:number;display_order:number;notes:string;created_at:string;updated_at:string}

import type{OfferCandidate,ProcurementProviderDiagnostic,ResearchJob}from'./assistedResearch'
export interface ProcurementData{suppliers:Supplier[];supplierProductSources:SupplierProductSource[];contacts:SupplierContact[];candidates:ResearchCandidate[];quotes:SupplierQuote[];quoteLines:QuoteLine[];stockPolicies:StockPolicy[];purchasePlans:PurchasePlan[];purchasePlanBaskets:PurchasePlanBasket[];purchasePlanLines:PurchasePlanLine[];purchaseOrders:PurchaseOrder[];purchaseOrderLines:PurchaseOrderLine[];equipment:EquipmentItem[];capabilities:EquipmentCapability[];equipmentPolicies:EquipmentPolicy[];serviceEvents:EquipmentServiceEvent[];processRequirements:ProcessEquipmentRequirement[];requests:ProcurementRequest[];requestedItems:RequestedItem[];offers:SupplierOffer[];recommendations:ProcurementRecommendation[];supplierDiscounts:SupplierDiscount[];supplierShippingRules:SupplierShippingRule[];supplierDocuments:SupplierDocumentRecord[];supplierEvents:SupplierEvent[];cartScenarios:ProcurementCartScenario[];cartScenarioItems:ProcurementCartScenarioItem[];researchJobs:ResearchJob[];researchDiagnostics:ProcurementProviderDiagnostic[];offerCandidates:OfferCandidate[]}

export const emptyProcurementData=():ProcurementData=>({suppliers:[],supplierProductSources:[],contacts:[],candidates:[],quotes:[],quoteLines:[],stockPolicies:[],purchasePlans:[],purchasePlanBaskets:[],purchasePlanLines:[],purchaseOrders:[],purchaseOrderLines:[],equipment:[],capabilities:[],equipmentPolicies:[],serviceEvents:[],processRequirements:[],requests:[],requestedItems:[],offers:[],recommendations:[],supplierDiscounts:[],supplierShippingRules:[],supplierDocuments:[],supplierEvents:[],cartScenarios:[],cartScenarioItems:[],researchJobs:[],researchDiagnostics:[],offerCandidates:[]})
export function quoteArithmetic(quote:SupplierQuote,lines:QuoteLine[]){const merchandise=lines.filter(x=>x.quote_id===quote.id).reduce((sum,x)=>sum+Number(x.quantity)*Number(x.unit_price)-Number(x.line_discount||0),0),components={merchandise,shipping:quote.shipping_cost,duties:quote.duties_estimate,tax:quote.tax_estimate,paymentFee:quote.payment_fee,additional:quote.additional_cost},missing=Object.entries(components).filter(([key,value])=>key!=='merchandise'&&value==null).map(([key])=>key),knownTotal=Object.values(components).reduce<number>((sum,value)=>sum+Number(value??0),0);return{components,missing,knownTotal,complete:missing.length===0}}
export function compareQuotes(quotes:SupplierQuote[],lines:QuoteLine[],rates:Record<string,number>,comparisonCurrency:string){return quotes.map(quote=>{const landed=quoteArithmetic(quote,lines),rate=quote.currency===comparisonCurrency?1:rates[`${quote.currency}:${comparisonCurrency}`];return{quote,nativeTotal:landed.knownTotal,comparisonTotal:rate==null?null:landed.knownTotal*rate,rate:rate??null,missing:rate==null&&quote.currency!==comparisonCurrency?[...landed.missing,'exchangeRate']:landed.missing}})}
export function requirement(input:{currentUsable:number;minimum:number;target:number;plannedDemand:number;openPlannedSupply:number;moq?:number;orderMultiple?:number}){const uncovered=Math.max(0,input.target+input.plannedDemand-input.currentUsable-input.openPlannedSupply),minimumGap=Math.max(0,input.minimum+input.plannedDemand-input.currentUsable-input.openPlannedSupply);let suggested=uncovered;if(suggested&&input.moq)suggested=Math.max(suggested,input.moq);if(suggested&&input.orderMultiple)suggested=Math.ceil(suggested/input.orderMultiple)*input.orderMultiple;return{uncovered,suggested,urgency:minimumGap>0?'below_minimum':uncovered>0?'planned_need':'covered',basis:{...input}}}
export function purchasePlanTransition(from:PurchasePlanStatus,to:PurchasePlanStatus){const allowed:Record<PurchasePlanStatus,PurchasePlanStatus[]>={draft:['verification_required','approved','cancelled'],verification_required:['draft','approved','cancelled'],approved:['verification_required','checkout_ready','superseded','cancelled'],checkout_ready:['verification_required','superseded','cancelled'],superseded:[],cancelled:[]};return allowed[from].includes(to)}
export function purchaseOrderTransition(from:PurchaseOrderStatus,to:PurchaseOrderStatus){const allowed:Record<PurchaseOrderStatus,PurchaseOrderStatus[]>={draft:['placed','cancelled'],placed:['supplier_confirmed','partially_confirmed','confirmation_exception','cancelled'],supplier_confirmed:['partially_shipped','shipped','confirmation_exception','cancelled'],partially_confirmed:['supplier_confirmed','confirmation_exception','partially_shipped','cancelled'],confirmation_exception:['supplier_confirmed','partially_confirmed','cancelled'],partially_shipped:['shipped','confirmation_exception','cancelled'],shipped:[],confirmed:['cancelled','partially_fulfilled','fulfilled'],partially_fulfilled:['fulfilled','cancelled'],fulfilled:[],cancelled:[]};return allowed[from].includes(to)}
export function equipmentReadiness(item:EquipmentItem,capabilities:EquipmentCapability[],policy:EquipmentPolicy|undefined,events:EquipmentServiceEvent[],requirement?:{capacity?:number;precision?:number;capability?:string}){const issues:string[]=[];if(!['available','in_use'].includes(item.status))issues.push(`Status is ${item.status.replaceAll('_',' ')}.`);if(requirement?.capability&&!capabilities.some(x=>x.equipment_item_id===item.id&&x.capability_type===requirement.capability))issues.push(`Missing ${requirement.capability} capability.`);if(requirement?.capacity!=null&&(item.capacity_value==null||item.capacity_value<requirement.capacity))issues.push(item.capacity_value==null?'Capacity not recorded.':'Capacity below requirement.');if(requirement?.precision!=null&&(item.precision_value==null||item.precision_value>requirement.precision))issues.push(item.precision_value==null?'Precision not recorded.':'Precision may be insufficient.');const now=Date.now(),latest=(type:string)=>events.filter(x=>x.equipment_item_id===item.id&&x.event_type===type).sort((a,b)=>b.performed_at.localeCompare(a.performed_at))[0];if(policy?.calibration_interval_days&&!latest('calibration'))issues.push('Calibration not yet recorded.');for(const type of ['calibration','maintenance','inspection']){const due=latest(type)?.next_due_at;if(due&&new Date(due).getTime()<=now)issues.push(`${type} is due.`)}if(policy?.cleaning_required_before_use&&!latest('cleaning'))issues.push('Cleaning record required before use.');return{state:issues.length?'review':'ready',issues,label:issues.length?'Operational readiness needs review.':'Operationally ready under recorded Koalafrog rules.'}}
export function procurementCopilot(data:ProcurementData){return[...data.candidates.filter(x=>x.status==='unreviewed').map(x=>({category:'Review suppliers',reason:`${x.candidate_name} awaits human review.`,sourceId:x.id})),...data.quotes.filter(x=>x.valid_until&&new Date(x.valid_until).getTime()-Date.now()<14*86400000&&!['expired','declined','archived'].includes(x.status)).map(x=>({category:'Review quotes',reason:`Quote ${x.quote_reference??x.id} expires soon.`,sourceId:x.id})),...data.equipment.flatMap(item=>{const readiness=equipmentReadiness(item,data.capabilities,data.equipmentPolicies.find(x=>x.equipment_item_id===item.id),data.serviceEvents);return readiness.issues.map(reason=>({category:'Equipment attention',reason:`${item.name}: ${reason}`,sourceId:item.id}))}),...(data.purchaseOrders??[]).filter(x=>['placed','supplier_confirmed','partially_confirmed','confirmation_exception','partially_shipped','shipped','confirmed','partially_fulfilled'].includes(x.status)).map(x=>({category:['placed','supplier_confirmed','partially_confirmed','confirmation_exception'].includes(x.status)?'Supplier execution':'Receive orders',reason:`Order ${x.order_reference??x.id} has outstanding ${['placed','supplier_confirmed','partially_confirmed','confirmation_exception'].includes(x.status)?'supplier execution':'physical receipt'} work.`,sourceId:x.id}))]}

const convertible:Record<string,Record<string,number>>={mg:{mg:1,g:.001,kg:.000001},g:{mg:1000,g:1,kg:.001},kg:{mg:1e6,g:1000,kg:1},ml:{ml:1,L:.001},L:{ml:1000,L:1},pcs:{pcs:1}}
export function convertQuantity(quantity:number,from:string,to:string){return convertible[from]?.[to]==null?null:quantity*convertible[from][to]}
export function calculateOffer(item:RequestedItem,offer:SupplierOffer){
  if(item.requested_quantity==null||!item.unit)return{normalizedUnitPrice:null,quantityRequired:null,purchaseQuantity:null,productSubtotal:null,estimatedLandedTotal:null,knownLandedTotal:null,effectiveLandedUnitCost:null,surplusQuantity:null,completeness:0,confidence:offer.confidence}
  const packageInRequestUnit=convertQuantity(offer.package_quantity,offer.package_unit,item.unit)
  const requiredInPackageUnit=convertQuantity(item.requested_quantity,item.unit,offer.package_unit)
  const purchaseQuantity=requiredInPackageUnit==null?null:Math.max(Math.ceil(requiredInPackageUnit/offer.package_quantity),offer.moq??1)
  const productSubtotal=purchaseQuantity==null||offer.item_price==null?null:purchaseQuantity*offer.item_price
  const landedKnown=productSubtotal==null?null:productSubtotal+(offer.shipping_cost??0)+(offer.tax_duty_estimate??0)-Math.min(offer.first_order_discount??0,productSubtotal)
  const landedComplete=productSubtotal!=null&&offer.shipping_cost!=null&&offer.tax_duty_estimate!=null
  const purchasedInRequestUnit=purchaseQuantity==null||packageInRequestUnit==null?null:purchaseQuantity*packageInRequestUnit
  const normalizedUnitPrice=packageInRequestUnit==null||offer.item_price==null?null:offer.item_price/packageInRequestUnit
  const requiredFields=[offer.country_code,offer.product_url,offer.item_price,offer.currency,offer.shipping_cost,offer.tax_duty_estimate,offer.delivery_estimate_days,offer.moq]
  const known=requiredFields.filter(value=>value!=null&&value!=='').length
  return{normalizedUnitPrice,quantityRequired:requiredInPackageUnit,purchaseQuantity,productSubtotal,estimatedLandedTotal:landedComplete?landedKnown:null,knownLandedTotal:landedKnown,effectiveLandedUnitCost:landedComplete&&purchasedInRequestUnit?landedKnown!/purchasedInRequestUnit:null,surplusQuantity:purchasedInRequestUnit==null?null:Math.max(0,purchasedInRequestUnit-item.requested_quantity),completeness:Math.round(known/requiredFields.length*100),confidence:offer.confidence}
}

export function calculateCartScenario(input:{scenario:ProcurementCartScenario;items:ProcurementCartScenarioItem[];discount?:SupplierDiscount|null;shippingRule?:SupplierShippingRule|null;now?:Date}){
  const merchandise=input.items.reduce((sum,item)=>sum+item.package_count*item.unit_price-Math.min(item.line_discount,item.package_count*item.unit_price),0)
  const discount=input.discount
  const now=input.now??new Date()
  const discountCurrencyMatches=!discount?.currency||discount.currency===input.scenario.currency
  const firstPurchaseAvailable=!discount?.first_purchase_only||discount.used_at==null
  const discountEligible=Boolean(discount&&discount.supplier_id===input.scenario.supplier_id&&['available','planned'].includes(discount.status)&&firstPurchaseAvailable&&discountCurrencyMatches&&(!discount.valid_from||new Date(discount.valid_from)<=now)&&(!discount.expires_at||new Date(discount.expires_at)>now)&&(discount.minimum_order_value==null||merchandise>=discount.minimum_order_value))
  let orderDiscount=0
  if(discountEligible&&discount){
    if(discount.discount_type==='percentage'&&discount.percentage!=null)orderDiscount=merchandise*discount.percentage/100
    if(discount.discount_type==='fixed_amount'&&discount.fixed_amount!=null)orderDiscount=discount.fixed_amount
    if(discount.maximum_discount!=null)orderDiscount=Math.min(orderDiscount,discount.maximum_discount)
    orderDiscount=Math.min(orderDiscount,merchandise)
  }
  const discountedMerchandise=merchandise-orderDiscount
  const rule=input.shippingRule
  const destinationMatches=Boolean(rule&&rule.supplier_id===input.scenario.supplier_id&&rule.status==='active'&&rule.currency===input.scenario.currency&&(
    rule.destination_country_code===input.scenario.destination_country_code||
    (!rule.destination_country_code&&rule.destination_region==='NO'&&input.scenario.destination_country_code==='NO')
  ))
  const applicableRule=destinationMatches?rule:null
  const freeShippingByRule=Boolean(applicableRule?.free_shipping_threshold!=null&&discountedMerchandise>=applicableRule.free_shipping_threshold)
  const freeShippingByDiscount=Boolean(discountEligible&&discount?.discount_type==='free_shipping')
  const shipping=input.scenario.manual_shipping_cost??(freeShippingByRule||freeShippingByDiscount?0:applicableRule?.flat_rate??null)
  const components={merchandise,orderDiscount,discountedMerchandise,shipping,tax:input.scenario.manual_tax_estimate??applicableRule?.tax_estimate??null,duty:input.scenario.manual_duty_estimate??applicableRule?.duty_estimate??null,paymentFee:input.scenario.payment_fee,additional:input.scenario.additional_cost}
  const nullableCosts=[['shipping',shipping],['tax',components.tax],['duty',components.duty],['paymentFee',components.paymentFee],['additional',components.additional]] as const
  const missing=nullableCosts.filter(([,value])=>value==null).map(([name])=>name)
  const knownTotal=discountedMerchandise+nullableCosts.reduce((sum,[,value])=>sum+Number(value??0),0)
  return{components,discountEligible,shippingRuleApplicable:destinationMatches,freeShipping:freeShippingByRule||freeShippingByDiscount,missing,knownTotal,landedTotal:missing.length===0?knownTotal:null,savings:orderDiscount,complete:missing.length===0}
}

export const procurementRequestTransitions:Record<ProcurementRequestStatus,ProcurementRequestStatus[]>={
 identified:['researching','specification_required','cancelled','rejected'],
 researching:['identified','specification_required','quote_requested','planned','cancelled','rejected'],
 specification_required:['researching','planned','cancelled','rejected'],
 quote_requested:['researching','planned','cancelled','rejected'],
 planned:['researching','ready_to_order','cancelled','rejected'],
 ready_to_order:['planned','ordered','cancelled'],
 ordered:['partially_received','received','cancelled'],
 partially_received:['received','cancelled'],
 received:[],cancelled:[],rejected:[],
}
export function canTransitionProcurementRequest(from:ProcurementRequestStatus,to:ProcurementRequestStatus){return procurementRequestTransitions[from].includes(to)}
