import { ArrowDown, ArrowUp, LockKeyhole, Plus, Trash2 } from 'lucide-react'
import type { FormulaLine, FormulaVersion } from '../../../types/domain'
import { calculatePercentageTotal, percentageBalance } from '../domain/formulaLogic'
import { useFormulaData } from '../state/FormulaDataContext'
import { ingredientBalance, stockState } from '../../inventory/domain/inventoryLogic'

export function FormulaBuilder({ version, lines }: { version: FormulaVersion; lines: FormulaLine[] }) {
  const { ingredients, inventoryLots, inventoryMovements, updateLine, addLine, removeLine, moveLine } = useFormulaData(); const editable = version.status === 'Draft'
  const sorted = [...lines].sort((a,b) => a.sortOrder-b.sortOrder); const total = calculatePercentageTotal(lines); const balance = percentageBalance(lines)
  const available = ingredients.filter((ingredient) => !lines.some((line) => line.ingredientId === ingredient.id))
  return <section className="formula-builder panel"><div className="builder-heading"><div><h2>Composition</h2><p>Percentage by weight is canonical. Inventory shown here is informational only.</p></div><div className={`formula-total ${balance === 0 ? 'valid' : balance < 0 ? 'over' : ''}`}><span>Total</span><strong>{total}%</strong><small>{balance === 0 ? 'Valid · exactly 100%' : balance > 0 ? `${balance}% remaining` : `${Math.abs(balance)}% over`}</small></div></div>
    {!editable && <div className="frozen-banner"><LockKeyhole size={15} /><span><strong>Frozen historical version</strong>Composition is read-only. Duplicate this version to make changes safely.</span></div>}
  <div className="builder-table"><div className="builder-columns"><span>Order</span><span>Ingredient</span><span>Phase</span><span>Percentage</span><span>Formulation role</span><span>Line notes</span><span /></div>{sorted.map((line, index) => { const ingredient = ingredients.find((item) => item.id === line.ingredientId); const state = ingredient ? stockState(ingredient, inventoryLots, inventoryMovements) : 'No Inventory Data'; return <div className="builder-line" key={line.id}><div className="reorder"><button disabled={!editable || index === 0} aria-label="Move ingredient up" onClick={() => moveLine(version.id, line.id, -1)}><ArrowUp size={12} /></button><button disabled={!editable || index === sorted.length - 1} aria-label="Move ingredient down" onClick={() => moveLine(version.id, line.id, 1)}><ArrowDown size={12} /></button></div><div className="ingredient-cell"><strong>{ingredient?.commonName}</strong><small>{ingredient?.inciName}</small>{ingredient && <em className={state === 'Low' || state === 'Out of Stock' ? 'stock-warning' : ''}>{ingredientBalance(ingredient, inventoryLots, inventoryMovements)} {ingredient.defaultUnit} · {state}</em>}</div><input disabled={!editable} value={line.phase} onChange={(e) => updateLine(version.id, line.id, { phase: e.target.value })} aria-label={`Phase for ${ingredient?.commonName}`} /><label className="percentage-input"><input disabled={!editable} type="number" min="0" max="100" step="0.1" value={line.percentage} onChange={(e) => updateLine(version.id, line.id, { percentage: Number(e.target.value) })} aria-label={`Percentage for ${ingredient?.commonName}`} /><span>%</span></label><input disabled={!editable} value={line.formulationRole??''} placeholder="Why this ingredient is used" onChange={(e) => updateLine(version.id, line.id, { formulationRole: e.target.value })} aria-label={`Formulation role for ${ingredient?.commonName}`} /><input disabled={!editable} value={line.notes} placeholder="Optional observation" onChange={(e) => updateLine(version.id, line.id, { notes: e.target.value })} aria-label={`Notes for ${ingredient?.commonName}`} /><button disabled={!editable} className="remove-line" aria-label={`Remove ${ingredient?.commonName}`} onClick={() => removeLine(version.id, line.id)}><Trash2 size={14} /></button></div>})}</div>
    {editable && <div className="add-line"><select aria-label="Ingredient to add" id="ingredient-add">{available.map((item) => <option value={item.id} key={item.id}>{item.commonName} · {item.inciName}</option>)}</select><button className="button ghost" disabled={!available.length} onClick={() => { const select = document.getElementById('ingredient-add') as HTMLSelectElement; if (select.value) addLine(version.id, select.value) }}><Plus size={15} />Add ingredient</button></div>}
    {!available.length && editable && <p className="content-note">Every material in the current Ingredient Library is already present.</p>}
  </section>
}
