import{describe,expect,it,vi}from'vitest'
import{authViewAfterEvent,completePasswordRecovery,initialAuthView,passwordRecoveryRedirectUrl,recoveryLinkError,requestPasswordRecovery,submitPasswordRecovery,validateRecoveredPassword}from'./passwordRecovery'

function client(){return{auth:{resetPasswordForEmail:vi.fn().mockResolvedValue({error:null}),updateUser:vi.fn().mockResolvedValue({error:null}),signOut:vi.fn().mockResolvedValue({error:null})}}}

describe('owner password recovery',()=>{
 it('calls the Supabase auth API with the running origin and public callback route',async()=>{const sdk=client();await requestPasswordRecovery(sdk,'owner@example.test','http://127.0.0.1:4173');expect(sdk.auth.resetPasswordForEmail).toHaveBeenCalledWith('owner@example.test',{redirectTo:'http://127.0.0.1:4173/auth/recovery'})})
 it('builds the recovery callback route for a deployed Pages origin',()=>expect(passwordRecoveryRedirectUrl('https://example.pages.dev')).toBe('https://example.pages.dev/auth/recovery'))
 it('preserves the local recovery callback route',()=>expect(passwordRecoveryRedirectUrl('http://127.0.0.1:4173')).toBe('http://127.0.0.1:4173/auth/recovery'))
 it('loads the public callback route in recovery mode',()=>expect(initialAuthView('/auth/recovery')).toBe('recovery'))
 it('shows the new-password form for PASSWORD_RECOVERY',()=>expect(authViewAfterEvent('PASSWORD_RECOVERY','login')).toBe('recovery'))
 it('rejects mismatching password confirmation',()=>expect(validateRecoveredPassword('a-secure-password','a-different-password')).toBe('Password confirmation does not match.'))
 it('renders success state after exactly one accepted request',async()=>{const sdk=client(),guard={current:false},states:unknown[]=[];expect(await submitPasswordRecovery(sdk,'owner@example.test','http://127.0.0.1:4173',guard,state=>states.push(state))).toBe(true);expect(sdk.auth.resetPasswordForEmail).toHaveBeenCalledOnce();expect(states).toEqual([{pending:true,error:'',notice:''},{pending:false,error:'',notice:'Password reset email requested. Use the newest email; earlier recovery links may expire.'}])})
 it('renders a Supabase error such as a rate limit and restores the button state',async()=>{const sdk=client(),guard={current:false},states:unknown[]=[];sdk.auth.resetPasswordForEmail.mockResolvedValue({error:{message:'Email rate limit exceeded'}});await submitPasswordRecovery(sdk,'owner@example.test','http://127.0.0.1:4173',guard,state=>states.push(state));expect(states.at(-1)).toEqual({pending:false,error:'Email rate limit exceeded',notice:''});expect(guard.current).toBe(false)})
 it('catches a network or unexpected exception and renders a safe visible error',async()=>{const sdk=client(),guard={current:false},states:unknown[]=[],consoleError=vi.spyOn(console,'error').mockImplementation(()=>{});sdk.auth.resetPasswordForEmail.mockRejectedValue(new Error('secret token payload'));await submitPasswordRecovery(sdk,'owner@example.test','http://127.0.0.1:4173',guard,state=>states.push(state));expect(states.at(-1)).toEqual({pending:false,error:'Password reset could not be requested. Check the network connection and try again.',notice:''});expect(consoleError).not.toHaveBeenCalled();consoleError.mockRestore()})
 it('prevents duplicate submits while the first request is pending',async()=>{let resolveRequest!:(value:{error:null})=>void;const sdk=client(),guard={current:false},states:unknown[]=[],pending=new Promise<{error:null}>(resolve=>{resolveRequest=resolve});sdk.auth.resetPasswordForEmail.mockReturnValue(pending);const first=submitPasswordRecovery(sdk,'owner@example.test','http://127.0.0.1:4173',guard,state=>states.push(state));expect(await submitPasswordRecovery(sdk,'owner@example.test','http://127.0.0.1:4173',guard,state=>states.push(state))).toBe(false);expect(sdk.auth.resetPasswordForEmail).toHaveBeenCalledOnce();resolveRequest({error:null});await first})
 it('updates the password and signs out before returning to login',async()=>{const sdk=client();expect(await completePasswordRecovery(sdk,'a-secure-password')).toEqual({error:null});expect(sdk.auth.updateUser).toHaveBeenCalledWith({password:'a-secure-password'});expect(sdk.auth.signOut).toHaveBeenCalledOnce()})
 it('keeps update errors visible and does not sign out',async()=>{const sdk=client();sdk.auth.updateUser.mockResolvedValue({error:{message:'Update failed'}});expect(await completePasswordRecovery(sdk,'a-secure-password')).toEqual({error:{message:'Update failed'}});expect(sdk.auth.signOut).not.toHaveBeenCalled()})
 it('explains expired and invalid recovery links without exposing URL tokens',()=>{expect(recoveryLinkError('?error_code=otp_expired&error_description=secret-token')).toContain('expired');expect(recoveryLinkError('?error_code=access_denied')).toContain('could not be used');expect(recoveryLinkError('?access_token=secret-token')).toBe('')})
})
