import { useMemo, useState } from 'react'
import { Box, Plus, Search } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PageHeader } from '../../components/ui/PageHeader'
import { StatusPill } from '../../components/ui/StatusPill'
import { formatDate } from '../../utils/format'
import { useFormulaData } from '../formulas/state/FormulaDataContext'
import { expiryState, ingredientBalance, stockState } from './domain/inventoryLogic'
import { ReceiveStockForm } from './components/ReceiveStockForm'
const INVENTORY_TODAY = new Date('2026-07-14T12:00:00')

export function InventoryPage(){const data=useFormulaData();const [search,setSearch]=useState('');const [stock,setStock]=useState('All');const [lotStatus,setLotStatus]=useState('All');const [expiry,setExpiry]=useState('All');const [receive,setReceive]=useState(false);const rows=useMemo(()=>data.ingredients.map(ingredient=>{const lots=data.inventoryLots.filter(l=>l.ingredientId===ingredient.id&&(lotStatus==='All'||l.status===lotStatus));const states=lots.map(l=>expiryState(l,INVENTORY_TODAY));return{ingredient,lots,balance:ingredientBalance(ingredient,data.inventoryLots,data.inventoryMovements),state:stockState(ingredient,data.inventoryLots,data.inventoryMovements),nearest:lots.map(l=>l.expiryDate??l.bestBeforeDate).filter(Boolean).sort()[0],expiryStates:states}}).filter(row=>row.ingredient.commonName.toLowerCase().includes(search.toLowerCase())&&(stock==='All'||row.state===stock)&&(expiry==='All'||row.expiryStates.includes(expiry as never))),[data.ingredients,data.inventoryLots,data.inventoryMovements,search,stock,lotStatus,expiry]);const expired=data.inventoryLots.filter(l=>expiryState(l,INVENTORY_TODAY)==='Expired').length;const soon=data.inventoryLots.filter(l=>expiryState(l,INVENTORY_TODAY)==='Expiring Soon').length
return <><PageHeader eyebrow="Stockroom / Lot-level inventory" title="Inventory" description="A practical view of physical raw-material stock, derived from an auditable movement ledger." action={<button className="button primary" onClick={()=>setReceive(true)}><Plus size={16}/>Receive stock</button>}/><div className="metric-strip"><div><span>Ingredients with stock</span><strong>{data.ingredients.filter(i=>ingredientBalance(i,data.inventoryLots,data.inventoryMovements)>0).length}</strong><small>Across active lot records</small></div><div><span>Expiring soon</span><strong className="warning-text">{soon}</strong><small>Within the 60-day awareness window</small></div><div><span>Expired lots</span><strong>{expired}</strong><small>Inventory information only</small></div></div><div className="inventory-filters"><label className="search-field"><Search size={16}/><input aria-label="Search inventory" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search material"/></label><select aria-label="Stock status" value={stock} onChange={e=>setStock(e.target.value)}>{['All','In Stock','Low','Out of Stock','No Inventory Data'].map(v=><option key={v}>{v}</option>)}</select><select aria-label="Lot status" value={lotStatus} onChange={e=>setLotStatus(e.target.value)}>{['All','Active','Quarantined','Exhausted','Expired','Disposed'].map(v=><option key={v}>{v}</option>)}</select><select aria-label="Expiry state" value={expiry} onChange={e=>setExpiry(e.target.value)}>{['All','Expired','Expiring Soon','Healthy','No Expiry Data'].map(v=><option key={v}>{v}</option>)}</select></div><div className="inventory-rows">{rows.map(({ingredient,lots,balance,state,nearest})=><Link to={`/ingredients/${ingredient.id}`} key={ingredient.id}><span className="material-icon"><Box size={16}/></span><div><span className="eyebrow">{ingredient.category}</span><h2>{ingredient.commonName}</h2><p>{ingredient.inciName}</p></div><dl><div><dt>Available</dt><dd>{balance} {ingredient.defaultUnit}</dd></div><div><dt>Active lots</dt><dd>{lots.filter(l=>l.status==='Active').length}</dd></div><div><dt>Oldest lot</dt><dd>{lots.map(l=>l.receivedDate).sort()[0]?formatDate(lots.map(l=>l.receivedDate).sort()[0]):'—'}</dd></div><div><dt>Nearest date</dt><dd>{nearest?formatDate(nearest):'No date'}</dd></div></dl><StatusPill tone={state==='In Stock'?'green':state==='Low'?'amber':'neutral'}>{state}</StatusPill></Link>)}</div>{receive&&<ReceiveStockForm onClose={()=>setReceive(false)}/>}</>}
