import { useState } from 'react'
import { ArrowLeft, MapPin, Plus } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { PageHeader } from '../../components/ui/PageHeader'
import { SectionHeader } from '../../components/ui/SectionHeader'
import { StatusPill } from '../../components/ui/StatusPill'
import { formatDate } from '../../utils/format'
import { useFormulaData } from '../formulas/state/FormulaDataContext'
import { expiryState, lotBalance, signedMovementQuantity } from './domain/inventoryLogic'
import { MovementForm } from './components/MovementForm'

export function LotDetailPage(){const {lotId}=useParams();const data=useFormulaData();const [moving,setMoving]=useState(false);const lot=data.inventoryLots.find(l=>l.id===lotId);if(!lot)return <div className="empty-state"><h1>Lot not found</h1></div>;const ingredient=data.ingredients.find(i=>i.id===lot.ingredientId);const supplier=data.supplierProducts.find(p=>p.id===lot.supplierProductId);const movements=data.inventoryMovements.filter(m=>m.inventoryLotId===lot.id).sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt));const balance=lotBalance(lot,data.inventoryMovements);const expiry=expiryState(lot,new Date('2026-07-14T12:00:00'))
return <><Link className="back-link" to={`/ingredients/${ingredient?.id}`}><ArrowLeft size={14}/>{ingredient?.commonName}</Link><PageHeader eyebrow={`${ingredient?.commonName} / Physical lot`} title={lot.internalLotNumber} description="An immutable stock history for one received physical lot." action={<button className="button primary" onClick={()=>setMoving(true)}><Plus size={15}/>Record movement</button>}/><div className="lot-summary"><section><span>Available balance</span><strong>{balance} <small>{lot.unit}</small></strong><StatusPill tone={balance>0?'green':'neutral'}>{lot.status}</StatusPill></section><dl><div><dt>Opening receipt</dt><dd>{lot.openingQuantity} {lot.unit}</dd></div><div><dt>Supplier lot</dt><dd>{lot.supplierLotNumber??'Not recorded'}</dd></div><div><dt>Received</dt><dd>{formatDate(lot.receivedDate)}</dd></div><div><dt>Expiry awareness</dt><dd><StatusPill tone={expiry==='Expired'?'red':expiry==='Expiring Soon'?'amber':'green'}>{expiry}</StatusPill></dd></div><div><dt>Supplier product</dt><dd>{supplier?`${supplier.supplierName} — ${supplier.productName}`:'Not linked'}</dd></div><div><dt>Location</dt><dd><MapPin size={12}/>{lot.location}</dd></div></dl></div><section className="panel movement-ledger"><SectionHeader title="Movement history" detail="Authoritative ledger · corrections are new Adjustment movements"/><div className="movement-list">{movements.map(m=>{const signed=signedMovementQuantity(m);return <article key={m.id}><span className={`movement-mark ${signed>=0?'positive':'negative'}`}>{signed>=0?'+':'−'}</span><div><strong>{m.type}</strong><p>{m.reason}</p><small>{m.notes||'No notes'}{m.referenceType?` · ${m.referenceType} ${m.referenceId??''}`:''}</small></div><b className={signed>=0?'positive-text':'negative-text'}>{signed>0?'+':''}{signed} {m.unit}</b><time>{new Date(m.occurredAt).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'})}</time></article>})}</div></section>{moving&&<MovementForm lotId={lot.id} onClose={()=>setMoving(false)}/>}</>}
