import { useMemo,useState } from 'react'
import { Factory,Search } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PageHeader } from '../../components/ui/PageHeader'
import { StatusPill } from '../../components/ui/StatusPill'
import { useFormulaData } from '../formulas/state/FormulaDataContext'
import { actualMaterialCost } from '../costing/domain/costingLogic'
import { CreateProductionRunForm } from './components/CreateProductionRunForm'
export function ProductionPage(){const d=useFormulaData();const [creating,setCreating]=useState(false);const [search,setSearch]=useState('');const [product,setProduct]=useState('All');const [status,setStatus]=useState('All');const rows=useMemo(()=>d.productionRuns.filter(r=>(r.productionRunNumber.toLowerCase().includes(search.toLowerCase())||r.purpose.toLowerCase().includes(search.toLowerCase()))&&(product==='All'||r.productId===product)&&(status==='All'||r.status===status)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),[d.productionRuns,search,product,status]);return <><PageHeader eyebrow={`Production log / ${d.productionRuns.length} runs`} title="Production" description="Controlled manufacturing records sourced only from exact Approved Formula Versions." action={<button className="button primary" onClick={()=>setCreating(true)}><Factory size={15}/>Create Production Run</button>}/><div className="lab-summary-strip"><div><span>Planned</span><strong>{d.productionRuns.filter(r=>r.status==='Planned').length}</strong></div><div><span>In progress</span><strong>{d.productionRuns.filter(r=>r.status==='In Progress').length}</strong></div><div><span>Completed</span><strong>{d.productionRuns.filter(r=>r.status==='Completed').length}</strong></div></div><div className="inventory-filters"><label className="search-field"><Search size={15}/><input aria-label="Search production" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search run or purpose"/></label><select value={product} onChange={e=>setProduct(e.target.value)}><option>All</option>{d.products.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}>{['All','Planned','In Progress','Completed','Aborted','Archived'].map(s=><option key={s}>{s}</option>)}</select></div><div className="lab-notebook-list production-list">{rows.map(r=>{const p=d.products.find(p=>p.id===r.productId);const v=d.formulaVersions.find(v=>v.id===r.formulaVersionId);const lines=d.productionRunLines.filter(l=>l.productionRunId===r.id);const actual=actualMaterialCost(lines,d.productionRunAllocations);return <Link to={`/production/${r.id}`} key={r.id}><span className="batch-stamp">PR</span><div><span className="eyebrow">{p?.name}</span><h2>{r.productionRunNumber}</h2><p>{r.purpose}</p></div><dl><div><dt>Formula</dt><dd>{v?.version}</dd></div><div><dt>Planned</dt><dd>{r.plannedBatchSize} {r.plannedBatchUnit}</dd></div><div><dt>Output</dt><dd>{r.actualYield??'—'} {r.actualYieldUnit??''} · {r.actualUnitsProduced??'—'} units</dd></div><div><dt>Cost status</dt><dd>{actual.totalAllocations?actual.complete?'Complete':'Incomplete':'Awaiting consumption'}</dd></div></dl><div className="batch-state"><StatusPill tone={r.status==='Completed'?'green':r.status==='In Progress'?'blue':'neutral'}>{r.status}</StatusPill></div></Link>})}</div>{creating&&<CreateProductionRunForm onClose={()=>setCreating(false)}/>}</>}
