import type { ComplianceDossier,CpnpRecord,CpsrRecord,InciDraft,LabelArtworkVersion,PifSection,ReadinessIssue,RegulatoryReview,RegulatorySource } from '../../../types/domain'
export function configurationMismatches(d:ComplianceDossier,config:{formulaVersionId:string;packagingSpecificationVersionId?:string;labelArtworkVersionId?:string}){const issues:string[]=[];if(d.formulaVersionId!==config.formulaVersionId)issues.push('Formula Version mismatch');if(d.packagingSpecificationVersionId!==config.packagingSpecificationVersionId)issues.push('Packaging Specification Version mismatch');if(d.labelArtworkVersionId!==config.labelArtworkVersionId)issues.push('Label Artwork Version mismatch');return issues}
export function duplicateDossier(source:ComplianceDossier,config:Pick<ComplianceDossier,'formulaVersionId'|'packagingSpecificationVersionId'|'labelArtworkVersionId'>,id:string,now=new Date().toISOString()):ComplianceDossier{return{...source,...config,id,status:'Evidence Gathering',derivedFromDossierId:source.id,compositionSnapshot:source.compositionSnapshot.map(x=>({...x})),createdAt:now,updatedAt:now,notes:`Duplicated from ${source.id}. Version-sensitive evidence requires review.`}}
export function copiedEvidenceStatus(status:PifSection['status']):PifSection['status']{return['Evidence Recorded','External Review Complete'].includes(status)?'Needs Review':status}
export function pifEvidenceSummary(sections:PifSection[]){const complete=sections.filter(s=>['Evidence Recorded','External Review Complete','Not Applicable'].includes(s.status)).length;return{complete,total:sections.length,internallyComplete:sections.length>0&&complete===sections.length}}
export function cpnpValidation(record:CpnpRecord){if(record.status==='Confirmation Recorded'&&!record.externalReference&&!record.confirmationDocumentId)return'Confirmation Recorded requires external confirmation metadata.';return null}
export function cpsrHasIssuedEvidence(record:CpsrRecord){return record.status==='Issued'&&!!record.cpsrDocumentId&&!!record.issuedDate}
export const inciHasUnresolvedItems=(draft:InciDraft)=>draft.unresolvedItems.length>0
export function sourceReviewAgeDays(source:RegulatorySource,today=new Date()){if(!source.lastReviewedAt)return undefined;return Math.floor((today.getTime()-new Date(`${source.lastReviewedAt}T12:00:00`).getTime())/86400000)}
export function deriveReadinessIssues(input:{dossier:ComplianceDossier;reviews:RegulatoryReview[];pif:PifSection[];cpsr?:CpsrRecord;cpnp?:CpnpRecord;inci?:InciDraft;label?:LabelArtworkVersion;claimsMissing:number}):ReadinessIssue[]{const issues:Omit<ReadinessIssue,'id'>[]=[];const add=(category:string,severity:ReadinessIssue['severity'],title:string)=>issues.push({complianceDossierId:input.dossier.id,category,severity,title,description:title,status:'Open',notes:''});if(!input.dossier.responsiblePersonId)add('Responsible Person','Blocking','No Responsible Person selected');if(input.reviews.some(r=>['Not Reviewed','Unknown','Blocked Pending Review'].includes(r.conclusion)))add('Ingredient Review','Blocking','Ingredient regulatory review remains unresolved');if(!input.cpsr||!cpsrHasIssuedEvidence(input.cpsr))add('CPSR','Blocking','No issued CPSR evidence recorded');if(!pifEvidenceSummary(input.pif).internallyComplete)add('PIF','Important','Internal PIF evidence checklist is incomplete');if(!input.label)add('Label','Important','No Label Artwork Version linked');if(input.inci&&inciHasUnresolvedItems(input.inci))add('INCI','Important','INCI Working Draft has unresolved items');if(input.claimsMissing)add('Claims','Important',`${input.claimsMissing} claim(s) lack recorded evidence`);if(!input.cpnp||input.cpnp.status!=='Confirmation Recorded'||cpnpValidation(input.cpnp))add('CPNP','Blocking','External CPNP confirmation is not recorded');return issues.map((x,i)=>({...x,id:`derived-${i}`}))}
export function internalReadiness(issues:ReadinessIssue[],dossierStatus:ComplianceDossier['status']){if(dossierStatus==='Internally Released')return'Internally Released';if(issues.some(i=>i.status==='Open'&&i.severity==='Blocking'))return'Blocked';if(issues.some(i=>i.status==='Open'&&i.severity==='Important'))return'Significant Gaps';if(dossierStatus==='External Review')return'External Review Pending';return'Ready for Internal Release Decision'}
