import {useRef,useState} from 'react'
import {ArrowLeft,Download,FileUp,Plus} from 'lucide-react'
import {Link,useParams} from 'react-router-dom'
import {procurementActions} from './actions/procurementActions'
import {offersToCsv,parseCsv} from './data/procurementInterchange'
import {calculateOffer,canTransitionProcurementRequest,procurementRequestTransitions,type ProcurementDocumentState,type ProcurementRequestStatus} from './domain/procurement'
import {useProcurement} from './useProcurement'
import {ResearchPanel} from './components/ResearchPanel'

const unknown=(value:number|null|undefined,format=(x:number)=>String(x))=>value==null?'Unknown':format(value)
const amount=(value:number|null|undefined,currency:string|null)=>unknown(value,x=>`${x.toFixed(2)} ${currency||'currency unknown'}`)
const split=(value:FormDataEntryValue|undefined)=>String(value||'').split(/[,\n]/).map(x=>x.trim()).filter(Boolean)
const nullableNumber=(value:FormDataEntryValue|undefined)=>String(value||'').trim()===''?null:Number(value)
function downloadCsv(content:string){const url=URL.createObjectURL(new Blob([content],{type:'text/csv'})),anchor=document.createElement('a');anchor.href=url;anchor.download='koalafrog-procurement-offers.csv';anchor.click();URL.revokeObjectURL(url)}

export function ProcurementRequestPage(){
 const{id}=useParams(),{workspace,data,error,refresh}=useProcurement(),[showItem,setShowItem]=useState(false),[offerItem,setOfferItem]=useState(''),[recommendItem,setRecommendItem]=useState(''),[message,setMessage]=useState(''),csvRef=useRef<HTMLInputElement>(null)
 const request=data?.requests.find(x=>x.id===id),items=[...(data?.requestedItems.filter(x=>x.procurement_request_id===id)??[])].sort((a,b)=>a.display_order-b.display_order),offers=data?.offers.filter(x=>items.some(item=>item.id===x.requested_item_id))??[],recommendations=data?.recommendations.filter(x=>x.procurement_request_id===id)??[]
 if(error)return <section className="panel procurement-state" role="alert"><h1>Procurement unavailable</h1><p>{error}</p></section>
 if(!data)return <section className="panel procurement-state">Loading request…</section>
 if(!request)return <section className="panel procurement-state"><h1>Request not found</h1><Link to="/procurement">Return to Procurement</Link></section>
 const createItem=async(form:HTMLFormElement)=>{if(!workspace)return;const value=Object.fromEntries(new FormData(form));try{await procurementActions.createRequestedItem(workspace.workspaceId,{procurement_request_id:request.id,name:value.name,category:value.category,requested_quantity:Number(value.quantity),unit:value.unit,intended_product_ids:split(value.products),intended_formula_ids:split(value.formulas),required_specifications:split(value.specifications),acceptable_substitutes:split(value.substitutes),priority:value.priority,needed_by:value.needed_by||null,notes:value.notes||'',display_order:items.length});setShowItem(false);await refresh()}catch(cause){setMessage(cause instanceof Error?cause.message:'Could not add item.')}}
 const createOffer=async(form:HTMLFormElement,itemId:string)=>{if(!workspace)return;const value=Object.fromEntries(new FormData(form));try{await procurementActions.createOffer(workspace.workspaceId,{requested_item_id:itemId,supplier_id:value.supplier_id,source_supplier_product_domain:null,source_supplier_product_id:null,product_title:value.product_title,product_url:value.product_url||null,country_code:value.country_code||null,package_quantity:Number(value.package_quantity),package_unit:value.package_unit,item_price:Number(value.item_price),currency:String(value.currency).toUpperCase(),moq:nullableNumber(value.moq),shipping_cost:nullableNumber(value.shipping_cost),tax_duty_estimate:nullableNumber(value.tax_duty_estimate),delivery_estimate_days:nullableNumber(value.delivery_estimate_days),stock_status:value.stock_status,coa_availability:value.coa,sds_availability:value.sds,technical_document_availability:value.technical,certification_claims:split(value.certifications),first_order_discount:nullableNumber(value.first_order_discount),notes:value.notes||'',date_checked:value.date_checked,confidence:value.confidence});setOfferItem('');await refresh()}catch(cause){setMessage(cause instanceof Error?cause.message:'Could not add offer.')}}
 const recommend=async(form:HTMLFormElement,itemId:string)=>{if(!workspace)return;const value=Object.fromEntries(new FormData(form));try{await procurementActions.createRecommendation(workspace.workspaceId,{procurement_request_id:request.id,requested_item_id:itemId,supplier_offer_id:value.offer_id,summary:value.summary,rationale:value.rationale||'',recommended_purchase_quantity:nullableNumber(value.quantity),status:'recommended'});setRecommendItem('');await refresh()}catch(cause){setMessage(cause instanceof Error?cause.message:'Could not save recommendation.')}}
 const transition=async(to:ProcurementRequestStatus)=>{try{await procurementActions.update('procurement_requests',request.id,request.revision,{status:to});await refresh()}catch(cause){setMessage(cause instanceof Error?cause.message:'Could not update status.')}}
 const importCsv=async(file:File)=>{if(!workspace)return;try{const rows=parseCsv(await file.text());if(!rows.length)throw new Error('CSV contains no offer rows.');if(rows.some(row=>!items.some(item=>item.id===row.requested_item_id)||!data.suppliers.some(supplier=>supplier.id===row.supplier_id)||!row.product_title||!(Number(row.package_quantity)>0)||!row.package_unit))throw new Error('CSV contains an unknown item or supplier, or a missing required value.');await procurementActions.importOffers(workspace.workspaceId,rows.map(row=>({requested_item_id:row.requested_item_id,supplier_id:row.supplier_id,source_supplier_product_domain:null,source_supplier_product_id:null,product_title:row.product_title,product_url:row.product_url||null,country_code:row.country_code||null,package_quantity:Number(row.package_quantity),package_unit:row.package_unit,item_price:row.item_price===''?null:Number(row.item_price),currency:row.currency||null,moq:row.moq===''?null:Number(row.moq),shipping_cost:row.shipping_cost===''?null:Number(row.shipping_cost),tax_duty_estimate:row.tax_duty_estimate===''?null:Number(row.tax_duty_estimate),delivery_estimate_days:row.delivery_estimate_days===''?null:Number(row.delivery_estimate_days),stock_status:row.stock_status||'unknown',coa_availability:row.coa_availability||'unknown',sds_availability:row.sds_availability||'unknown',technical_document_availability:row.technical_document_availability||'unknown',certification_claims:(row.certification_claims||'').split('|').filter(Boolean),first_order_discount:row.first_order_discount===''?null:Number(row.first_order_discount),notes:row.notes||'',date_checked:row.date_checked,confidence:row.confidence||'unknown'})));setMessage('Offers imported.');await refresh()}catch(cause){setMessage(cause instanceof Error?cause.message:'Could not import CSV.')}finally{if(csvRef.current)csvRef.current.value=''}}
 return <div className="procurement-request-detail">
  <Link className="back-link" to="/procurement"><ArrowLeft size={14}/>Procurement</Link>
  <header className="detail-hero"><span className="eyebrow">{request.category.replaceAll('_',' ')}</span><h1>{request.title}</h1><p>{request.notes||'No request notes recorded.'}</p><div className="request-meta"><strong className={`procurement-status ${request.status}`}>{request.status}</strong><span>{request.priority} priority</span><span>Needed {request.needed_by||'date unknown'}</span></div></header>
  <div className="procurement-toolbar"><button className="button primary" onClick={()=>setShowItem(x=>!x)}><Plus size={14}/>Add requested item</button><button className="button ghost" onClick={()=>downloadCsv(offersToCsv(offers))}><Download size={14}/>Export offers CSV</button><button className="button ghost" onClick={()=>csvRef.current?.click()}><FileUp size={14}/>Import offers CSV</button><input ref={csvRef} className="visually-hidden" type="file" accept=".csv,text/csv" onChange={e=>{const file=e.target.files?.[0];if(file)void importCsv(file)}}/></div>
  <section className="panel status-workflow" aria-label="Request status workflow"><h2>Status workflow</h2><ol>{(['needed','researching','recommended','ordered','received'] as ProcurementRequestStatus[]).map(status=><li className={status===request.status?'current':''} key={status}>{status}</li>)}</ol>{procurementRequestTransitions[request.status].map(status=><button className="button ghost" key={status} disabled={!canTransitionProcurementRequest(request.status,status)} onClick={()=>void transition(status)}>Move to {status}</button>)}</section>
  {message&&<p className="form-message" role="status">{message}</p>}
  {workspace&&<ResearchPanel workspaceId={workspace.workspaceId} request={request} data={data} refresh={refresh}/>}
  {showItem&&<form className="panel procurement-detail-form" onSubmit={e=>{e.preventDefault();void createItem(e.currentTarget)}}><h2>Requested item</h2><label>Name<input name="name" required/></label><label>Category<input name="category" required/></label><label>Quantity<input name="quantity" type="number" min="0.0001" step="any" required/></label><label>Unit<input name="unit" required placeholder="g, kg, ml, L or pcs"/></label><label>Priority<select name="priority" defaultValue={request.priority}><option>low</option><option>normal</option><option>high</option><option>urgent</option></select></label><label>Needed by<input name="needed_by" type="date" defaultValue={request.needed_by||''}/></label><label>Intended product IDs<input name="products" placeholder="Comma separated"/></label><label>Intended formula IDs<input name="formulas" placeholder="Comma separated"/></label><label className="wide">Required specifications<textarea name="specifications" placeholder="One per line"/></label><label className="wide">Acceptable substitutes<textarea name="substitutes" placeholder="One per line"/></label><label className="wide">Notes<textarea name="notes"/></label><button className="button primary">Save item</button></form>}
  {items.map(item=>{const itemOffers=offers.filter(x=>x.requested_item_id===item.id),recommendation=recommendations.find(x=>x.requested_item_id===item.id&&x.status==='recommended');return <section className="procurement-item-section" key={item.id}>
   <header><div><span className="eyebrow">{item.category.replaceAll('_',' ')}</span><h2>{item.name}</h2><p>{item.requested_quantity} {item.unit} · {item.priority} priority · Needed {item.needed_by||'date unknown'}</p></div><button className="button ghost" onClick={()=>setOfferItem(offerItem===item.id?'':item.id)}><Plus size={14}/>Add offer</button></header>
   <div className="item-requirements"><div><strong>Required specifications</strong><p>{item.required_specifications.join(' · ')||'Unknown'}</p></div><div><strong>Acceptable substitutes</strong><p>{item.acceptable_substitutes.join(' · ')||'None recorded'}</p></div><div><strong>Intended products/formulas</strong><p>{[...item.intended_product_ids,...item.intended_formula_ids].join(' · ')||'Not linked'}</p></div></div>
   {offerItem===item.id&&<OfferForm suppliers={data.suppliers} onSubmit={form=>void createOffer(form,item.id)}/>}
   <div className="offer-table-wrap"><table className="offer-comparison"><caption>Supplier offer comparison for {item.name}</caption><thead><tr><th>Supplier / offer</th><th>Package</th><th>Unit price</th><th>Purchase</th><th>Landed total</th><th>Landed unit</th><th>Surplus</th><th>Stock / delivery</th><th>Documents</th><th>Completeness</th></tr></thead><tbody>{itemOffers.map(offer=>{const supplier=data.suppliers.find(x=>x.id===offer.supplier_id),calc=calculateOffer(item,offer);return <tr key={offer.id}><th><a href={offer.product_url||undefined} target="_blank" rel="noreferrer">{offer.product_title}</a><small>{supplier?.trading_name||supplier?.legal_name||'Unknown supplier'} · {offer.country_code||'Country unknown'}</small></th><td>{offer.package_quantity} {offer.package_unit}</td><td>{amount(calc.normalizedUnitPrice,offer.currency)} / {item.unit}</td><td>{unknown(calc.purchaseQuantity,x=>`${x} packs`)}<small>{amount(calc.productSubtotal,offer.currency)}</small></td><td>{amount(calc.estimatedLandedTotal,offer.currency)}</td><td>{amount(calc.effectiveLandedUnitCost,offer.currency)} / {item.unit}</td><td>{unknown(calc.surplusQuantity,x=>`${x.toFixed(2)} ${item.unit}`)}</td><td>{offer.stock_status.replaceAll('_',' ')}<small>{unknown(offer.delivery_estimate_days,x=>`${x} days`)}</small></td><td><small>COA {offer.coa_availability}<br/>SDS {offer.sds_availability}<br/>Technical {offer.technical_document_availability}</small></td><td><strong>{calc.completeness}%</strong><small>{offer.confidence} confidence</small></td></tr>})}{!itemOffers.length&&<tr><td colSpan={10}>No offers recorded. Unknown values are expected during early research.</td></tr>}</tbody></table></div>
   <article className="panel recommendation-summary"><span className="eyebrow">Recommendation</span>{recommendation?<><h3>{recommendation.summary}</h3><p>{recommendation.rationale||'No rationale recorded.'}</p><small>Recorded recommendation only; no order has been placed.</small></>:<><h3>No recommendation yet</h3><p>Compare at least one offer, then record the owner-reviewed choice.</p>{itemOffers.length>0&&<button className="button ghost" onClick={()=>setRecommendItem(recommendItem===item.id?'':item.id)}>Record recommendation</button>}</>}{recommendItem===item.id&&<form className="inline-recommendation" onSubmit={e=>{e.preventDefault();void recommend(e.currentTarget,item.id)}}><label>Offer<select name="offer_id">{itemOffers.map(x=><option key={x.id} value={x.id}>{x.product_title}</option>)}</select></label><label>Summary<input name="summary" required/></label><label>Purchase quantity<input name="quantity" type="number" min="0" step="any"/></label><label>Rationale<textarea name="rationale"/></label><button className="button primary">Save recommendation</button></form>}</article>
  </section>})}
  {!items.length&&!showItem&&<article className="panel procurement-empty"><h2>No requested items</h2><p>Add the first requested item to begin structured supplier research.</p></article>}
 </div>
}

function OfferForm({suppliers,onSubmit}:{suppliers:Array<{id:string;legal_name:string;trading_name:string|null}>,onSubmit:(form:HTMLFormElement)=>void}){
 const documents:ProcurementDocumentState[]=['unknown','available','partial','unavailable']
 return <form className="panel procurement-detail-form offer-entry" onSubmit={e=>{e.preventDefault();onSubmit(e.currentTarget)}}><h3>Supplier offer</h3><label>Supplier<select name="supplier_id" required><option value="">Select supplier</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.trading_name||x.legal_name}</option>)}</select></label><label>Product title<input name="product_title" required/></label><label>Product URL<input name="product_url" type="url"/></label><label>Country<input name="country_code" maxLength={2} placeholder="NO"/></label><label>Package quantity<input name="package_quantity" type="number" min="0.0001" step="any" required/></label><label>Package unit<input name="package_unit" required/></label><label>Item price<input name="item_price" type="number" min="0" step="any" required/></label><label>Currency<input name="currency" maxLength={3} defaultValue="NOK" required/></label><label>MOQ (packages)<input name="moq" type="number" min="1" step="any"/></label><label>Shipping cost<input name="shipping_cost" type="number" min="0" step="any"/></label><label>Tax/duty estimate<input name="tax_duty_estimate" type="number" min="0" step="any"/></label><label>Delivery estimate (days)<input name="delivery_estimate_days" type="number" min="0"/></label><label>Stock<select name="stock_status"><option>unknown</option><option>in_stock</option><option>limited</option><option>backorder</option><option>out_of_stock</option></select></label><label>COA<select name="coa">{documents.map(x=><option key={x}>{x}</option>)}</select></label><label>SDS<select name="sds">{documents.map(x=><option key={x}>{x}</option>)}</select></label><label>Technical documents<select name="technical">{documents.map(x=><option key={x}>{x}</option>)}</select></label><label>Organic/certification claims<input name="certifications" placeholder="Unverified claims, comma separated"/></label><label>First-order discount<input name="first_order_discount" type="number" min="0" step="any"/></label><label>Date checked<input name="date_checked" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Confidence<select name="confidence"><option>unknown</option><option>low</option><option>medium</option><option>high</option></select></label><label className="wide">Notes<textarea name="notes"/></label><button className="button primary">Save offer</button></form>
}
