import{useState}from'react'
import{calculateCartScenario,type ProcurementData,type SupplierDiscount,type SupplierShippingRule}from'./domain/procurement'
import{procurementActions}from'./actions/procurementActions'

const numberOrNull=(value:FormDataEntryValue|null)=>value==null||value===''?null:Number(value)
const textOrNull=(value:FormDataEntryValue|null)=>value==null||value===''?null:String(value)
const money=(value:number|null,currency:string)=>value==null?'Unknown':new Intl.NumberFormat(undefined,{style:'currency',currency}).format(value)

export function PurchasingIntelligencePanel({workspaceId,data,refresh}:{workspaceId:string;data:ProcurementData;refresh:()=>Promise<void>}){
 const[supplierId,setSupplierId]=useState(data.suppliers[0]?.id??''),[editingDiscount,setEditingDiscount]=useState<SupplierDiscount|null>(null),[editingRule,setEditingRule]=useState<SupplierShippingRule|null>(null),[message,setMessage]=useState(''),[offerId,setOfferId]=useState(''),[packageCount,setPackageCount]=useState(1),[discountId,setDiscountId]=useState(''),[ruleId,setRuleId]=useState('')
 const supplier=data.suppliers.find(x=>x.id===supplierId),discounts=data.supplierDiscounts.filter(x=>x.supplier_id===supplierId),rules=data.supplierShippingRules.filter(x=>x.supplier_id===supplierId),offers=data.offers.filter(x=>x.supplier_id===supplierId&&x.item_price!=null&&x.currency),offer=data.offers.find(x=>x.id===offerId)
 const currency=offer?.currency??supplier?.default_currency??'NOK',scenario={id:'preview',supplier_id:supplierId,name:'Cart preview',destination_country_code:'NO',currency,shipping_rule_id:ruleId||null,discount_id:discountId||null,manual_shipping_cost:null,manual_tax_estimate:null,manual_duty_estimate:null,payment_fee:null,additional_cost:null,status:'draft' as const,notes:'',calculated_at:null,created_at:'',updated_at:''}
 const preview=calculateCartScenario({scenario,items:offer?[{id:'preview-item',scenario_id:'preview',supplier_offer_id:offer.id,requested_item_id:offer.requested_item_id,package_count:packageCount,unit_price:offer.item_price!,line_discount:0,display_order:0,notes:'',created_at:'',updated_at:''}]:[],discount:discounts.find(x=>x.id===discountId),shippingRule:rules.find(x=>x.id===ruleId)})
 const saveDiscount=async(form:HTMLFormElement)=>{const value=new FormData(form),record={supplier_id:supplierId,name:String(value.get('name')),discount_type:value.get('discount_type'),percentage:numberOrNull(value.get('percentage')),fixed_amount:numberOrNull(value.get('fixed_amount')),currency:textOrNull(value.get('currency'))?.toUpperCase()??null,coupon_code:textOrNull(value.get('coupon_code')),minimum_order_value:numberOrNull(value.get('minimum_order_value')),maximum_discount:numberOrNull(value.get('maximum_discount')),first_purchase_only:value.get('first_purchase_only')==='on',requires_newsletter:false,valid_from:textOrNull(value.get('valid_from')),expires_at:textOrNull(value.get('expires_at')),status:value.get('status'),source_url:textOrNull(value.get('source_url')),evidence_notes:String(value.get('evidence_notes')??''),verified_at:textOrNull(value.get('verified_at')),used_at:editingDiscount?.used_at??null};try{if(editingDiscount)await procurementActions.updatePurchasingRecord('procurement_supplier_discounts',editingDiscount.id,record);else await procurementActions.createSupplierDiscount(workspaceId,record);setEditingDiscount(null);setMessage('Discount saved.');await refresh()}catch(cause){setMessage(cause instanceof Error?cause.message:'Could not save discount.')}}
 const saveRule=async(form:HTMLFormElement)=>{const value=new FormData(form),record={supplier_id:supplierId,destination_country_code:textOrNull(value.get('destination_country_code'))?.toUpperCase()??null,destination_region:textOrNull(value.get('destination_region')),shipping_method:textOrNull(value.get('shipping_method')),currency:textOrNull(value.get('currency'))?.toUpperCase()??null,flat_rate:numberOrNull(value.get('flat_rate')),free_shipping_threshold:numberOrNull(value.get('free_shipping_threshold')),minimum_order_value:null,delivery_estimate_min_days:null,delivery_estimate_max_days:null,tax_handling:value.get('tax_estimate')===''?'unknown':'excluded',duty_handling:value.get('duty_estimate')===''?'unknown':'excluded',tax_estimate:numberOrNull(value.get('tax_estimate')),duty_estimate:numberOrNull(value.get('duty_estimate')),status:value.get('status'),source_url:textOrNull(value.get('source_url')),evidence_notes:String(value.get('evidence_notes')??''),verified_at:textOrNull(value.get('verified_at'))};try{if(editingRule)await procurementActions.updatePurchasingRecord('procurement_supplier_shipping_rules',editingRule.id,record);else await procurementActions.createSupplierShippingRule(workspaceId,record);setEditingRule(null);setMessage('Shipping rule saved.');await refresh()}catch(cause){setMessage(cause instanceof Error?cause.message:'Could not save shipping rule.')}}
 const saveScenario=async()=>{if(!offer)return;try{const saved=await procurementActions.createCartScenario(workspaceId,{...scenario,id:undefined,name:`${supplier?.trading_name||supplier?.legal_name||'Supplier'} Norway cart`,calculated_at:new Date().toISOString(),created_at:undefined,updated_at:undefined});await procurementActions.createCartScenarioItem(workspaceId,{scenario_id:saved.id,supplier_offer_id:offer.id,requested_item_id:offer.requested_item_id,package_count:packageCount,unit_price:offer.item_price,line_discount:0,display_order:0,notes:''});setMessage('Cart scenario saved.');await refresh()}catch(cause){setMessage(cause instanceof Error?cause.message:'Could not save scenario.')}}
 if(!data.suppliers.length)return null
 return <section className="purchasing-intelligence" aria-labelledby="purchasing-intelligence-title">
  <header><div><span className="eyebrow">Planning only</span><h2 id="purchasing-intelligence-title">Purchasing intelligence</h2><p>Review supplier terms and estimate a cart. This does not order, pay, or change inventory.</p></div><label>Supplier<select value={supplierId} onChange={e=>{setSupplierId(e.target.value);setOfferId('');setDiscountId('');setRuleId('')}}>{data.suppliers.map(x=><option key={x.id} value={x.id}>{x.trading_name||x.legal_name}</option>)}</select></label></header>
  {message&&<p className="form-message" role="status">{message}</p>}
  <div className="purchasing-columns">
   <section className="panel"><h3>Commercial terms</h3><form className="purchasing-form" key={editingDiscount?.id??`new-${supplierId}`} onSubmit={e=>{e.preventDefault();void saveDiscount(e.currentTarget)}}>
    <label>Name<input name="name" required defaultValue={editingDiscount?.name}/></label><label>Type<select name="discount_type" defaultValue={editingDiscount?.discount_type??'percentage'}><option value="percentage">Percentage</option><option value="fixed_amount">Fixed discount</option><option value="free_shipping">Free shipping</option><option value="other">Other</option></select></label><label>Percentage<input name="percentage" type="number" min="0.01" max="100" step="any" defaultValue={editingDiscount?.percentage??''}/></label><label>Fixed amount<input name="fixed_amount" type="number" min="0" step="any" defaultValue={editingDiscount?.fixed_amount??''}/></label><label>Currency<input name="currency" maxLength={3} defaultValue={editingDiscount?.currency??currency}/></label><label>Code<input name="coupon_code" defaultValue={editingDiscount?.coupon_code??''}/></label><label>Minimum order<input name="minimum_order_value" type="number" min="0" step="any" defaultValue={editingDiscount?.minimum_order_value??''}/></label><label>Maximum discount<input name="maximum_discount" type="number" min="0" step="any" defaultValue={editingDiscount?.maximum_discount??''}/></label><label>Status<select name="status" defaultValue={editingDiscount?.status??'available'}>{['unknown','available','planned','used','expired','invalid'].map(x=><option key={x}>{x}</option>)}</select></label><label>Valid from<input name="valid_from" type="date" defaultValue={editingDiscount?.valid_from??''}/></label><label>Valid until<input name="expires_at" type="date" defaultValue={editingDiscount?.expires_at?.slice(0,10)??''}/></label><label>Checked date<input name="verified_at" type="date" defaultValue={editingDiscount?.verified_at?.slice(0,10)??''}/></label><label className="check"><input name="first_purchase_only" type="checkbox" defaultChecked={editingDiscount?.first_purchase_only}/>First order only</label><label className="wide">Source URL<input name="source_url" type="url" defaultValue={editingDiscount?.source_url??''}/></label><label className="wide">Notes<textarea name="evidence_notes" defaultValue={editingDiscount?.evidence_notes}/></label><button className="button primary">Save discount</button>
   </form>{discounts.map(x=><button className="term-row" key={x.id} onClick={()=>setEditingDiscount(x)}>{x.name} · {x.status} · Edit</button>)}
   <form className="purchasing-form shipping-form" key={editingRule?.id??`rule-${supplierId}`} onSubmit={e=>{e.preventDefault();void saveRule(e.currentTarget)}}><h3>Shipping rule</h3><label>Country<input name="destination_country_code" maxLength={2} placeholder="NO" defaultValue={editingRule?.destination_country_code??''}/></label><label>Region<input name="destination_region" placeholder="Norway, EU…" defaultValue={editingRule?.destination_region??''}/></label><label>Fixed shipping<input name="flat_rate" type="number" min="0" step="any" defaultValue={editingRule?.flat_rate??''}/></label><label>Free over<input name="free_shipping_threshold" type="number" min="0" step="any" defaultValue={editingRule?.free_shipping_threshold??''}/></label><label>Currency<input name="currency" maxLength={3} defaultValue={editingRule?.currency??currency}/></label><label>Tax estimate<input name="tax_estimate" type="number" min="0" step="any" defaultValue={editingRule?.tax_estimate??''}/></label><label>Duty estimate<input name="duty_estimate" type="number" min="0" step="any" defaultValue={editingRule?.duty_estimate??''}/></label><label>Status<select name="status" defaultValue={editingRule?.status??'needs_verification'}>{['active','needs_verification','inactive','expired'].map(x=><option key={x}>{x}</option>)}</select></label><label>Checked date<input name="verified_at" type="date" defaultValue={editingRule?.verified_at?.slice(0,10)??''}/></label><label className="wide">Source URL<input name="source_url" type="url" defaultValue={editingRule?.source_url??''}/></label><label className="wide">Notes<textarea name="evidence_notes" defaultValue={editingRule?.evidence_notes}/></label><button className="button primary">Save shipping rule</button></form>{rules.map(x=><button className="term-row" key={x.id} onClick={()=>setEditingRule(x)}>{x.destination_country_code||x.destination_region||'Destination unknown'} · {x.status} · Edit</button>)}
   </section>
   <section className="panel cart-scenario"><h3>Cart scenario</h3><label>Accepted supplier offer<select value={offerId} onChange={e=>setOfferId(e.target.value)}><option value="">Select offer</option>{offers.map(x=><option key={x.id} value={x.id}>{x.product_title} · {money(x.item_price,x.currency!)}</option>)}</select></label><label>Package count<input value={packageCount} onChange={e=>setPackageCount(Math.max(1,Number(e.target.value)))} type="number" min="1" step="1"/></label><label>Discount<select value={discountId} onChange={e=>setDiscountId(e.target.value)}><option value="">None</option>{discounts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Norway shipping rule<select value={ruleId} onChange={e=>setRuleId(e.target.value)}><option value="">Unknown</option>{rules.map(x=><option key={x.id} value={x.id}>{x.destination_country_code||x.destination_region||'Unknown destination'}</option>)}</select></label>
    <dl><div><dt>Merchandise</dt><dd>{money(preview.components.merchandise,currency)}</dd></div><div><dt>Discount</dt><dd>{money(preview.components.orderDiscount,currency)}</dd></div><div><dt>Shipping</dt><dd>{money(preview.components.shipping,currency)}</dd></div><div><dt>Tax</dt><dd>{money(preview.components.tax,currency)}</dd></div><div><dt>Duty</dt><dd>{money(preview.components.duty,currency)}</dd></div><div><dt>Payment fee</dt><dd>{money(preview.components.paymentFee,currency)}</dd></div><div><dt>Additional fee</dt><dd>{money(preview.components.additional,currency)}</dd></div><div><dt>Known total</dt><dd>{money(preview.knownTotal,currency)}</dd></div><div><dt>Complete landed total</dt><dd>{money(preview.landedTotal,currency)}</dd></div></dl>
    <p className={preview.complete?'complete':'unknown'}>{preview.complete?'Complete estimate':`Incomplete · unknown: ${preview.missing.join(', ')||'none'}`}</p><button className="button primary" disabled={!offer} onClick={()=>void saveScenario()}>Save scenario</button>
   </section>
  </div>
 </section>
}
